CompatWireless3.2: drivers/net/wireless/b43/bus.h File Reference
drivers/net/wireless/b43/bus.h File Reference
Data Structures
struct b43_bus_dev
Enumerations
enum b43_bus_type { B43_BUS_SSB }
Functions
static bool b43_bus_host_is_pcmcia (struct b43_bus_dev *dev)
static bool b43_bus_host_is_sdio (struct b43_bus_dev *dev)
struct b43_bus_dev * b43_bus_dev_bcma_init (struct bcma_device *core)
struct b43_bus_dev * b43_bus_dev_ssb_init (struct ssb_device *sdev)
void * b43_bus_get_wldev (struct b43_bus_dev *dev)
void b43_bus_set_wldev (struct b43_bus_dev *dev, void *data)
Enumeration Type Documentation
enum b43_bus_type
Enumerator:
B43_BUS_SSB
Definition at line 4 of file bus.h.
Function Documentation
struct b43_bus_dev* b43_bus_dev_bcma_init (struct bcma_device * core) [read]
struct b43_bus_dev* b43_bus_dev_ssb_init (struct ssb_device * sdev) [read]
void* b43_bus_get_wldev (struct b43_bus_dev * dev)
Definition at line 228 of file bus.c.
References B43_BUS_SSB, b43_bus_dev::bdev, b43_bus_dev::bus_type, and b43_bus_dev::sdev.
Referenced by b43_one_core_detach().
static bool b43_bus_host_is_pcmcia (struct b43_bus_dev * dev) [inline, static]
Definition at line 53 of file bus.h.
References B43_BUS_SSB, b43_bus_dev::bus_type, and b43_bus_dev::sdev.
Referenced by b43_wireless_core_init().
static bool b43_bus_host_is_sdio (struct b43_bus_dev * dev) [inline, static]
Definition at line 58 of file bus.h.
References B43_BUS_SSB, b43_bus_dev::bus_type, and b43_bus_dev::sdev.
Referenced by b43_beacon_update_trigger_work(), b43_wireless_core_init(), b43_wireless_core_start(), and b43_wireless_core_stop().
void b43_bus_set_wldev (struct b43_bus_dev * dev, void * data)
Definition at line 243 of file bus.c.
References B43_BUS_SSB, b43_bus_dev::bdev, b43_bus_dev::bus_type, and b43_bus_dev::sdev.
Referenced by b43_one_core_attach(), and b43_one_core_detach().