CompatWireless3.2: drivers/net/wireless/b43/bus.c File Reference
drivers/net/wireless/b43/bus.c File Reference
#include "b43.h"
#include <linux/kernel.h>
#include <linux/spinlock.h>
#include <linux/interrupt.h>
#include <linux/hw_random.h>
#include <linux/bcma/bcma.h>
#include <linux/ssb/ssb.h>
#include <net/mac80211.h>
#include "debugfs.h"
#include "leds.h"
#include "rfkill.h"
#include "bus.h"
#include "lo.h"
#include "phy_common.h"
Functions
void * b43_bus_get_wldev (struct b43_bus_dev *dev)
void b43_bus_set_wldev (struct b43_bus_dev *dev, void *wldev)
Function Documentation
void* b43_bus_get_wldev (struct b43_bus_dev * dev)
Definition at line 228 of file bus.c.
References B43_BUS_SSB, b43_bus_dev::bdev, b43_bus_dev::bus_type, and b43_bus_dev::sdev.
Referenced by b43_one_core_detach().
void b43_bus_set_wldev (struct b43_bus_dev * dev, void * wldev)
Definition at line 243 of file bus.c.
References B43_BUS_SSB, b43_bus_dev::bdev, b43_bus_dev::bus_type, and b43_bus_dev::sdev.
Referenced by b43_one_core_attach(), and b43_one_core_detach().