CompatWireless3.2: drivers/net/wireless/b43/debugfs.c File Reference
drivers/net/wireless/b43/debugfs.c File Reference
#include <linux/fs.h>
#include <linux/debugfs.h>
#include <linux/slab.h>
#include <linux/netdevice.h>
#include <linux/pci.h>
#include <linux/mutex.h>
#include "b43.h"
#include "main.h"
#include "debugfs.h"
#include <linux/err.h>
#include "main.h"
#include <net/mac80211.h>
Data Structures
struct b43_debugfs_fops
Defines
#define fappend(fmt, x...)
#define B43_MAX_SHM_ROUTING 4
#define B43_MAX_SHM_ADDR 0xFFFF
#define B43_MAX_MMIO_ACCESS (0xF00 - 1)
#define B43_DEBUGFS_FOPS(name, _read, _write)
#define add_dyn_dbg(name, id, initstate)
#define ADD_FILE(name, mode)
Functions
static struct b43_dfs_file * fops_to_dfs_file (struct b43_wldev *dev, const struct b43_debugfs_fops *dfops)
static ssize_t shm16read__read_file (struct b43_wldev *dev, char *buf, size_t bufsize)
static int shm16read__write_file (struct b43_wldev *dev, const char *buf, size_t count)
static int shm16write__write_file (struct b43_wldev *dev, const char *buf, size_t count)
static ssize_t shm32read__read_file (struct b43_wldev *dev, char *buf, size_t bufsize)
static int shm32read__write_file (struct b43_wldev *dev, const char *buf, size_t count)
static int shm32write__write_file (struct b43_wldev *dev, const char *buf, size_t count)
static ssize_t mmio16read__read_file (struct b43_wldev *dev, char *buf, size_t bufsize)
static int mmio16read__write_file (struct b43_wldev *dev, const char *buf, size_t count)
static int mmio16write__write_file (struct b43_wldev *dev, const char *buf, size_t count)
static ssize_t mmio32read__read_file (struct b43_wldev *dev, char *buf, size_t bufsize)
static int mmio32read__write_file (struct b43_wldev *dev, const char *buf, size_t count)
static int mmio32write__write_file (struct b43_wldev *dev, const char *buf, size_t count)
static ssize_t txstat_read_file (struct b43_wldev *dev, char *buf, size_t bufsize)
static int restart_write_file (struct b43_wldev *dev, const char *buf, size_t count)
static unsigned long calc_expire_secs (unsigned long now, unsigned long time, unsigned long expire)
static ssize_t loctls_read_file (struct b43_wldev *dev, char *buf, size_t bufsize)
static int b43_debugfs_open (struct inode *inode, struct file *file)
static ssize_t b43_debugfs_read (struct file *file, char __user *userbuf, size_t count, loff_t *ppos)
static ssize_t b43_debugfs_write (struct file *file, const char __user *userbuf, size_t count, loff_t *ppos)
B43_DEBUGFS_FOPS (shm16read, shm16read__read_file, shm16read__write_file)
B43_DEBUGFS_FOPS (shm16write, NULL, shm16write__write_file)
B43_DEBUGFS_FOPS (shm32read, shm32read__read_file, shm32read__write_file)
B43_DEBUGFS_FOPS (shm32write, NULL, shm32write__write_file)
B43_DEBUGFS_FOPS (mmio16read, mmio16read__read_file, mmio16read__write_file)
B43_DEBUGFS_FOPS (mmio16write, NULL, mmio16write__write_file)
B43_DEBUGFS_FOPS (mmio32read, mmio32read__read_file, mmio32read__write_file)
B43_DEBUGFS_FOPS (mmio32write, NULL, mmio32write__write_file)
B43_DEBUGFS_FOPS (txstat, txstat_read_file, NULL)
B43_DEBUGFS_FOPS (restart, NULL, restart_write_file)
B43_DEBUGFS_FOPS (loctls, loctls_read_file, NULL)
bool b43_debug (struct b43_wldev *dev, enum b43_dyndbg feature)
static void b43_remove_dynamic_debug (struct b43_wldev *dev)
static void b43_add_dynamic_debug (struct b43_wldev *dev)
void b43_debugfs_add_device (struct b43_wldev *dev)
void b43_debugfs_remove_device (struct b43_wldev *dev)
void b43_debugfs_log_txstat (struct b43_wldev *dev, const struct b43_txstatus *status)
void b43_debugfs_init (void)
void b43_debugfs_exit (void)
Variables
static struct dentry * rootdir
Define Documentation
#define add_dyn_dbg (name, id, initstate)
Value:
do {            \
        e->dyn_debug[id] = (initstate);                 \
        d = debugfs_create_bool(name, 0600, e->subdir,  \
                                &(e->dyn_debug[id]));   \
        if (!IS_ERR(d))                                 \
                e->dyn_debug_dentries[id] = d;          \
                                } while (0)
Referenced by b43_add_dynamic_debug().
#define ADD_FILE (name, mode)
Value:
do {                                                    \
                struct dentry *d;                               \
                d = debugfs_create_file(__stringify(name),      \
                                        mode, e->subdir, dev,   \
                                        &fops_##name.fops);     \
                e->file_##name.dentry = NULL;                   \
                if (!IS_ERR(d))                                 \
                        e->file_##name.dentry = d;              \
        } while (0)
Referenced by b43_debugfs_add_device().
#define B43_DEBUGFS_FOPS (name, _read, _write)
Value:
static struct b43_debugfs_fops fops_##name = {          \
                .read   = _read,                                \
                .write  = _write,                               \
                .fops   = {                                     \
                        .open   = b43_debugfs_open,             \
                        .read   = b43_debugfs_read,             \
                        .write  = b43_debugfs_write,            \
                        .llseek = generic_file_llseek,          \
                },                                              \
                .file_struct_offset = offsetof(struct b43_dfsentry, \
                                               file_##name),    \
        }
Definition at line 622 of file debugfs.c.
#define B43_MAX_MMIO_ACCESS (0xF00 - 1)
Definition at line 232 of file debugfs.c.
Referenced by mmio16read__read_file(), mmio16read__write_file(), mmio16write__write_file(), mmio32read__read_file(), mmio32read__write_file(), and mmio32write__write_file().
#define B43_MAX_SHM_ADDR 0xFFFF
Definition at line 77 of file debugfs.c.
Referenced by shm16read__read_file(), shm16read__write_file(), shm16write__write_file(), shm32read__read_file(), shm32read__write_file(), and shm32write__write_file().
#define B43_MAX_SHM_ROUTING 4
Definition at line 76 of file debugfs.c.
Referenced by shm16read__read_file(), shm16read__write_file(), shm16write__write_file(), shm32read__read_file(), shm32read__write_file(), and shm32write__write_file().
#define fappend (fmt, x...)
Value:
do {                                                    \
                if (bufsize - count)                            \
                        count += snprintf(buf + count,          \
                                          bufsize - count,      \
                                          fmt , ##x);           \
                else                                            \
                        printk(KERN_ERR "b43: fappend overflow\n"); \
        } while (0)
Definition at line 64 of file debugfs.c.
Referenced by loctls_read_file(), mmio16read__read_file(), mmio32read__read_file(), shm16read__read_file(), shm32read__read_file(), and txstat_read_file().
Function Documentation
static void b43_add_dynamic_debug (struct b43_wldev * dev) [static]
Definition at line 672 of file debugfs.c.
References add_dyn_dbg, B43_DBG_DMAOVERFLOW, B43_DBG_DMAVERBOSE, B43_DBG_FIRMWARE, B43_DBG_KEYS, B43_DBG_LO, B43_DBG_PWORK_FAST, B43_DBG_PWORK_STOP, B43_DBG_VERBOSESTATS, and B43_DBG_XMITPOWER.
Referenced by b43_debugfs_add_device().
bool b43_debug (struct b43_wldev * dev, enum b43_dyndbg feature)
Definition at line 649 of file debugfs.c.
References b43_modparam_verbose, and B43_VERBOSITY_MAX.
Referenced by b43_calibrate_lo_setting(), b43_dma_handle_txstatus(), b43_dma_tx(), b43_do_interrupt_thread(), b43_dump_keymemory(), b43_gphy_op_adjust_txpower(), b43_gphy_op_recalc_txpower(), b43_lo_g_maintanance_work(), b43_mac_enable(), b43_periodic_every15sec(), b43_periodic_work_handler(), b43_set_txpower_g(), rx_tkip_phase1_write(), and should_inject_overflow().
void b43_debugfs_add_device (struct b43_wldev * dev)
Definition at line 698 of file debugfs.c.
References ADD_FILE, b43_add_dynamic_debug(), B43_WARN_ON, b43dbg(), b43err(), b43_wl::hw, rootdir, and b43_wldev::wl.
Referenced by b43_one_core_attach().
void b43_debugfs_exit (void)
Definition at line 829 of file debugfs.c.
References rootdir.
Referenced by b43_exit(), and b43_init().
B43_DEBUGFS_FOPS (loctls , loctls_read_file , NULL)
B43_DEBUGFS_FOPS (restart , NULL , restart_write_file)
B43_DEBUGFS_FOPS (txstat , txstat_read_file , NULL)
B43_DEBUGFS_FOPS (mmio32write , NULL , mmio32write__write_file)
B43_DEBUGFS_FOPS (mmio32read , mmio32read__read_file , mmio32read__write_file)
B43_DEBUGFS_FOPS (mmio16write , NULL , mmio16write__write_file)
B43_DEBUGFS_FOPS (mmio16read , mmio16read__read_file , mmio16read__write_file)
B43_DEBUGFS_FOPS (shm32write , NULL , shm32write__write_file)
B43_DEBUGFS_FOPS (shm32read , shm32read__read_file , shm32read__write_file)
B43_DEBUGFS_FOPS (shm16write , NULL , shm16write__write_file)
B43_DEBUGFS_FOPS (shm16read , shm16read__read_file , shm16read__write_file)
void b43_debugfs_init (void)
Definition at line 822 of file debugfs.c.
References rootdir.
Referenced by b43_init().
void b43_debugfs_log_txstat (struct b43_wldev * dev, const struct b43_txstatus * status)
Definition at line 803 of file debugfs.c.
Referenced by b43_handle_txstatus().
static int b43_debugfs_open (struct inode * inode, struct file * file) [static]
Definition at line 503 of file debugfs.c.
static ssize_t b43_debugfs_read (struct file * file, char __user * userbuf, size_t count, loff_t * ppos) [static]
Definition at line 509 of file debugfs.c.
References B43_STAT_INITIALIZED, b43_status, b43_wldev::dev, fops_to_dfs_file(), b43_wl::mutex, b43_debugfs_fops::read, and b43_wldev::wl.
void b43_debugfs_remove_device (struct b43_wldev * dev)
Definition at line 775 of file debugfs.c.
References b43_remove_dynamic_debug().
Referenced by b43_one_core_detach().
static ssize_t b43_debugfs_write (struct file * file, const char __user * userbuf, size_t count, loff_t * ppos) [static]
Definition at line 571 of file debugfs.c.
References B43_STAT_INITIALIZED, b43_status, b43_wldev::dev, b43_debugfs_fops::fops, b43_wl::mutex, b43_wldev::wl, and b43_debugfs_fops::write.
static void b43_remove_dynamic_debug (struct b43_wldev * dev) [static]
Definition at line 663 of file debugfs.c.
References __B43_NR_DYNDBG.
Referenced by b43_debugfs_remove_device().
static unsigned long calc_expire_secs (unsigned long now, unsigned long time, unsigned long expire) [static]
Definition at line 420 of file debugfs.c.
References B43_WARN_ON.
Referenced by loctls_read_file().
static struct b43_dfs_file* fops_to_dfs_file (struct b43_wldev * dev, const struct b43_debugfs_fops * dfops) [static, read]
Definition at line 52 of file debugfs.c.
References b43_debugfs_fops::file_struct_offset.
Referenced by b43_debugfs_read().
static ssize_t loctls_read_file (struct b43_wldev * dev, char * buf, size_t bufsize) [static]
Definition at line 438 of file debugfs.c.
References b43_rfatt::att, b43_bbatt::att, b43_compare_bbatt(), b43_compare_rfatt(), B43_LO_CALIB_EXPIRE, B43_LO_PWRVEC_EXPIRE, B43_LO_TXCTL_EXPIRE, B43_PHYTYPE_G, b43_phy_g::bbatt, b43_lo_calib::bbatt, b43_txpower_lo_control::bbatt_list, calc_expire_secs(), b43_txpower_lo_control::calib_list, b43_lo_calib::calib_time, b43_lo_calib::ctl, fappend, b43_phy::g, b43_phy::hardware_power_control, b43_loctl::i, b43_bbatt_list::len, b43_rfatt_list::len, b43_bbatt_list::list, b43_rfatt_list::list, b43_phy_g::lo_control, b43_wldev::phy, b43_txpower_lo_control::power_vector, b43_txpower_lo_control::pwr_vec_read_time, b43_loctl::q, b43_phy_g::rfatt, b43_lo_calib::rfatt, b43_txpower_lo_control::rfatt_list, b43_txpower_lo_control::tx_bias, b43_txpower_lo_control::tx_magn, b43_txpower_lo_control::txctl_measured_time, b43_phy::type, and b43_rfatt::with_padmix.
static ssize_t mmio16read__read_file (struct b43_wldev * dev, char * buf, size_t bufsize) [static]
Definition at line 234 of file debugfs.c.
References B43_MAX_MMIO_ACCESS, b43_read16(), and fappend.
static int mmio16read__write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 251 of file debugfs.c.
References B43_MAX_MMIO_ACCESS.
static int mmio16write__write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 270 of file debugfs.c.
References B43_MAX_MMIO_ACCESS, b43_read16(), and b43_write16().
static ssize_t mmio32read__read_file (struct b43_wldev * dev, char * buf, size_t bufsize) [static]
Definition at line 298 of file debugfs.c.
References B43_MAX_MMIO_ACCESS, b43_read32(), and fappend.
static int mmio32read__write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 315 of file debugfs.c.
References B43_MAX_MMIO_ACCESS.
static int mmio32write__write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 334 of file debugfs.c.
References B43_MAX_MMIO_ACCESS, b43_read32(), and b43_write32().
static int restart_write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 407 of file debugfs.c.
References b43_controller_restart().
static ssize_t shm16read__read_file (struct b43_wldev * dev, char * buf, size_t bufsize) [static]
Definition at line 79 of file debugfs.c.
References B43_MAX_SHM_ADDR, B43_MAX_SHM_ROUTING, b43_shm_read16(), and fappend.
static int shm16read__write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 98 of file debugfs.c.
References B43_MAX_SHM_ADDR, B43_MAX_SHM_ROUTING, and B43_SHM_SHARED.
static int shm16write__write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 122 of file debugfs.c.
References B43_MAX_SHM_ADDR, B43_MAX_SHM_ROUTING, b43_shm_read16(), B43_SHM_SHARED, and b43_shm_write16().
static ssize_t shm32read__read_file (struct b43_wldev * dev, char * buf, size_t bufsize) [static]
Definition at line 155 of file debugfs.c.
References B43_MAX_SHM_ADDR, B43_MAX_SHM_ROUTING, b43_shm_read32(), and fappend.
static int shm32read__write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 174 of file debugfs.c.
References B43_MAX_SHM_ADDR, B43_MAX_SHM_ROUTING, and B43_SHM_SHARED.
static int shm32write__write_file (struct b43_wldev * dev, const char * buf, size_t count) [static]
Definition at line 198 of file debugfs.c.
References B43_MAX_SHM_ADDR, B43_MAX_SHM_ROUTING, b43_shm_read32(), B43_SHM_SHARED, and b43_shm_write32().
static ssize_t txstat_read_file (struct b43_wldev * dev, char * buf, size_t bufsize) [static]
Definition at line 362 of file debugfs.c.
References b43_txstatus::acked, b43_txstatus::cookie, fappend, b43_txstatus::for_ampdu, b43_txstatus::frame_count, b43_txstatus::intermediate, b43_txstatus::phy_stat, b43_txstatus::pm_indicated, b43_txstatus::rts_count, b43_txstatus::seq, and b43_txstatus::supp_reason.
Variable Documentation
struct dentry* rootdir [static]
Definition at line 41 of file debugfs.c.
Referenced by b43_debugfs_add_device(), b43_debugfs_exit(), and b43_debugfs_init().