CompatWireless3.2: drivers/net/wireless/b43/dma.c File Reference
drivers/net/wireless/b43/dma.c File Reference
#include "b43.h"
#include "dma.h"
#include "main.h"
#include "debugfs.h"
#include "xmit.h"
#include <linux/dma-mapping.h>
#include <linux/pci.h>
#include <linux/delay.h>
#include <linux/skbuff.h>
#include <linux/etherdevice.h>
#include <linux/slab.h>
#include <asm/div64.h>
Defines
#define TX_SLOTS_PER_FRAME 2
#define divide(a, b)
#define modulo(a, b)
#define destroy_ring(dma, ring)
Functions
static u32 b43_dma_address (struct b43_dma *dma, dma_addr_t dmaaddr, enum b43_addrtype addrtype)
static struct b43_dmadesc_generic * op32_idx2desc (struct b43_dmaring *ring, int slot, struct b43_dmadesc_meta **meta)
static void op32_fill_descriptor (struct b43_dmaring *ring, struct b43_dmadesc_generic *desc, dma_addr_t dmaaddr, u16 bufsize, int start, int end, int irq)
static void op32_poke_tx (struct b43_dmaring *ring, int slot)
static void op32_tx_suspend (struct b43_dmaring *ring)
static void op32_tx_resume (struct b43_dmaring *ring)
static int op32_get_current_rxslot (struct b43_dmaring *ring)
static void op32_set_current_rxslot (struct b43_dmaring *ring, int slot)
static struct b43_dmadesc_generic * op64_idx2desc (struct b43_dmaring *ring, int slot, struct b43_dmadesc_meta **meta)
static void op64_fill_descriptor (struct b43_dmaring *ring, struct b43_dmadesc_generic *desc, dma_addr_t dmaaddr, u16 bufsize, int start, int end, int irq)
static void op64_poke_tx (struct b43_dmaring *ring, int slot)
static void op64_tx_suspend (struct b43_dmaring *ring)
static void op64_tx_resume (struct b43_dmaring *ring)
static int op64_get_current_rxslot (struct b43_dmaring *ring)
static void op64_set_current_rxslot (struct b43_dmaring *ring, int slot)
static int free_slots (struct b43_dmaring *ring)
static int next_slot (struct b43_dmaring *ring, int slot)
static int prev_slot (struct b43_dmaring *ring, int slot)
static void update_max_used_slots (struct b43_dmaring *ring, int current_used_slots)
static int request_slot (struct b43_dmaring *ring)
static u16 b43_dmacontroller_base (enum b43_dmatype type, int controller_idx)
static dma_addr_t map_descbuffer (struct b43_dmaring *ring, unsigned char *buf, size_t len, int tx)
static void unmap_descbuffer (struct b43_dmaring *ring, dma_addr_t addr, size_t len, int tx)
static void sync_descbuffer_for_cpu (struct b43_dmaring *ring, dma_addr_t addr, size_t len)
static void sync_descbuffer_for_device (struct b43_dmaring *ring, dma_addr_t addr, size_t len)
static void free_descriptor_buffer (struct b43_dmaring *ring, struct b43_dmadesc_meta *meta)
static int alloc_ringmemory (struct b43_dmaring *ring)
static void free_ringmemory (struct b43_dmaring *ring)
static int b43_dmacontroller_rx_reset (struct b43_wldev *dev, u16 mmio_base, enum b43_dmatype type)
static int b43_dmacontroller_tx_reset (struct b43_wldev *dev, u16 mmio_base, enum b43_dmatype type)
static bool b43_dma_mapping_error (struct b43_dmaring *ring, dma_addr_t addr, size_t buffersize, bool dma_to_device)
static bool b43_rx_buffer_is_poisoned (struct b43_dmaring *ring, struct sk_buff *skb)
static void b43_poison_rx_buffer (struct b43_dmaring *ring, struct sk_buff *skb)
static int setup_rx_descbuffer (struct b43_dmaring *ring, struct b43_dmadesc_generic *desc, struct b43_dmadesc_meta *meta, gfp_t gfp_flags)
static int alloc_initial_descbuffers (struct b43_dmaring *ring)
static int dmacontroller_setup (struct b43_dmaring *ring)
static void dmacontroller_cleanup (struct b43_dmaring *ring)
static void free_all_descbuffers (struct b43_dmaring *ring)
static u64 supported_dma_mask (struct b43_wldev *dev)
static enum b43_dmatype dma_mask_to_engine_type (u64 dmamask)
static struct b43_dmaring * b43_setup_dmaring (struct b43_wldev *dev, int controller_index, int for_tx, enum b43_dmatype type)
static void b43_destroy_dmaring (struct b43_dmaring *ring, const char *ringname)
void b43_dma_free (struct b43_wldev *dev)
static int b43_dma_set_mask (struct b43_wldev *dev, u64 mask)
static bool b43_dma_translation_in_low_word (struct b43_wldev *dev, enum b43_dmatype type)
int b43_dma_init (struct b43_wldev *dev)
static u16 generate_cookie (struct b43_dmaring *ring, int slot)
static struct b43_dmaring * parse_cookie (struct b43_wldev *dev, u16 cookie, int *slot)
static int dma_tx_fragment (struct b43_dmaring *ring, struct sk_buff *skb)
static int should_inject_overflow (struct b43_dmaring *ring)
static struct b43_dmaring * select_ring_by_priority (struct b43_wldev *dev, u8 queue_prio)
int b43_dma_tx (struct b43_wldev *dev, struct sk_buff *skb)
void b43_dma_handle_txstatus (struct b43_wldev *dev, const struct b43_txstatus *status)
static void dma_rx (struct b43_dmaring *ring, int *slot)
void b43_dma_rx (struct b43_dmaring *ring)
static void b43_dma_tx_suspend_ring (struct b43_dmaring *ring)
static void b43_dma_tx_resume_ring (struct b43_dmaring *ring)
void b43_dma_tx_suspend (struct b43_wldev *dev)
void b43_dma_tx_resume (struct b43_wldev *dev)
static void direct_fifo_rx (struct b43_wldev *dev, enum b43_dmatype type, u16 mmio_base, bool enable)
void b43_dma_direct_fifo_rx (struct b43_wldev *dev, unsigned int engine_index, bool enable)
Variables
static struct b43_dma_ops dma32_ops
static struct b43_dma_ops dma64_ops
Define Documentation
#define destroy_ring (dma, ring)
Value:
do {                            \
        b43_destroy_dmaring((dma)->ring, __stringify(ring));    \
        (dma)->ring = NULL;                                     \
    } while (0)
Definition at line 1040 of file dma.c.
Referenced by b43_dma_free(), and b43_dma_init().
#define divide (a, b)
Value:
({      \
        typeof(a) __a = a;      \
        do_div(__a, b);         \
        __a;                    \
  })
Definition at line 982 of file dma.c.
Referenced by b43_destroy_dmaring().
#define modulo (a, b)
Value:
({      \
        typeof(a) __a = a;      \
        do_div(__a, b);         \
  })
Definition at line 988 of file dma.c.
Referenced by b43_destroy_dmaring().
#define TX_SLOTS_PER_FRAME 2
Definition at line 48 of file dma.c.
Referenced by b43_dma_handle_txstatus(), b43_dma_tx(), b43_setup_dmaring(), and dma_tx_fragment().
Function Documentation
static int alloc_initial_descbuffers (struct b43_dmaring * ring) [static]
Definition at line 651 of file dma.c.
References b43err(), b43_dmaring::dev, b43_dmadesc_meta::dmaaddr, b43_dma_ops::idx2desc, b43_dmaring::nr_slots, b43_dmaring::ops, b43_dmaring::rx_buffersize, setup_rx_descbuffer(), b43_dmadesc_meta::skb, unmap_descbuffer(), b43_dmaring::used_slots, and b43_wldev::wl.
Referenced by dmacontroller_setup().
static int alloc_ringmemory (struct b43_dmaring * ring) [static]
Definition at line 417 of file dma.c.
References B43_DMA32_RINGMEMSIZE, B43_DMA64_RINGMEMSIZE, B43_DMA_64BIT, b43err(), b43_dmaring::descbase, b43_wldev::dev, b43_dmaring::dev, b43_bus_dev::dma_dev, b43_dmaring::dmabase, b43_dmaring::type, and b43_wldev::wl.
Referenced by b43_setup_dmaring().
static void b43_destroy_dmaring (struct b43_dmaring * ring, const char * ringname) [static]
Definition at line 994 of file dma.c.
References b43dbg(), b43_dmaring::dev, divide, dmacontroller_cleanup(), free_all_descbuffers(), free_ringmemory(), b43_dmaring::meta, modulo, b43_dmaring::nr_slots, b43_dmaring::txhdr_cache, b43_dmaring::type, and b43_wldev::wl.
static u32 b43_dma_address (struct b43_dma * dma, dma_addr_t dmaaddr, enum b43_addrtype addrtype) [static]
Definition at line 50 of file dma.c.
References B43_DMA_ADDR_EXT, B43_DMA_ADDR_HIGH, B43_DMA_ADDR_LOW, b43_dma::translation, and b43_dma::translation_in_low.
Referenced by dmacontroller_setup(), op32_fill_descriptor(), and op64_fill_descriptor().
void b43_dma_direct_fifo_rx (struct b43_wldev * dev, unsigned int engine_index, bool enable)
Definition at line 1755 of file dma.c.
References b43_dmacontroller_base(), direct_fifo_rx(), dma_mask_to_engine_type(), and supported_dma_mask().
Referenced by b43_setup_pioqueue_rx().
void b43_dma_free (struct b43_wldev * dev)
Definition at line 1045 of file dma.c.
References b43_using_pio_transfers(), destroy_ring, b43_wldev::dma, b43_dma::rx_ring, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, and b43_dma::tx_ring_mcast.
Referenced by b43_wireless_core_exit().
void b43_dma_handle_txstatus (struct b43_wldev * dev, const struct b43_txstatus * status)
Definition at line 1479 of file dma.c.
References B43_DBG_DMAVERBOSE, b43_debug(), b43_dma_ptr_is_poisoned, B43_DMA_PTR_POISON, b43_fill_txstatus_report(), b43_get_priv_tx_info(), b43_txhdr_size(), B43_WARN_ON, b43dbg(), b43_private_tx_info::bouncebuffer, b43_txstatus::cookie, b43_dmaring::current_slot, b43_dmadesc_meta::dmaaddr, b43_txstatus::frame_count, free_slots(), b43_wl::hw, b43_dma_ops::idx2desc, b43_dmaring::index, b43_dmadesc_meta::is_last_fragment, next_slot(), b43_dmaring::nr_slots, b43_dmaring::ops, parse_cookie(), b43_dmaring::queue_prio, b43_dmadesc_meta::skb, b43_dmaring::stopped, b43_dmaring::tx, TX_SLOTS_PER_FRAME, unmap_descbuffer(), b43_dmaring::used_slots, and b43_wldev::wl.
Referenced by b43_handle_txstatus().
int b43_dma_init (struct b43_wldev * dev)
Definition at line 1119 of file dma.c.
References B43_BUS_SSB, b43_dma_set_mask(), b43_dma_translation_in_low_word(), b43_setup_dmaring(), B43_WARN_ON, b43dbg(), b43_bus_dev::bdev, b43_bus_dev::bus_type, b43_bus_dev::core_rev, destroy_ring, b43_wldev::dev, b43_wldev::dma, dma_mask_to_engine_type(), b43_dma::parity, b43_dma::rx_ring, b43_bus_dev::sdev, supported_dma_mask(), b43_dma::translation, b43_dma::translation_in_low, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, b43_dma::tx_ring_mcast, and b43_wldev::wl.
Referenced by b43_wireless_core_init().
static bool b43_dma_mapping_error (struct b43_dmaring * ring, dma_addr_t addr, size_t buffersize, bool dma_to_device) [static]
Definition at line 553 of file dma.c.
References B43_DMA_30BIT, B43_DMA_32BIT, B43_DMA_64BIT, b43_wldev::dev, b43_dmaring::dev, b43_bus_dev::dma_dev, b43_dmaring::type, and unmap_descbuffer().
Referenced by b43_setup_dmaring(), dma_tx_fragment(), and setup_rx_descbuffer().
void b43_dma_rx (struct b43_dmaring * ring)
Definition at line 1681 of file dma.c.
References B43_WARN_ON, b43_dmaring::current_slot, dma_rx(), b43_dma_ops::get_current_rxslot, next_slot(), b43_dmaring::ops, b43_dma_ops::set_current_rxslot, b43_dmaring::tx, and update_max_used_slots().
Referenced by b43_do_interrupt_thread().
static int b43_dma_set_mask (struct b43_wldev * dev, u64 mask) [static]
Definition at line 1061 of file dma.c.
References b43err(), b43info(), b43_wldev::dev, b43_bus_dev::dma_dev, dma_mask_to_engine_type(), and b43_wldev::wl.
Referenced by b43_dma_init().
static bool b43_dma_translation_in_low_word (struct b43_wldev * dev, enum b43_dmatype type) [static]
Definition at line 1103 of file dma.c.
References B43_BUS_SSB, B43_DMA_64BIT, b43_bus_dev::bus_type, b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_dma_init().
int b43_dma_tx (struct b43_wldev * dev, struct sk_buff * skb)
Definition at line 1407 of file dma.c.
References B43_DBG_DMAVERBOSE, b43_debug(), B43_WARN_ON, b43dbg(), b43err(), b43_wldev::dma, dma_tx_fragment(), free_slots(), b43_wl::hw, b43_dmaring::index, b43_dmaring::queue_prio, select_ring_by_priority(), should_inject_overflow(), b43_dmaring::stopped, b43_dmaring::tx, b43_dma::tx_ring_mcast, TX_SLOTS_PER_FRAME, and b43_wldev::wl.
Referenced by b43_tx_work().
void b43_dma_tx_resume (struct b43_wldev * dev)
Definition at line 1723 of file dma.c.
References b43_dma_tx_resume_ring(), b43_power_saving_ctl_bits(), b43_wldev::dma, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, and b43_dma::tx_ring_mcast.
Referenced by b43_tx_resume().
static void b43_dma_tx_resume_ring (struct b43_dmaring * ring) [static]
Definition at line 1707 of file dma.c.
References B43_WARN_ON, b43_dmaring::ops, b43_dmaring::tx, and b43_dma_ops::tx_resume.
Referenced by b43_dma_tx_resume().
void b43_dma_tx_suspend (struct b43_wldev * dev)
Definition at line 1713 of file dma.c.
References b43_dma_tx_suspend_ring(), b43_power_saving_ctl_bits(), B43_PS_AWAKE, b43_wldev::dma, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, and b43_dma::tx_ring_mcast.
Referenced by b43_tx_suspend().
static void b43_dma_tx_suspend_ring (struct b43_dmaring * ring) [static]
Definition at line 1701 of file dma.c.
References B43_WARN_ON, b43_dmaring::ops, b43_dmaring::tx, and b43_dma_ops::tx_suspend.
Referenced by b43_dma_tx_suspend().
static u16 b43_dmacontroller_base (enum b43_dmatype type, int controller_idx) [static]
Definition at line 330 of file dma.c.
References B43_DMA_64BIT, B43_MMIO_DMA32_BASE0, B43_MMIO_DMA32_BASE1, B43_MMIO_DMA32_BASE2, B43_MMIO_DMA32_BASE3, B43_MMIO_DMA32_BASE4, B43_MMIO_DMA32_BASE5, B43_MMIO_DMA64_BASE0, B43_MMIO_DMA64_BASE1, B43_MMIO_DMA64_BASE2, B43_MMIO_DMA64_BASE3, B43_MMIO_DMA64_BASE4, B43_MMIO_DMA64_BASE5, and B43_WARN_ON.
Referenced by b43_dma_direct_fifo_rx(), b43_setup_dmaring(), and supported_dma_mask().
static int b43_dmacontroller_rx_reset (struct b43_wldev * dev, u16 mmio_base, enum b43_dmatype type) [static]
Definition at line 454 of file dma.c.
References B43_DMA32_RXCTL, B43_DMA32_RXSTAT_DISABLED, B43_DMA32_RXSTATE, B43_DMA32_RXSTATUS, B43_DMA64_RXCTL, B43_DMA64_RXSTAT, B43_DMA64_RXSTAT_DISABLED, B43_DMA64_RXSTATUS, B43_DMA_64BIT, b43_read32(), b43_write32(), b43err(), and b43_wldev::wl.
Referenced by dmacontroller_cleanup().
static int b43_dmacontroller_tx_reset (struct b43_wldev * dev, u16 mmio_base, enum b43_dmatype type) [static]
Definition at line 493 of file dma.c.
References B43_DMA32_TXCTL, B43_DMA32_TXSTAT_DISABLED, B43_DMA32_TXSTAT_IDLEWAIT, B43_DMA32_TXSTAT_STOPPED, B43_DMA32_TXSTATE, B43_DMA32_TXSTATUS, B43_DMA64_TXCTL, B43_DMA64_TXSTAT, B43_DMA64_TXSTAT_DISABLED, B43_DMA64_TXSTAT_IDLEWAIT, B43_DMA64_TXSTAT_STOPPED, B43_DMA64_TXSTATUS, B43_DMA_64BIT, b43_read32(), b43_write32(), b43err(), and b43_wldev::wl.
Referenced by dmacontroller_cleanup().
static void b43_poison_rx_buffer (struct b43_dmaring * ring, struct sk_buff * skb) [static]
Definition at line 592 of file dma.c.
References B43_WARN_ON, b43_rxhdr_fw4::frame_len, b43_dmaring::frameoffset, and b43_dmaring::rx_buffersize.
Referenced by dma_rx(), and setup_rx_descbuffer().
static bool b43_rx_buffer_is_poisoned (struct b43_dmaring * ring, struct sk_buff * skb) [static]
Definition at line 585 of file dma.c.
References b43_dmaring::frameoffset.
Referenced by dma_rx().
static struct b43_dmaring* b43_setup_dmaring (struct b43_wldev * dev, int controller_index, int for_tx, enum b43_dmatype type) [static, read]
Definition at line 860 of file dma.c.
References alloc_ringmemory(), B43_DMA0_RX_FW351_BUFSIZE, B43_DMA0_RX_FW351_FO, B43_DMA0_RX_FW598_BUFSIZE, B43_DMA0_RX_FW598_FO, B43_DMA_64BIT, b43_dma_mapping_error(), B43_DMA_PTR_POISON, b43_dmacontroller_base(), B43_FW_HDR_351, B43_FW_HDR_410, B43_FW_HDR_598, B43_RXRING_SLOTS, b43_txhdr_size(), B43_TXRING_SLOTS, B43_WARN_ON, b43err(), b43_dmaring::current_slot, b43_wldev::dev, b43_dmaring::dev, b43_bus_dev::dma_dev, dmacontroller_setup(), b43_dmaring::frameoffset, free_ringmemory(), b43_wldev::fw, b43_firmware::hdr_format, b43_dmaring::index, b43_dmaring::meta, b43_dmaring::mmio_base, b43_dmaring::nr_slots, b43_dmaring::ops, b43_dmaring::rx_buffersize, b43_dmadesc_meta::skb, b43_dmaring::tx, TX_SLOTS_PER_FRAME, b43_dmaring::txhdr_cache, b43_dmaring::type, and b43_wldev::wl.
Referenced by b43_dma_init().
static void direct_fifo_rx (struct b43_wldev * dev, enum b43_dmatype type, u16 mmio_base, bool enable) [static]
Definition at line 1733 of file dma.c.
References B43_DMA32_RXCTL, B43_DMA32_RXDIRECTFIFO, B43_DMA64_RXCTL, B43_DMA64_RXDIRECTFIFO, B43_DMA_64BIT, b43_read32(), and b43_write32().
Referenced by b43_dma_direct_fifo_rx().
static enum b43_dmatype dma_mask_to_engine_type (u64 dmamask) [static]
Definition at line 846 of file dma.c.
References B43_DMA_30BIT, B43_DMA_32BIT, B43_DMA_64BIT, and B43_WARN_ON.
Referenced by b43_dma_direct_fifo_rx(), b43_dma_init(), and b43_dma_set_mask().
static void dma_rx (struct b43_dmaring * ring, int * slot) [static]
Definition at line 1595 of file dma.c.
References b43_poison_rx_buffer(), b43_rx(), b43_rx_buffer_is_poisoned(), b43dbg(), b43err(), b43_dmaring::dev, b43_dmadesc_meta::dmaaddr, b43_rxhdr_fw4::frame_len, b43_dmaring::frameoffset, b43_dma_ops::idx2desc, next_slot(), b43_dmaring::ops, b43_dmaring::rx_buffersize, setup_rx_descbuffer(), b43_dmadesc_meta::skb, sync_descbuffer_for_cpu(), sync_descbuffer_for_device(), unmap_descbuffer(), and b43_wldev::wl.
Referenced by b43_dma_rx().
static int dma_tx_fragment (struct b43_dmaring * ring, struct sk_buff * skb) [static]
Definition at line 1256 of file dma.c.
References b43_dma_mapping_error(), b43_generate_txhdr(), b43_get_priv_tx_info(), B43_SHM_SH_MCASTCOOKIE, B43_SHM_SHARED, b43_shm_write16(), b43_txhdr_size(), b43_private_tx_info::bouncebuffer, b43_dmaring::current_slot, b43_dmaring::dev, b43_dmadesc_meta::dmaaddr, b43_dma_ops::fill_descriptor, generate_cookie(), b43_dma_ops::idx2desc, b43_dmadesc_meta::is_last_fragment, map_descbuffer(), next_slot(), b43_dmaring::ops, b43_dma_ops::poke_tx, request_slot(), b43_dmadesc_meta::skb, TX_SLOTS_PER_FRAME, b43_dmaring::txhdr_cache, unmap_descbuffer(), and b43_dmaring::used_slots.
Referenced by b43_dma_tx().
static void dmacontroller_cleanup (struct b43_dmaring * ring) [static]
Definition at line 768 of file dma.c.
References B43_DMA32_RXRING, B43_DMA32_TXRING, B43_DMA64_RXRINGHI, B43_DMA64_RXRINGLO, B43_DMA64_TXRINGHI, B43_DMA64_TXRINGLO, B43_DMA_64BIT, b43_dma_write(), b43_dmacontroller_rx_reset(), b43_dmacontroller_tx_reset(), b43_dmaring::dev, b43_dmaring::mmio_base, b43_dmaring::tx, and b43_dmaring::type.
Referenced by b43_destroy_dmaring().
static int dmacontroller_setup (struct b43_dmaring * ring) [static]
Definition at line 687 of file dma.c.
References alloc_initial_descbuffers(), B43_DMA32_RXADDREXT_MASK, B43_DMA32_RXADDREXT_SHIFT, B43_DMA32_RXCTL, B43_DMA32_RXENABLE, B43_DMA32_RXFROFF_SHIFT, B43_DMA32_RXINDEX, B43_DMA32_RXPARITYDISABLE, B43_DMA32_RXRING, B43_DMA32_TXADDREXT_MASK, B43_DMA32_TXADDREXT_SHIFT, B43_DMA32_TXCTL, B43_DMA32_TXENABLE, B43_DMA32_TXPARITYDISABLE, B43_DMA32_TXRING, B43_DMA64_RXADDREXT_MASK, B43_DMA64_RXADDREXT_SHIFT, B43_DMA64_RXCTL, B43_DMA64_RXENABLE, B43_DMA64_RXFROFF_SHIFT, B43_DMA64_RXINDEX, B43_DMA64_RXPARITYDISABLE, B43_DMA64_RXRINGHI, B43_DMA64_RXRINGLO, B43_DMA64_TXADDREXT_MASK, B43_DMA64_TXADDREXT_SHIFT, B43_DMA64_TXCTL, B43_DMA64_TXENABLE, B43_DMA64_TXPARITYDISABLE, B43_DMA64_TXRINGHI, B43_DMA64_TXRINGLO, B43_DMA_64BIT, B43_DMA_ADDR_EXT, B43_DMA_ADDR_HIGH, B43_DMA_ADDR_LOW, b43_dma_address(), b43_dma_write(), b43_dmaring::dev, b43_wldev::dma, b43_dmaring::dmabase, b43_dmaring::frameoffset, b43_dmaring::nr_slots, b43_dma::parity, b43_dmaring::tx, and b43_dmaring::type.
Referenced by b43_setup_dmaring().
static void free_all_descbuffers (struct b43_dmaring * ring) [static]
Definition at line 789 of file dma.c.
References b43_dma_ptr_is_poisoned, B43_WARN_ON, b43_dmadesc_meta::dmaaddr, free_descriptor_buffer(), b43_dma_ops::idx2desc, b43_dmaring::nr_slots, b43_dmaring::ops, b43_dmaring::rx_buffersize, b43_dmadesc_meta::skb, b43_dmaring::tx, unmap_descbuffer(), and b43_dmaring::used_slots.
Referenced by b43_destroy_dmaring().
static void free_descriptor_buffer (struct b43_dmaring * ring, struct b43_dmadesc_meta * meta) [inline, static]
Definition at line 408 of file dma.c.
References b43_dmadesc_meta::skb.
Referenced by free_all_descbuffers().
static void free_ringmemory (struct b43_dmaring * ring) [static]
Definition at line 445 of file dma.c.
References B43_DMA32_RINGMEMSIZE, B43_DMA64_RINGMEMSIZE, B43_DMA_64BIT, b43_dmaring::descbase, b43_wldev::dev, b43_dmaring::dev, b43_bus_dev::dma_dev, b43_dmaring::dmabase, and b43_dmaring::type.
Referenced by b43_destroy_dmaring(), and b43_setup_dmaring().
static int free_slots (struct b43_dmaring * ring) [inline, static]
Definition at line 270 of file dma.c.
References b43_dmaring::nr_slots, and b43_dmaring::used_slots.
Referenced by b43_dma_handle_txstatus(), b43_dma_tx(), and request_slot().
static u16 generate_cookie (struct b43_dmaring * ring, int slot) [static]
Definition at line 1203 of file dma.c.
References B43_WARN_ON, and b43_dmaring::index.
Referenced by dma_tx_fragment().
static dma_addr_t map_descbuffer (struct b43_dmaring * ring, unsigned char * buf, size_t len, int tx) [inline, static]
Definition at line 360 of file dma.c.
References b43_wldev::dev, b43_dmaring::dev, and b43_bus_dev::dma_dev.
Referenced by dma_tx_fragment(), and setup_rx_descbuffer().
static int next_slot (struct b43_dmaring * ring, int slot) [inline, static]
Definition at line 275 of file dma.c.
References B43_WARN_ON, and b43_dmaring::nr_slots.
Referenced by b43_dma_handle_txstatus(), b43_dma_rx(), dma_rx(), dma_tx_fragment(), and request_slot().
static void op32_fill_descriptor (struct b43_dmaring * ring, struct b43_dmadesc_generic * desc, dma_addr_t dmaaddr, u16 bufsize, int start, int end, int irq) [static]
Definition at line 98 of file dma.c.
References b43_dmadesc32::address, B43_DMA32_DCTL_ADDREXT_MASK, B43_DMA32_DCTL_ADDREXT_SHIFT, B43_DMA32_DCTL_BYTECNT, B43_DMA32_DCTL_DTABLEEND, B43_DMA32_DCTL_FRAMEEND, B43_DMA32_DCTL_FRAMESTART, B43_DMA32_DCTL_IRQ, B43_DMA_ADDR_EXT, B43_DMA_ADDR_LOW, b43_dma_address(), B43_WARN_ON, b43_dmadesc32::control, b43_dmaring::descbase, b43_dmaring::dev, b43_wldev::dma, b43_dmadesc_generic::dma32, and b43_dmaring::nr_slots.
static int op32_get_current_rxslot (struct b43_dmaring * ring) [static]
Definition at line 149 of file dma.c.
References B43_DMA32_RXDPTR, B43_DMA32_RXSTATUS, and b43_dma_read().
static struct b43_dmadesc_generic* op32_idx2desc (struct b43_dmaring * ring, int slot, struct b43_dmadesc_meta ** meta) [static, read]
Definition at line 85 of file dma.c.
References b43_dmaring::descbase, and b43_dmaring::meta.
static void op32_poke_tx (struct b43_dmaring * ring, int slot) [static]
Definition at line 131 of file dma.c.
References B43_DMA32_TXINDEX, and b43_dma_write().
static void op32_set_current_rxslot (struct b43_dmaring * ring, int slot) [static]
Definition at line 159 of file dma.c.
References B43_DMA32_RXINDEX, and b43_dma_write().
static void op32_tx_resume (struct b43_dmaring * ring) [static]
Definition at line 143 of file dma.c.
References B43_DMA32_TXCTL, B43_DMA32_TXSUSPEND, b43_dma_read(), and b43_dma_write().
static void op32_tx_suspend (struct b43_dmaring * ring) [static]
Definition at line 137 of file dma.c.
References B43_DMA32_TXCTL, B43_DMA32_TXSUSPEND, b43_dma_read(), and b43_dma_write().
static void op64_fill_descriptor (struct b43_dmaring * ring, struct b43_dmadesc_generic * desc, dma_addr_t dmaaddr, u16 bufsize, int start, int end, int irq) [static]
Definition at line 190 of file dma.c.
References b43_dmadesc64::address_high, b43_dmadesc64::address_low, B43_DMA64_DCTL0_DTABLEEND, B43_DMA64_DCTL0_FRAMEEND, B43_DMA64_DCTL0_FRAMESTART, B43_DMA64_DCTL0_IRQ, B43_DMA64_DCTL1_ADDREXT_MASK, B43_DMA64_DCTL1_ADDREXT_SHIFT, B43_DMA64_DCTL1_BYTECNT, B43_DMA_ADDR_EXT, B43_DMA_ADDR_HIGH, B43_DMA_ADDR_LOW, b43_dma_address(), B43_WARN_ON, b43_dmadesc64::control0, b43_dmadesc64::control1, b43_dmaring::descbase, b43_dmaring::dev, b43_wldev::dma, b43_dmadesc_generic::dma64, and b43_dmaring::nr_slots.
static int op64_get_current_rxslot (struct b43_dmaring * ring) [static]
Definition at line 244 of file dma.c.
References B43_DMA64_RXSTATDPTR, B43_DMA64_RXSTATUS, and b43_dma_read().
static struct b43_dmadesc_generic* op64_idx2desc (struct b43_dmaring * ring, int slot, struct b43_dmadesc_meta ** meta) [static, read]
Definition at line 177 of file dma.c.
References b43_dmaring::descbase, and b43_dmaring::meta.
static void op64_poke_tx (struct b43_dmaring * ring, int slot) [static]
Definition at line 226 of file dma.c.
References B43_DMA64_TXINDEX, and b43_dma_write().
static void op64_set_current_rxslot (struct b43_dmaring * ring, int slot) [static]
Definition at line 254 of file dma.c.
References B43_DMA64_RXINDEX, and b43_dma_write().
static void op64_tx_resume (struct b43_dmaring * ring) [static]
Definition at line 238 of file dma.c.
References B43_DMA64_TXCTL, B43_DMA64_TXSUSPEND, b43_dma_read(), and b43_dma_write().
static void op64_tx_suspend (struct b43_dmaring * ring) [static]
Definition at line 232 of file dma.c.
References B43_DMA64_TXCTL, B43_DMA64_TXSUSPEND, b43_dma_read(), and b43_dma_write().
static struct b43_dmaring* parse_cookie (struct b43_wldev * dev, u16 cookie, int * slot) [static, read]
Definition at line 1224 of file dma.c.
References b43dbg(), b43_wldev::dma, b43_dmaring::nr_slots, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, b43_dma::tx_ring_mcast, and b43_wldev::wl.
Referenced by b43_dma_handle_txstatus().
static int prev_slot (struct b43_dmaring * ring, int slot) [inline, static]
Definition at line 283 of file dma.c.
References B43_WARN_ON, and b43_dmaring::nr_slots.
static int request_slot (struct b43_dmaring * ring) [inline, static]
Definition at line 313 of file dma.c.
References B43_WARN_ON, b43_dmaring::current_slot, free_slots(), next_slot(), b43_dmaring::stopped, b43_dmaring::tx, update_max_used_slots(), and b43_dmaring::used_slots.
Referenced by dma_tx_fragment().
static struct b43_dmaring* select_ring_by_priority (struct b43_wldev * dev, u8 queue_prio) [static, read]
Definition at line 1377 of file dma.c.
References B43_WARN_ON, b43_wldev::dma, b43_wldev::qos_enabled, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, and b43_dma::tx_ring_AC_VO.
Referenced by b43_dma_tx().
static int setup_rx_descbuffer (struct b43_dmaring * ring, struct b43_dmadesc_generic * desc, struct b43_dmadesc_meta * meta, gfp_t gfp_flags) [static]
Definition at line 607 of file dma.c.
References b43_dma_mapping_error(), b43_poison_rx_buffer(), B43_WARN_ON, b43err(), b43_dmaring::dev, b43_dmadesc_meta::dmaaddr, b43_dma_ops::fill_descriptor, map_descbuffer(), b43_dmaring::ops, b43_dmaring::rx_buffersize, b43_dmadesc_meta::skb, b43_dmaring::tx, and b43_wldev::wl.
Referenced by alloc_initial_descbuffers(), and dma_rx().
static int should_inject_overflow (struct b43_dmaring * ring) [inline, static]
Definition at line 1355 of file dma.c.
References B43_DBG_DMAOVERFLOW, b43_debug(), b43dbg(), b43_dmaring::dev, b43_dmaring::index, and b43_wldev::wl.
Referenced by b43_dma_tx().
static u64 supported_dma_mask (struct b43_wldev * dev) [static]
Definition at line 815 of file dma.c.
References B43_BUS_SSB, B43_DMA32_TXADDREXT_MASK, B43_DMA32_TXCTL, b43_dmacontroller_base(), b43_read32(), b43_write32(), b43_bus_dev::bdev, b43_bus_dev::bus_type, b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_dma_direct_fifo_rx(), and b43_dma_init().
static void sync_descbuffer_for_cpu (struct b43_dmaring * ring, dma_addr_t addr, size_t len) [inline, static]
Definition at line 390 of file dma.c.
References B43_WARN_ON, b43_wldev::dev, b43_dmaring::dev, b43_bus_dev::dma_dev, and b43_dmaring::tx.
Referenced by dma_rx().
static void sync_descbuffer_for_device (struct b43_dmaring * ring, dma_addr_t addr, size_t len) [inline, static]
Definition at line 399 of file dma.c.
References B43_WARN_ON, b43_wldev::dev, b43_dmaring::dev, b43_bus_dev::dma_dev, and b43_dmaring::tx.
Referenced by dma_rx().
static void unmap_descbuffer (struct b43_dmaring * ring, dma_addr_t addr, size_t len, int tx) [inline, static]
Definition at line 377 of file dma.c.
References b43_wldev::dev, b43_dmaring::dev, and b43_bus_dev::dma_dev.
Referenced by alloc_initial_descbuffers(), b43_dma_handle_txstatus(), b43_dma_mapping_error(), dma_rx(), dma_tx_fragment(), and free_all_descbuffers().
static void update_max_used_slots (struct b43_dmaring * ring, int current_used_slots) [inline, static]
Definition at line 307 of file dma.c.
Referenced by b43_dma_rx(), and request_slot().
Variable Documentation
struct b43_dma_ops dma32_ops [static]
Initial value:
 {
        .idx2desc = op32_idx2desc,
        .fill_descriptor = op32_fill_descriptor,
        .poke_tx = op32_poke_tx,
        .tx_suspend = op32_tx_suspend,
        .tx_resume = op32_tx_resume,
        .get_current_rxslot = op32_get_current_rxslot,
        .set_current_rxslot = op32_set_current_rxslot,
}
Definition at line 165 of file dma.c.
struct b43_dma_ops dma64_ops [static]
Initial value:
 {
        .idx2desc = op64_idx2desc,
        .fill_descriptor = op64_fill_descriptor,
        .poke_tx = op64_poke_tx,
        .tx_suspend = op64_tx_suspend,
        .tx_resume = op64_tx_resume,
        .get_current_rxslot = op64_get_current_rxslot,
        .set_current_rxslot = op64_set_current_rxslot,
}
Definition at line 260 of file dma.c.