CompatWireless3.2: drivers/net/wireless/b43/dma.h File Reference
drivers/net/wireless/b43/dma.h File Reference
#include <linux/err.h>
#include "b43.h"
Data Structures
struct b43_dmadesc32
struct b43_dmadesc64
struct b43_dmadesc_generic
struct b43_dmadesc_meta
struct b43_dma_ops
struct b43_dmaring
Defines
#define B43_DMAIRQ_FATALMASK
#define B43_DMAIRQ_NONFATALMASK (1 << 13)
#define B43_DMAIRQ_RX_DONE (1 << 16)
#define B43_DMA32_TXCTL 0x00
#define B43_DMA32_TXENABLE 0x00000001
#define B43_DMA32_TXSUSPEND 0x00000002
#define B43_DMA32_TXLOOPBACK 0x00000004
#define B43_DMA32_TXFLUSH 0x00000010
#define B43_DMA32_TXPARITYDISABLE 0x00000800
#define B43_DMA32_TXADDREXT_MASK 0x00030000
#define B43_DMA32_TXADDREXT_SHIFT 16
#define B43_DMA32_TXRING 0x04
#define B43_DMA32_TXINDEX 0x08
#define B43_DMA32_TXSTATUS 0x0C
#define B43_DMA32_TXDPTR 0x00000FFF
#define B43_DMA32_TXSTATE 0x0000F000
#define B43_DMA32_TXSTAT_DISABLED 0x00000000
#define B43_DMA32_TXSTAT_ACTIVE 0x00001000
#define B43_DMA32_TXSTAT_IDLEWAIT 0x00002000
#define B43_DMA32_TXSTAT_STOPPED 0x00003000
#define B43_DMA32_TXSTAT_SUSP 0x00004000
#define B43_DMA32_TXERROR 0x000F0000
#define B43_DMA32_TXERR_NOERR 0x00000000
#define B43_DMA32_TXERR_PROT 0x00010000
#define B43_DMA32_TXERR_UNDERRUN 0x00020000
#define B43_DMA32_TXERR_BUFREAD 0x00030000
#define B43_DMA32_TXERR_DESCREAD 0x00040000
#define B43_DMA32_TXACTIVE 0xFFF00000
#define B43_DMA32_RXCTL 0x10
#define B43_DMA32_RXENABLE 0x00000001
#define B43_DMA32_RXFROFF_MASK 0x000000FE
#define B43_DMA32_RXFROFF_SHIFT 1
#define B43_DMA32_RXDIRECTFIFO 0x00000100
#define B43_DMA32_RXPARITYDISABLE 0x00000800
#define B43_DMA32_RXADDREXT_MASK 0x00030000
#define B43_DMA32_RXADDREXT_SHIFT 16
#define B43_DMA32_RXRING 0x14
#define B43_DMA32_RXINDEX 0x18
#define B43_DMA32_RXSTATUS 0x1C
#define B43_DMA32_RXDPTR 0x00000FFF
#define B43_DMA32_RXSTATE 0x0000F000
#define B43_DMA32_RXSTAT_DISABLED 0x00000000
#define B43_DMA32_RXSTAT_ACTIVE 0x00001000
#define B43_DMA32_RXSTAT_IDLEWAIT 0x00002000
#define B43_DMA32_RXSTAT_STOPPED 0x00003000
#define B43_DMA32_RXERROR 0x000F0000
#define B43_DMA32_RXERR_NOERR 0x00000000
#define B43_DMA32_RXERR_PROT 0x00010000
#define B43_DMA32_RXERR_OVERFLOW 0x00020000
#define B43_DMA32_RXERR_BUFWRITE 0x00030000
#define B43_DMA32_RXERR_DESCREAD 0x00040000
#define B43_DMA32_RXACTIVE 0xFFF00000
#define B43_DMA32_DCTL_BYTECNT 0x00001FFF
#define B43_DMA32_DCTL_ADDREXT_MASK 0x00030000
#define B43_DMA32_DCTL_ADDREXT_SHIFT 16
#define B43_DMA32_DCTL_DTABLEEND 0x10000000
#define B43_DMA32_DCTL_IRQ 0x20000000
#define B43_DMA32_DCTL_FRAMEEND 0x40000000
#define B43_DMA32_DCTL_FRAMESTART 0x80000000
#define B43_DMA64_TXCTL 0x00
#define B43_DMA64_TXENABLE 0x00000001
#define B43_DMA64_TXSUSPEND 0x00000002
#define B43_DMA64_TXLOOPBACK 0x00000004
#define B43_DMA64_TXFLUSH 0x00000010
#define B43_DMA64_TXPARITYDISABLE 0x00000800
#define B43_DMA64_TXADDREXT_MASK 0x00030000
#define B43_DMA64_TXADDREXT_SHIFT 16
#define B43_DMA64_TXINDEX 0x04
#define B43_DMA64_TXRINGLO 0x08
#define B43_DMA64_TXRINGHI 0x0C
#define B43_DMA64_TXSTATUS 0x10
#define B43_DMA64_TXSTATDPTR 0x00001FFF
#define B43_DMA64_TXSTAT 0xF0000000
#define B43_DMA64_TXSTAT_DISABLED 0x00000000
#define B43_DMA64_TXSTAT_ACTIVE 0x10000000
#define B43_DMA64_TXSTAT_IDLEWAIT 0x20000000
#define B43_DMA64_TXSTAT_STOPPED 0x30000000
#define B43_DMA64_TXSTAT_SUSP 0x40000000
#define B43_DMA64_TXERROR 0x14
#define B43_DMA64_TXERRDPTR 0x0001FFFF
#define B43_DMA64_TXERR 0xF0000000
#define B43_DMA64_TXERR_NOERR 0x00000000
#define B43_DMA64_TXERR_PROT 0x10000000
#define B43_DMA64_TXERR_UNDERRUN 0x20000000
#define B43_DMA64_TXERR_TRANSFER 0x30000000
#define B43_DMA64_TXERR_DESCREAD 0x40000000
#define B43_DMA64_TXERR_CORE 0x50000000
#define B43_DMA64_RXCTL 0x20
#define B43_DMA64_RXENABLE 0x00000001
#define B43_DMA64_RXFROFF_MASK 0x000000FE
#define B43_DMA64_RXFROFF_SHIFT 1
#define B43_DMA64_RXDIRECTFIFO 0x00000100
#define B43_DMA64_RXPARITYDISABLE 0x00000800
#define B43_DMA64_RXADDREXT_MASK 0x00030000
#define B43_DMA64_RXADDREXT_SHIFT 16
#define B43_DMA64_RXINDEX 0x24
#define B43_DMA64_RXRINGLO 0x28
#define B43_DMA64_RXRINGHI 0x2C
#define B43_DMA64_RXSTATUS 0x30
#define B43_DMA64_RXSTATDPTR 0x00001FFF
#define B43_DMA64_RXSTAT 0xF0000000
#define B43_DMA64_RXSTAT_DISABLED 0x00000000
#define B43_DMA64_RXSTAT_ACTIVE 0x10000000
#define B43_DMA64_RXSTAT_IDLEWAIT 0x20000000
#define B43_DMA64_RXSTAT_STOPPED 0x30000000
#define B43_DMA64_RXSTAT_SUSP 0x40000000
#define B43_DMA64_RXERROR 0x34
#define B43_DMA64_RXERRDPTR 0x0001FFFF
#define B43_DMA64_RXERR 0xF0000000
#define B43_DMA64_RXERR_NOERR 0x00000000
#define B43_DMA64_RXERR_PROT 0x10000000
#define B43_DMA64_RXERR_UNDERRUN 0x20000000
#define B43_DMA64_RXERR_TRANSFER 0x30000000
#define B43_DMA64_RXERR_DESCREAD 0x40000000
#define B43_DMA64_RXERR_CORE 0x50000000
#define B43_DMA64_DCTL0_DTABLEEND 0x10000000
#define B43_DMA64_DCTL0_IRQ 0x20000000
#define B43_DMA64_DCTL0_FRAMEEND 0x40000000
#define B43_DMA64_DCTL0_FRAMESTART 0x80000000
#define B43_DMA64_DCTL1_BYTECNT 0x00001FFF
#define B43_DMA64_DCTL1_ADDREXT_MASK 0x00030000
#define B43_DMA64_DCTL1_ADDREXT_SHIFT 16
#define B43_DMA32_RINGMEMSIZE 4096
#define B43_DMA64_RINGMEMSIZE 8192
#define B43_DMA0_RX_FW598_FO 38
#define B43_DMA0_RX_FW351_FO 30
#define B43_TXRING_SLOTS 256
#define B43_RXRING_SLOTS 64
#define B43_DMA0_RX_FW598_BUFSIZE (B43_DMA0_RX_FW598_FO + IEEE80211_MAX_FRAME_LEN)
#define B43_DMA0_RX_FW351_BUFSIZE (B43_DMA0_RX_FW351_FO + IEEE80211_MAX_FRAME_LEN)
#define B43_DMA_PTR_POISON ((void *)ERR_PTR(-ENOMEM))
#define b43_dma_ptr_is_poisoned(ptr) (unlikely((ptr) == B43_DMA_PTR_POISON))
Enumerations
enum b43_dmatype { B43_DMA_30BIT = 30, B43_DMA_32BIT = 32, B43_DMA_64BIT = 64 }
enum b43_addrtype { B43_DMA_ADDR_LOW, B43_DMA_ADDR_HIGH, B43_DMA_ADDR_EXT }
Functions
static u32 b43_dma_read (struct b43_dmaring *ring, u16 offset)
static void b43_dma_write (struct b43_dmaring *ring, u16 offset, u32 value)
int b43_dma_init (struct b43_wldev *dev)
void b43_dma_free (struct b43_wldev *dev)
void b43_dma_tx_suspend (struct b43_wldev *dev)
void b43_dma_tx_resume (struct b43_wldev *dev)
int b43_dma_tx (struct b43_wldev *dev, struct sk_buff *skb)
void b43_dma_handle_txstatus (struct b43_wldev *dev, const struct b43_txstatus *status)
void b43_dma_rx (struct b43_dmaring *ring)
void b43_dma_direct_fifo_rx (struct b43_wldev *dev, unsigned int engine_index, bool enable)
Variables
struct b43_dmadesc32 __packed
Define Documentation
#define B43_DMA0_RX_FW351_BUFSIZE (B43_DMA0_RX_FW351_FO + IEEE80211_MAX_FRAME_LEN)
Definition at line 174 of file dma.h.
Referenced by b43_setup_dmaring().
#define B43_DMA0_RX_FW351_FO 30
Definition at line 168 of file dma.h.
Referenced by b43_setup_dmaring().
#define B43_DMA0_RX_FW598_BUFSIZE (B43_DMA0_RX_FW598_FO + IEEE80211_MAX_FRAME_LEN)
Definition at line 173 of file dma.h.
Referenced by b43_setup_dmaring().
#define B43_DMA0_RX_FW598_FO 38
Definition at line 167 of file dma.h.
Referenced by b43_setup_dmaring().
#define B43_DMA32_DCTL_ADDREXT_MASK 0x00030000
Definition at line 74 of file dma.h.
Referenced by op32_fill_descriptor().
#define B43_DMA32_DCTL_ADDREXT_SHIFT 16
Definition at line 75 of file dma.h.
Referenced by op32_fill_descriptor().
#define B43_DMA32_DCTL_BYTECNT 0x00001FFF
Definition at line 73 of file dma.h.
Referenced by op32_fill_descriptor().
#define B43_DMA32_DCTL_DTABLEEND 0x10000000
Definition at line 76 of file dma.h.
Referenced by op32_fill_descriptor().
#define B43_DMA32_DCTL_FRAMEEND 0x40000000
Definition at line 78 of file dma.h.
Referenced by op32_fill_descriptor().
#define B43_DMA32_DCTL_FRAMESTART 0x80000000
Definition at line 79 of file dma.h.
Referenced by op32_fill_descriptor().
#define B43_DMA32_DCTL_IRQ 0x20000000
Definition at line 77 of file dma.h.
Referenced by op32_fill_descriptor().
#define B43_DMA32_RINGMEMSIZE 4096
Definition at line 164 of file dma.h.
Referenced by alloc_ringmemory(), and free_ringmemory().
#define B43_DMA32_RXACTIVE 0xFFF00000
Definition at line 66 of file dma.h.
#define B43_DMA32_RXADDREXT_MASK 0x00030000
Definition at line 49 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA32_RXADDREXT_SHIFT 16
Definition at line 50 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA32_RXCTL 0x10
Definition at line 43 of file dma.h.
Referenced by b43_dmacontroller_rx_reset(), direct_fifo_rx(), and dmacontroller_setup().
#define B43_DMA32_RXDIRECTFIFO 0x00000100
Definition at line 47 of file dma.h.
Referenced by direct_fifo_rx().
#define B43_DMA32_RXDPTR 0x00000FFF
Definition at line 54 of file dma.h.
Referenced by op32_get_current_rxslot().
#define B43_DMA32_RXENABLE 0x00000001
Definition at line 44 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA32_RXERR_BUFWRITE 0x00030000
Definition at line 64 of file dma.h.
#define B43_DMA32_RXERR_DESCREAD 0x00040000
Definition at line 65 of file dma.h.
#define B43_DMA32_RXERR_NOERR 0x00000000
Definition at line 61 of file dma.h.
#define B43_DMA32_RXERR_OVERFLOW 0x00020000
Definition at line 63 of file dma.h.
#define B43_DMA32_RXERR_PROT 0x00010000
Definition at line 62 of file dma.h.
#define B43_DMA32_RXERROR 0x000F0000
Definition at line 60 of file dma.h.
#define B43_DMA32_RXFROFF_MASK 0x000000FE
Definition at line 45 of file dma.h.
#define B43_DMA32_RXFROFF_SHIFT 1
Definition at line 46 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA32_RXINDEX 0x18
Definition at line 52 of file dma.h.
Referenced by dmacontroller_setup(), and op32_set_current_rxslot().
#define B43_DMA32_RXPARITYDISABLE 0x00000800
Definition at line 48 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA32_RXRING 0x14
Definition at line 51 of file dma.h.
Referenced by dmacontroller_cleanup(), and dmacontroller_setup().
#define B43_DMA32_RXSTAT_ACTIVE 0x00001000
Definition at line 57 of file dma.h.
#define B43_DMA32_RXSTAT_DISABLED 0x00000000
Definition at line 56 of file dma.h.
Referenced by b43_dmacontroller_rx_reset().
#define B43_DMA32_RXSTAT_IDLEWAIT 0x00002000
Definition at line 58 of file dma.h.
#define B43_DMA32_RXSTAT_STOPPED 0x00003000
Definition at line 59 of file dma.h.
#define B43_DMA32_RXSTATE 0x0000F000
Definition at line 55 of file dma.h.
Referenced by b43_dmacontroller_rx_reset().
#define B43_DMA32_RXSTATUS 0x1C
Definition at line 53 of file dma.h.
Referenced by b43_dmacontroller_rx_reset(), and op32_get_current_rxslot().
#define B43_DMA32_TXACTIVE 0xFFF00000
Definition at line 42 of file dma.h.
#define B43_DMA32_TXADDREXT_MASK 0x00030000
Definition at line 24 of file dma.h.
Referenced by dmacontroller_setup(), and supported_dma_mask().
#define B43_DMA32_TXADDREXT_SHIFT 16
Definition at line 25 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA32_TXCTL 0x00
Definition at line 18 of file dma.h.
Referenced by b43_dmacontroller_tx_reset(), dmacontroller_setup(), op32_tx_resume(), op32_tx_suspend(), and supported_dma_mask().
#define B43_DMA32_TXDPTR 0x00000FFF
Definition at line 29 of file dma.h.
#define B43_DMA32_TXENABLE 0x00000001
Definition at line 19 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA32_TXERR_BUFREAD 0x00030000
Definition at line 40 of file dma.h.
#define B43_DMA32_TXERR_DESCREAD 0x00040000
Definition at line 41 of file dma.h.
#define B43_DMA32_TXERR_NOERR 0x00000000
Definition at line 37 of file dma.h.
#define B43_DMA32_TXERR_PROT 0x00010000
Definition at line 38 of file dma.h.
#define B43_DMA32_TXERR_UNDERRUN 0x00020000
Definition at line 39 of file dma.h.
#define B43_DMA32_TXERROR 0x000F0000
Definition at line 36 of file dma.h.
#define B43_DMA32_TXFLUSH 0x00000010
Definition at line 22 of file dma.h.
#define B43_DMA32_TXINDEX 0x08
Definition at line 27 of file dma.h.
Referenced by op32_poke_tx().
#define B43_DMA32_TXLOOPBACK 0x00000004
Definition at line 21 of file dma.h.
#define B43_DMA32_TXPARITYDISABLE 0x00000800
Definition at line 23 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA32_TXRING 0x04
Definition at line 26 of file dma.h.
Referenced by dmacontroller_cleanup(), and dmacontroller_setup().
#define B43_DMA32_TXSTAT_ACTIVE 0x00001000
Definition at line 32 of file dma.h.
#define B43_DMA32_TXSTAT_DISABLED 0x00000000
Definition at line 31 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA32_TXSTAT_IDLEWAIT 0x00002000
Definition at line 33 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA32_TXSTAT_STOPPED 0x00003000
Definition at line 34 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA32_TXSTAT_SUSP 0x00004000
Definition at line 35 of file dma.h.
#define B43_DMA32_TXSTATE 0x0000F000
Definition at line 30 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA32_TXSTATUS 0x0C
Definition at line 28 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA32_TXSUSPEND 0x00000002
Definition at line 20 of file dma.h.
Referenced by op32_tx_resume(), and op32_tx_suspend().
#define B43_DMA64_DCTL0_DTABLEEND 0x10000000
Definition at line 148 of file dma.h.
Referenced by op64_fill_descriptor().
#define B43_DMA64_DCTL0_FRAMEEND 0x40000000
Definition at line 150 of file dma.h.
Referenced by op64_fill_descriptor().
#define B43_DMA64_DCTL0_FRAMESTART 0x80000000
Definition at line 151 of file dma.h.
Referenced by op64_fill_descriptor().
#define B43_DMA64_DCTL0_IRQ 0x20000000
Definition at line 149 of file dma.h.
Referenced by op64_fill_descriptor().
#define B43_DMA64_DCTL1_ADDREXT_MASK 0x00030000
Definition at line 153 of file dma.h.
Referenced by op64_fill_descriptor().
#define B43_DMA64_DCTL1_ADDREXT_SHIFT 16
Definition at line 154 of file dma.h.
Referenced by op64_fill_descriptor().
#define B43_DMA64_DCTL1_BYTECNT 0x00001FFF
Definition at line 152 of file dma.h.
Referenced by op64_fill_descriptor().
#define B43_DMA64_RINGMEMSIZE 8192
Definition at line 165 of file dma.h.
Referenced by alloc_ringmemory(), and free_ringmemory().
#define B43_DMA64_RXADDREXT_MASK 0x00030000
Definition at line 118 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_RXADDREXT_SHIFT 16
Definition at line 119 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_RXCTL 0x20
Definition at line 112 of file dma.h.
Referenced by b43_dmacontroller_rx_reset(), direct_fifo_rx(), and dmacontroller_setup().
#define B43_DMA64_RXDIRECTFIFO 0x00000100
Definition at line 116 of file dma.h.
Referenced by direct_fifo_rx().
#define B43_DMA64_RXENABLE 0x00000001
Definition at line 113 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_RXERR 0xF0000000
Definition at line 133 of file dma.h.
#define B43_DMA64_RXERR_CORE 0x50000000
Definition at line 139 of file dma.h.
#define B43_DMA64_RXERR_DESCREAD 0x40000000
Definition at line 138 of file dma.h.
#define B43_DMA64_RXERR_NOERR 0x00000000
Definition at line 134 of file dma.h.
#define B43_DMA64_RXERR_PROT 0x10000000
Definition at line 135 of file dma.h.
#define B43_DMA64_RXERR_TRANSFER 0x30000000
Definition at line 137 of file dma.h.
#define B43_DMA64_RXERR_UNDERRUN 0x20000000
Definition at line 136 of file dma.h.
#define B43_DMA64_RXERRDPTR 0x0001FFFF
Definition at line 132 of file dma.h.
#define B43_DMA64_RXERROR 0x34
Definition at line 131 of file dma.h.
#define B43_DMA64_RXFROFF_MASK 0x000000FE
Definition at line 114 of file dma.h.
#define B43_DMA64_RXFROFF_SHIFT 1
Definition at line 115 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_RXINDEX 0x24
Definition at line 120 of file dma.h.
Referenced by dmacontroller_setup(), and op64_set_current_rxslot().
#define B43_DMA64_RXPARITYDISABLE 0x00000800
Definition at line 117 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_RXRINGHI 0x2C
Definition at line 122 of file dma.h.
Referenced by dmacontroller_cleanup(), and dmacontroller_setup().
#define B43_DMA64_RXRINGLO 0x28
Definition at line 121 of file dma.h.
Referenced by dmacontroller_cleanup(), and dmacontroller_setup().
#define B43_DMA64_RXSTAT 0xF0000000
Definition at line 125 of file dma.h.
Referenced by b43_dmacontroller_rx_reset().
#define B43_DMA64_RXSTAT_ACTIVE 0x10000000
Definition at line 127 of file dma.h.
#define B43_DMA64_RXSTAT_DISABLED 0x00000000
Definition at line 126 of file dma.h.
Referenced by b43_dmacontroller_rx_reset().
#define B43_DMA64_RXSTAT_IDLEWAIT 0x20000000
Definition at line 128 of file dma.h.
#define B43_DMA64_RXSTAT_STOPPED 0x30000000
Definition at line 129 of file dma.h.
#define B43_DMA64_RXSTAT_SUSP 0x40000000
Definition at line 130 of file dma.h.
#define B43_DMA64_RXSTATDPTR 0x00001FFF
Definition at line 124 of file dma.h.
Referenced by op64_get_current_rxslot().
#define B43_DMA64_RXSTATUS 0x30
Definition at line 123 of file dma.h.
Referenced by b43_dmacontroller_rx_reset(), and op64_get_current_rxslot().
#define B43_DMA64_TXADDREXT_MASK 0x00030000
Definition at line 90 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_TXADDREXT_SHIFT 16
Definition at line 91 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_TXCTL 0x00
Definition at line 84 of file dma.h.
Referenced by b43_dmacontroller_tx_reset(), dmacontroller_setup(), op64_tx_resume(), and op64_tx_suspend().
#define B43_DMA64_TXENABLE 0x00000001
Definition at line 85 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_TXERR 0xF0000000
Definition at line 105 of file dma.h.
#define B43_DMA64_TXERR_CORE 0x50000000
Definition at line 111 of file dma.h.
#define B43_DMA64_TXERR_DESCREAD 0x40000000
Definition at line 110 of file dma.h.
#define B43_DMA64_TXERR_NOERR 0x00000000
Definition at line 106 of file dma.h.
#define B43_DMA64_TXERR_PROT 0x10000000
Definition at line 107 of file dma.h.
#define B43_DMA64_TXERR_TRANSFER 0x30000000
Definition at line 109 of file dma.h.
#define B43_DMA64_TXERR_UNDERRUN 0x20000000
Definition at line 108 of file dma.h.
#define B43_DMA64_TXERRDPTR 0x0001FFFF
Definition at line 104 of file dma.h.
#define B43_DMA64_TXERROR 0x14
Definition at line 103 of file dma.h.
#define B43_DMA64_TXFLUSH 0x00000010
Definition at line 88 of file dma.h.
#define B43_DMA64_TXINDEX 0x04
Definition at line 92 of file dma.h.
Referenced by op64_poke_tx().
#define B43_DMA64_TXLOOPBACK 0x00000004
Definition at line 87 of file dma.h.
#define B43_DMA64_TXPARITYDISABLE 0x00000800
Definition at line 89 of file dma.h.
Referenced by dmacontroller_setup().
#define B43_DMA64_TXRINGHI 0x0C
Definition at line 94 of file dma.h.
Referenced by dmacontroller_cleanup(), and dmacontroller_setup().
#define B43_DMA64_TXRINGLO 0x08
Definition at line 93 of file dma.h.
Referenced by dmacontroller_cleanup(), and dmacontroller_setup().
#define B43_DMA64_TXSTAT 0xF0000000
Definition at line 97 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA64_TXSTAT_ACTIVE 0x10000000
Definition at line 99 of file dma.h.
#define B43_DMA64_TXSTAT_DISABLED 0x00000000
Definition at line 98 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA64_TXSTAT_IDLEWAIT 0x20000000
Definition at line 100 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA64_TXSTAT_STOPPED 0x30000000
Definition at line 101 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA64_TXSTAT_SUSP 0x40000000
Definition at line 102 of file dma.h.
#define B43_DMA64_TXSTATDPTR 0x00001FFF
Definition at line 96 of file dma.h.
#define B43_DMA64_TXSTATUS 0x10
Definition at line 95 of file dma.h.
Referenced by b43_dmacontroller_tx_reset().
#define B43_DMA64_TXSUSPEND 0x00000002
Definition at line 86 of file dma.h.
Referenced by op64_tx_resume(), and op64_tx_suspend().
#define b43_dma_ptr_is_poisoned (ptr) (unlikely((ptr) == B43_DMA_PTR_POISON))
Definition at line 178 of file dma.h.
Referenced by b43_dma_handle_txstatus(), and free_all_descbuffers().
#define B43_DMA_PTR_POISON ((void *)ERR_PTR(-ENOMEM))
Definition at line 177 of file dma.h.
Referenced by b43_dma_handle_txstatus(), and b43_setup_dmaring().
#define B43_DMAIRQ_FATALMASK
Value:
((1 << 10) | (1 << 11) | (1 << 12) \
                                         | (1 << 14) | (1 << 15))
Definition at line 10 of file dma.h.
Referenced by b43_do_interrupt_thread().
#define B43_DMAIRQ_NONFATALMASK (1 << 13)
Definition at line 12 of file dma.h.
Referenced by b43_do_interrupt_thread().
#define B43_DMAIRQ_RX_DONE (1 << 16)
Definition at line 13 of file dma.h.
Referenced by b43_do_interrupt_thread().
#define B43_RXRING_SLOTS 64
Definition at line 172 of file dma.h.
Referenced by b43_setup_dmaring().
#define B43_TXRING_SLOTS 256
Definition at line 171 of file dma.h.
Referenced by b43_setup_dmaring().
Enumeration Type Documentation
enum b43_addrtype
Enumerator:
B43_DMA_ADDR_LOW
B43_DMA_ADDR_HIGH
B43_DMA_ADDR_EXT
Definition at line 219 of file dma.h.
enum b43_dmatype
Enumerator:
B43_DMA_30BIT
B43_DMA_32BIT
B43_DMA_64BIT
Definition at line 213 of file dma.h.
Function Documentation
void b43_dma_direct_fifo_rx (struct b43_wldev * dev, unsigned int engine_index, bool enable)
Definition at line 1755 of file dma.c.
References b43_dmacontroller_base(), direct_fifo_rx(), dma_mask_to_engine_type(), and supported_dma_mask().
Referenced by b43_setup_pioqueue_rx().
void b43_dma_free (struct b43_wldev * dev)
Definition at line 1045 of file dma.c.
References b43_using_pio_transfers(), destroy_ring, b43_wldev::dma, b43_dma::rx_ring, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, and b43_dma::tx_ring_mcast.
Referenced by b43_wireless_core_exit().
void b43_dma_handle_txstatus (struct b43_wldev * dev, const struct b43_txstatus * status)
Definition at line 1479 of file dma.c.
References B43_DBG_DMAVERBOSE, b43_debug(), b43_dma_ptr_is_poisoned, B43_DMA_PTR_POISON, b43_fill_txstatus_report(), b43_get_priv_tx_info(), b43_txhdr_size(), B43_WARN_ON, b43dbg(), b43_private_tx_info::bouncebuffer, b43_txstatus::cookie, b43_dmaring::current_slot, b43_dmadesc_meta::dmaaddr, b43_txstatus::frame_count, free_slots(), b43_wl::hw, b43_dma_ops::idx2desc, b43_dmaring::index, b43_dmadesc_meta::is_last_fragment, next_slot(), b43_dmaring::nr_slots, b43_dmaring::ops, parse_cookie(), b43_dmaring::queue_prio, b43_dmadesc_meta::skb, b43_dmaring::stopped, b43_dmaring::tx, TX_SLOTS_PER_FRAME, unmap_descbuffer(), b43_dmaring::used_slots, and b43_wldev::wl.
Referenced by b43_handle_txstatus().
int b43_dma_init (struct b43_wldev * dev)
Definition at line 1119 of file dma.c.
References B43_BUS_SSB, b43_dma_set_mask(), b43_dma_translation_in_low_word(), b43_setup_dmaring(), B43_WARN_ON, b43dbg(), b43_bus_dev::bdev, b43_bus_dev::bus_type, b43_bus_dev::core_rev, destroy_ring, b43_wldev::dev, b43_wldev::dma, dma_mask_to_engine_type(), b43_dma::parity, b43_dma::rx_ring, b43_bus_dev::sdev, supported_dma_mask(), b43_dma::translation, b43_dma::translation_in_low, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, b43_dma::tx_ring_mcast, and b43_wldev::wl.
Referenced by b43_wireless_core_init().
static u32 b43_dma_read (struct b43_dmaring * ring, u16 offset) [inline, static]
Definition at line 277 of file dma.h.
References b43_read32(), b43_dmaring::dev, and b43_dmaring::mmio_base.
Referenced by op32_get_current_rxslot(), op32_tx_resume(), op32_tx_suspend(), op64_get_current_rxslot(), op64_tx_resume(), and op64_tx_suspend().
void b43_dma_rx (struct b43_dmaring * ring)
Definition at line 1681 of file dma.c.
References B43_WARN_ON, b43_dmaring::current_slot, dma_rx(), b43_dma_ops::get_current_rxslot, next_slot(), b43_dmaring::ops, b43_dma_ops::set_current_rxslot, b43_dmaring::tx, and update_max_used_slots().
Referenced by b43_do_interrupt_thread().
int b43_dma_tx (struct b43_wldev * dev, struct sk_buff * skb)
Definition at line 1407 of file dma.c.
References B43_DBG_DMAVERBOSE, b43_debug(), B43_WARN_ON, b43dbg(), b43err(), b43_wldev::dma, dma_tx_fragment(), free_slots(), b43_wl::hw, b43_dmaring::index, b43_dmaring::queue_prio, select_ring_by_priority(), should_inject_overflow(), b43_dmaring::stopped, b43_dmaring::tx, b43_dma::tx_ring_mcast, TX_SLOTS_PER_FRAME, and b43_wldev::wl.
Referenced by b43_tx_work().
void b43_dma_tx_resume (struct b43_wldev * dev)
Definition at line 1723 of file dma.c.
References b43_dma_tx_resume_ring(), b43_power_saving_ctl_bits(), b43_wldev::dma, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, and b43_dma::tx_ring_mcast.
Referenced by b43_tx_resume().
void b43_dma_tx_suspend (struct b43_wldev * dev)
Definition at line 1713 of file dma.c.
References b43_dma_tx_suspend_ring(), b43_power_saving_ctl_bits(), B43_PS_AWAKE, b43_wldev::dma, b43_dma::tx_ring_AC_BE, b43_dma::tx_ring_AC_BK, b43_dma::tx_ring_AC_VI, b43_dma::tx_ring_AC_VO, and b43_dma::tx_ring_mcast.
Referenced by b43_tx_suspend().
static void b43_dma_write (struct b43_dmaring * ring, u16 offset, u32 value) [inline, static]
Definition at line 282 of file dma.h.
References b43_write32(), b43_dmaring::dev, and b43_dmaring::mmio_base.
Referenced by dmacontroller_cleanup(), dmacontroller_setup(), op32_poke_tx(), op32_set_current_rxslot(), op32_tx_resume(), op32_tx_suspend(), op64_poke_tx(), op64_set_current_rxslot(), op64_tx_resume(), and op64_tx_suspend().
Variable Documentation
struct b43_dmadesc_generic __packed