CompatWireless3.2: drivers/net/wireless/b43/leds.c File Reference
drivers/net/wireless/b43/leds.c File Reference
#include "b43.h"
#include "leds.h"
#include "rfkill.h"
Functions
static void b43_led_turn_on (struct b43_wldev *dev, u8 led_index, bool activelow)
static void b43_led_turn_off (struct b43_wldev *dev, u8 led_index, bool activelow)
static void b43_led_update (struct b43_wldev *dev, struct b43_led *led)
static void b43_leds_work (struct work_struct *work)
static void b43_led_brightness_set (struct led_classdev *led_dev, enum led_brightness brightness)
static int b43_register_led (struct b43_wldev *dev, struct b43_led *led, const char *name, const char *default_trigger, u8 led_index, bool activelow)
static void b43_unregister_led (struct b43_led *led)
static void b43_map_led (struct b43_wldev *dev, u8 led_index, enum b43_led_behaviour behaviour, bool activelow)
static void b43_led_get_sprominfo (struct b43_wldev *dev, unsigned int led_index, enum b43_led_behaviour *behaviour, bool *activelow)
void b43_leds_init (struct b43_wldev *dev)
void b43_leds_exit (struct b43_wldev *dev)
void b43_leds_stop (struct b43_wldev *dev)
void b43_leds_register (struct b43_wldev *dev)
void b43_leds_unregister (struct b43_wl *wl)
Function Documentation
static void b43_led_brightness_set (struct led_classdev * led_dev, enum led_brightness brightness) [static]
Definition at line 109 of file leds.c.
References b43_wl::hw, and b43_wl::leds.
Referenced by b43_register_led().
static void b43_led_get_sprominfo (struct b43_wldev * dev, unsigned int led_index, enum b43_led_behaviour * behaviour, bool * activelow) [static]
Definition at line 213 of file leds.c.
References B43_WARN_ON, b43_bus_dev::board_vendor, b43_bus_dev::bus_sprom, and b43_wldev::dev.
Referenced by b43_leds_init(), and b43_leds_register().
static void b43_led_turn_off (struct b43_wldev * dev, u8 led_index, bool activelow) [static]
Definition at line 47 of file leds.c.
References B43_MMIO_GPIO_CONTROL, b43_read16(), and b43_write16().
Referenced by b43_led_update(), b43_leds_exit(), and b43_leds_init().
static void b43_led_turn_on (struct b43_wldev * dev, u8 led_index, bool activelow) [static]
Definition at line 34 of file leds.c.
References B43_MMIO_GPIO_CONTROL, b43_read16(), and b43_write16().
Referenced by b43_led_update(), and b43_leds_init().
static void b43_led_update (struct b43_wldev * dev, struct b43_led * led) [static]
Definition at line 60 of file leds.c.
References b43_led_turn_off(), b43_led_turn_on(), b43_wldev::phy, b43_wldev::radio_hw_enable, and b43_phy::radio_on.
Referenced by b43_leds_work().
void b43_leds_exit (struct b43_wldev * dev)
Definition at line 318 of file leds.c.
References b43_led_turn_off(), b43_wl::leds, and b43_wldev::wl.
Referenced by b43_wireless_core_stop().
void b43_leds_init (struct b43_wldev * dev)
Definition at line 258 of file leds.c.
References b43_is_hw_radio_enabled(), b43_led_get_sprominfo(), b43_led_turn_off(), b43_led_turn_on(), b43_wl::leds, b43_wldev::phy, b43_phy::radio_on, and b43_wldev::wl.
Referenced by b43_wireless_core_start().
void b43_leds_register (struct b43_wldev * dev)
Definition at line 336 of file leds.c.
References b43_led_get_sprominfo(), b43_leds_work(), b43_map_led(), b43_wl::leds, and b43_wldev::wl.
void b43_leds_stop (struct b43_wldev * dev)
Definition at line 328 of file leds.c.
References b43_wl::leds, and b43_wldev::wl.
void b43_leds_unregister (struct b43_wl * wl)
Definition at line 351 of file leds.c.
References b43_unregister_led(), and b43_wl::leds.
static void b43_leds_work (struct work_struct * work) [static]
Definition at line 88 of file leds.c.
References b43_led_update(), B43_STAT_STARTED, b43_status, b43_wl::current_dev, b43_wldev::dev, b43_wl::leds, and b43_wl::mutex.
Referenced by b43_leds_register().
static void b43_map_led (struct b43_wldev * dev, u8 led_index, enum b43_led_behaviour behaviour, bool activelow) [static]
Definition at line 159 of file leds.c.
References b43_register_led(), b43warn(), b43_wl::hw, b43_wl::leds, and b43_wldev::wl.
Referenced by b43_leds_register().
static int b43_register_led (struct b43_wldev * dev, struct b43_led * led, const char * name, const char * default_trigger, u8 led_index, bool activelow) [static]
Definition at line 121 of file leds.c.
References b43_led_brightness_set(), b43warn(), b43_bus_dev::dev, b43_wldev::dev, and b43_wldev::wl.
Referenced by b43_map_led().
static void b43_unregister_led (struct b43_led * led) [static]
Definition at line 151 of file leds.c.
Referenced by b43_leds_unregister().