CompatWireless3.2: drivers/net/wireless/b43/lo.c File Reference
drivers/net/wireless/b43/lo.c File Reference
#include "b43.h"
#include "lo.h"
#include "phy_g.h"
#include "main.h"
#include <linux/delay.h>
#include <linux/sched.h>
#include <linux/slab.h>
Data Structures
struct lo_g_saved_values
struct b43_lo_g_statemachine
Functions
static struct b43_lo_calib * b43_find_lo_calib (struct b43_txpower_lo_control *lo, const struct b43_bbatt *bbatt, const struct b43_rfatt *rfatt)
static void b43_lo_write (struct b43_wldev *dev, struct b43_loctl *control)
static u16 lo_measure_feedthrough (struct b43_wldev *dev, u16 lna, u16 pga, u16 trsw_rx)
static u16 lo_txctl_register_table (struct b43_wldev *dev, u16 *value, u16 *pad_mix_gain)
static void lo_measure_txctl_values (struct b43_wldev *dev)
static void lo_read_power_vector (struct b43_wldev *dev)
static void lo_measure_gain_values (struct b43_wldev *dev, s16 max_rx_gain, int use_trsw_rx)
static void lo_measure_setup (struct b43_wldev *dev, struct lo_g_saved_values *sav)
static void lo_measure_restore (struct b43_wldev *dev, struct lo_g_saved_values *sav)
static int lo_probe_possible_loctls (struct b43_wldev *dev, struct b43_loctl *probe_loctl, struct b43_lo_g_statemachine *d)
static void lo_probe_loctls_statemachine (struct b43_wldev *dev, struct b43_loctl *loctl, int *max_rx_gain)
static struct b43_lo_calib * b43_calibrate_lo_setting (struct b43_wldev *dev, const struct b43_bbatt *bbatt, const struct b43_rfatt *rfatt)
static struct b43_lo_calib * b43_get_calib_lo_settings (struct b43_wldev *dev, const struct b43_bbatt *bbatt, const struct b43_rfatt *rfatt)
void b43_gphy_dc_lt_init (struct b43_wldev *dev, bool update_all)
static void b43_lo_fixup_rfatt (struct b43_rfatt *rf)
void b43_lo_g_adjust (struct b43_wldev *dev)
void b43_lo_g_adjust_to (struct b43_wldev *dev, u16 rfatt, u16 bbatt, u16 tx_control)
void b43_lo_g_maintanance_work (struct b43_wldev *dev)
void b43_lo_g_cleanup (struct b43_wldev *dev)
void b43_lo_g_init (struct b43_wldev *dev)
Function Documentation
static struct b43_lo_calib* b43_calibrate_lo_setting (struct b43_wldev * dev, const struct b43_bbatt * bbatt, const struct b43_rfatt * rfatt) [static, read]
Definition at line 733 of file lo.c.
References b43_bbatt::att, b43_rfatt::att, B43_DBG_LO, b43_debug(), b43_gphy_set_baseband_attenuation(), b43_mac_enable(), b43_mac_suspend(), b43_radio_maskset(), b43dbg(), b43warn(), b43_lo_calib::bbatt, b43_lo_calib::calib_time, b43_phy::channel, b43_lo_calib::ctl, b43_phy::g, has_loopback_gain, b43_loctl::i, b43_lo_calib::list, lo_measure_gain_values(), lo_measure_restore(), lo_measure_setup(), lo_probe_loctls_statemachine(), lo_txctl_register_table(), b43_phy_g::max_lb_gain, lo_g_saved_values::old_channel, b43_wldev::phy, b43_loctl::q, b43_lo_calib::rfatt, b43_rfatt::with_padmix, and b43_wldev::wl.
Referenced by b43_get_calib_lo_settings(), b43_gphy_dc_lt_init(), and b43_lo_g_maintanance_work().
static struct b43_lo_calib* b43_find_lo_calib (struct b43_txpower_lo_control * lo, const struct b43_bbatt * bbatt, const struct b43_rfatt * rfatt) [static, read]
Definition at line 40 of file lo.c.
References b43_compare_bbatt(), b43_compare_rfatt(), b43_lo_calib::bbatt, b43_txpower_lo_control::calib_list, b43_lo_calib::list, and b43_lo_calib::rfatt.
Referenced by b43_get_calib_lo_settings().
static struct b43_lo_calib* b43_get_calib_lo_settings (struct b43_wldev * dev, const struct b43_bbatt * bbatt, const struct b43_rfatt * rfatt) [static, read]
Definition at line 799 of file lo.c.
References b43_calibrate_lo_setting(), b43_find_lo_calib(), b43_txpower_lo_control::calib_list, b43_phy::g, b43_lo_calib::list, b43_phy_g::lo_control, and b43_wldev::phy.
Referenced by b43_lo_g_adjust(), and b43_lo_g_adjust_to().
void b43_gphy_dc_lt_init (struct b43_wldev * dev, bool update_all)
Definition at line 819 of file lo.c.
References b43_calibrate_lo_setting(), B43_DC_LT_SIZE, b43_mac_enable(), b43_mac_suspend(), b43_phy_write(), B43_WARN_ON, b43warn(), b43_txpower_lo_control::bbatt_list, b43_lo_calib::ctl, b43_txpower_lo_control::dc_lt, b43_phy::g, b43_loctl::i, b43_bbatt_list::len, b43_rfatt_list::len, b43_rfatt_list::list, b43_bbatt_list::list, b43_phy_g::lo_control, b43_wldev::phy, b43_txpower_lo_control::power_vector, b43_loctl::q, b43_txpower_lo_control::rfatt_list, and b43_wldev::wl.
Referenced by b43_hardware_pctl_init_gphy(), b43_lo_g_init(), and b43_lo_g_maintanance_work().
static void b43_lo_fixup_rfatt (struct b43_rfatt * rf) [inline, static]
Definition at line 891 of file lo.c.
References b43_rfatt::att, and b43_rfatt::with_padmix.
Referenced by b43_lo_g_adjust(), and b43_lo_g_adjust_to().
void b43_lo_g_adjust (struct b43_wldev * dev)
Definition at line 899 of file lo.c.
References b43_get_calib_lo_settings(), b43_lo_fixup_rfatt(), b43_lo_write(), b43_phy_g::bbatt, b43_lo_calib::ctl, b43_phy::g, b43_wldev::phy, and b43_phy_g::rfatt.
Referenced by b43_phy_initg(), and b43_set_txpower_g().
void b43_lo_g_adjust_to (struct b43_wldev * dev, u16 rfatt, u16 bbatt, u16 tx_control)
Definition at line 914 of file lo.c.
References b43_bbatt::att, b43_rfatt::att, b43_get_calib_lo_settings(), b43_lo_fixup_rfatt(), b43_lo_write(), and b43_lo_calib::ctl.
void b43_lo_g_cleanup (struct b43_wldev * dev)
Definition at line 996 of file lo.c.
References b43_txpower_lo_control::calib_list, b43_phy::g, b43_lo_calib::list, b43_phy_g::lo_control, and b43_wldev::phy.
Referenced by b43_gphy_op_exit().
void b43_lo_g_init (struct b43_wldev * dev)
Definition at line 1010 of file lo.c.
References b43_gphy_dc_lt_init(), b43_has_hardware_pctl(), and lo_read_power_vector().
Referenced by b43_phy_initg().
void b43_lo_g_maintanance_work (struct b43_wldev * dev)
Definition at line 933 of file lo.c.
References b43_rfatt::att, b43_bbatt::att, b43_calibrate_lo_setting(), b43_compare_bbatt(), b43_compare_rfatt(), B43_DBG_LO, b43_debug(), b43_gphy_dc_lt_init(), b43_has_hardware_pctl(), B43_LO_CALIB_EXPIRE, B43_LO_PWRVEC_EXPIRE, b43_lo_write(), B43_WARN_ON, b43dbg(), b43warn(), b43_phy_g::bbatt, b43_lo_calib::bbatt, b43_txpower_lo_control::calib_list, b43_lo_calib::calib_time, b43_lo_calib::ctl, b43_phy::g, b43_loctl::i, b43_lo_calib::list, b43_phy_g::lo_control, lo_read_power_vector(), b43_wldev::phy, b43_txpower_lo_control::pwr_vec_read_time, b43_loctl::q, b43_phy_g::rfatt, b43_lo_calib::rfatt, b43_rfatt::with_padmix, and b43_wldev::wl.
Referenced by b43_gphy_op_pwork_15sec().
static void b43_lo_write (struct b43_wldev * dev, struct b43_loctl * control) [static]
Definition at line 58 of file lo.c.
References B43_DEBUG, B43_PHY_LO_CTL, b43_phy_write(), B43_PHYTYPE_G, B43_WARN_ON, b43dbg(), b43_loctl::i, b43_wldev::phy, b43_loctl::q, b43_phy::type, and b43_wldev::wl.
Referenced by b43_lo_g_adjust(), b43_lo_g_adjust_to(), b43_lo_g_maintanance_work(), lo_probe_loctls_statemachine(), and lo_probe_possible_loctls().
static u16 lo_measure_feedthrough (struct b43_wldev * dev, u16 lna, u16 pga, u16 trsw_rx) [static]
Definition at line 78 of file lo.c.
References B43_BFL_EXTLNA, B43_PHY_LO_LEAKAGE, B43_PHY_PGACTL, B43_PHY_PGACTL_LOWBANDW, B43_PHY_PGACTL_LPF, B43_PHY_PGACTL_UNKNOWN, b43_phy_read(), B43_PHY_RFOVERVAL, B43_PHY_RFOVERVAL_BW, B43_PHY_RFOVERVAL_BW_LBW, B43_PHY_RFOVERVAL_BW_LPF, B43_PHY_RFOVERVAL_EXTLNA, B43_PHY_RFOVERVAL_LNA, B43_PHY_RFOVERVAL_LNA_SHIFT, B43_PHY_RFOVERVAL_PGA, B43_PHY_RFOVERVAL_PGA_SHIFT, B43_PHY_RFOVERVAL_TRSWRX, B43_PHY_RFOVERVAL_UNK, b43_phy_write(), B43_WARN_ON, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::gmode, b43_wldev::phy, and b43_phy::rev.
Referenced by lo_measure_txctl_values(), lo_probe_loctls_statemachine(), and lo_probe_possible_loctls().
static void lo_measure_gain_values (struct b43_wldev * dev, s16 max_rx_gain, int use_trsw_rx) [static]
Definition at line 293 of file lo.c.
References b43_radio_read16, b43_radio_write16, b43_phy::g, has_loopback_gain, b43_phy_g::lna_gain, b43_phy_g::lna_lod_gain, b43_phy_g::pga_gain, b43_wldev::phy, and b43_phy_g::trsw_rx_gain.
Referenced by b43_calibrate_lo_setting(), and lo_probe_loctls_statemachine().
static void lo_measure_restore (struct b43_wldev * dev, struct lo_g_saved_values * sav) [static]
Definition at line 500 of file lo.c.
References b43_gphy_channel_switch(), b43_has_hardware_pctl(), B43_PHY_ANALOGOVER, B43_PHY_ANALOGOVERVAL, B43_PHY_CCK, B43_PHY_CLASSCTL, B43_PHY_CRS0, B43_PHY_DACCTL, B43_PHY_EXTG, B43_PHY_HPWR_TSSICTL, B43_PHY_LO_MASK, B43_PHY_PGACTL, B43_PHY_RFOVER, B43_PHY_RFOVERVAL, B43_PHY_SYNCCTL, b43_phy_write(), B43_PHYTYPE_B, B43_PHYTYPE_G, b43_radio_maskset(), b43_radio_write16, b43_write16(), b43_phy::g, has_tx_magnification, lo_g_saved_values::old_channel, b43_phy_g::pga_gain, b43_wldev::phy, lo_g_saved_values::phy_analogover, lo_g_saved_values::phy_analogoverval, lo_g_saved_values::phy_cck_06, lo_g_saved_values::phy_cck_14, lo_g_saved_values::phy_cck_2A, lo_g_saved_values::phy_cck_30, lo_g_saved_values::phy_cck_3E, lo_g_saved_values::phy_classctl, lo_g_saved_values::phy_crs0, lo_g_saved_values::phy_dacctl, lo_g_saved_values::phy_dacctl_hwpctl, lo_g_saved_values::phy_extg_01, lo_g_saved_values::phy_hpwr_tssictl, lo_g_saved_values::phy_lo_mask, lo_g_saved_values::phy_pgactl, lo_g_saved_values::phy_rfover, lo_g_saved_values::phy_rfoverval, lo_g_saved_values::phy_syncctl, lo_g_saved_values::radio_43, lo_g_saved_values::radio_52, lo_g_saved_values::radio_7A, b43_phy::radio_rev, b43_phy::radio_ver, lo_g_saved_values::reg_3E2, lo_g_saved_values::reg_3F4, b43_phy::rev, and b43_phy::type.
Referenced by b43_calibrate_lo_setting().
static void lo_measure_setup (struct b43_wldev * dev, struct lo_g_saved_values * sav) [static]
Definition at line 385 of file lo.c.
References B43_BFL_EXTLNA, b43_dummy_transmission(), b43_gphy_channel_switch(), b43_has_hardware_pctl(), B43_LO_TXCTL_EXPIRE, B43_PHY_ANALOGOVER, B43_PHY_ANALOGOVERVAL, B43_PHY_CCK, B43_PHY_CLASSCTL, B43_PHY_CRS0, B43_PHY_DACCTL, B43_PHY_EXTG, B43_PHY_HPWR_TSSICTL, B43_PHY_LO_MASK, b43_phy_mask(), B43_PHY_PGACTL, b43_phy_read(), B43_PHY_RFOVER, B43_PHY_RFOVERVAL, b43_phy_set(), B43_PHY_SYNCCTL, b43_phy_write(), B43_PHYTYPE_B, B43_PHYTYPE_G, b43_radio_read16, b43_radio_write16, b43_read16(), b43_write16(), b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::g, has_tx_magnification, b43_phy_g::lo_control, lo_measure_txctl_values(), b43_wldev::phy, lo_g_saved_values::phy_analogover, lo_g_saved_values::phy_analogoverval, lo_g_saved_values::phy_cck_06, lo_g_saved_values::phy_cck_14, lo_g_saved_values::phy_cck_2A, lo_g_saved_values::phy_cck_30, lo_g_saved_values::phy_cck_3E, lo_g_saved_values::phy_classctl, lo_g_saved_values::phy_crs0, lo_g_saved_values::phy_dacctl, lo_g_saved_values::phy_dacctl_hwpctl, lo_g_saved_values::phy_extg_01, lo_g_saved_values::phy_hpwr_tssictl, lo_g_saved_values::phy_lo_mask, lo_g_saved_values::phy_pgactl, lo_g_saved_values::phy_rfover, lo_g_saved_values::phy_rfoverval, lo_g_saved_values::phy_syncctl, lo_g_saved_values::radio_43, lo_g_saved_values::radio_52, lo_g_saved_values::radio_7A, b43_phy::radio_rev, b43_phy::radio_ver, lo_g_saved_values::reg_3E2, lo_g_saved_values::reg_3F4, b43_phy::rev, b43_txpower_lo_control::txctl_measured_time, and b43_phy::type.
Referenced by b43_calibrate_lo_setting().
static void lo_measure_txctl_values (struct b43_wldev * dev) [static]
Definition at line 175 of file lo.c.
References b43_gphy_set_baseband_attenuation(), b43_radio_mask(), b43_radio_maskset(), b43_radio_read16, b43_radio_write16, b43_phy::g, has_loopback_gain, has_tx_magnification, b43_phy_g::lo_control, lo_measure_feedthrough(), lo_txctl_register_table(), b43_phy_g::max_lb_gain, b43_wldev::phy, b43_phy::radio_rev, b43_phy::radio_ver, b43_phy::rev, b43_txpower_lo_control::tx_bias, b43_txpower_lo_control::tx_magn, and b43_txpower_lo_control::txctl_measured_time.
Referenced by lo_measure_setup().
static void lo_probe_loctls_statemachine (struct b43_wldev * dev, struct b43_loctl * loctl, int * max_rx_gain) [static]
Definition at line 657 of file lo.c.
References b43_lo_write(), B43_WARN_ON, b43_lo_g_statemachine::current_state, b43_phy::g, has_loopback_gain, b43_loctl::i, b43_phy_g::lna_gain, lo_measure_feedthrough(), lo_measure_gain_values(), lo_probe_possible_loctls(), b43_lo_g_statemachine::lowest_feedth, b43_lo_g_statemachine::min_loctl, b43_lo_g_statemachine::nr_measured, b43_phy_g::pga_gain, b43_wldev::phy, b43_loctl::q, b43_lo_g_statemachine::state_val_multiplier, and b43_phy_g::trsw_rx_gain.
Referenced by b43_calibrate_lo_setting().
static int lo_probe_possible_loctls (struct b43_wldev * dev, struct b43_loctl * probe_loctl, struct b43_lo_g_statemachine * d) [static]
Definition at line 576 of file lo.c.
References b43_lo_write(), B43_WARN_ON, b43_lo_g_statemachine::current_state, b43_phy::g, has_loopback_gain, b43_loctl::i, b43_phy_g::lna_gain, lo_measure_feedthrough(), b43_lo_g_statemachine::lowest_feedth, b43_lo_g_statemachine::nr_measured, b43_phy_g::pga_gain, b43_wldev::phy, b43_loctl::q, b43_lo_g_statemachine::state_val_multiplier, and b43_phy_g::trsw_rx_gain.
Referenced by lo_probe_loctls_statemachine().
static void lo_read_power_vector (struct b43_wldev * dev) [static]
Definition at line 272 of file lo.c.
References b43_shm_read16(), B43_SHM_SHARED, b43_shm_write16(), b43_phy::g, b43_phy_g::lo_control, b43_wldev::phy, b43_txpower_lo_control::power_vector, and b43_txpower_lo_control::pwr_vec_read_time.
Referenced by b43_lo_g_init(), and b43_lo_g_maintanance_work().
static u16 lo_txctl_register_table (struct b43_wldev * dev, u16 * value, u16 * pad_mix_gain) [static]
Definition at line 141 of file lo.c.
References B43_PHYTYPE_B, b43_wldev::phy, b43_phy::radio_rev, b43_phy::rev, and b43_phy::type.
Referenced by b43_calibrate_lo_setting(), and lo_measure_txctl_values().