CompatWireless3.2: drivers/net/wireless/b43/lo.h File Reference
drivers/net/wireless/b43/lo.h File Reference
#include "phy_g.h"
Data Structures
struct b43_loctl
struct b43_lo_calib
struct b43_txpower_lo_control
Defines
#define B43_LOCTL_POISON 111
#define B43_DC_LT_SIZE 32
#define B43_LO_CALIB_EXPIRE (HZ * (30 - 2))
#define B43_LO_PWRVEC_EXPIRE (HZ * (30 - 2))
#define B43_LO_TXCTL_EXPIRE (HZ * (180 - 4))
Functions
void b43_lo_g_adjust (struct b43_wldev *dev)
void b43_lo_g_adjust_to (struct b43_wldev *dev, u16 rfatt, u16 bbatt, u16 tx_control)
void b43_gphy_dc_lt_init (struct b43_wldev *dev, bool update_all)
void b43_lo_g_maintanance_work (struct b43_wldev *dev)
void b43_lo_g_cleanup (struct b43_wldev *dev)
void b43_lo_g_init (struct b43_wldev *dev)
Define Documentation
#define B43_DC_LT_SIZE 32
Definition at line 35 of file lo.h.
Referenced by b43_gphy_dc_lt_init().
#define B43_LO_CALIB_EXPIRE (HZ * (30 - 2))
Definition at line 68 of file lo.h.
Referenced by b43_lo_g_maintanance_work(), and loctls_read_file().
#define B43_LO_PWRVEC_EXPIRE (HZ * (30 - 2))
Definition at line 69 of file lo.h.
Referenced by b43_lo_g_maintanance_work(), and loctls_read_file().
#define B43_LO_TXCTL_EXPIRE (HZ * (180 - 4))
Definition at line 70 of file lo.h.
Referenced by lo_measure_setup(), and loctls_read_file().
#define B43_LOCTL_POISON 111
Definition at line 17 of file lo.h.
Function Documentation
void b43_gphy_dc_lt_init (struct b43_wldev * dev, bool update_all)
Definition at line 819 of file lo.c.
References b43_calibrate_lo_setting(), B43_DC_LT_SIZE, b43_mac_enable(), b43_mac_suspend(), b43_phy_write(), B43_WARN_ON, b43warn(), b43_txpower_lo_control::bbatt_list, b43_lo_calib::ctl, b43_txpower_lo_control::dc_lt, b43_phy::g, b43_loctl::i, b43_bbatt_list::len, b43_rfatt_list::len, b43_rfatt_list::list, b43_bbatt_list::list, b43_phy_g::lo_control, b43_wldev::phy, b43_txpower_lo_control::power_vector, b43_loctl::q, b43_txpower_lo_control::rfatt_list, and b43_wldev::wl.
Referenced by b43_hardware_pctl_init_gphy(), b43_lo_g_init(), and b43_lo_g_maintanance_work().
void b43_lo_g_adjust (struct b43_wldev * dev)
Definition at line 899 of file lo.c.
References b43_get_calib_lo_settings(), b43_lo_fixup_rfatt(), b43_lo_write(), b43_phy_g::bbatt, b43_lo_calib::ctl, b43_phy::g, b43_wldev::phy, and b43_phy_g::rfatt.
Referenced by b43_phy_initg(), and b43_set_txpower_g().
void b43_lo_g_adjust_to (struct b43_wldev * dev, u16 rfatt, u16 bbatt, u16 tx_control)
Definition at line 914 of file lo.c.
References b43_bbatt::att, b43_rfatt::att, b43_get_calib_lo_settings(), b43_lo_fixup_rfatt(), b43_lo_write(), and b43_lo_calib::ctl.
void b43_lo_g_cleanup (struct b43_wldev * dev)
Definition at line 996 of file lo.c.
References b43_txpower_lo_control::calib_list, b43_phy::g, b43_lo_calib::list, b43_phy_g::lo_control, and b43_wldev::phy.
Referenced by b43_gphy_op_exit().
void b43_lo_g_init (struct b43_wldev * dev)
Definition at line 1010 of file lo.c.
References b43_gphy_dc_lt_init(), b43_has_hardware_pctl(), and lo_read_power_vector().
Referenced by b43_phy_initg().
void b43_lo_g_maintanance_work (struct b43_wldev * dev)
Definition at line 933 of file lo.c.
References b43_rfatt::att, b43_bbatt::att, b43_calibrate_lo_setting(), b43_compare_bbatt(), b43_compare_rfatt(), B43_DBG_LO, b43_debug(), b43_gphy_dc_lt_init(), b43_has_hardware_pctl(), B43_LO_CALIB_EXPIRE, B43_LO_PWRVEC_EXPIRE, b43_lo_write(), B43_WARN_ON, b43dbg(), b43warn(), b43_phy_g::bbatt, b43_lo_calib::bbatt, b43_txpower_lo_control::calib_list, b43_lo_calib::calib_time, b43_lo_calib::ctl, b43_phy::g, b43_loctl::i, b43_lo_calib::list, b43_phy_g::lo_control, lo_read_power_vector(), b43_wldev::phy, b43_txpower_lo_control::pwr_vec_read_time, b43_loctl::q, b43_phy_g::rfatt, b43_lo_calib::rfatt, b43_rfatt::with_padmix, and b43_wldev::wl.
Referenced by b43_gphy_op_pwork_15sec().