CompatWireless3.2: drivers/net/wireless/b43/main.h File Reference
drivers/net/wireless/b43/main.h File Reference
#include "b43.h"
Defines
#define P4D_BYT3S(magic, nr_bytes) u8 __p4dding##magic[nr_bytes]
#define P4D_BYTES(line, nr_bytes) P4D_BYT3S(line, nr_bytes)
#define PAD_BYTES(nr_bytes) P4D_BYTES(__LINE__ , (nr_bytes))
#define B43_PS_ENABLED (1 << 0)
#define B43_PS_DISABLED (1 << 1)
#define B43_PS_AWAKE (1 << 2)
#define B43_PS_ASLEEP (1 << 3)
Enumerations
enum b43_verbosity {
B43_VERBOSITY_ERROR, B43_VERBOSITY_WARN, B43_VERBOSITY_INFO, B43_VERBOSITY_DEBUG,
__B43_VERBOSITY_AFTERLAST, B43_VERBOSITY_MAX = __B43_VERBOSITY_AFTERLAST - 1, B43_VERBOSITY_DEFAULT = B43_VERBOSITY_INFO
}
Functions
static u8 b43_freq_to_channel_5ghz (int freq)
static u8 b43_freq_to_channel_2ghz (int freq)
static int b43_channel_to_freq_5ghz (u8 channel)
static int b43_channel_to_freq_2ghz (u8 channel)
static int b43_is_cck_rate (int rate)
static int b43_is_ofdm_rate (int rate)
u8 b43_ieee80211_antenna_sanitize (struct b43_wldev *dev, u8 antenna_nr)
void b43_tsf_read (struct b43_wldev *dev, u64 *tsf)
void b43_tsf_write (struct b43_wldev *dev, u64 tsf)
u32 b43_shm_read32 (struct b43_wldev *dev, u16 routing, u16 offset)
u16 b43_shm_read16 (struct b43_wldev *dev, u16 routing, u16 offset)
void b43_shm_write32 (struct b43_wldev *dev, u16 routing, u16 offset, u32 value)
void b43_shm_write16 (struct b43_wldev *dev, u16 routing, u16 offset, u16 value)
u64 b43_hf_read (struct b43_wldev *dev)
void b43_hf_write (struct b43_wldev *dev, u64 value)
void b43_dummy_transmission (struct b43_wldev *dev, bool ofdm, bool pa_on)
void b43_wireless_core_reset (struct b43_wldev *dev, bool gmode)
void b43_controller_restart (struct b43_wldev *dev, const char *reason)
void b43_power_saving_ctl_bits (struct b43_wldev *dev, unsigned int ps_flags)
void b43_mac_suspend (struct b43_wldev *dev)
void b43_mac_enable (struct b43_wldev *dev)
void b43_mac_phy_clock_set (struct b43_wldev *dev, bool on)
int b43_do_request_fw (struct b43_request_fw_context *ctx, const char *name, struct b43_firmware_file *fw)
void b43_do_release_fw (struct b43_firmware_file *fw)
Variables
int b43_modparam_verbose
Define Documentation
#define B43_PS_ASLEEP (1 << 3)
Definition at line 131 of file main.h.
Referenced by b43_power_saving_ctl_bits().
#define B43_PS_AWAKE (1 << 2)
Definition at line 130 of file main.h.
Referenced by b43_dma_tx_suspend(), b43_mac_suspend(), b43_phy_lock(), b43_pio_tx_suspend(), and b43_power_saving_ctl_bits().
#define B43_PS_DISABLED (1 << 1)
Definition at line 129 of file main.h.
Referenced by b43_power_saving_ctl_bits().
#define B43_PS_ENABLED (1 << 0)
Definition at line 128 of file main.h.
Referenced by b43_power_saving_ctl_bits().
#define P4D_BYT3S (magic, nr_bytes) u8 __p4dding##magic[nr_bytes]
Definition at line 36 of file main.h.
#define P4D_BYTES (line, nr_bytes) P4D_BYT3S(line, nr_bytes)
Definition at line 37 of file main.h.
#define PAD_BYTES (nr_bytes) P4D_BYTES(__LINE__ , (nr_bytes))
Definition at line 39 of file main.h.
Enumeration Type Documentation
enum b43_verbosity
Enumerator:
B43_VERBOSITY_ERROR
B43_VERBOSITY_WARN
B43_VERBOSITY_INFO
B43_VERBOSITY_DEBUG
__B43_VERBOSITY_AFTERLAST
B43_VERBOSITY_MAX
B43_VERBOSITY_DEFAULT
Definition at line 46 of file main.h.
Function Documentation
static int b43_channel_to_freq_2ghz (u8 channel) [inline, static]
Definition at line 84 of file main.h.
static int b43_channel_to_freq_5ghz (u8 channel) [inline, static]
Definition at line 80 of file main.h.
Referenced by b43_rx().
void b43_controller_restart (struct b43_wldev * dev, const char * reason)
Definition at line 5465 of file main.c.
References B43_STAT_INITIALIZED, b43_status, b43info(), b43_wl::hw, b43_wldev::restart_work, and b43_wldev::wl.
Referenced by b43_do_interrupt_thread(), b43_handle_firmware_panic(), b43_periodic_every15sec(), and restart_write_file().
void b43_do_release_fw (struct b43_firmware_file * fw)
Definition at line 2068 of file main.c.
References b43_firmware_file::data, and b43_firmware_file::filename.
Referenced by b43_do_request_fw(), and b43_release_firmware().
int b43_do_request_fw (struct b43_request_fw_context * ctx, const char * name, struct b43_firmware_file * fw)
Definition at line 2097 of file main.c.
References b43_do_release_fw(), B43_FW_TYPE_IV, B43_FW_TYPE_PCM, B43_FW_TYPE_UCODE, B43_FWTYPE_OPENSOURCE, B43_FWTYPE_PROPRIETARY, B43_WARN_ON, b43_firmware_file::data, b43_bus_dev::dev, b43_wldev::dev, b43_request_fw_context::dev, b43_request_fw_context::errors, b43_firmware_file::filename, b43_request_fw_context::fwname, modparam_fwpostfix, b43_request_fw_context::req_type, b43_fw_header::size, b43_fw_header::type, b43_firmware_file::type, and b43_fw_header::ver.
Referenced by b43_try_request_fw().
void b43_dummy_transmission (struct b43_wldev * dev, bool ofdm, bool pa_on)
Definition at line 708 of file main.c.
References B43_MMIO_IFSSTAT, B43_MMIO_TXE0_AUX, B43_MMIO_TXE0_CTL, B43_MMIO_TXE0_PHYCTL, B43_MMIO_TXE0_PHYCTL1, B43_MMIO_TXE0_STATUS, B43_MMIO_TXE0_WM_0, B43_MMIO_TXE0_WM_1, B43_MMIO_WEPCTL, B43_MMIO_XMTSEL, B43_MMIO_XMTTPLATETXPTR, B43_MMIO_XMTTXCNT, B43_PHYTYPE_LCN, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_radio_write16, b43_ram_write(), b43_read16(), b43_write16(), b43_bus_dev::core_rev, b43_wldev::dev, b43_wldev::phy, b43_phy::radio_rev, b43_phy::radio_ver, and b43_phy::type.
Referenced by b43_phy_init_pctl(), b43_phy_lcn_sense_setup(), b43_set_all_gains(), b43_set_original_gains(), b43_wa_papd(), lo_measure_setup(), and lpphy_tx_pctl_init_hw().
static u8 b43_freq_to_channel_2ghz (int freq) [inline, static]
Definition at line 67 of file main.h.
Referenced by b43_rx().
static u8 b43_freq_to_channel_5ghz (int freq) [inline, static]
Definition at line 63 of file main.h.
Referenced by b43_rx().
u64 b43_hf_read (struct b43_wldev * dev)
Definition at line 530 of file main.c.
References b43_shm_read16(), B43_SHM_SH_HOSTFHI, B43_SHM_SH_HOSTFLO, B43_SHM_SH_HOSTFMI, and B43_SHM_SHARED.
Referenced by b43_aphy_op_set_rx_antenna(), b43_bluetooth_coext_enable(), b43_dump_keymemory(), b43_gphy_channel_switch(), b43_gphy_op_set_rx_antenna(), b43_hardware_pctl_init_gphy(), b43_lpphy_op_set_rx_antenna(), b43_nphy_tx_power_ctrl(), b43_nphy_workarounds_rev1_2(), b43_op_set_key(), b43_op_sw_scan_complete_notifier(), b43_op_sw_scan_start_notifier(), b43_phy_initb6(), b43_qos_init(), b43_radio_interference_mitigation_disable(), b43_radio_interference_mitigation_enable(), b43_wa_2060txlna_gain(), b43_wireless_core_init(), and lpphy_baseband_rev0_1_init().
void b43_hf_write (struct b43_wldev * dev, u64 value)
Definition at line 544 of file main.c.
References B43_SHM_SH_HOSTFHI, B43_SHM_SH_HOSTFLO, B43_SHM_SH_HOSTFMI, B43_SHM_SHARED, and b43_shm_write16().
Referenced by b43_aphy_op_set_rx_antenna(), b43_bluetooth_coext_enable(), b43_gphy_channel_switch(), b43_gphy_op_set_rx_antenna(), b43_hardware_pctl_init_gphy(), b43_lpphy_op_set_rx_antenna(), b43_nphy_tx_power_ctrl(), b43_nphy_workarounds_rev1_2(), b43_op_set_key(), b43_op_sw_scan_complete_notifier(), b43_op_sw_scan_start_notifier(), b43_phy_initb6(), b43_qos_init(), b43_radio_interference_mitigation_disable(), b43_radio_interference_mitigation_enable(), b43_wa_2060txlna_gain(), b43_wireless_core_init(), and lpphy_baseband_rev0_1_init().
u8 b43_ieee80211_antenna_sanitize (struct b43_wldev * dev, u8 antenna_nr)
Definition at line 1491 of file main.c.
References b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::gmode, and b43_wldev::phy.
Referenced by b43_generate_txhdr().
static int b43_is_cck_rate (int rate) [inline, static]
Definition at line 96 of file main.h.
References B43_CCK_RATE_11MB, B43_CCK_RATE_1MB, B43_CCK_RATE_2MB, and B43_CCK_RATE_5MB.
Referenced by b43_generate_tx_phy_ctl1(), b43_is_ofdm_rate(), b43_update_basic_rates(), and b43_write_beacon_template().
static int b43_is_ofdm_rate (int rate) [inline, static]
Definition at line 103 of file main.h.
References b43_is_cck_rate().
Referenced by b43_generate_plcp_hdr(), and b43_generate_txhdr().
void b43_mac_enable (struct b43_wldev * dev)
Definition at line 2783 of file main.c.
References B43_DBG_FIRMWARE, b43_debug(), B43_IRQ_MAC_SUSPENDED, B43_MACCTL_ENABLED, B43_MMIO_GEN_IRQ_REASON, B43_MMIO_MACCTL, b43_power_saving_ctl_bits(), b43_read32(), b43_shm_read16(), B43_SHM_SH_UCODESTAT, B43_SHM_SH_UCODESTAT_SLEEP, B43_SHM_SH_UCODESTAT_SUSP, B43_SHM_SHARED, B43_WARN_ON, b43_write32(), b43err(), b43_wldev::mac_suspended, and b43_wldev::wl.
Referenced by b43_calibrate_lo_setting(), b43_gphy_dc_lt_init(), b43_gphy_op_adjust_txpower(), b43_gphy_op_pwork_15sec(), b43_gphy_op_pwork_60sec(), b43_nphy_classifier(), b43_nphy_set_rx_core_state(), b43_op_bss_info_changed(), b43_op_conf_tx(), b43_op_config(), b43_phy_lcn_sense_setup(), b43_phy_lcn_tx_pwr_ctl_init(), b43_qos_upload_all(), b43_software_rfkill(), b43_wireless_core_start(), and lpphy_calibration().
void b43_mac_phy_clock_set (struct b43_wldev * dev, bool on)
Definition at line 2849 of file main.c.
References B43_BCMA_IOCTL_MACPHYCLKEN, B43_BUS_SSB, B43_TMSLOW_MACPHYCLKEN, b43_bus_dev::bdev, b43_bus_dev::bus_type, b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_chip_init(), b43_phy_ht_op_init(), and b43_phy_initn().
void b43_mac_suspend (struct b43_wldev * dev)
Definition at line 2814 of file main.c.
References B43_IRQ_MAC_SUSPENDED, B43_MACCTL_ENABLED, B43_MMIO_GEN_IRQ_REASON, B43_MMIO_MACCTL, b43_power_saving_ctl_bits(), B43_PS_AWAKE, b43_read32(), B43_WARN_ON, b43_write32(), b43err(), b43_wldev::mac_suspended, and b43_wldev::wl.
Referenced by b43_calibrate_lo_setting(), b43_gphy_dc_lt_init(), b43_gphy_op_adjust_txpower(), b43_gphy_op_pwork_15sec(), b43_gphy_op_pwork_60sec(), b43_nphy_classifier(), b43_nphy_set_rx_core_state(), b43_op_bss_info_changed(), b43_op_conf_tx(), b43_op_config(), b43_phy_lcn_sense_setup(), b43_phy_lcn_tx_pwr_ctl_init(), b43_qos_upload_all(), b43_software_rfkill(), b43_wireless_core_stop(), and lpphy_calibration().
void b43_power_saving_ctl_bits (struct b43_wldev * dev, unsigned int ps_flags)
Definition at line 1112 of file main.c.
References B43_MACCTL_AWAKE, B43_MACCTL_HWPS, B43_MMIO_MACCTL, B43_PS_ASLEEP, B43_PS_AWAKE, B43_PS_DISABLED, B43_PS_ENABLED, b43_read32(), b43_shm_read16(), B43_SHM_SH_UCODESTAT, B43_SHM_SH_UCODESTAT_SLEEP, B43_SHM_SHARED, B43_WARN_ON, b43_write32(), b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_dma_tx_resume(), b43_dma_tx_suspend(), b43_mac_enable(), b43_mac_suspend(), b43_phy_lock(), b43_phy_unlock(), b43_pio_tx_resume(), b43_pio_tx_suspend(), and handle_irq_tbtt_indication().
u16 b43_shm_read16 (struct b43_wldev * dev, u16 routing, u16 offset)
Definition at line 472 of file main.c.
References B43_MMIO_SHM_DATA, B43_MMIO_SHM_DATA_UNALIGNED, b43_read16(), b43_shm_control_word(), B43_SHM_SHARED, and B43_WARN_ON.
Referenced by b43_dump_keymemory(), b43_fwcapa_read(), b43_handle_firmware_panic(), b43_hf_read(), b43_jssi_read(), b43_mac_enable(), b43_mgmtframe_txantenna(), b43_periodic_every15sec(), b43_phy_shm_tssi_read(), b43_power_saving_ctl_bits(), b43_qos_params_upload(), b43_rate_memory_write(), b43_security_init(), b43_switch_channel(), b43_update_basic_rates(), b43_upload_microcode(), b43_validate_chipaccess(), b43_write_beacon_template(), handle_irq_noise(), handle_irq_ucode_debug(), lo_read_power_vector(), shm16read__read_file(), and shm16write__write_file().
u32 b43_shm_read32 (struct b43_wldev * dev, u16 routing, u16 offset)
Definition at line 449 of file main.c.
References B43_MMIO_SHM_DATA, B43_MMIO_SHM_DATA_UNALIGNED, b43_read16(), b43_read32(), b43_shm_control_word(), B43_SHM_SHARED, and B43_WARN_ON.
Referenced by b43_dump_keymemory(), b43_phy_shm_tssi_read(), b43_validate_chipaccess(), shm32read__read_file(), and shm32write__write_file().
void b43_shm_write16 (struct b43_wldev * dev, u16 routing, u16 offset, u16 value)
Definition at line 513 of file main.c.
References B43_MMIO_SHM_DATA, B43_MMIO_SHM_DATA_UNALIGNED, b43_shm_control_word(), B43_SHM_SHARED, B43_WARN_ON, and b43_write16().
Referenced by b43_chip_init(), b43_hf_write(), b43_jssi_write(), b43_mgmtframe_txantenna(), b43_nphy_tx_iq_workaround(), b43_nphy_tx_pwr_ctrl_coef_setup(), b43_periodic_every15sec(), b43_pio_init(), b43_qos_params_upload(), b43_rate_memory_write(), b43_set_phytxctl_defaults(), b43_set_pretbtt(), b43_set_retry_limits(), b43_set_synth_pu_delay(), b43_set_txpower_g(), b43_shm_clear_tssi(), b43_switch_channel(), b43_update_basic_rates(), b43_upload_microcode(), b43_validate_chipaccess(), b43_wireless_core_init(), b43_write_beacon_template(), b43_write_template_common(), dma_tx_fragment(), handle_irq_ucode_debug(), key_write(), keymac_write(), lo_read_power_vector(), pio_tx_frame(), rx_tkip_phase1_write(), and shm16write__write_file().
void b43_shm_write32 (struct b43_wldev * dev, u16 routing, u16 offset, u32 value)
Definition at line 493 of file main.c.
References B43_MMIO_SHM_DATA, B43_MMIO_SHM_DATA_UNALIGNED, b43_shm_control_word(), B43_SHM_SHARED, B43_WARN_ON, b43_write16(), and b43_write32().
Referenced by b43_phy_shm_tssi_read(), b43_validate_chipaccess(), keymac_write(), and shm32write__write_file().
void b43_tsf_read (struct b43_wldev * dev, u64 * tsf)
Definition at line 563 of file main.c.
References B43_MMIO_REV3PLUS_TSF_HIGH, B43_MMIO_REV3PLUS_TSF_LOW, b43_read32(), B43_WARN_ON, b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_op_get_tsf(), and b43_rx().
void b43_tsf_write (struct b43_wldev * dev, u64 tsf)
Definition at line 617 of file main.c.
References b43_time_lock(), b43_time_unlock(), and b43_tsf_write_locked().
Referenced by b43_op_set_tsf().
void b43_wireless_core_reset (struct b43_wldev * dev, bool gmode)
Definition at line 1233 of file main.c.
References B43_BUS_SSB, B43_MACCTL_GMODE, B43_MACCTL_IHR_ENABLED, B43_MMIO_MACCTL, b43_read32(), b43_ssb_wireless_core_reset(), b43_write32(), b43_bus_dev::bus_type, b43_wldev::dev, b43_phy::ops, b43_wldev::phy, and b43_phy_operations::switch_analog.
Referenced by b43_gphy_op_prepare_hardware(), b43_wireless_core_attach(), and b43_wireless_core_init().
Variable Documentation
int b43_modparam_verbose
Definition at line 108 of file main.c.
Referenced by b43_debug(), b43dbg(), b43err(), b43info(), b43warn(), and setup_struct_wldev_for_init().