CompatWireless3.2: drivers/net/wireless/b43/main.c File Reference
drivers/net/wireless/b43/main.c File Reference
#include <linux/delay.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/if_arp.h>
#include <linux/etherdevice.h>
#include <linux/firmware.h>
#include <linux/workqueue.h>
#include <linux/skbuff.h>
#include <linux/io.h>
#include <linux/dma-mapping.h>
#include <linux/slab.h>
#include <asm/unaligned.h>
#include "b43.h"
#include "main.h"
#include "debugfs.h"
#include "phy_common.h"
#include "phy_g.h"
#include "phy_n.h"
#include "dma.h"
#include <linux/interrupt.h>
#include <linux/list.h>
#include "xmit.h"
#include "lo.h"
#include <linux/ssb/ssb.h>
#include <linux/mmc/sdio_func.h>
Defines
#define RATETAB_ENT(_rateid, _flags)
#define b43_a_ratetable (__b43_ratetable + 4)
#define b43_a_ratetable_size 8
#define b43_b_ratetable (__b43_ratetable + 0)
#define b43_b_ratetable_size 4
#define b43_g_ratetable (__b43_ratetable + 0)
#define b43_g_ratetable_size 12
#define CHAN4G(_channel, _freq, _flags)
#define CHAN5G(_channel, _flags)
#define IS_PDEV(pdev, _vendor, _device, _subvendor, _subdevice)
Functions
MODULE_DESCRIPTION ("Broadcom B43 wireless driver")
MODULE_AUTHOR ("Martin Langer")
MODULE_AUTHOR ("Stefano Brivio")
MODULE_AUTHOR ("Michael Buesch")
MODULE_AUTHOR ("Gábor Stefanik")
MODULE_AUTHOR ("Rafał Miłecki")
MODULE_LICENSE ("GPL")
MODULE_FIRMWARE ("b43/ucode11.fw")
MODULE_FIRMWARE ("b43/ucode13.fw")
MODULE_FIRMWARE ("b43/ucode14.fw")
MODULE_FIRMWARE ("b43/ucode15.fw")
MODULE_FIRMWARE ("b43/ucode16_mimo.fw")
MODULE_FIRMWARE ("b43/ucode5.fw")
MODULE_FIRMWARE ("b43/ucode9.fw")
module_param_named (bad_frames_preempt, modparam_bad_frames_preempt, int, 0444)
MODULE_PARM_DESC (bad_frames_preempt,"enable(1) / disable(0) Bad Frames Preemption")
module_param_string (fwpostfix, modparam_fwpostfix, 16, 0444)
MODULE_PARM_DESC (fwpostfix,"Postfix for the .fw files to load.")
module_param_named (hwpctl, modparam_hwpctl, int, 0444)
MODULE_PARM_DESC (hwpctl,"Enable hardware-side power control (default off)")
module_param_named (nohwcrypt, modparam_nohwcrypt, int, 0444)
MODULE_PARM_DESC (nohwcrypt,"Disable hardware encryption.")
module_param_named (hwtkip, modparam_hwtkip, int, 0444)
MODULE_PARM_DESC (hwtkip,"Enable hardware tkip.")
module_param_named (qos, modparam_qos, int, 0444)
MODULE_PARM_DESC (qos,"Enable QOS support (default on)")
module_param_named (btcoex, modparam_btcoex, int, 0444)
MODULE_PARM_DESC (btcoex,"Enable Bluetooth coexistence (default on)")
module_param_named (verbose, b43_modparam_verbose, int, 0644)
MODULE_PARM_DESC (verbose,"Log message verbosity: 0=error, 1=warn, 2=info(default), 3=debug")
module_param_named (pio, b43_modparam_pio, int, 0644)
MODULE_PARM_DESC (pio,"Use PIO accesses by default: 0=DMA, 1=PIO")
static void b43_wireless_core_exit (struct b43_wldev *dev)
static int b43_wireless_core_init (struct b43_wldev *dev)
static struct b43_wldev * b43_wireless_core_stop (struct b43_wldev *dev)
static int b43_wireless_core_start (struct b43_wldev *dev)
static void b43_op_bss_info_changed (struct ieee80211_hw *hw, struct ieee80211_vif *vif, struct ieee80211_bss_conf *conf, u32 changed)
static int b43_ratelimit (struct b43_wl *wl)
void b43info (struct b43_wl *wl, const char *fmt,...)
void b43err (struct b43_wl *wl, const char *fmt,...)
void b43warn (struct b43_wl *wl, const char *fmt,...)
void b43dbg (struct b43_wl *wl, const char *fmt,...)
static void b43_ram_write (struct b43_wldev *dev, u16 offset, u32 val)
static void b43_shm_control_word (struct b43_wldev *dev, u16 routing, u16 offset)
u32 b43_shm_read32 (struct b43_wldev *dev, u16 routing, u16 offset)
u16 b43_shm_read16 (struct b43_wldev *dev, u16 routing, u16 offset)
void b43_shm_write32 (struct b43_wldev *dev, u16 routing, u16 offset, u32 value)
void b43_shm_write16 (struct b43_wldev *dev, u16 routing, u16 offset, u16 value)
u64 b43_hf_read (struct b43_wldev *dev)
void b43_hf_write (struct b43_wldev *dev, u64 value)
static u16 b43_fwcapa_read (struct b43_wldev *dev)
void b43_tsf_read (struct b43_wldev *dev, u64 *tsf)
static void b43_time_lock (struct b43_wldev *dev)
static void b43_time_unlock (struct b43_wldev *dev)
static void b43_tsf_write_locked (struct b43_wldev *dev, u64 tsf)
void b43_tsf_write (struct b43_wldev *dev, u64 tsf)
static void b43_macfilter_set (struct b43_wldev *dev, u16 offset, const u8 *mac)
static void b43_write_mac_bssid_templates (struct b43_wldev *dev)
static void b43_upload_card_macaddress (struct b43_wldev *dev)
static void b43_set_slot_time (struct b43_wldev *dev, u16 slot_time)
static void b43_short_slot_timing_enable (struct b43_wldev *dev)
static void b43_short_slot_timing_disable (struct b43_wldev *dev)
void b43_dummy_transmission (struct b43_wldev *dev, bool ofdm, bool pa_on)
static void key_write (struct b43_wldev *dev, u8 index, u8 algorithm, const u8 *key)
static void keymac_write (struct b43_wldev *dev, u8 index, const u8 *addr)
static void rx_tkip_phase1_write (struct b43_wldev *dev, u8 index, u32 iv32, u16 *phase1key)
static void b43_op_update_tkip_key (struct ieee80211_hw *hw, struct ieee80211_vif *vif, struct ieee80211_key_conf *keyconf, struct ieee80211_sta *sta, u32 iv32, u16 *phase1key)
static void do_key_write (struct b43_wldev *dev, u8 index, u8 algorithm, const u8 *key, size_t key_len, const u8 *mac_addr)
static int b43_key_write (struct b43_wldev *dev, int index, u8 algorithm, const u8 *key, size_t key_len, const u8 *mac_addr, struct ieee80211_key_conf *keyconf)
static int b43_key_clear (struct b43_wldev *dev, int index)
static void b43_clear_keys (struct b43_wldev *dev)
static void b43_dump_keymemory (struct b43_wldev *dev)
void b43_power_saving_ctl_bits (struct b43_wldev *dev, unsigned int ps_flags)
static void b43_ssb_wireless_core_reset (struct b43_wldev *dev, bool gmode)
void b43_wireless_core_reset (struct b43_wldev *dev, bool gmode)
static void handle_irq_transmit_status (struct b43_wldev *dev)
static void drain_txstatus_queue (struct b43_wldev *dev)
static u32 b43_jssi_read (struct b43_wldev *dev)
static void b43_jssi_write (struct b43_wldev *dev, u32 jssi)
static void b43_generate_noise_sample (struct b43_wldev *dev)
static void b43_calculate_link_quality (struct b43_wldev *dev)
static void handle_irq_noise (struct b43_wldev *dev)
static void handle_irq_tbtt_indication (struct b43_wldev *dev)
static void handle_irq_atim_end (struct b43_wldev *dev)
static void handle_irq_pmq (struct b43_wldev *dev)
static void b43_write_template_common (struct b43_wldev *dev, const u8 *data, u16 size, u16 ram_offset, u16 shm_size_offset, u8 rate)
u8 b43_ieee80211_antenna_sanitize (struct b43_wldev *dev, u8 antenna_nr)
static u16 b43_antenna_to_phyctl (int antenna)
static void b43_write_beacon_template (struct b43_wldev *dev, u16 ram_offset, u16 shm_size_offset)
static void b43_upload_beacon0 (struct b43_wldev *dev)
static void b43_upload_beacon1 (struct b43_wldev *dev)
static void handle_irq_beacon (struct b43_wldev *dev)
static void b43_do_beacon_update_trigger_work (struct b43_wldev *dev)
static void b43_beacon_update_trigger_work (struct work_struct *work)
static void b43_update_templates (struct b43_wl *wl)
static void b43_set_beacon_int (struct b43_wldev *dev, u16 beacon_int)
static void b43_handle_firmware_panic (struct b43_wldev *dev)
static void handle_irq_ucode_debug (struct b43_wldev *dev)
static void b43_do_interrupt_thread (struct b43_wldev *dev)
static irqreturn_t b43_interrupt_thread_handler (int irq, void *dev_id)
static irqreturn_t b43_do_interrupt (struct b43_wldev *dev)
static irqreturn_t b43_interrupt_handler (int irq, void *dev_id)
static void b43_sdio_interrupt_handler (struct b43_wldev *dev)
void b43_do_release_fw (struct b43_firmware_file *fw)
static void b43_release_firmware (struct b43_wldev *dev)
static void b43_print_fw_helptext (struct b43_wl *wl, bool error)
int b43_do_request_fw (struct b43_request_fw_context *ctx, const char *name, struct b43_firmware_file *fw)
static int b43_try_request_fw (struct b43_request_fw_context *ctx)
static int b43_request_firmware (struct b43_wldev *dev)
static int b43_upload_microcode (struct b43_wldev *dev)
static int b43_write_initvals (struct b43_wldev *dev, const struct b43_iv *ivals, size_t count, size_t array_size)
static int b43_upload_initvals (struct b43_wldev *dev)
static struct ssb_device * b43_ssb_gpio_dev (struct b43_wldev *dev)
static int b43_gpio_init (struct b43_wldev *dev)
static void b43_gpio_cleanup (struct b43_wldev *dev)
void b43_mac_enable (struct b43_wldev *dev)
void b43_mac_suspend (struct b43_wldev *dev)
void b43_mac_phy_clock_set (struct b43_wldev *dev, bool on)
static void b43_adjust_opmode (struct b43_wldev *dev)
static void b43_rate_memory_write (struct b43_wldev *dev, u16 rate, int is_ofdm)
static void b43_rate_memory_init (struct b43_wldev *dev)
static void b43_set_phytxctl_defaults (struct b43_wldev *dev)
static void b43_mgmtframe_txantenna (struct b43_wldev *dev, int antenna)
static void b43_chip_exit (struct b43_wldev *dev)
static int b43_chip_init (struct b43_wldev *dev)
static void b43_periodic_every60sec (struct b43_wldev *dev)
static void b43_periodic_every30sec (struct b43_wldev *dev)
static void b43_periodic_every15sec (struct b43_wldev *dev)
static void do_periodic_work (struct b43_wldev *dev)
static void b43_periodic_work_handler (struct work_struct *work)
static void b43_periodic_tasks_setup (struct b43_wldev *dev)
static int b43_validate_chipaccess (struct b43_wldev *dev)
static void b43_security_init (struct b43_wldev *dev)
static void b43_rng_exit (struct b43_wl *wl)
static int b43_rng_init (struct b43_wl *wl)
static void b43_tx_work (struct work_struct *work)
static void b43_op_tx (struct ieee80211_hw *hw, struct sk_buff *skb)
static void b43_qos_params_upload (struct b43_wldev *dev, const struct ieee80211_tx_queue_params *p, u16 shm_offset)
static void b43_qos_upload_all (struct b43_wldev *dev)
static void b43_qos_clear (struct b43_wl *wl)
static void b43_qos_init (struct b43_wldev *dev)
static int b43_op_conf_tx (struct ieee80211_hw *hw, struct ieee80211_vif *vif, u16 _queue, const struct ieee80211_tx_queue_params *params)
static int b43_op_get_stats (struct ieee80211_hw *hw, struct ieee80211_low_level_stats *stats)
static u64 b43_op_get_tsf (struct ieee80211_hw *hw, struct ieee80211_vif *vif)
static void b43_op_set_tsf (struct ieee80211_hw *hw, struct ieee80211_vif *vif, u64 tsf)
static void b43_put_phy_into_reset (struct b43_wldev *dev)
static const char * band_to_string (enum ieee80211_band band)
static int b43_switch_band (struct b43_wl *wl, struct ieee80211_channel *chan)
static void b43_set_retry_limits (struct b43_wldev *dev, unsigned int short_retry, unsigned int long_retry)
static int b43_op_config (struct ieee80211_hw *hw, u32 changed)
static void b43_update_basic_rates (struct b43_wldev *dev, u32 brates)
static int b43_op_set_key (struct ieee80211_hw *hw, enum set_key_cmd cmd, struct ieee80211_vif *vif, struct ieee80211_sta *sta, struct ieee80211_key_conf *key)
static void b43_op_configure_filter (struct ieee80211_hw *hw, unsigned int changed, unsigned int *fflags, u64 multicast)
static int b43_phy_versioning (struct b43_wldev *dev)
static void setup_struct_phy_for_init (struct b43_wldev *dev, struct b43_phy *phy)
static void setup_struct_wldev_for_init (struct b43_wldev *dev)
static void b43_bluetooth_coext_enable (struct b43_wldev *dev)
static void b43_bluetooth_coext_disable (struct b43_wldev *dev)
static void b43_imcfglo_timeouts_workaround (struct b43_wldev *dev)
static void b43_set_synth_pu_delay (struct b43_wldev *dev, bool idle)
static void b43_set_pretbtt (struct b43_wldev *dev)
static int b43_op_add_interface (struct ieee80211_hw *hw, struct ieee80211_vif *vif)
static void b43_op_remove_interface (struct ieee80211_hw *hw, struct ieee80211_vif *vif)
static int b43_op_start (struct ieee80211_hw *hw)
static void b43_op_stop (struct ieee80211_hw *hw)
static int b43_op_beacon_set_tim (struct ieee80211_hw *hw, struct ieee80211_sta *sta, bool set)
static void b43_op_sta_notify (struct ieee80211_hw *hw, struct ieee80211_vif *vif, enum sta_notify_cmd notify_cmd, struct ieee80211_sta *sta)
static void b43_op_sw_scan_start_notifier (struct ieee80211_hw *hw)
static void b43_op_sw_scan_complete_notifier (struct ieee80211_hw *hw)
static int b43_op_get_survey (struct ieee80211_hw *hw, int idx, struct survey_info *survey)
static void b43_chip_reset (struct work_struct *work)
static int b43_setup_bands (struct b43_wldev *dev, bool have_2ghz_phy, bool have_5ghz_phy)
static void b43_wireless_core_detach (struct b43_wldev *dev)
static int b43_wireless_core_attach (struct b43_wldev *dev)
static void b43_one_core_detach (struct b43_bus_dev *dev)
static int b43_one_core_attach (struct b43_bus_dev *dev, struct b43_wl *wl)
static void b43_sprom_fixup (struct ssb_bus *bus)
static void b43_wireless_exit (struct b43_bus_dev *dev, struct b43_wl *wl)
static struct b43_wl * b43_wireless_init (struct b43_bus_dev *dev)
void b43_controller_restart (struct b43_wldev *dev, const char *reason)
static void b43_print_driverinfo (void)
static int __init b43_init (void)
static void __exit b43_exit (void)
Variables
static int modparam_bad_frames_preempt
static char modparam_fwpostfix [16]
static int modparam_hwpctl
static int modparam_nohwcrypt
static int modparam_hwtkip
static int modparam_qos = 1
static int modparam_btcoex = 1
int b43_modparam_verbose = B43_VERBOSITY_DEFAULT
static int b43_modparam_pio = 0
static struct ieee80211_rate __b43_ratetable []
static struct ieee80211_channel b43_2ghz_chantable []
static struct ieee80211_channel b43_5ghz_nphy_chantable []
static struct ieee80211_channel b43_5ghz_aphy_chantable []
static struct
ieee80211_supported_band b43_band_5GHz_nphy
static struct
ieee80211_supported_band b43_band_5GHz_aphy
static struct
ieee80211_supported_band b43_band_2GHz
static const u16 b43_qos_shm_offsets []
static struct ieee80211_ops b43_hw_ops
Define Documentation
#define b43_a_ratetable (__b43_ratetable + 4)
Definition at line 174 of file main.c.
#define b43_a_ratetable_size 8
Definition at line 175 of file main.c.
#define b43_b_ratetable (__b43_ratetable + 0)
Definition at line 176 of file main.c.
#define b43_b_ratetable_size 4
Definition at line 177 of file main.c.
#define b43_g_ratetable (__b43_ratetable + 0)
Definition at line 178 of file main.c.
#define b43_g_ratetable_size 12
Definition at line 179 of file main.c.
#define CHAN4G (_channel, _freq, _flags)
Value:
{                       \
        .band                   = IEEE80211_BAND_2GHZ,          \
        .center_freq            = (_freq),                      \
        .hw_value               = (_channel),                   \
        .flags                  = (_flags),                     \
        .max_antenna_gain       = 0,                            \
        .max_power              = 30,                           \
}
Definition at line 181 of file main.c.
#define CHAN5G (_channel, _flags)
Value:
{                               \
        .band                   = IEEE80211_BAND_5GHZ,          \
        .center_freq            = 5000 + (5 * (_channel)),      \
        .hw_value               = (_channel),                   \
        .flags                  = (_flags),                     \
        .max_antenna_gain       = 0,                            \
        .max_power              = 30,                           \
}
Definition at line 207 of file main.c.
#define IS_PDEV (pdev, _vendor, _device, _subvendor, _subdevice)
Value:
(\
        (pdev->vendor == PCI_VENDOR_ID_##_vendor) &&                    \
        (pdev->device == _device) &&                                    \
        (pdev->subsystem_vendor == PCI_VENDOR_ID_##_subvendor) &&       \
        (pdev->subsystem_device == _subdevice)                          )
Definition at line 5221 of file main.c.
Referenced by b43_sprom_fixup().
#define RATETAB_ENT (_rateid, _flags)
Value:
{                                                               \
                .bitrate        = B43_RATE_TO_BASE100KBPS(_rateid),     \
                .hw_value       = (_rateid),                            \
                .flags          = (_flags),                             \
        }
Definition at line 148 of file main.c.
Function Documentation
static void b43_adjust_opmode (struct b43_wldev * dev) [static]
Definition at line 2877 of file main.c.
References b43_is_mode(), B43_MACCTL_AP, B43_MACCTL_BEACPROMISC, B43_MACCTL_DISCPMQ, B43_MACCTL_INFRA, B43_MACCTL_KEEP_BAD, B43_MACCTL_KEEP_BADPLCP, B43_MACCTL_KEEP_CTL, B43_MACCTL_PROMISC, B43_MMIO_MACCTL, b43_read32(), b43_write16(), b43_write32(), b43_bus_dev::chip_id, b43_bus_dev::chip_rev, b43_bus_dev::core_rev, b43_wldev::dev, b43_wl::filter_flags, and b43_wldev::wl.
Referenced by b43_chip_init(), b43_op_add_interface(), b43_op_configure_filter(), and b43_op_remove_interface().
static u16 b43_antenna_to_phyctl (int antenna) [static]
Definition at line 1516 of file main.c.
References B43_ANTENNA0, B43_ANTENNA1, B43_ANTENNA2, B43_ANTENNA3, B43_ANTENNA_AUTO0, B43_ANTENNA_AUTO1, B43_TXH_PHY_ANT0, B43_TXH_PHY_ANT01AUTO, B43_TXH_PHY_ANT1, B43_TXH_PHY_ANT2, B43_TXH_PHY_ANT3, and B43_WARN_ON.
Referenced by b43_mgmtframe_txantenna(), and b43_write_beacon_template().
static void b43_beacon_update_trigger_work (struct work_struct * work) [static]
Definition at line 1712 of file main.c.
References b43_bus_host_is_sdio(), b43_do_beacon_update_trigger_work(), B43_STAT_INITIALIZED, b43_status, b43_wl::beacon_update_trigger, b43_wl::current_dev, b43_wldev::dev, b43_wl::hardirq_lock, and b43_wl::mutex.
Referenced by b43_wireless_init().
static void b43_bluetooth_coext_disable (struct b43_wldev * dev) [static]
Definition at line 4492 of file main.c.
References modparam_btcoex.
Referenced by b43_wireless_core_init().
static void b43_bluetooth_coext_enable (struct b43_wldev * dev) [static]
Definition at line 4472 of file main.c.
References B43_BFL_BTCMOD, B43_BFL_BTCOEXIST, B43_HF_BTCOEX, B43_HF_BTCOEXALT, b43_hf_read(), b43_hf_write(), B43_PHYTYPE_B, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::gmode, modparam_btcoex, b43_wldev::phy, and b43_phy::type.
Referenced by b43_wireless_core_init().
static void b43_calculate_link_quality (struct b43_wldev * dev) [static]
Definition at line 1334 of file main.c.
References b43_generate_noise_sample(), B43_PHYTYPE_G, b43_noise_calculation::calculation_running, b43_wldev::noisecalc, b43_noise_calculation::nr_samples, b43_wldev::phy, and b43_phy::type.
Referenced by b43_periodic_every30sec().
static void b43_chip_exit (struct b43_wldev * dev) [static]
Definition at line 3021 of file main.c.
References b43_gpio_cleanup(), and b43_phy_exit().
Referenced by b43_wireless_core_exit(), and b43_wireless_core_init().
static int b43_chip_init (struct b43_wldev * dev) [static]
Definition at line 3031 of file main.c.
References b43_adjust_opmode(), B43_ANTENNA_DEFAULT, B43_BUS_SSB, b43_gpio_cleanup(), b43_gpio_init(), B43_INTERFMODE_NONE, b43_mac_phy_clock_set(), B43_MACCTL_GMODE, B43_MACCTL_IHR_ENABLED, B43_MACCTL_INFRA, B43_MACCTL_SHM_ENABLED, b43_mgmtframe_txantenna(), B43_MMIO_DMA0_IRQ_MASK, B43_MMIO_DMA1_IRQ_MASK, B43_MMIO_DMA2_IRQ_MASK, B43_MMIO_DMA3_IRQ_MASK, B43_MMIO_DMA4_IRQ_MASK, B43_MMIO_DMA5_IRQ_MASK, B43_MMIO_GEN_IRQ_REASON, B43_MMIO_MACCTL, B43_MMIO_POWERUP_DELAY, b43_phy_init(), B43_PHYTYPE_B, b43_read16(), b43_read32(), b43_request_firmware(), B43_SHM_SHARED, b43_shm_write16(), b43_upload_initvals(), b43_upload_microcode(), b43_write16(), b43_write32(), b43dbg(), b43_bus_dev::bus_type, b43_bus_dev::core_rev, b43_wldev::dev, b43_phy::gmode, b43_phy_operations::interf_mitigation, b43_phy::ops, b43_wldev::phy, b43_bus_dev::sdev, b43_phy_operations::set_rx_antenna, b43_phy_operations::switch_analog, b43_phy::type, and b43_wldev::wl.
Referenced by b43_wireless_core_init().
static void b43_chip_reset (struct work_struct * work) [static]
Definition at line 4956 of file main.c.
References b43_op_bss_info_changed(), b43_op_config(), B43_STAT_INITIALIZED, B43_STAT_STARTED, b43_status, b43_wireless_core_exit(), b43_wireless_core_init(), b43_wireless_core_start(), b43_wireless_core_stop(), b43err(), b43info(), b43_wl::current_dev, b43_wldev::dev, b43_wl::hw, b43_wl::mutex, b43_wldev::restart_work, b43_wl::vif, and b43_wldev::wl.
Referenced by b43_wireless_core_attach().
static void b43_clear_keys (struct b43_wldev * dev) [static]
Definition at line 1041 of file main.c.
References b43_key_clear(), b43_new_kidx_api(), B43_NR_GROUP_KEYS, and B43_NR_PAIRWISE_KEYS.
Referenced by b43_security_init().
void b43_controller_restart (struct b43_wldev * dev, const char * reason)
Definition at line 5465 of file main.c.
References B43_STAT_INITIALIZED, b43_status, b43info(), b43_wl::hw, b43_wldev::restart_work, and b43_wldev::wl.
Referenced by b43_do_interrupt_thread(), b43_handle_firmware_panic(), b43_periodic_every15sec(), and restart_write_file().
static void b43_do_beacon_update_trigger_work (struct b43_wldev * dev) [static]
Definition at line 1691 of file main.c.
References B43_MMIO_GEN_IRQ_MASK, b43_read32(), B43_WARN_ON, b43_write32(), handle_irq_beacon(), and b43_wldev::irq_mask.
Referenced by b43_beacon_update_trigger_work().
static irqreturn_t b43_do_interrupt (struct b43_wldev * dev) [static]
Definition at line 1988 of file main.c.
References B43_MMIO_DMA0_REASON, B43_MMIO_DMA1_REASON, B43_MMIO_DMA2_REASON, B43_MMIO_DMA3_REASON, B43_MMIO_DMA4_REASON, B43_MMIO_GEN_IRQ_MASK, B43_MMIO_GEN_IRQ_REASON, b43_read32(), b43_write32(), b43_wldev::dma_reason, b43_wldev::irq_mask, and b43_wldev::irq_reason.
Referenced by b43_interrupt_handler(), and b43_sdio_interrupt_handler().
static void b43_do_interrupt_thread (struct b43_wldev * dev) [static]
Definition at line 1873 of file main.c.
References b43_controller_restart(), B43_DBG_VERBOSESTATS, b43_debug(), b43_dma_rx(), B43_DMAIRQ_FATALMASK, B43_DMAIRQ_NONFATALMASK, B43_DMAIRQ_RX_DONE, B43_IRQ_ATIM_END, B43_IRQ_BEACON, B43_IRQ_MAC_TXERR, B43_IRQ_NOISESAMPLE_OK, B43_IRQ_PHY_TXERR, B43_IRQ_PMQ, B43_IRQ_TBTT_INDI, B43_IRQ_TX_OK, B43_IRQ_TXFIFO_FLUSH_OK, B43_IRQ_UCODE_DEBUG, B43_MMIO_GEN_IRQ_MASK, B43_PHY_TX_BADNESS_LIMIT, b43_pio_rx(), B43_STAT_STARTED, b43_status, b43_using_pio_transfers(), B43_WARN_ON, b43_write32(), b43err(), b43_wldev::dma, b43_wldev::dma_reason, handle_irq_atim_end(), handle_irq_beacon(), handle_irq_noise(), handle_irq_pmq(), handle_irq_tbtt_indication(), handle_irq_transmit_status(), handle_irq_ucode_debug(), b43_wldev::irq_mask, b43_wldev::irq_reason, b43_wldev::phy, b43_wldev::pio, b43_pio::rx_queue, b43_dma::rx_ring, b43_phy::txerr_cnt, b43_wldev::use_pio, and b43_wldev::wl.
Referenced by b43_interrupt_thread_handler(), and b43_sdio_interrupt_handler().
void b43_do_release_fw (struct b43_firmware_file * fw)
Definition at line 2068 of file main.c.
References b43_firmware_file::data, and b43_firmware_file::filename.
Referenced by b43_do_request_fw(), and b43_release_firmware().
int b43_do_request_fw (struct b43_request_fw_context * ctx, const char * name, struct b43_firmware_file * fw)
Definition at line 2097 of file main.c.
References b43_do_release_fw(), B43_FW_TYPE_IV, B43_FW_TYPE_PCM, B43_FW_TYPE_UCODE, B43_FWTYPE_OPENSOURCE, B43_FWTYPE_PROPRIETARY, B43_WARN_ON, b43_firmware_file::data, b43_bus_dev::dev, b43_wldev::dev, b43_request_fw_context::dev, b43_request_fw_context::errors, b43_firmware_file::filename, b43_request_fw_context::fwname, modparam_fwpostfix, b43_request_fw_context::req_type, b43_fw_header::size, b43_fw_header::type, b43_firmware_file::type, and b43_fw_header::ver.
Referenced by b43_try_request_fw().
void b43_dummy_transmission (struct b43_wldev * dev, bool ofdm, bool pa_on)
Definition at line 708 of file main.c.
References B43_MMIO_IFSSTAT, B43_MMIO_TXE0_AUX, B43_MMIO_TXE0_CTL, B43_MMIO_TXE0_PHYCTL, B43_MMIO_TXE0_PHYCTL1, B43_MMIO_TXE0_STATUS, B43_MMIO_TXE0_WM_0, B43_MMIO_TXE0_WM_1, B43_MMIO_WEPCTL, B43_MMIO_XMTSEL, B43_MMIO_XMTTPLATETXPTR, B43_MMIO_XMTTXCNT, B43_PHYTYPE_LCN, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_radio_write16, b43_ram_write(), b43_read16(), b43_write16(), b43_bus_dev::core_rev, b43_wldev::dev, b43_wldev::phy, b43_phy::radio_rev, b43_phy::radio_ver, and b43_phy::type.
Referenced by b43_phy_init_pctl(), b43_phy_lcn_sense_setup(), b43_set_all_gains(), b43_set_original_gains(), b43_wa_papd(), lo_measure_setup(), and lpphy_tx_pctl_init_hw().
static void b43_dump_keymemory (struct b43_wldev * dev) [static]
Definition at line 1053 of file main.c.
References b43_key::algorithm, B43_DBG_KEYS, b43_debug(), b43_hf_read(), B43_HF_USEDEFKEYS, b43_new_kidx_api(), B43_NR_GROUP_KEYS, B43_NR_PAIRWISE_KEYS, B43_SEC_ALGO_TKIP, B43_SEC_KEYSIZE, B43_SHM_RCMTA, b43_shm_read16(), b43_shm_read32(), B43_SHM_SH_KEYIDXBLOCK, B43_SHM_SH_TKIPTSCTTAK, B43_SHM_SHARED, b43dbg(), b43_wldev::key, b43_key::keyconf, b43_wldev::ktp, and b43_wldev::wl.
Referenced by b43_op_set_key().
static void __exit b43_exit (void) [static]
Definition at line 5540 of file main.c.
References b43_debugfs_exit(), b43_pcmcia_exit(), and b43_sdio_exit().
static u16 b43_fwcapa_read (struct b43_wldev * dev) [static]
Definition at line 557 of file main.c.
References b43_shm_read16(), B43_SHM_SH_FWCAPA, B43_SHM_SHARED, B43_WARN_ON, b43_wldev::fw, and b43_firmware::opensource.
Referenced by b43_upload_microcode().
static void b43_generate_noise_sample (struct b43_wldev * dev) [static]
Definition at line 1327 of file main.c.
References b43_jssi_write(), B43_MACCMD_BGNOISE, B43_MMIO_MACCMD, b43_read32(), and b43_write32().
Referenced by b43_calculate_link_quality(), and handle_irq_noise().
static void b43_gpio_cleanup (struct b43_wldev * dev) [static]
Definition at line 2761 of file main.c.
References B43_BUS_SSB, B43_GPIO_CONTROL, b43_ssb_gpio_dev(), b43_bus_dev::bdev, b43_bus_dev::bus_type, and b43_wldev::dev.
Referenced by b43_chip_exit(), and b43_chip_init().
static int b43_gpio_init (struct b43_wldev * dev) [static]
Definition at line 2704 of file main.c.
References B43_BFL_PACTRL, B43_BUS_SSB, B43_GPIO_CONTROL, B43_MACCTL_GPOUTSMSK, B43_MMIO_GPIO_MASK, B43_MMIO_MACCTL, b43_read16(), b43_read32(), b43_ssb_gpio_dev(), b43_write16(), b43_write32(), b43_bus_dev::bdev, b43_bus_dev::bus_sprom, b43_bus_dev::bus_type, b43_bus_dev::chip_id, b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_chip_init().
static void b43_handle_firmware_panic (struct b43_wldev * dev) [static]
Definition at line 1777 of file main.c.
References b43_controller_restart(), B43_FWPANIC_DIE, B43_FWPANIC_REASON_REG, B43_FWPANIC_RESTART, b43_shm_read16(), B43_SHM_SCRATCH, b43dbg(), b43err(), and b43_wldev::wl.
Referenced by handle_irq_ucode_debug().
u64 b43_hf_read (struct b43_wldev * dev)
Definition at line 530 of file main.c.
References b43_shm_read16(), B43_SHM_SH_HOSTFHI, B43_SHM_SH_HOSTFLO, B43_SHM_SH_HOSTFMI, and B43_SHM_SHARED.
Referenced by b43_aphy_op_set_rx_antenna(), b43_bluetooth_coext_enable(), b43_dump_keymemory(), b43_gphy_channel_switch(), b43_gphy_op_set_rx_antenna(), b43_hardware_pctl_init_gphy(), b43_lpphy_op_set_rx_antenna(), b43_nphy_tx_power_ctrl(), b43_nphy_workarounds_rev1_2(), b43_op_set_key(), b43_op_sw_scan_complete_notifier(), b43_op_sw_scan_start_notifier(), b43_phy_initb6(), b43_qos_init(), b43_radio_interference_mitigation_disable(), b43_radio_interference_mitigation_enable(), b43_wa_2060txlna_gain(), b43_wireless_core_init(), and lpphy_baseband_rev0_1_init().
void b43_hf_write (struct b43_wldev * dev, u64 value)
Definition at line 544 of file main.c.
References B43_SHM_SH_HOSTFHI, B43_SHM_SH_HOSTFLO, B43_SHM_SH_HOSTFMI, B43_SHM_SHARED, and b43_shm_write16().
Referenced by b43_aphy_op_set_rx_antenna(), b43_bluetooth_coext_enable(), b43_gphy_channel_switch(), b43_gphy_op_set_rx_antenna(), b43_hardware_pctl_init_gphy(), b43_lpphy_op_set_rx_antenna(), b43_nphy_tx_power_ctrl(), b43_nphy_workarounds_rev1_2(), b43_op_set_key(), b43_op_sw_scan_complete_notifier(), b43_op_sw_scan_start_notifier(), b43_phy_initb6(), b43_qos_init(), b43_radio_interference_mitigation_disable(), b43_radio_interference_mitigation_enable(), b43_wa_2060txlna_gain(), b43_wireless_core_init(), and lpphy_baseband_rev0_1_init().
u8 b43_ieee80211_antenna_sanitize (struct b43_wldev * dev, u8 antenna_nr)
Definition at line 1491 of file main.c.
References b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::gmode, and b43_wldev::phy.
Referenced by b43_generate_txhdr().
static void b43_imcfglo_timeouts_workaround (struct b43_wldev * dev) [static]
Definition at line 4499 of file main.c.
References B43_BUS_SSB, b43_bus_dev::bus_type, b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_wireless_core_init().
static int __init b43_init (void) [static]
Definition at line 5500 of file main.c.
References b43_debugfs_exit(), b43_debugfs_init(), b43_pcmcia_exit(), b43_pcmcia_init(), b43_print_driverinfo(), b43_sdio_exit(), and b43_sdio_init().
static irqreturn_t b43_interrupt_handler (int irq, void * dev_id) [static]
Definition at line 2037 of file main.c.
References b43_do_interrupt(), B43_STAT_STARTED, b43_status, b43_wldev::dev, b43_wl::hardirq_lock, and b43_wldev::wl.
Referenced by b43_wireless_core_start().
static irqreturn_t b43_interrupt_thread_handler (int irq, void * dev_id) [static]
Definition at line 1976 of file main.c.
References b43_do_interrupt_thread(), b43_wldev::dev, b43_wl::mutex, and b43_wldev::wl.
Referenced by b43_wireless_core_start().
static u32 b43_jssi_read (struct b43_wldev * dev) [static]
Definition at line 1310 of file main.c.
References b43_shm_read16(), and B43_SHM_SHARED.
Referenced by handle_irq_noise().
static void b43_jssi_write (struct b43_wldev * dev, u32 jssi) [static]
Definition at line 1321 of file main.c.
References B43_SHM_SHARED, and b43_shm_write16().
Referenced by b43_generate_noise_sample().
static int b43_key_clear (struct b43_wldev * dev, int index) [static]
Definition at line 1026 of file main.c.
References b43_new_kidx_api(), B43_SEC_ALGO_NONE, B43_SEC_KEYSIZE, B43_WARN_ON, do_key_write(), b43_wldev::key, and b43_key::keyconf.
Referenced by b43_clear_keys(), and b43_op_set_key().
static int b43_key_write (struct b43_wldev * dev, int index, u8 algorithm, const u8 * key, size_t key_len, const u8 * mac_addr, struct ieee80211_key_conf * keyconf) [static]
Definition at line 967 of file main.c.
References b43_new_kidx_api(), B43_NR_GROUP_KEYS, B43_NR_PAIRWISE_KEYS, B43_SEC_ALGO_TKIP, B43_SEC_KEYSIZE, B43_WARN_ON, b43warn(), do_key_write(), b43_wldev::key, b43_key::keyconf, and b43_wldev::wl.
Referenced by b43_op_set_key().
void b43_mac_enable (struct b43_wldev * dev)
Definition at line 2783 of file main.c.
References B43_DBG_FIRMWARE, b43_debug(), B43_IRQ_MAC_SUSPENDED, B43_MACCTL_ENABLED, B43_MMIO_GEN_IRQ_REASON, B43_MMIO_MACCTL, b43_power_saving_ctl_bits(), b43_read32(), b43_shm_read16(), B43_SHM_SH_UCODESTAT, B43_SHM_SH_UCODESTAT_SLEEP, B43_SHM_SH_UCODESTAT_SUSP, B43_SHM_SHARED, B43_WARN_ON, b43_write32(), b43err(), b43_wldev::mac_suspended, and b43_wldev::wl.
Referenced by b43_calibrate_lo_setting(), b43_gphy_dc_lt_init(), b43_gphy_op_adjust_txpower(), b43_gphy_op_pwork_15sec(), b43_gphy_op_pwork_60sec(), b43_nphy_classifier(), b43_nphy_set_rx_core_state(), b43_op_bss_info_changed(), b43_op_conf_tx(), b43_op_config(), b43_phy_lcn_sense_setup(), b43_phy_lcn_tx_pwr_ctl_init(), b43_qos_upload_all(), b43_software_rfkill(), b43_wireless_core_start(), and lpphy_calibration().
void b43_mac_phy_clock_set (struct b43_wldev * dev, bool on)
Definition at line 2849 of file main.c.
References B43_BCMA_IOCTL_MACPHYCLKEN, B43_BUS_SSB, B43_TMSLOW_MACPHYCLKEN, b43_bus_dev::bdev, b43_bus_dev::bus_type, b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_chip_init(), b43_phy_ht_op_init(), and b43_phy_initn().
void b43_mac_suspend (struct b43_wldev * dev)
Definition at line 2814 of file main.c.
References B43_IRQ_MAC_SUSPENDED, B43_MACCTL_ENABLED, B43_MMIO_GEN_IRQ_REASON, B43_MMIO_MACCTL, b43_power_saving_ctl_bits(), B43_PS_AWAKE, b43_read32(), B43_WARN_ON, b43_write32(), b43err(), b43_wldev::mac_suspended, and b43_wldev::wl.
Referenced by b43_calibrate_lo_setting(), b43_gphy_dc_lt_init(), b43_gphy_op_adjust_txpower(), b43_gphy_op_pwork_15sec(), b43_gphy_op_pwork_60sec(), b43_nphy_classifier(), b43_nphy_set_rx_core_state(), b43_op_bss_info_changed(), b43_op_conf_tx(), b43_op_config(), b43_phy_lcn_sense_setup(), b43_phy_lcn_tx_pwr_ctl_init(), b43_qos_upload_all(), b43_software_rfkill(), b43_wireless_core_stop(), and lpphy_calibration().
static void b43_macfilter_set (struct b43_wldev * dev, u16 offset, const u8 * mac) [static]
Definition at line 625 of file main.c.
References B43_MMIO_MACFILTER_CONTROL, B43_MMIO_MACFILTER_DATA, and b43_write16().
Referenced by b43_upload_card_macaddress(), and b43_write_mac_bssid_templates().
static void b43_mgmtframe_txantenna (struct b43_wldev * dev, int antenna) [static]
Definition at line 3003 of file main.c.
References b43_antenna_to_phyctl(), b43_shm_read16(), B43_SHM_SH_ACKCTSPHYCTL, B43_SHM_SH_PRPHYCTL, B43_SHM_SHARED, b43_shm_write16(), and B43_TXH_PHY_ANT.
Referenced by b43_chip_init(), and b43_op_config().
static int b43_one_core_attach (struct b43_bus_dev * dev, struct b43_wl * wl) [static]
Definition at line 5188 of file main.c.
References b43_bus_set_wldev(), b43_debugfs_add_device(), b43_modparam_pio, b43_set_status, B43_STAT_UNINIT, b43_wireless_core_attach(), b43_wldev::bad_frames_preempt, b43_wldev::dev, b43_wl::devlist, b43_wldev::list, modparam_bad_frames_preempt, b43_wl::nr_devs, b43_wldev::use_pio, and b43_wldev::wl.
static void b43_one_core_detach (struct b43_bus_dev * dev) [static]
Definition at line 5170 of file main.c.
References b43_bus_get_wldev(), b43_bus_set_wldev(), b43_debugfs_remove_device(), b43_wireless_core_detach(), b43_wldev::list, b43_wl::nr_devs, and b43_wldev::wl.
static int b43_op_add_interface (struct ieee80211_hw * hw, struct ieee80211_vif * vif) [static]
Definition at line 4726 of file main.c.
References b43_adjust_opmode(), b43_op_bss_info_changed(), b43_set_pretbtt(), b43_set_synth_pu_delay(), b43_upload_card_macaddress(), b43dbg(), b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), b43_wl::if_type, b43_wl::mac_addr, b43_wl::mutex, b43_wl::operating, and b43_wl::vif.
static int b43_op_beacon_set_tim (struct ieee80211_hw * hw, struct ieee80211_sta * sta, bool set) [static]
Definition at line 4864 of file main.c.
References b43_update_templates(), and hw_to_b43_wl().
static void b43_op_bss_info_changed (struct ieee80211_hw * hw, struct ieee80211_vif * vif, struct ieee80211_bss_conf * conf, u32 changed) [static]
Definition at line 3933 of file main.c.
References b43_is_mode(), b43_mac_enable(), b43_mac_suspend(), b43_set_beacon_int(), b43_short_slot_timing_disable(), b43_short_slot_timing_enable(), B43_STAT_INITIALIZED, B43_STAT_STARTED, b43_status, b43_update_basic_rates(), b43_update_templates(), B43_WARN_ON, b43_write_mac_bssid_templates(), b43_wl::bssid, b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), b43_wl::mutex, and b43_wl::vif.
Referenced by b43_chip_reset(), b43_op_add_interface(), and b43_op_config().
static int b43_op_conf_tx (struct ieee80211_hw * hw, struct ieee80211_vif * vif, u16 _queue, const struct ieee80211_tx_queue_params * params) [static]
Definition at line 3562 of file main.c.
References b43_mac_enable(), b43_mac_suspend(), b43_qos_params_upload(), B43_STAT_INITIALIZED, b43_status, b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), b43_wl::mutex, b43_qos_params::p, and b43_wl::qos_params.
static int b43_op_config (struct ieee80211_hw * hw, u32 changed) [static]
Definition at line 3796 of file main.c.
References B43_ANTENNA_DEFAULT, b43_mac_enable(), b43_mac_suspend(), b43_mgmtframe_txantenna(), b43_op_bss_info_changed(), b43_phy_txpower_check(), b43_set_retry_limits(), b43_software_rfkill(), b43_switch_band(), b43_switch_channel(), B43_TXPWR_IGNORE_TIME, B43_TXPWR_IGNORE_TSSI, b43info(), b43_phy::channel, b43_wl::current_dev, b43_phy::desired_txpower, b43_wldev::dev, hw_to_b43_wl(), b43_phy::is_40mhz, b43_wl::mutex, b43_phy::ops, b43_wldev::phy, b43_wl::radio_enabled, b43_wldev::radio_hw_enable, b43_phy::radio_on, b43_wl::radiotap_enabled, b43_phy_operations::set_rx_antenna, b43_wl::vif, and b43_wldev::wl.
Referenced by b43_chip_reset(), and b43_op_start().
static void b43_op_configure_filter (struct ieee80211_hw * hw, unsigned int changed, unsigned int * fflags, u64 multicast) [static]
Definition at line 4103 of file main.c.
References b43_adjust_opmode(), B43_STAT_INITIALIZED, b43_status, b43_wl::current_dev, b43_wldev::dev, b43_wl::filter_flags, hw_to_b43_wl(), and b43_wl::mutex.
static int b43_op_get_stats (struct ieee80211_hw * hw, struct ieee80211_low_level_stats * stats) [static]
Definition at line 3598 of file main.c.
References hw_to_b43_wl(), b43_wl::ieee_stats, and b43_wl::mutex.
static int b43_op_get_survey (struct ieee80211_hw * hw, int idx, struct survey_info * survey) [static]
Definition at line 4913 of file main.c.
References b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), b43_stats::link_noise, and b43_wldev::stats.
static u64 b43_op_get_tsf (struct ieee80211_hw * hw, struct ieee80211_vif * vif) [static]
Definition at line 3610 of file main.c.
References B43_STAT_INITIALIZED, b43_status, b43_tsf_read(), b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), and b43_wl::mutex.
static void b43_op_remove_interface (struct ieee80211_hw * hw, struct ieee80211_vif * vif) [static]
Definition at line 4769 of file main.c.
References b43_adjust_opmode(), b43_upload_card_macaddress(), B43_WARN_ON, b43dbg(), b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), b43_wl::mac_addr, b43_wl::mutex, b43_wl::operating, and b43_wl::vif.
static int b43_op_set_key (struct ieee80211_hw * hw, enum set_key_cmd cmd, struct ieee80211_vif * vif, struct ieee80211_sta * sta, struct ieee80211_key_conf * key) [static]
Definition at line 3992 of file main.c.
References b43_dump_keymemory(), b43_hf_read(), B43_HF_USEDEFKEYS, b43_hf_write(), b43_key_clear(), b43_key_write(), B43_SEC_ALGO_AES, B43_SEC_ALGO_TKIP, B43_SEC_ALGO_WEP104, B43_SEC_ALGO_WEP40, B43_STAT_INITIALIZED, b43_status, B43_WARN_ON, b43dbg(), b43_wl::current_dev, b43_wldev::dev, b43_wldev::fw, hw_to_b43_wl(), b43_wldev::hwcrypto_enabled, b43_wldev::key, modparam_hwtkip, modparam_nohwcrypt, b43_wl::mutex, and b43_firmware::pcm_request_failed.
static void b43_op_set_tsf (struct ieee80211_hw * hw, struct ieee80211_vif * vif, u64 tsf) [static]
Definition at line 3629 of file main.c.
References B43_STAT_INITIALIZED, b43_status, b43_tsf_write(), b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), and b43_wl::mutex.
static void b43_op_sta_notify (struct ieee80211_hw * hw, struct ieee80211_vif * vif, enum sta_notify_cmd notify_cmd, struct ieee80211_sta * sta) [static]
Definition at line 4875 of file main.c.
References B43_WARN_ON, hw_to_b43_wl(), and b43_wl::vif.
static int b43_op_start (struct ieee80211_hw * hw) [static]
Definition at line 4792 of file main.c.
References b43_op_config(), b43_qos_clear(), B43_STAT_INITIALIZED, B43_STAT_STARTED, b43_status, b43_wireless_core_exit(), b43_wireless_core_init(), b43_wireless_core_start(), b43_wl::beacon0_uploaded, b43_wl::beacon1_uploaded, b43_wl::beacon_templates_virgin, b43_wl::bssid, b43_wl::current_dev, b43_wldev::dev, b43_wl::filter_flags, hw_to_b43_wl(), b43_wl::mac_addr, b43_wl::mutex, b43_wl::radio_enabled, and b43_wl::radiotap_enabled.
static void b43_op_stop (struct ieee80211_hw * hw) [static]
Definition at line 4842 of file main.c.
References B43_STAT_STARTED, b43_status, b43_wireless_core_exit(), b43_wireless_core_stop(), b43_wl::beacon_update_trigger, b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), b43_wl::mutex, b43_wl::radio_enabled, and b43_wl::txpower_adjust_work.
static void b43_op_sw_scan_complete_notifier (struct ieee80211_hw * hw) [static]
Definition at line 4899 of file main.c.
References b43_hf_read(), B43_HF_SKCFPUP, b43_hf_write(), B43_STAT_INITIALIZED, b43_status, b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), and b43_wl::mutex.
static void b43_op_sw_scan_start_notifier (struct ieee80211_hw * hw) [static]
Definition at line 4885 of file main.c.
References b43_hf_read(), B43_HF_SKCFPUP, b43_hf_write(), B43_STAT_INITIALIZED, b43_status, b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), and b43_wl::mutex.
static void b43_op_tx (struct ieee80211_hw * hw, struct sk_buff * skb) [static]
Definition at line 3407 of file main.c.
References B43_WARN_ON, b43_wl::hw, hw_to_b43_wl(), b43_wl::tx_queue, and b43_wl::tx_work.
static void b43_op_update_tkip_key (struct ieee80211_hw * hw, struct ieee80211_vif * vif, struct ieee80211_key_conf * keyconf, struct ieee80211_sta * sta, u32 iv32, u16 * phase1key) [static]
Definition at line 902 of file main.c.
References B43_STAT_INITIALIZED, b43_status, B43_WARN_ON, b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), keymac_write(), modparam_hwtkip, b43_wl::mutex, and rx_tkip_phase1_write().
static void b43_periodic_every15sec (struct b43_wldev * dev) [static]
Definition at line 3157 of file main.c.
References b43_controller_restart(), B43_DBG_VERBOSESTATS, b43_debug(), B43_PHY_TX_BADNESS_LIMIT, b43_shm_read16(), B43_SHM_SCRATCH, b43_shm_write16(), B43_WATCHDOG_REG, b43dbg(), b43err(), b43_wldev::fw, b43_firmware::opensource, b43_phy::ops, b43_wldev::phy, b43_phy_operations::pwork_15sec, b43_phy::txerr_cnt, and b43_wldev::wl.
Referenced by do_periodic_work().
static void b43_periodic_every30sec (struct b43_wldev * dev) [static]
Definition at line 3151 of file main.c.
References b43_calculate_link_quality().
Referenced by do_periodic_work().
static void b43_periodic_every60sec (struct b43_wldev * dev) [static]
Definition at line 3140 of file main.c.
References b43_phy_txpower_check(), B43_TXPWR_IGNORE_TIME, b43_phy::ops, b43_wldev::phy, and b43_phy_operations::pwork_60sec.
Referenced by do_periodic_work().
static void b43_periodic_tasks_setup (struct b43_wldev * dev) [static]
Definition at line 3248 of file main.c.
References b43_periodic_work_handler(), b43_wl::hw, b43_wldev::periodic_state, b43_wldev::periodic_work, and b43_wldev::wl.
Referenced by b43_wireless_core_start().
static void b43_periodic_work_handler (struct work_struct * work) [static]
Definition at line 3221 of file main.c.
References B43_DBG_PWORK_FAST, B43_DBG_PWORK_STOP, b43_debug(), B43_STAT_STARTED, b43_status, b43_wldev::dev, do_periodic_work(), b43_wl::hw, b43_wl::mutex, b43_wldev::periodic_state, b43_wldev::periodic_work, and b43_wldev::wl.
Referenced by b43_periodic_tasks_setup().
static int b43_phy_versioning (struct b43_wldev * dev) [static]
Definition at line 4270 of file main.c.
References b43_phy::analog, B43_MMIO_PHY_VER, B43_MMIO_RADIO24_CONTROL, B43_MMIO_RADIO24_DATA, B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_HIGH, B43_MMIO_RADIO_DATA_LOW, B43_PHYTYPE_A, B43_PHYTYPE_B, B43_PHYTYPE_G, B43_PHYTYPE_HT, B43_PHYTYPE_LCN, B43_PHYTYPE_LP, B43_PHYTYPE_N, B43_PHYVER_ANALOG, B43_PHYVER_ANALOG_SHIFT, B43_PHYVER_TYPE, B43_PHYVER_TYPE_SHIFT, B43_PHYVER_VERSION, B43_RADIOCTL_ID, b43_read16(), B43_WARN_ON, b43_write16(), b43dbg(), b43err(), b43_bus_dev::chip_id, b43_bus_dev::chip_rev, b43_bus_dev::core_rev, b43_wldev::dev, b43_wldev::phy, b43_phy::radio_manuf, b43_phy::radio_rev, b43_phy::radio_ver, b43_phy::rev, b43_phy::type, and b43_wldev::wl.
Referenced by b43_wireless_core_attach().
void b43_power_saving_ctl_bits (struct b43_wldev * dev, unsigned int ps_flags)
Definition at line 1112 of file main.c.
References B43_MACCTL_AWAKE, B43_MACCTL_HWPS, B43_MMIO_MACCTL, B43_PS_ASLEEP, B43_PS_AWAKE, B43_PS_DISABLED, B43_PS_ENABLED, b43_read32(), b43_shm_read16(), B43_SHM_SH_UCODESTAT, B43_SHM_SH_UCODESTAT_SLEEP, B43_SHM_SHARED, B43_WARN_ON, b43_write32(), b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_dma_tx_resume(), b43_dma_tx_suspend(), b43_mac_enable(), b43_mac_suspend(), b43_phy_lock(), b43_phy_unlock(), b43_pio_tx_resume(), b43_pio_tx_suspend(), and handle_irq_tbtt_indication().
static void b43_print_driverinfo (void) [static]
Definition at line 5474 of file main.c.
Referenced by b43_init().
static void b43_print_fw_helptext (struct b43_wl * wl, bool error) [static]
Definition at line 2083 of file main.c.
References b43err(), and b43warn().
Referenced by b43_request_firmware(), b43_upload_microcode(), and b43_write_initvals().
static void b43_put_phy_into_reset (struct b43_wldev * dev) [static]
Definition at line 3644 of file main.c.
References B43_BUS_SSB, B43_TMSLOW_GMODE, B43_TMSLOW_PHYRESET, b43err(), b43_bus_dev::bus_type, b43_wldev::dev, b43_bus_dev::sdev, and b43_wldev::wl.
Referenced by b43_switch_band().
static void b43_qos_clear (struct b43_wl * wl) [static]
Definition at line 3494 of file main.c.
References B43_QOS_BACKGROUND, B43_QOS_BESTEFFORT, B43_QOS_VIDEO, B43_QOS_VOICE, B43_WARN_ON, b43_qos_params::p, and b43_wl::qos_params.
Referenced by b43_op_start().
static void b43_qos_init (struct b43_wldev * dev) [static]
Definition at line 3539 of file main.c.
References B43_HF_EDCF, b43_hf_read(), b43_hf_write(), B43_MMIO_IFSCTL, B43_MMIO_IFSCTL_USE_EDCF, b43_qos_upload_all(), b43_read16(), b43_write16(), b43dbg(), b43_wldev::qos_enabled, and b43_wldev::wl.
Referenced by b43_wireless_core_init().
static void b43_qos_params_upload (struct b43_wldev * dev, const struct ieee80211_tx_queue_params * p, u16 shm_offset) [static]
Definition at line 3423 of file main.c.
References B43_MMIO_RNG, B43_NR_QOSPARAMS, B43_QOSPARAM_AIFS, B43_QOSPARAM_BSLOTS, B43_QOSPARAM_CWCUR, B43_QOSPARAM_CWMAX, B43_QOSPARAM_CWMIN, B43_QOSPARAM_REGGAP, B43_QOSPARAM_STATUS, B43_QOSPARAM_TXOP, b43_read16(), b43_shm_read16(), B43_SHM_SHARED, b43_shm_write16(), and b43_wldev::qos_enabled.
Referenced by b43_op_conf_tx(), and b43_qos_upload_all().
static void b43_qos_upload_all (struct b43_wldev * dev) [static]
Definition at line 3473 of file main.c.
References b43_mac_enable(), b43_mac_suspend(), b43_qos_params_upload(), b43_qos_params::p, b43_wldev::qos_enabled, b43_wl::qos_params, and b43_wldev::wl.
Referenced by b43_qos_init().
static void b43_ram_write (struct b43_wldev * dev, u16 offset, u32 val) [static]
Definition at line 422 of file main.c.
References B43_MACCTL_BE, B43_MMIO_MACCTL, B43_MMIO_RAM_CONTROL, B43_MMIO_RAM_DATA, b43_read32(), B43_WARN_ON, and b43_write32().
Referenced by b43_dummy_transmission(), b43_write_mac_bssid_templates(), and b43_write_template_common().
static void b43_rate_memory_init (struct b43_wldev * dev) [static]
Definition at line 2958 of file main.c.
References B43_CCK_RATE_11MB, B43_CCK_RATE_1MB, B43_CCK_RATE_2MB, B43_CCK_RATE_5MB, B43_OFDM_RATE_12MB, B43_OFDM_RATE_18MB, B43_OFDM_RATE_24MB, B43_OFDM_RATE_36MB, B43_OFDM_RATE_48MB, B43_OFDM_RATE_54MB, B43_OFDM_RATE_6MB, B43_PHYTYPE_A, B43_PHYTYPE_B, B43_PHYTYPE_G, B43_PHYTYPE_HT, B43_PHYTYPE_LCN, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_rate_memory_write(), B43_WARN_ON, b43_wldev::phy, and b43_phy::type.
Referenced by b43_wireless_core_init().
static void b43_rate_memory_write (struct b43_wldev * dev, u16 rate, int is_ofdm) [static]
Definition at line 2943 of file main.c.
References b43_plcp_get_ratecode_cck(), b43_plcp_get_ratecode_ofdm(), b43_shm_read16(), B43_SHM_SHARED, and b43_shm_write16().
Referenced by b43_rate_memory_init().
static int b43_ratelimit (struct b43_wl * wl) [static]
Definition at line 329 of file main.c.
References B43_STAT_STARTED, b43_status, and b43_wl::current_dev.
Referenced by b43err(), b43info(), and b43warn().
static void b43_release_firmware (struct b43_wldev * dev) [static]
Definition at line 2075 of file main.c.
References b43_do_release_fw(), b43_wldev::fw, b43_firmware::initvals, b43_firmware::initvals_band, b43_firmware::pcm, and b43_firmware::ucode.
Referenced by b43_try_request_fw(), and b43_wireless_core_detach().
static int b43_request_firmware (struct b43_wldev * dev) [static]
Definition at line 2399 of file main.c.
References B43_FWTYPE_OPENSOURCE, B43_FWTYPE_PROPRIETARY, B43_NR_FWTYPES, b43_print_fw_helptext(), b43_try_request_fw(), b43err(), b43_request_fw_context::dev, b43_request_fw_context::errors, b43_request_fw_context::fatal_failure, b43_request_fw_context::req_type, and b43_wldev::wl.
Referenced by b43_chip_init().
static void b43_rng_exit (struct b43_wl * wl) [static]
Definition at line 3346 of file main.c.
Referenced by b43_wireless_core_exit().
static int b43_rng_init (struct b43_wl * wl) [static]
Definition at line 3354 of file main.c.
References b43err(), and b43_wl::hw.
Referenced by b43_wireless_core_init().
static void b43_sdio_interrupt_handler (struct b43_wldev * dev) [static]
Definition at line 2054 of file main.c.
References b43_do_interrupt(), b43_do_interrupt_thread(), b43_wl::mutex, and b43_wldev::wl.
Referenced by b43_wireless_core_start().
static void b43_security_init (struct b43_wldev * dev) [static]
Definition at line 3314 of file main.c.
References b43_clear_keys(), B43_MMIO_RCMTA_COUNT, B43_NR_PAIRWISE_KEYS, b43_shm_read16(), B43_SHM_SH_KTP, B43_SHM_SHARED, b43_write16(), and b43_wldev::ktp.
Referenced by b43_wireless_core_init().
static void b43_set_beacon_int (struct b43_wldev * dev, u16 beacon_int) [static]
Definition at line 1763 of file main.c.
References B43_MMIO_TSF_CFP_REP, B43_MMIO_TSF_CFP_START, b43_time_lock(), b43_time_unlock(), b43_write16(), b43_write32(), b43dbg(), b43_bus_dev::core_rev, b43_wldev::dev, and b43_wldev::wl.
Referenced by b43_op_bss_info_changed().
static void b43_set_phytxctl_defaults (struct b43_wldev * dev) [static]
Definition at line 2989 of file main.c.
References B43_SHM_SH_ACKCTSPHYCTL, B43_SHM_SH_BEACPHYCTL, B43_SHM_SH_PRPHYCTL, B43_SHM_SHARED, b43_shm_write16(), B43_TXH_PHY_ANT01AUTO, B43_TXH_PHY_ENC_CCK, and B43_TXH_PHY_TXPWR.
Referenced by b43_wireless_core_init().
static void b43_set_pretbtt (struct b43_wldev * dev) [static]
Definition at line 4538 of file main.c.
References b43_is_mode(), B43_MMIO_TSF_CFP_PRETBTT, B43_PHYTYPE_A, B43_SHM_SH_PRETBTT, B43_SHM_SHARED, b43_shm_write16(), b43_write16(), b43_wldev::phy, b43_phy::type, and b43_wldev::wl.
Referenced by b43_op_add_interface().
static void b43_set_retry_limits (struct b43_wldev * dev, unsigned int short_retry, unsigned int long_retry) [static]
Definition at line 3781 of file main.c.
References B43_SHM_SC_LRLIMIT, B43_SHM_SC_SRLIMIT, B43_SHM_SCRATCH, and b43_shm_write16().
Referenced by b43_op_config(), and b43_wireless_core_init().
static void b43_set_slot_time (struct b43_wldev * dev, u16 slot_time) [static]
Definition at line 679 of file main.c.
References b43_current_band(), B43_MMIO_IFSSLOT, b43_write16(), and b43_wldev::wl.
Referenced by b43_short_slot_timing_disable(), and b43_short_slot_timing_enable().
static void b43_set_synth_pu_delay (struct b43_wldev * dev, bool idle) [static]
Definition at line 4520 of file main.c.
References b43_is_mode(), B43_PHYTYPE_A, B43_SHM_SH_SPUWKUP, B43_SHM_SHARED, b43_shm_write16(), b43_wldev::phy, b43_phy::radio_rev, b43_phy::radio_ver, b43_phy::type, and b43_wldev::wl.
Referenced by b43_op_add_interface(), and b43_wireless_core_init().
static int b43_setup_bands (struct b43_wldev * dev, bool have_2ghz_phy, bool have_5ghz_phy) [static]
Definition at line 5009 of file main.c.
References b43_band_2GHz, b43_band_5GHz_aphy, b43_band_5GHz_nphy, B43_PHYTYPE_N, b43_wl::hw, b43_wldev::phy, b43_phy::supports_2ghz, b43_phy::supports_5ghz, b43_phy::type, and b43_wldev::wl.
Referenced by b43_wireless_core_attach().
static void b43_shm_control_word (struct b43_wldev * dev, u16 routing, u16 offset) [inline, static]
Definition at line 437 of file main.c.
References B43_MMIO_SHM_CONTROL, and b43_write32().
Referenced by b43_shm_read16(), b43_shm_read32(), b43_shm_write16(), b43_shm_write32(), and b43_upload_microcode().
u16 b43_shm_read16 (struct b43_wldev * dev, u16 routing, u16 offset)
Definition at line 472 of file main.c.
References B43_MMIO_SHM_DATA, B43_MMIO_SHM_DATA_UNALIGNED, b43_read16(), b43_shm_control_word(), B43_SHM_SHARED, and B43_WARN_ON.
Referenced by b43_dump_keymemory(), b43_fwcapa_read(), b43_handle_firmware_panic(), b43_hf_read(), b43_jssi_read(), b43_mac_enable(), b43_mgmtframe_txantenna(), b43_periodic_every15sec(), b43_phy_shm_tssi_read(), b43_power_saving_ctl_bits(), b43_qos_params_upload(), b43_rate_memory_write(), b43_security_init(), b43_switch_channel(), b43_update_basic_rates(), b43_upload_microcode(), b43_validate_chipaccess(), b43_write_beacon_template(), handle_irq_noise(), handle_irq_ucode_debug(), lo_read_power_vector(), shm16read__read_file(), and shm16write__write_file().
u32 b43_shm_read32 (struct b43_wldev * dev, u16 routing, u16 offset)
Definition at line 449 of file main.c.
References B43_MMIO_SHM_DATA, B43_MMIO_SHM_DATA_UNALIGNED, b43_read16(), b43_read32(), b43_shm_control_word(), B43_SHM_SHARED, and B43_WARN_ON.
Referenced by b43_dump_keymemory(), b43_phy_shm_tssi_read(), b43_validate_chipaccess(), shm32read__read_file(), and shm32write__write_file().
void b43_shm_write16 (struct b43_wldev * dev, u16 routing, u16 offset, u16 value)
Definition at line 513 of file main.c.
References B43_MMIO_SHM_DATA, B43_MMIO_SHM_DATA_UNALIGNED, b43_shm_control_word(), B43_SHM_SHARED, B43_WARN_ON, and b43_write16().
Referenced by b43_chip_init(), b43_hf_write(), b43_jssi_write(), b43_mgmtframe_txantenna(), b43_nphy_tx_iq_workaround(), b43_nphy_tx_pwr_ctrl_coef_setup(), b43_periodic_every15sec(), b43_pio_init(), b43_qos_params_upload(), b43_rate_memory_write(), b43_set_phytxctl_defaults(), b43_set_pretbtt(), b43_set_retry_limits(), b43_set_synth_pu_delay(), b43_set_txpower_g(), b43_shm_clear_tssi(), b43_switch_channel(), b43_update_basic_rates(), b43_upload_microcode(), b43_validate_chipaccess(), b43_wireless_core_init(), b43_write_beacon_template(), b43_write_template_common(), dma_tx_fragment(), handle_irq_ucode_debug(), key_write(), keymac_write(), lo_read_power_vector(), pio_tx_frame(), rx_tkip_phase1_write(), and shm16write__write_file().
void b43_shm_write32 (struct b43_wldev * dev, u16 routing, u16 offset, u32 value)
Definition at line 493 of file main.c.
References B43_MMIO_SHM_DATA, B43_MMIO_SHM_DATA_UNALIGNED, b43_shm_control_word(), B43_SHM_SHARED, B43_WARN_ON, b43_write16(), and b43_write32().
Referenced by b43_phy_shm_tssi_read(), b43_validate_chipaccess(), keymac_write(), and shm32write__write_file().
static void b43_short_slot_timing_disable (struct b43_wldev * dev) [static]
Definition at line 700 of file main.c.
References b43_set_slot_time().
Referenced by b43_op_bss_info_changed().
static void b43_short_slot_timing_enable (struct b43_wldev * dev) [static]
Definition at line 695 of file main.c.
References b43_set_slot_time().
Referenced by b43_op_bss_info_changed().
static void b43_sprom_fixup (struct ssb_bus * bus) [static]
Definition at line 5227 of file main.c.
References B43_BFL_BTCOEXIST, B43_BFL_PACTRL, and IS_PDEV.
static struct ssb_device* b43_ssb_gpio_dev (struct b43_wldev * dev) [static, read]
Definition at line 2693 of file main.c.
References b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_gpio_cleanup(), and b43_gpio_init().
static void b43_ssb_wireless_core_reset (struct b43_wldev * dev, bool gmode) [static]
Definition at line 1205 of file main.c.
References b43_device_enable(), B43_PHYTYPE_N, B43_TMSLOW_GMODE, B43_TMSLOW_PHY_BANDWIDTH_20MHZ, B43_TMSLOW_PHYCLKEN, B43_TMSLOW_PHYRESET, b43_wldev::dev, b43_wldev::phy, b43_bus_dev::sdev, and b43_phy::type.
Referenced by b43_wireless_core_reset().
static int b43_switch_band (struct b43_wl * wl, struct ieee80211_channel * chan) [static]
Definition at line 3690 of file main.c.
References b43_put_phy_into_reset(), B43_STAT_INITIALIZED, B43_STAT_STARTED, b43_status, B43_WARN_ON, b43_wireless_core_exit(), b43_wireless_core_init(), b43_wireless_core_start(), b43_wireless_core_stop(), b43dbg(), b43err(), band_to_string(), b43_wl::current_dev, b43_wl::devlist, b43_phy::gmode, b43_wldev::list, b43_wldev::phy, b43_phy::supports_2ghz, and b43_phy::supports_5ghz.
Referenced by b43_op_config().
static void b43_time_lock (struct b43_wldev * dev) [static]
Definition at line 579 of file main.c.
References B43_MACCTL_TBTTHOLD, B43_MMIO_MACCTL, b43_read32(), and b43_write32().
Referenced by b43_set_beacon_int(), and b43_tsf_write().
static void b43_time_unlock (struct b43_wldev * dev) [static]
Definition at line 590 of file main.c.
References B43_MACCTL_TBTTHOLD, B43_MMIO_MACCTL, b43_read32(), and b43_write32().
Referenced by b43_set_beacon_int(), and b43_tsf_write().
static int b43_try_request_fw (struct b43_request_fw_context * ctx) [static]
Definition at line 2186 of file main.c.
References b43_do_request_fw(), B43_PHYTYPE_A, B43_PHYTYPE_G, B43_PHYTYPE_HT, B43_PHYTYPE_LCN, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_release_firmware(), B43_TMSHIGH_HAVE_2GHZ_PHY, b43err(), b43_bus_dev::core_rev, b43_request_fw_context::dev, b43_wldev::dev, b43_request_fw_context::fatal_failure, b43_wldev::fw, b43_firmware::initvals, b43_firmware::initvals_band, b43_firmware::pcm, b43_firmware::pcm_request_failed, b43_wldev::phy, b43_firmware::rev, b43_bus_dev::sdev, b43_phy::type, b43_firmware::ucode, and b43_wldev::wl.
Referenced by b43_request_firmware().
void b43_tsf_read (struct b43_wldev * dev, u64 * tsf)
Definition at line 563 of file main.c.
References B43_MMIO_REV3PLUS_TSF_HIGH, B43_MMIO_REV3PLUS_TSF_LOW, b43_read32(), B43_WARN_ON, b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_op_get_tsf(), and b43_rx().
void b43_tsf_write (struct b43_wldev * dev, u64 tsf)
Definition at line 617 of file main.c.
References b43_time_lock(), b43_time_unlock(), and b43_tsf_write_locked().
Referenced by b43_op_set_tsf().
static void b43_tsf_write_locked (struct b43_wldev * dev, u64 tsf) [static]
Definition at line 601 of file main.c.
References B43_MMIO_REV3PLUS_TSF_HIGH, B43_MMIO_REV3PLUS_TSF_LOW, B43_WARN_ON, b43_write32(), b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_tsf_write().
static void b43_tx_work (struct work_struct * work) [static]
Definition at line 3376 of file main.c.
References b43_dma_tx(), b43_pio_tx(), B43_STAT_STARTED, b43_status, b43_using_pio_transfers(), b43_wl::current_dev, b43_wldev::dev, b43_wl::mutex, b43_wl::tx_queue, and b43_wl::tx_work.
Referenced by b43_wireless_init().
static void b43_update_basic_rates (struct b43_wldev * dev, u32 brates) [static]
Definition at line 3888 of file main.c.
References b43_current_band(), b43_is_cck_rate(), b43_plcp_get_ratecode_cck(), b43_plcp_get_ratecode_ofdm(), b43_shm_read16(), B43_SHM_SH_CCKBASIC, B43_SHM_SH_CCKDIRECT, B43_SHM_SH_OFDMBASIC, B43_SHM_SH_OFDMDIRECT, B43_SHM_SHARED, b43_shm_write16(), b43_wl::hw, and b43_wldev::wl.
Referenced by b43_op_bss_info_changed().
static void b43_update_templates (struct b43_wl * wl) [static]
Definition at line 1737 of file main.c.
References b43_wl::beacon0_uploaded, b43_wl::beacon1_uploaded, b43_wl::beacon_update_trigger, b43_wl::current_beacon, b43_wl::hw, and b43_wl::vif.
Referenced by b43_op_beacon_set_tim(), and b43_op_bss_info_changed().
static void b43_upload_beacon0 (struct b43_wldev * dev) [static]
Definition at line 1621 of file main.c.
References b43_write_beacon_template(), b43_wl::beacon0_uploaded, and b43_wldev::wl.
Referenced by handle_irq_beacon().
static void b43_upload_beacon1 (struct b43_wldev * dev) [static]
Definition at line 1631 of file main.c.
References b43_write_beacon_template(), b43_wl::beacon1_uploaded, and b43_wldev::wl.
Referenced by handle_irq_beacon().
static void b43_upload_card_macaddress (struct b43_wldev * dev) [static]
Definition at line 673 of file main.c.
References B43_MACFILTER_SELF, b43_macfilter_set(), b43_write_mac_bssid_templates(), b43_wl::mac_addr, and b43_wldev::wl.
Referenced by b43_op_add_interface(), b43_op_remove_interface(), and b43_wireless_core_init().
static int b43_upload_initvals (struct b43_wldev * dev) [static]
Definition at line 2660 of file main.c.
References b43_write_initvals(), b43_firmware_file::data, b43_wldev::fw, b43_firmware::initvals, b43_firmware::initvals_band, and b43_fw_header::size.
Referenced by b43_chip_init().
static int b43_upload_microcode (struct b43_wldev * dev) [static]
Definition at line 2441 of file main.c.
References B43_FW_HDR_351, B43_FW_HDR_410, B43_FW_HDR_598, B43_FWCAPA_HWCRYPTO, B43_FWCAPA_QOS, b43_fwcapa_read(), B43_IRQ_ALL, B43_IRQ_MAC_SUSPENDED, B43_MACCTL_PSM_JMP0, B43_MACCTL_PSM_RUN, B43_MMIO_GEN_IRQ_REASON, B43_MMIO_MACCTL, B43_MMIO_SHM_DATA, b43_print_fw_helptext(), b43_read32(), B43_SHM_AUTOINC_W, b43_shm_control_word(), B43_SHM_HW, b43_shm_read16(), B43_SHM_SCRATCH, B43_SHM_SH_UCODEDATE, B43_SHM_SH_UCODEPATCH, B43_SHM_SH_UCODEREV, B43_SHM_SH_UCODETIME, B43_SHM_SHARED, B43_SHM_UCODE, b43_shm_write16(), B43_WARN_ON, b43_write32(), b43err(), b43info(), b43warn(), b43_bus_dev::core_id, b43_firmware_file::data, b43_wldev::dev, b43_wldev::fw, b43_firmware::hdr_format, b43_wl::hw, b43_wldev::hwcrypto_enabled, b43_wl::mac80211_initially_registered_queues, modparam_qos, b43_firmware::opensource, b43_firmware::patch, b43_firmware::pcm, b43_firmware::pcm_request_failed, b43_wldev::qos_enabled, b43_firmware::rev, b43_firmware::ucode, and b43_wldev::wl.
Referenced by b43_chip_init().
static int b43_validate_chipaccess (struct b43_wldev * dev) [static]
Definition at line 3258 of file main.c.
References B43_MACCTL_GMODE, B43_MACCTL_IHR_ENABLED, B43_MMIO_MACCTL, B43_MMIO_TSF_CFP_START, B43_MMIO_TSF_CFP_START_HIGH, B43_MMIO_TSF_CFP_START_LOW, b43_read16(), b43_read32(), b43_shm_read16(), b43_shm_read32(), B43_SHM_SHARED, b43_shm_write16(), b43_shm_write32(), b43_write16(), b43_write32(), b43err(), b43warn(), b43_bus_dev::core_rev, b43_wldev::dev, and b43_wldev::wl.
Referenced by b43_wireless_core_attach().
static int b43_wireless_core_attach (struct b43_wldev * dev) [static]
Definition at line 5042 of file main.c.
References B43_BCMA_IOST_2G_PHY, B43_BCMA_IOST_5G_PHY, b43_bus_may_powerdown(), b43_bus_powerup(), B43_BUS_SSB, b43_chip_reset(), b43_device_disable(), b43_phy_allocate(), b43_phy_free(), b43_phy_versioning(), B43_PHYTYPE_A, B43_PHYTYPE_G, B43_PHYTYPE_HT, B43_PHYTYPE_LCN, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_setup_bands(), B43_TMSHIGH_HAVE_2GHZ_PHY, B43_TMSHIGH_HAVE_5GHZ_PHY, b43_validate_chipaccess(), B43_WARN_ON, b43_wireless_core_reset(), b43err(), b43_bus_dev::bdev, b43_bus_dev::bus_type, b43_bus_dev::core_rev, b43_wl::current_dev, b43_wldev::dev, b43_phy::gmode, b43_phy::ops, b43_wldev::phy, b43_phy::radio_on, b43_wldev::restart_work, b43_bus_dev::sdev, b43_phy_operations::switch_analog, b43_phy::type, and b43_wldev::wl.
Referenced by b43_one_core_attach().
static void b43_wireless_core_detach (struct b43_wldev * dev) [static]
Definition at line 5030 of file main.c.
References b43_phy_free(), b43_release_firmware(), b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_one_core_detach().
static void b43_wireless_core_exit (struct b43_wldev * dev) [static]
Definition at line 4557 of file main.c.
References b43_bus_may_powerdown(), b43_chip_exit(), b43_device_disable(), b43_dma_free(), B43_MACCTL_PSM_JMP0, B43_MACCTL_PSM_RUN, B43_MMIO_MACCTL, b43_pio_free(), b43_read32(), b43_rng_exit(), b43_set_status, B43_STAT_INITIALIZED, B43_STAT_UNINIT, b43_status, B43_WARN_ON, b43_write32(), b43_wl::current_beacon, b43_phy::ops, b43_wldev::phy, b43_phy_operations::switch_analog, and b43_wldev::wl.
Referenced by b43_chip_reset(), b43_op_start(), b43_op_stop(), and b43_switch_band().
static int b43_wireless_core_init (struct b43_wldev * dev) [static]
Definition at line 4590 of file main.c.
References b43_wldev::__using_pio_transfers, B43_BFL_PACTRL, B43_BFL_XTAL_NOSLOW, b43_bluetooth_coext_disable(), b43_bluetooth_coext_enable(), b43_bus_host_is_pcmcia(), b43_bus_host_is_sdio(), b43_bus_may_powerdown(), b43_bus_powerup(), B43_BUS_SSB, b43_chip_exit(), b43_chip_init(), B43_DEFAULT_LONG_RETRY_LIMIT, B43_DEFAULT_SHORT_RETRY_LIMIT, b43_device_is_enabled(), b43_dma_init(), B43_HF_4318TSSI, B43_HF_DSCRQ, B43_HF_GDCW, B43_HF_OFDMPABOOST, B43_HF_PCISCW, b43_hf_read(), B43_HF_SKCFPUP, B43_HF_SYMW, B43_HF_VCORECALC, b43_hf_write(), b43_imcfglo_timeouts_workaround(), B43_PHYTYPE_B, B43_PHYTYPE_G, b43_pio_init(), b43_qos_init(), b43_rate_memory_init(), b43_rng_init(), b43_security_init(), b43_set_phytxctl_defaults(), b43_set_retry_limits(), b43_set_status, b43_set_synth_pu_delay(), B43_SHM_SC_MAXCONT, B43_SHM_SC_MINCONT, B43_SHM_SCRATCH, B43_SHM_SH_LFFBLIM, B43_SHM_SH_PRMAXTIME, B43_SHM_SH_SFFBLIM, B43_SHM_SH_WLCOREREV, B43_SHM_SHARED, b43_shm_write16(), B43_STAT_INITIALIZED, B43_STAT_UNINIT, b43_status, b43_upload_card_macaddress(), B43_WARN_ON, b43_wireless_core_reset(), b43warn(), b43_bus_dev::bdev, b43_bus_dev::bus_sprom, b43_bus_dev::bus_type, b43_bus_dev::core_rev, b43_wldev::dev, b43_phy::gmode, b43_wl::hw, b43_phy::ops, b43_wldev::phy, b43_phy_operations::prepare_hardware, b43_phy_operations::prepare_structs, b43_phy::radio_rev, b43_phy::radio_ver, b43_phy::rev, b43_bus_dev::sdev, setup_struct_wldev_for_init(), b43_phy::type, b43_wldev::use_pio, and b43_wldev::wl.
Referenced by b43_chip_reset(), b43_op_start(), and b43_switch_band().
void b43_wireless_core_reset (struct b43_wldev * dev, bool gmode)
Definition at line 1233 of file main.c.
References B43_BUS_SSB, B43_MACCTL_GMODE, B43_MACCTL_IHR_ENABLED, B43_MMIO_MACCTL, b43_read32(), b43_ssb_wireless_core_reset(), b43_write32(), b43_bus_dev::bus_type, b43_wldev::dev, b43_phy::ops, b43_wldev::phy, and b43_phy_operations::switch_analog.
Referenced by b43_gphy_op_prepare_hardware(), b43_wireless_core_attach(), and b43_wireless_core_init().
static int b43_wireless_core_start (struct b43_wldev * dev) [static]
Definition at line 4219 of file main.c.
References b43_bus_host_is_sdio(), b43_interrupt_handler(), b43_interrupt_thread_handler(), b43_leds_init(), b43_mac_enable(), B43_MMIO_GEN_IRQ_MASK, b43_periodic_tasks_setup(), b43_sdio_interrupt_handler(), b43_sdio_request_irq(), b43_set_status, B43_STAT_INITIALIZED, B43_STAT_STARTED, b43_status, B43_WARN_ON, b43_write32(), b43dbg(), b43err(), b43_wldev::dev, drain_txstatus_queue(), b43_wl::hw, b43_bus_dev::irq, b43_wldev::irq_mask, and b43_wldev::wl.
Referenced by b43_chip_reset(), b43_op_start(), and b43_switch_band().
static struct b43_wldev * b43_wireless_core_stop (struct b43_wldev * dev) [static, read]
Definition at line 4145 of file main.c.
References b43_bus_host_is_sdio(), b43_leds_exit(), b43_mac_suspend(), B43_MMIO_GEN_IRQ_MASK, b43_read32(), b43_sdio_free_irq(), b43_set_status, B43_STAT_INITIALIZED, B43_STAT_STARTED, b43_status, B43_WARN_ON, b43_write32(), b43dbg(), b43_wl::current_dev, b43_wldev::dev, b43_wl::hardirq_lock, b43_bus_dev::irq, b43_wl::mutex, b43_wldev::periodic_work, b43_wl::tx_queue, b43_wl::tx_work, and b43_wldev::wl.
Referenced by b43_chip_reset(), b43_op_stop(), and b43_switch_band().
static void b43_wireless_exit (struct b43_bus_dev * dev, struct b43_wl * wl) [static]
Definition at line 5251 of file main.c.
References b43_wl::hw, and b43_bus_dev::sdev.
static struct b43_wl* b43_wireless_init (struct b43_bus_dev * dev) [static, read]
Definition at line 5259 of file main.c.
References b43_beacon_update_trigger_work(), b43_phy_txpower_adjust_work(), b43_tx_work(), b43err(), b43info(), b43_wl::beacon_update_trigger, b43_bus_dev::bus_sprom, b43_bus_dev::chip_id, b43_bus_dev::core_rev, b43_bus_dev::dev, b43_wl::devlist, b43_wl::hardirq_lock, b43_wl::hw, hw_to_b43_wl(), b43_wl::mac80211_initially_registered_queues, modparam_qos, b43_wl::mutex, b43_wl::tx_queue, b43_wl::tx_work, and b43_wl::txpower_adjust_work.
static void b43_write_beacon_template (struct b43_wldev * dev, u16 ram_offset, u16 shm_size_offset) [static]
Definition at line 1535 of file main.c.
References B43_ANTENNA_DEFAULT, b43_antenna_to_phyctl(), b43_is_cck_rate(), b43_shm_read16(), B43_SHM_SH_BEACPHYCTL, B43_SHM_SH_DTIMPER, B43_SHM_SH_TIMBPOS, B43_SHM_SHARED, b43_shm_write16(), B43_TXH_PHY_ANT, B43_TXH_PHY_ENC, B43_TXH_PHY_ENC_CCK, B43_TXH_PHY_ENC_OFDM, B43_TXH_PHY_SHORTPRMBL, b43_write_template_common(), b43dbg(), b43_wl::current_beacon, b43_wl::hw, and b43_wldev::wl.
Referenced by b43_upload_beacon0(), and b43_upload_beacon1().
static int b43_write_initvals (struct b43_wldev * dev, const struct b43_iv * ivals, size_t count, size_t array_size) [static]
Definition at line 2599 of file main.c.
References B43_IV_32BIT, B43_IV_OFFSET_MASK, b43_print_fw_helptext(), b43_write16(), b43_write32(), b43err(), b43_iv::d16, b43_iv::d32, b43_iv::offset_size, and b43_wldev::wl.
Referenced by b43_upload_initvals().
static void b43_write_mac_bssid_templates (struct b43_wldev * dev) [static]
Definition at line 647 of file main.c.
References B43_MACFILTER_BSSID, b43_macfilter_set(), b43_ram_write(), b43_wl::bssid, b43_wl::mac_addr, and b43_wldev::wl.
Referenced by b43_op_bss_info_changed(), and b43_upload_card_macaddress().
static void b43_write_template_common (struct b43_wldev * dev, const u8 * data, u16 size, u16 ram_offset, u16 shm_size_offset, u8 rate) [static]
Definition at line 1455 of file main.c.
References b43_generate_plcp_hdr(), b43_ram_write(), B43_SHM_SHARED, and b43_shm_write16().
Referenced by b43_write_beacon_template().
void b43dbg (struct b43_wl * wl, const char * fmt, ...)
Definition at line 403 of file main.c.
References b43_modparam_verbose, B43_VERBOSITY_DEBUG, and b43_wl::hw.
Referenced by assert_mac_suspended(), b43_calibrate_lo_setting(), b43_chip_init(), b43_debugfs_add_device(), b43_destroy_dmaring(), b43_dma_handle_txstatus(), b43_dma_init(), b43_dma_tx(), b43_dump_keymemory(), b43_gphy_op_adjust_txpower(), b43_gphy_op_recalc_txpower(), b43_handle_firmware_panic(), b43_lo_g_maintanance_work(), b43_lo_write(), b43_lpphy_op_init(), b43_op_add_interface(), b43_op_remove_interface(), b43_op_set_key(), b43_periodic_every15sec(), b43_phy_init_pctl(), b43_phy_versioning(), b43_pio_init(), b43_pio_tx(), b43_qos_init(), b43_rx(), b43_set_beacon_int(), b43_set_txpower_g(), b43_switch_band(), b43_wireless_core_start(), b43_wireless_core_stop(), b43_write_beacon_template(), dma_rx(), handle_irq_ucode_debug(), lpphy_2062_init(), lpphy_rev0_1_rc_calib(), parse_cookie(), pio_rx_frame(), rx_tkip_phase1_write(), and should_inject_overflow().
void b43err (struct b43_wl * wl, const char * fmt, ...)
Definition at line 361 of file main.c.
References b43_modparam_verbose, b43_ratelimit(), B43_VERBOSITY_ERROR, and b43_wl::hw.
Referenced by adjust_phyreg(), alloc_initial_descbuffers(), alloc_ringmemory(), b43_aphy_init_tssi2dbm_table(), b43_attr_interfmode_store(), b43_chip_reset(), b43_debugfs_add_device(), b43_dma_set_mask(), b43_dma_tx(), b43_dmacontroller_rx_reset(), b43_dmacontroller_tx_reset(), b43_do_interrupt_thread(), b43_generate_dyn_tssi2dbm_tab(), b43_handle_firmware_panic(), b43_lpphy_op_init(), b43_mac_enable(), b43_mac_suspend(), b43_nphy_force_rf_sequence(), b43_nphy_gen_load_samples(), b43_nphy_load_samples(), b43_nphy_op_software_rfkill(), b43_nphy_rf_control_intc_override(), b43_nphy_rf_control_override(), b43_nphy_run_samples(), b43_periodic_every15sec(), b43_phy_ht_force_rf_sequence(), b43_phy_ht_op_software_rfkill(), b43_phy_init(), b43_phy_lcn_op_software_rfkill(), b43_phy_lcn_tables_init(), b43_phy_lcn_tx_pwr_ctl_init(), b43_phy_versioning(), b43_pio_tx(), b43_print_fw_helptext(), b43_put_phy_into_reset(), b43_radio_2059_init(), b43_radio_init2055_post(), b43_request_firmware(), b43_rng_init(), b43_setup_dmaring(), b43_switch_band(), b43_try_request_fw(), b43_upload_microcode(), b43_validate_chipaccess(), b43_wireless_core_attach(), b43_wireless_core_start(), b43_wireless_init(), b43_write_initvals(), check_phyreg(), dma_rx(), lpphy_pr41573_workaround(), and setup_rx_descbuffer().
void b43info (struct b43_wl * wl, const char * fmt, ...)
Definition at line 340 of file main.c.
References b43_modparam_verbose, b43_ratelimit(), B43_VERBOSITY_INFO, and b43_wl::hw.
Referenced by b43_chip_reset(), b43_controller_restart(), b43_dma_set_mask(), b43_op_config(), b43_rfkill_poll(), b43_upload_microcode(), b43_wireless_init(), and handle_irq_ucode_debug().
void b43warn (struct b43_wl * wl, const char * fmt, ...)
Definition at line 382 of file main.c.
References b43_modparam_verbose, b43_ratelimit(), B43_VERBOSITY_WARN, and b43_wl::hw.
Referenced by b43_calibrate_lo_setting(), b43_gphy_dc_lt_init(), b43_gphy_op_recalc_txpower(), b43_key_write(), b43_lo_g_maintanance_work(), b43_map_led(), b43_pio_tx(), b43_print_fw_helptext(), b43_register_led(), b43_upload_microcode(), b43_validate_chipaccess(), and b43_wireless_core_init().
static const char* band_to_string (enum ieee80211_band band) [static]
Definition at line 3675 of file main.c.
References B43_WARN_ON.
Referenced by b43_switch_band().
static void do_key_write (struct b43_wldev * dev, u8 index, u8 algorithm, const u8 * key, size_t key_len, const u8 * mac_addr) [static]
Definition at line 930 of file main.c.
References b43_key::algorithm, b43_new_kidx_api(), B43_NR_GROUP_KEYS, B43_SEC_ALGO_TKIP, B43_SEC_KEYSIZE, B43_WARN_ON, b43_wldev::key, key_write(), keymac_write(), and rx_tkip_phase1_write().
Referenced by b43_key_clear(), and b43_key_write().
static void do_periodic_work (struct b43_wldev * dev) [static]
Definition at line 3204 of file main.c.
References b43_periodic_every15sec(), b43_periodic_every30sec(), b43_periodic_every60sec(), and b43_wldev::periodic_state.
Referenced by b43_periodic_work_handler().
static void drain_txstatus_queue (struct b43_wldev * dev) [static]
Definition at line 1293 of file main.c.
References B43_MMIO_XMITSTAT_0, B43_MMIO_XMITSTAT_1, b43_read32(), b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_wireless_core_start().
static void handle_irq_atim_end (struct b43_wldev * dev) [static]
Definition at line 1430 of file main.c.
References B43_MACCMD_DFQ_VALID, B43_MMIO_MACCMD, b43_read32(), b43_write32(), and b43_wldev::dfq_valid.
Referenced by b43_do_interrupt_thread().
static void handle_irq_beacon (struct b43_wldev * dev) [static]
Definition at line 1641 of file main.c.
References B43_IRQ_BEACON, b43_is_mode(), B43_MACCMD_BEACON0_VALID, B43_MACCMD_BEACON1_VALID, B43_MMIO_GEN_IRQ_REASON, B43_MMIO_MACCMD, b43_read32(), b43_upload_beacon0(), b43_upload_beacon1(), b43_write32(), b43_wl::beacon_templates_virgin, b43_wldev::irq_mask, and b43_wldev::wl.
Referenced by b43_do_beacon_update_trigger_work(), and b43_do_interrupt_thread().
static void handle_irq_noise (struct b43_wldev * dev) [static]
Definition at line 1348 of file main.c.
References b43_generate_noise_sample(), b43_jssi_read(), B43_PHYTYPE_G, b43_shm_read16(), B43_SHM_SHARED, B43_WARN_ON, b43_noise_calculation::calculation_running, b43_phy::g, b43_stats::link_noise, b43_wldev::noisecalc, b43_noise_calculation::nr_samples, b43_phy_g::nrssi_lt, b43_wldev::phy, b43_noise_calculation::samples, b43_wldev::stats, and b43_phy::type.
Referenced by b43_do_interrupt_thread().
static void handle_irq_pmq (struct b43_wldev * dev) [static]
Definition at line 1440 of file main.c.
References B43_MMIO_PS_STATUS, b43_read32(), and b43_write16().
Referenced by b43_do_interrupt_thread().
static void handle_irq_tbtt_indication (struct b43_wldev * dev) [static]
TODO: PS TBTT
Definition at line 1418 of file main.c.
References b43_is_mode(), b43_power_saving_ctl_bits(), b43_wldev::dfq_valid, and b43_wldev::wl.
Referenced by b43_do_interrupt_thread().
static void handle_irq_transmit_status (struct b43_wldev * dev) [static]
Definition at line 1265 of file main.c.
References b43_txstatus::acked, b43_handle_txstatus(), B43_MMIO_XMITSTAT_0, B43_MMIO_XMITSTAT_1, b43_read32(), b43_txstatus::cookie, b43_txstatus::for_ampdu, b43_txstatus::frame_count, b43_txstatus::intermediate, b43_txstatus::phy_stat, b43_txstatus::pm_indicated, b43_txstatus::rts_count, b43_txstatus::seq, and b43_txstatus::supp_reason.
Referenced by b43_do_interrupt_thread().
static void handle_irq_ucode_debug (struct b43_wldev * dev) [static]
Definition at line 1801 of file main.c.
References B43_DEBUG, B43_DEBUGIRQ_ACK, B43_DEBUGIRQ_DUMP_REGS, B43_DEBUGIRQ_DUMP_SHM, B43_DEBUGIRQ_MARKER, B43_DEBUGIRQ_PANIC, B43_DEBUGIRQ_REASON_REG, b43_handle_firmware_panic(), B43_MARKER_ID_REG, B43_MARKER_LINE_REG, b43_shm_read16(), B43_SHM_SCRATCH, B43_SHM_SHARED, b43_shm_write16(), b43dbg(), b43info(), b43_wldev::fw, b43_firmware::opensource, and b43_wldev::wl.
Referenced by b43_do_interrupt_thread().
static void key_write (struct b43_wldev * dev, u8 index, u8 algorithm, const u8 * key) [static]
Definition at line 793 of file main.c.
References b43_kidx_to_fw(), B43_SEC_KEYSIZE, B43_SHM_SH_KEYIDXBLOCK, B43_SHM_SHARED, b43_shm_write16(), and b43_wldev::ktp.
Referenced by do_key_write().
static void keymac_write (struct b43_wldev * dev, u8 index, const u8 * addr) [static]
Definition at line 816 of file main.c.
References b43_new_kidx_api(), B43_NR_GROUP_KEYS, B43_NR_PAIRWISE_KEYS, B43_SHM_RCMTA, b43_shm_write16(), b43_shm_write32(), and B43_WARN_ON.
Referenced by b43_op_update_tkip_key(), and do_key_write().
MODULE_AUTHOR ("Rafał Miłecki")
MODULE_AUTHOR ("Gábor Stefanik")
MODULE_AUTHOR ("Michael Buesch")
MODULE_AUTHOR ("Stefano Brivio")
MODULE_AUTHOR ("Martin Langer")
MODULE_DESCRIPTION ("Broadcom B43 wireless driver")
MODULE_FIRMWARE ("b43/ucode9.fw")
MODULE_FIRMWARE ("b43/ucode5.fw")
MODULE_FIRMWARE ("b43/ucode16_mimo.fw")
MODULE_FIRMWARE ("b43/ucode15.fw")
MODULE_FIRMWARE ("b43/ucode14.fw")
MODULE_FIRMWARE ("b43/ucode13.fw")
MODULE_FIRMWARE ("b43/ucode11.fw")
MODULE_LICENSE ("GPL")
module_param_named (pio , b43_modparam_pio , int , 0644)
module_param_named (verbose , b43_modparam_verbose , int , 0644)
module_param_named (btcoex , modparam_btcoex , int , 0444)
module_param_named (qos , modparam_qos , int , 0444)
module_param_named (hwtkip , modparam_hwtkip , int , 0444)
module_param_named (nohwcrypt , modparam_nohwcrypt , int , 0444)
module_param_named (hwpctl , modparam_hwpctl , int , 0444)
module_param_named (bad_frames_preempt , modparam_bad_frames_preempt , int , 0444)
module_param_string (fwpostfix , modparam_fwpostfix , 16 , 0444)
MODULE_PARM_DESC (pio , "Use PIO accesses by default: 0 = DMA)
MODULE_PARM_DESC (verbose , "Log message verbosity: 0 = error, 1 = warn, 2 = info(default))
MODULE_PARM_DESC (btcoex , "Enable Bluetooth coexistence (default on)")
MODULE_PARM_DESC (qos , "Enable QOS support (default on)")
MODULE_PARM_DESC (hwtkip , "Enable hardware tkip.")
MODULE_PARM_DESC (nohwcrypt , "Disable hardware encryption.")
MODULE_PARM_DESC (hwpctl , "Enable hardware-side power control (default off)")
MODULE_PARM_DESC (fwpostfix , "Postfix for the .fw files to load.")
MODULE_PARM_DESC (bad_frames_preempt , "enable(1) / disable(0) Bad Frames Preemption")
static void rx_tkip_phase1_write (struct b43_wldev * dev, u8 index, u32 iv32, u16 * phase1key) [static]
Definition at line 866 of file main.c.
References B43_DBG_KEYS, b43_debug(), b43_new_kidx_api(), B43_NR_GROUP_KEYS, B43_NR_PAIRWISE_KEYS, B43_SHM_SH_TKIPTSCTTAK, B43_SHM_SHARED, b43_shm_write16(), B43_WARN_ON, b43dbg(), modparam_hwtkip, and b43_wldev::wl.
Referenced by b43_op_update_tkip_key(), and do_key_write().
static void setup_struct_phy_for_init (struct b43_wldev * dev, struct b43_phy * phy) [static]
Definition at line 4432 of file main.c.
References B43_PHY_TX_BADNESS_LIMIT, b43_phy::hardware_power_control, modparam_hwpctl, b43_phy::next_txpwr_check_time, and b43_phy::txerr_cnt.
Referenced by setup_struct_wldev_for_init().
static void setup_struct_wldev_for_init (struct b43_wldev * dev) [static]
Definition at line 4446 of file main.c.
References B43_IRQ_MASKTEMPLATE, B43_IRQ_PHY_TXERR, b43_modparam_verbose, B43_VERBOSITY_DEBUG, b43_wldev::dfq_valid, b43_wldev::dma_reason, b43_wldev::irq_mask, b43_wldev::irq_reason, b43_wldev::mac_suspended, b43_wldev::noisecalc, b43_wldev::phy, b43_wldev::radio_hw_enable, setup_struct_phy_for_init(), and b43_wldev::stats.
Referenced by b43_wireless_core_init().
Variable Documentation
struct ieee80211_rate __b43_ratetable[] [static]
Initial value:
 {
        RATETAB_ENT(B43_CCK_RATE_1MB, 0),
        RATETAB_ENT(B43_CCK_RATE_2MB, IEEE80211_RATE_SHORT_PREAMBLE),
        RATETAB_ENT(B43_CCK_RATE_5MB, IEEE80211_RATE_SHORT_PREAMBLE),
        RATETAB_ENT(B43_CCK_RATE_11MB, IEEE80211_RATE_SHORT_PREAMBLE),
        RATETAB_ENT(B43_OFDM_RATE_6MB, 0),
        RATETAB_ENT(B43_OFDM_RATE_9MB, 0),
        RATETAB_ENT(B43_OFDM_RATE_12MB, 0),
        RATETAB_ENT(B43_OFDM_RATE_18MB, 0),
        RATETAB_ENT(B43_OFDM_RATE_24MB, 0),
        RATETAB_ENT(B43_OFDM_RATE_36MB, 0),
        RATETAB_ENT(B43_OFDM_RATE_48MB, 0),
        RATETAB_ENT(B43_OFDM_RATE_54MB, 0),
}
Definition at line 159 of file main.c.
struct ieee80211_channel b43_2ghz_chantable[] [static]
Initial value:
 {
        CHAN4G(1, 2412, 0),
        CHAN4G(2, 2417, 0),
        CHAN4G(3, 2422, 0),
        CHAN4G(4, 2427, 0),
        CHAN4G(5, 2432, 0),
        CHAN4G(6, 2437, 0),
        CHAN4G(7, 2442, 0),
        CHAN4G(8, 2447, 0),
        CHAN4G(9, 2452, 0),
        CHAN4G(10, 2457, 0),
        CHAN4G(11, 2462, 0),
        CHAN4G(12, 2467, 0),
        CHAN4G(13, 2472, 0),
        CHAN4G(14, 2484, 0),
}
Definition at line 189 of file main.c.
struct ieee80211_channel b43_5ghz_aphy_chantable[] [static]
Initial value:
 {
        CHAN5G(34, 0),          CHAN5G(36, 0),
        CHAN5G(38, 0),          CHAN5G(40, 0),
        CHAN5G(42, 0),          CHAN5G(44, 0),
        CHAN5G(46, 0),          CHAN5G(48, 0),
        CHAN5G(52, 0),          CHAN5G(56, 0),
        CHAN5G(60, 0),          CHAN5G(64, 0),
        CHAN5G(100, 0),         CHAN5G(104, 0),
        CHAN5G(108, 0),         CHAN5G(112, 0),
        CHAN5G(116, 0),         CHAN5G(120, 0),
        CHAN5G(124, 0),         CHAN5G(128, 0),
        CHAN5G(132, 0),         CHAN5G(136, 0),
        CHAN5G(140, 0),         CHAN5G(149, 0),
        CHAN5G(153, 0),         CHAN5G(157, 0),
        CHAN5G(161, 0),         CHAN5G(165, 0),
        CHAN5G(184, 0),         CHAN5G(188, 0),
        CHAN5G(192, 0),         CHAN5G(196, 0),
        CHAN5G(200, 0),         CHAN5G(204, 0),
        CHAN5G(208, 0),         CHAN5G(212, 0),
        CHAN5G(216, 0),
}
Definition at line 273 of file main.c.
struct ieee80211_channel b43_5ghz_nphy_chantable[] [static]
Definition at line 215 of file main.c.
struct ieee80211_supported_band b43_band_2GHz [static]
Initial value:
 {
        .band           = IEEE80211_BAND_2GHZ,
        .channels       = b43_2ghz_chantable,
        .n_channels     = ARRAY_SIZE(b43_2ghz_chantable),
        .bitrates       = b43_g_ratetable,
        .n_bitrates     = b43_g_ratetable_size,
}
Definition at line 312 of file main.c.
Referenced by b43_setup_bands().
struct ieee80211_supported_band b43_band_5GHz_aphy [static]
Initial value:
 {
        .band           = IEEE80211_BAND_5GHZ,
        .channels       = b43_5ghz_aphy_chantable,
        .n_channels     = ARRAY_SIZE(b43_5ghz_aphy_chantable),
        .bitrates       = b43_a_ratetable,
        .n_bitrates     = b43_a_ratetable_size,
}
Definition at line 304 of file main.c.
Referenced by b43_setup_bands().
struct ieee80211_supported_band b43_band_5GHz_nphy [static]
Initial value:
 {
        .band           = IEEE80211_BAND_5GHZ,
        .channels       = b43_5ghz_nphy_chantable,
        .n_channels     = ARRAY_SIZE(b43_5ghz_nphy_chantable),
        .bitrates       = b43_a_ratetable,
        .n_bitrates     = b43_a_ratetable_size,
}
Definition at line 296 of file main.c.
Referenced by b43_setup_bands().
struct ieee80211_ops b43_hw_ops [static]
Initial value:
 {
        .tx                     = b43_op_tx,
        .conf_tx                = b43_op_conf_tx,
        .add_interface          = b43_op_add_interface,
        .remove_interface       = b43_op_remove_interface,
        .config                 = b43_op_config,
        .bss_info_changed       = b43_op_bss_info_changed,
        .configure_filter       = b43_op_configure_filter,
        .set_key                = b43_op_set_key,
        .update_tkip_key        = b43_op_update_tkip_key,
        .get_stats              = b43_op_get_stats,
        .get_tsf                = b43_op_get_tsf,
        .set_tsf                = b43_op_set_tsf,
        .start                  = b43_op_start,
        .stop                   = b43_op_stop,
        .set_tim                = b43_op_beacon_set_tim,
        .sta_notify             = b43_op_sta_notify,
        .sw_scan_start          = b43_op_sw_scan_start_notifier,
        .sw_scan_complete       = b43_op_sw_scan_complete_notifier,
        .get_survey             = b43_op_get_survey,
        .rfkill_poll            = b43_rfkill_poll,
}
Definition at line 4930 of file main.c.
int b43_modparam_pio = 0 [static]
Definition at line 112 of file main.c.
Referenced by b43_one_core_attach().
int b43_modparam_verbose = B43_VERBOSITY_DEFAULT
Definition at line 108 of file main.c.
Referenced by b43_debug(), b43dbg(), b43err(), b43info(), b43warn(), and setup_struct_wldev_for_init().
const u16 b43_qos_shm_offsets[] [static]
Initial value:
 {
        [0] = B43_QOS_VOICE,
        [1] = B43_QOS_VIDEO,
        [2] = B43_QOS_BESTEFFORT,
        [3] = B43_QOS_BACKGROUND,
}
Definition at line 3464 of file main.c.
int modparam_bad_frames_preempt [static]
Definition at line 79 of file main.c.
Referenced by b43_one_core_attach().
int modparam_btcoex = 1 [static]
Definition at line 104 of file main.c.
Referenced by b43_bluetooth_coext_disable(), and b43_bluetooth_coext_enable().
char modparam_fwpostfix[16] [static]
Definition at line 84 of file main.c.
Referenced by b43_do_request_fw().
int modparam_hwpctl [static]
Definition at line 88 of file main.c.
Referenced by setup_struct_phy_for_init().
int modparam_hwtkip [static]
Definition at line 96 of file main.c.
Referenced by b43_op_set_key(), b43_op_update_tkip_key(), and rx_tkip_phase1_write().
int modparam_nohwcrypt [static]
Definition at line 92 of file main.c.
Referenced by b43_op_set_key().
int modparam_qos = 1 [static]
Definition at line 100 of file main.c.
Referenced by b43_upload_microcode(), and b43_wireless_init().