CompatWireless3.2: drivers/net/wireless/b43/pcmcia.c File Reference
drivers/net/wireless/b43/pcmcia.c File Reference
#include "pcmcia.h"
#include <linux/ssb/ssb.h>
#include <linux/slab.h>
#include <linux/module.h>
#include <pcmcia/cistpl.h>
#include <pcmcia/ciscode.h>
#include <pcmcia/ds.h>
#include <pcmcia/cisreg.h>
Defines
#define b43_pcmcia_suspend NULL
#define b43_pcmcia_resume NULL
Functions
MODULE_DEVICE_TABLE (pcmcia, b43_pcmcia_tbl)
static int __devinit b43_pcmcia_probe (struct pcmcia_device *dev)
static void __devexit b43_pcmcia_remove (struct pcmcia_device *dev)
int b43_pcmcia_init (void)
void b43_pcmcia_exit (void)
Variables
static struct pcmcia_device_id b43_pcmcia_tbl []
static struct pcmcia_driver b43_pcmcia_driver
Define Documentation
#define b43_pcmcia_resume NULL
Definition at line 60 of file pcmcia.c.
#define b43_pcmcia_suspend NULL
Definition at line 59 of file pcmcia.c.
Function Documentation
void b43_pcmcia_exit (void)
Definition at line 173 of file pcmcia.c.
References b43_pcmcia_driver.
Referenced by b43_exit(), and b43_init().
int b43_pcmcia_init (void)
Definition at line 168 of file pcmcia.c.
References b43_pcmcia_driver.
Referenced by b43_init().
static int __devinit b43_pcmcia_probe (struct pcmcia_device * dev) [static]
Definition at line 63 of file pcmcia.c.
static void __devexit b43_pcmcia_remove (struct pcmcia_device * dev) [static]
Definition at line 142 of file pcmcia.c.
MODULE_DEVICE_TABLE (pcmcia , b43_pcmcia_tbl)
Variable Documentation
struct pcmcia_driver b43_pcmcia_driver [static]
Initial value:
 {
        .owner          = THIS_MODULE,
        .drv            = {
                .name   = "b43-pcmcia",
        },
        .id_table       = b43_pcmcia_tbl,
        .probe          = b43_pcmcia_probe,
        .remove         = __devexit_p(b43_pcmcia_remove),
        .suspend        = b43_pcmcia_suspend,
        .resume         = b43_pcmcia_resume,
}
Definition at line 152 of file pcmcia.c.
Referenced by b43_pcmcia_exit(), and b43_pcmcia_init().
struct pcmcia_device_id b43_pcmcia_tbl[] [static]
Initial value:
 {
        PCMCIA_DEVICE_MANF_CARD(0x2D0, 0x448),
        PCMCIA_DEVICE_MANF_CARD(0x2D0, 0x476),
        PCMCIA_DEVICE_NULL,
}
Definition at line 36 of file pcmcia.c.