CompatWireless3.2: drivers/net/wireless/b43/phy_lcn.c File Reference
drivers/net/wireless/b43/phy_lcn.c File Reference
#include <linux/slab.h>
#include "b43.h"
#include "phy_lcn.h"
#include "tables_phy_lcn.h"
#include "main.h"
Data Structures
struct lcn_tx_gains
struct lcn_tx_iir_filter
Enumerations
enum lcn_sense_type { B43_SENSE_TEMP, B43_SENSE_VBAT }
Functions
static void b43_phy_switch_macfreq (struct b43_wldev *dev, u8 spurmode)
static void b43_radio_2064_channel_setup (struct b43_wldev *dev)
static void b43_radio_2064_init (struct b43_wldev *dev)
static void b43_phy_lcn_afe_set_unset (struct b43_wldev *dev)
static u16 b43_phy_lcn_get_pa_gain (struct b43_wldev *dev)
static void b43_phy_lcn_set_dac_gain (struct b43_wldev *dev, u16 dac_gain)
static void b43_phy_lcn_set_bbmult (struct b43_wldev *dev, u8 m0)
static void b43_phy_lcn_clear_tx_power_offsets (struct b43_wldev *dev)
static void b43_phy_lcn_rev0_baseband_init (struct b43_wldev *dev)
static void b43_phy_lcn_bu_tweaks (struct b43_wldev *dev)
static void b43_phy_lcn_sense_setup (struct b43_wldev *dev, enum lcn_sense_type sense_type)
static bool b43_phy_lcn_load_tx_iir_cck_filter (struct b43_wldev *dev, u8 filter_type)
static bool b43_phy_lcn_load_tx_iir_ofdm_filter (struct b43_wldev *dev, u8 filter_type)
static void b43_phy_lcn_set_tx_gain_override (struct b43_wldev *dev, bool enable)
static void b43_phy_lcn_set_tx_gain (struct b43_wldev *dev, struct lcn_tx_gains *target_gains)
static void b43_phy_lcn_tx_pwr_ctl_init (struct b43_wldev *dev)
static void b43_phy_lcn_txrx_spur_avoidance_mode (struct b43_wldev *dev, bool enable)
static void b43_phy_lcn_set_channel_tweaks (struct b43_wldev *dev, int channel)
static int b43_phy_lcn_set_channel (struct b43_wldev *dev, struct ieee80211_channel *channel, enum nl80211_channel_type channel_type)
static int b43_phy_lcn_op_allocate (struct b43_wldev *dev)
static void b43_phy_lcn_op_free (struct b43_wldev *dev)
static void b43_phy_lcn_op_prepare_structs (struct b43_wldev *dev)
static int b43_phy_lcn_op_init (struct b43_wldev *dev)
static void b43_phy_lcn_op_software_rfkill (struct b43_wldev *dev, bool blocked)
static void b43_phy_lcn_op_switch_analog (struct b43_wldev *dev, bool on)
static int b43_phy_lcn_op_switch_channel (struct b43_wldev *dev, unsigned int new_channel)
static unsigned int b43_phy_lcn_op_get_default_chan (struct b43_wldev *dev)
static enum b43_txpwr_result b43_phy_lcn_op_recalc_txpower (struct b43_wldev *dev, bool ignore_tssi)
static void b43_phy_lcn_op_adjust_txpower (struct b43_wldev *dev)
static u16 b43_phy_lcn_op_read (struct b43_wldev *dev, u16 reg)
static void b43_phy_lcn_op_write (struct b43_wldev *dev, u16 reg, u16 value)
static void b43_phy_lcn_op_maskset (struct b43_wldev *dev, u16 reg, u16 mask, u16 set)
static u16 b43_phy_lcn_op_radio_read (struct b43_wldev *dev, u16 reg)
static void b43_phy_lcn_op_radio_write (struct b43_wldev *dev, u16 reg, u16 value)
Variables
struct b43_phy_operations b43_phyops_lcn
Enumeration Type Documentation
enum lcn_sense_type
Enumerator:
B43_SENSE_TEMP
B43_SENSE_VBAT
Definition at line 52 of file phy_lcn.c.
Function Documentation
static void b43_phy_lcn_afe_set_unset (struct b43_wldev * dev) [static]
Definition at line 198 of file phy_lcn.c.
References B43_PHY_LCN_AFE_CTL1, B43_PHY_LCN_AFE_CTL2, b43_phy_read(), and b43_phy_write().
Referenced by b43_phy_lcn_op_init(), and b43_phy_lcn_set_channel().
static void b43_phy_lcn_bu_tweaks (struct b43_wldev * dev) [static]
Definition at line 292 of file phy_lcn.c.
References b43_phy_lcn_clear_tx_power_offsets(), b43_phy_maskset(), b43_phy_set(), b43_phy_write(), b43_radio_mask(), b43_radio_maskset(), b43_radio_set(), b43_bus_dev::bus_sprom, b43_wldev::dev, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_lcn_op_init().
static void b43_phy_lcn_clear_tx_power_offsets (struct b43_wldev * dev) [static]
Definition at line 237 of file phy_lcn.c.
References B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, and b43_phy_write().
Referenced by b43_phy_lcn_bu_tweaks().
static u16 b43_phy_lcn_get_pa_gain (struct b43_wldev * dev) [static]
Definition at line 214 of file phy_lcn.c.
References b43_phy_read().
Referenced by b43_phy_lcn_set_tx_gain().
static bool b43_phy_lcn_load_tx_iir_cck_filter (struct b43_wldev * dev, u8 filter_type) [static]
Definition at line 455 of file phy_lcn.c.
References b43_phy_write(), lcn_tx_iir_filter::type, and lcn_tx_iir_filter::values.
Referenced by b43_phy_lcn_set_channel().
static bool b43_phy_lcn_load_tx_iir_ofdm_filter (struct b43_wldev * dev, u8 filter_type) [static]
Definition at line 507 of file phy_lcn.c.
References b43_phy_write(), lcn_tx_iir_filter::type, and lcn_tx_iir_filter::values.
Referenced by b43_phy_lcn_set_channel().
static void b43_phy_lcn_op_adjust_txpower (struct b43_wldev * dev) [static]
Definition at line 837 of file phy_lcn.c.
static int b43_phy_lcn_op_allocate (struct b43_wldev * dev) [static]
Definition at line 701 of file phy_lcn.c.
References b43_phy::lcn, and b43_wldev::phy.
static void b43_phy_lcn_op_free (struct b43_wldev * dev) [static]
Definition at line 713 of file phy_lcn.c.
References b43_phy::lcn, and b43_wldev::phy.
static unsigned int b43_phy_lcn_op_get_default_chan (struct b43_wldev * dev) [static]
Definition at line 824 of file phy_lcn.c.
References b43_current_band(), and b43_wldev::wl.
static int b43_phy_lcn_op_init (struct b43_wldev * dev) [static]
Definition at line 731 of file phy_lcn.c.
References b43_current_band(), b43_phy_lcn_afe_set_unset(), b43_phy_lcn_bu_tweaks(), b43_phy_lcn_rev0_baseband_init(), b43_phy_lcn_tables_init(), b43_phy_lcn_tx_pwr_ctl_init(), b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy_write(), b43_radio_2064_init(), b43_switch_channel(), B43_WARN_ON, b43_bus_dev::bdev, b43_phy::channel, b43_wldev::dev, b43_wldev::phy, b43_phy::radio_ver, and b43_wldev::wl.
static void b43_phy_lcn_op_maskset (struct b43_wldev * dev, u16 reg, u16 mask, u16 set) [static]
Definition at line 857 of file phy_lcn.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), and b43_write16().
static void b43_phy_lcn_op_prepare_structs (struct b43_wldev * dev) [static]
Definition at line 722 of file phy_lcn.c.
References b43_phy::lcn, and b43_wldev::phy.
static u16 b43_phy_lcn_op_radio_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 865 of file phy_lcn.c.
References B43_MMIO_RADIO24_CONTROL, B43_MMIO_RADIO24_DATA, b43_read16(), and b43_write16().
static void b43_phy_lcn_op_radio_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 874 of file phy_lcn.c.
References B43_MMIO_RADIO24_CONTROL, B43_MMIO_RADIO24_DATA, and b43_write16().
static u16 b43_phy_lcn_op_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 845 of file phy_lcn.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), and b43_write16().
static enum b43_txpwr_result b43_phy_lcn_op_recalc_txpower (struct b43_wldev * dev, bool ignore_tssi) [static]
Definition at line 832 of file phy_lcn.c.
References B43_TXPWR_RES_DONE.
static void b43_phy_lcn_op_software_rfkill (struct b43_wldev * dev, bool blocked) [static]
Definition at line 775 of file phy_lcn.c.
References B43_MACCTL_ENABLED, B43_MMIO_MACCTL, B43_PHY_LCN_RF_CTL1, B43_PHY_LCN_RF_CTL2, B43_PHY_LCN_RF_CTL3, B43_PHY_LCN_RF_CTL4, B43_PHY_LCN_RF_CTL5, B43_PHY_LCN_RF_CTL6, B43_PHY_LCN_RF_CTL7, b43_phy_mask(), b43_phy_set(), b43_read32(), b43err(), and b43_wldev::wl.
static void b43_phy_lcn_op_switch_analog (struct b43_wldev * dev, bool on) [static]
Definition at line 798 of file phy_lcn.c.
References B43_PHY_LCN_AFE_CTL1, B43_PHY_LCN_AFE_CTL2, b43_phy_mask(), and b43_phy_set().
static int b43_phy_lcn_op_switch_channel (struct b43_wldev * dev, unsigned int new_channel) [static]
Definition at line 808 of file phy_lcn.c.
References b43_current_band(), b43_phy_lcn_set_channel(), b43_wl::hw, and b43_wldev::wl.
static void b43_phy_lcn_op_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 851 of file phy_lcn.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, and b43_write16().
static void b43_phy_lcn_rev0_baseband_init (struct b43_wldev * dev) [static]
Definition at line 257 of file phy_lcn.c.
References B43_BFL_FEM, b43_phy_maskset(), b43_phy_set(), b43_phy_write(), b43_radio_write(), b43_bus_dev::bus_sprom, and b43_wldev::dev.
Referenced by b43_phy_lcn_op_init().
static void b43_phy_lcn_sense_setup (struct b43_wldev * dev, enum lcn_sense_type sense_type) [static]
Definition at line 343 of file phy_lcn.c.
References b43_dummy_transmission(), B43_LCNTAB16, b43_lcntab_write(), b43_mac_enable(), b43_mac_suspend(), b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_radio_read(), b43_radio_set(), b43_radio_write(), B43_SENSE_TEMP, B43_SENSE_VBAT, b43_phy::lcn, b43_wldev::phy, and b43_phy_lcn::tx_pwr_curr_idx.
Referenced by b43_phy_lcn_tx_pwr_ctl_init().
static void b43_phy_lcn_set_bbmult (struct b43_wldev * dev, u8 m0) [static]
Definition at line 231 of file phy_lcn.c.
References B43_LCNTAB16, and b43_lcntab_write().
Referenced by b43_phy_lcn_tx_pwr_ctl_init().
static int b43_phy_lcn_set_channel (struct b43_wldev * dev, struct ieee80211_channel * channel, enum nl80211_channel_type channel_type) [static]
Definition at line 658 of file phy_lcn.c.
References b43_phy_lcn_afe_set_unset(), b43_phy_lcn_load_tx_iir_cck_filter(), b43_phy_lcn_load_tx_iir_ofdm_filter(), b43_phy_lcn_set_channel_tweaks(), b43_phy_maskset(), b43_phy_set(), b43_phy_write(), and b43_radio_2064_channel_setup().
Referenced by b43_phy_lcn_op_switch_channel().
static void b43_phy_lcn_set_channel_tweaks (struct b43_wldev * dev, int channel) [static]
Definition at line 620 of file phy_lcn.c.
References b43_phy_lcn_txrx_spur_avoidance_mode(), b43_phy_maskset(), b43_phy_set(), b43_phy_write(), b43_bus_dev::bdev, and b43_wldev::dev.
Referenced by b43_phy_lcn_set_channel().
static void b43_phy_lcn_set_dac_gain (struct b43_wldev * dev, u16 dac_gain) [static]
Definition at line 220 of file phy_lcn.c.
References b43_phy_maskset(), and b43_phy_read().
Referenced by b43_phy_lcn_set_tx_gain().
static void b43_phy_lcn_set_tx_gain (struct b43_wldev * dev, struct lcn_tx_gains * target_gains) [static]
Definition at line 544 of file phy_lcn.c.
References b43_phy_lcn_get_pa_gain(), b43_phy_lcn_set_dac_gain(), b43_phy_lcn_set_tx_gain_override(), b43_phy_maskset(), b43_phy_write(), lcn_tx_gains::dac_gain, lcn_tx_gains::gm_gain, lcn_tx_gains::pad_gain, and lcn_tx_gains::pga_gain.
Referenced by b43_phy_lcn_tx_pwr_ctl_init().
static void b43_phy_lcn_set_tx_gain_override (struct b43_wldev * dev, bool enable) [static]
Definition at line 536 of file phy_lcn.c.
References b43_phy_maskset().
Referenced by b43_phy_lcn_set_tx_gain().
static void b43_phy_lcn_tx_pwr_ctl_init (struct b43_wldev * dev) [static]
Definition at line 563 of file phy_lcn.c.
References b43_current_band(), b43_mac_enable(), b43_mac_suspend(), b43_phy_lcn_sense_setup(), b43_phy_lcn_set_bbmult(), b43_phy_lcn_set_tx_gain(), B43_SENSE_TEMP, b43err(), lcn_tx_gains::dac_gain, lcn_tx_gains::gm_gain, b43_phy_lcn::hw_pwr_ctl_capable, b43_phy::lcn, lcn_tx_gains::pad_gain, lcn_tx_gains::pga_gain, b43_wldev::phy, and b43_wldev::wl.
Referenced by b43_phy_lcn_op_init().
static void b43_phy_lcn_txrx_spur_avoidance_mode (struct b43_wldev * dev, bool enable) [static]
Definition at line 595 of file phy_lcn.c.
References b43_phy_switch_macfreq(), and b43_phy_write().
Referenced by b43_phy_lcn_set_channel_tweaks().
static void b43_phy_switch_macfreq (struct b43_wldev * dev, u8 spurmode) [static]
Definition at line 59 of file phy_lcn.c.
References B43_MMIO_TSF_CLK_FRAC_HIGH, B43_MMIO_TSF_CLK_FRAC_LOW, B43_PHYTYPE_LCN, b43_write16(), b43_bus_dev::chip_id, b43_wldev::dev, b43_wldev::phy, and b43_phy::type.
Referenced by b43_phy_lcn_txrx_spur_avoidance_mode().
static void b43_radio_2064_channel_setup (struct b43_wldev * dev) [static]
Definition at line 95 of file phy_lcn.c.
References b43_radio_maskset(), b43_radio_read(), b43_radio_set(), b43_radio_write(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_lcn_set_channel().
static void b43_radio_2064_init (struct b43_wldev * dev) [static]
Definition at line 142 of file phy_lcn.c.
References b43_current_band(), B43_LCNTAB16, b43_lcntab_write(), b43_phy_mask(), b43_phy_maskset(), b43_phy_write(), b43_radio_mask(), b43_radio_read(), b43_radio_set(), b43_radio_write(), b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by b43_phy_lcn_op_init().
Variable Documentation
struct b43_phy_operations b43_phyops_lcn
Initial value:
 {
        .allocate               = b43_phy_lcn_op_allocate,
        .free                   = b43_phy_lcn_op_free,
        .prepare_structs        = b43_phy_lcn_op_prepare_structs,
        .init                   = b43_phy_lcn_op_init,
        .phy_read               = b43_phy_lcn_op_read,
        .phy_write              = b43_phy_lcn_op_write,
        .phy_maskset            = b43_phy_lcn_op_maskset,
        .radio_read             = b43_phy_lcn_op_radio_read,
        .radio_write            = b43_phy_lcn_op_radio_write,
        .software_rfkill        = b43_phy_lcn_op_software_rfkill,
        .switch_analog          = b43_phy_lcn_op_switch_analog,
        .switch_channel         = b43_phy_lcn_op_switch_channel,
        .get_default_chan       = b43_phy_lcn_op_get_default_chan,
        .recalc_txpower         = b43_phy_lcn_op_recalc_txpower,
        .adjust_txpower         = b43_phy_lcn_op_adjust_txpower,
}
Definition at line 885 of file phy_lcn.c.
Referenced by b43_phy_allocate().