CompatWireless3.2: drivers/net/wireless/b43/phy_n.c File Reference
drivers/net/wireless/b43/phy_n.c File Reference
#include <linux/delay.h>
#include <linux/slab.h>
#include <linux/types.h>
#include "b43.h"
#include "phy_n.h"
#include "tables_nphy.h"
#include "tables_nphy.h"
#include "main.h"
Data Structures
struct nphy_txgains
struct nphy_iqcal_params
struct nphy_iq_est
Enumerations
enum b43_nphy_rf_sequence {
B43_RFSEQ_RX2TX, B43_RFSEQ_TX2RX, B43_RFSEQ_RESET2RX, B43_RFSEQ_UPDATE_GAINH,
B43_RFSEQ_UPDATE_GAINL, B43_RFSEQ_UPDATE_GAINU
}
enum b43_nphy_rssi_type {
B43_NPHY_RSSI_X = 0, B43_NPHY_RSSI_Y, B43_NPHY_RSSI_Z, B43_NPHY_RSSI_PWRDET,
B43_NPHY_RSSI_TSSI_I, B43_NPHY_RSSI_TSSI_Q, B43_NPHY_RSSI_TBD
}
Functions
static void b43_nphy_stay_in_carrier_search (struct b43_wldev *dev, bool enable)
static void b43_nphy_set_rf_sequence (struct b43_wldev *dev, u8 cmd, u8 *events, u8 *delays, u8 length)
static void b43_nphy_force_rf_sequence (struct b43_wldev *dev, enum b43_nphy_rf_sequence seq)
static void b43_nphy_rf_control_override (struct b43_wldev *dev, u16 field, u16 value, u8 core, bool off)
static void b43_nphy_rf_control_intc_override (struct b43_wldev *dev, u8 field, u16 value, u8 core)
static const u32 * b43_nphy_get_ipa_gain_table (struct b43_wldev *dev)
static bool b43_nphy_ipa (struct b43_wldev *dev)
void b43_nphy_set_rxantenna (struct b43_wldev *dev, int antenna)
static void b43_nphy_op_adjust_txpower (struct b43_wldev *dev)
static enum b43_txpwr_result b43_nphy_op_recalc_txpower (struct b43_wldev *dev, bool ignore_tssi)
static void b43_chantab_radio_upload (struct b43_wldev *dev, const struct b43_nphy_channeltab_entry_rev2 *e)
static void b43_chantab_radio_2056_upload (struct b43_wldev *dev, const struct b43_nphy_channeltab_entry_rev3 *e)
static void b43_radio_2056_setup (struct b43_wldev *dev, const struct b43_nphy_channeltab_entry_rev3 *e)
static void b43_chantab_phy_upload (struct b43_wldev *dev, const struct b43_phy_n_sfo_cfg *e)
static void b43_nphy_tx_power_ctrl (struct b43_wldev *dev, bool enable)
static void b43_nphy_tx_power_fix (struct b43_wldev *dev)
static void b43_nphy_tx_gain_table_upload (struct b43_wldev *dev)
static void b43_radio_2055_setup (struct b43_wldev *dev, const struct b43_nphy_channeltab_entry_rev2 *e)
static void b43_radio_init2055_pre (struct b43_wldev *dev)
static void b43_radio_init2055_post (struct b43_wldev *dev)
static void b43_radio_init2055 (struct b43_wldev *dev)
static void b43_radio_init2056_pre (struct b43_wldev *dev)
static void b43_radio_init2056_post (struct b43_wldev *dev)
static void b43_radio_init2056 (struct b43_wldev *dev)
static void b43_nphy_tables_init (struct b43_wldev *dev)
static void b43_nphy_pa_override (struct b43_wldev *dev, bool enable)
static void b43_nphy_tx_lp_fbw (struct b43_wldev *dev)
static void b43_nphy_reset_cca (struct b43_wldev *dev)
static void b43_nphy_update_mimo_config (struct b43_wldev *dev, s32 preamble)
static void b43_nphy_update_txrx_chain (struct b43_wldev *dev)
static void b43_nphy_rx_iq_est (struct b43_wldev *dev, struct nphy_iq_est *est, u16 samps, u8 time, bool wait)
static void b43_nphy_rx_iq_coeffs (struct b43_wldev *dev, bool write, struct b43_phy_n_iq_comp *pcomp)
static void b43_nphy_calc_rx_iq_comp (struct b43_wldev *dev, u8 mask)
static void b43_nphy_tx_iq_workaround (struct b43_wldev *dev)
static void b43_nphy_write_clip_detection (struct b43_wldev *dev, const u16 *clip_st)
static void b43_nphy_read_clip_detection (struct b43_wldev *dev, u16 *clip_st)
static void b43_nphy_superswitch_init (struct b43_wldev *dev, bool init)
static u16 b43_nphy_classifier (struct b43_wldev *dev, u16 mask, u16 val)
static void b43_nphy_stop_playback (struct b43_wldev *dev)
static void b43_nphy_spur_workaround (struct b43_wldev *dev)
static void b43_nphy_adjust_lna_gain_table (struct b43_wldev *dev)
static void b43_nphy_gain_ctrl_workarounds (struct b43_wldev *dev)
static void b43_nphy_workarounds_rev3plus (struct b43_wldev *dev)
static void b43_nphy_workarounds_rev1_2 (struct b43_wldev *dev)
static void b43_nphy_workarounds (struct b43_wldev *dev)
static int b43_nphy_load_samples (struct b43_wldev *dev, struct b43_c32 *samples, u16 len)
static u16 b43_nphy_gen_load_samples (struct b43_wldev *dev, u32 freq, u16 max, bool test)
static void b43_nphy_run_samples (struct b43_wldev *dev, u16 samps, u16 loops, u16 wait, bool iqmode, bool dac_test)
static int b43_nphy_tx_tone (struct b43_wldev *dev, u32 freq, u16 max_val, bool iqmode, bool dac_test)
static void b43_nphy_tx_pwr_ctrl_coef_setup (struct b43_wldev *dev)
static void b43_nphy_bphy_init (struct b43_wldev *dev)
static void b43_nphy_scale_offset_rssi (struct b43_wldev *dev, u16 scale, s8 offset, u8 core, u8 rail, enum b43_nphy_rssi_type type)
static void b43_nphy_rev2_rssi_select (struct b43_wldev *dev, u8 code, u8 type)
static void b43_nphy_rev3_rssi_select (struct b43_wldev *dev, u8 code, u8 type)
static void b43_nphy_rssi_select (struct b43_wldev *dev, u8 code, u8 type)
static void b43_nphy_set_rssi_2055_vcm (struct b43_wldev *dev, u8 type, u8 *buf)
static int b43_nphy_poll_rssi (struct b43_wldev *dev, u8 type, s32 *buf, u8 nsamp)
static void b43_nphy_rev2_rssi_cal (struct b43_wldev *dev, u8 type)
static void b43_nphy_rev3_rssi_cal (struct b43_wldev *dev)
static void b43_nphy_rssi_cal (struct b43_wldev *dev)
static void b43_nphy_restore_rssi_cal (struct b43_wldev *dev)
static void b43_nphy_tx_cal_radio_setup (struct b43_wldev *dev)
static void b43_nphy_iq_cal_gain_params (struct b43_wldev *dev, u16 core, struct nphy_txgains target, struct nphy_iqcal_params *params)
static void b43_nphy_update_tx_cal_ladder (struct b43_wldev *dev, u16 core)
static void b43_nphy_ext_pa_set_tx_dig_filters (struct b43_wldev *dev)
static void b43_nphy_int_pa_set_tx_dig_filters (struct b43_wldev *dev)
static struct nphy_txgains b43_nphy_get_tx_gains (struct b43_wldev *dev)
static void b43_nphy_tx_cal_phy_cleanup (struct b43_wldev *dev)
static void b43_nphy_tx_cal_phy_setup (struct b43_wldev *dev)
static void b43_nphy_save_cal (struct b43_wldev *dev)
static void b43_nphy_restore_cal (struct b43_wldev *dev)
static int b43_nphy_cal_tx_iq_lo (struct b43_wldev *dev, struct nphy_txgains target, bool full, bool mphase)
static void b43_nphy_reapply_tx_cal_coeffs (struct b43_wldev *dev)
static int b43_nphy_rev2_cal_rx_iq (struct b43_wldev *dev, struct nphy_txgains target, u8 type, bool debug)
static int b43_nphy_rev3_cal_rx_iq (struct b43_wldev *dev, struct nphy_txgains target, u8 type, bool debug)
static int b43_nphy_cal_rx_iq (struct b43_wldev *dev, struct nphy_txgains target, u8 type, bool debug)
static void b43_nphy_set_rx_core_state (struct b43_wldev *dev, u8 mask)
int b43_phy_initn (struct b43_wldev *dev)
static void b43_nphy_channel_setup (struct b43_wldev *dev, const struct b43_phy_n_sfo_cfg *e, struct ieee80211_channel *new_channel)
static int b43_nphy_set_channel (struct b43_wldev *dev, struct ieee80211_channel *channel, enum nl80211_channel_type channel_type)
static int b43_nphy_op_allocate (struct b43_wldev *dev)
static void b43_nphy_op_prepare_structs (struct b43_wldev *dev)
static void b43_nphy_op_free (struct b43_wldev *dev)
static int b43_nphy_op_init (struct b43_wldev *dev)
static void check_phyreg (struct b43_wldev *dev, u16 offset)
static u16 b43_nphy_op_read (struct b43_wldev *dev, u16 reg)
static void b43_nphy_op_write (struct b43_wldev *dev, u16 reg, u16 value)
static void b43_nphy_op_maskset (struct b43_wldev *dev, u16 reg, u16 mask, u16 set)
static u16 b43_nphy_op_radio_read (struct b43_wldev *dev, u16 reg)
static void b43_nphy_op_radio_write (struct b43_wldev *dev, u16 reg, u16 value)
static void b43_nphy_op_software_rfkill (struct b43_wldev *dev, bool blocked)
static void b43_nphy_op_switch_analog (struct b43_wldev *dev, bool on)
static int b43_nphy_op_switch_channel (struct b43_wldev *dev, unsigned int new_channel)
static unsigned int b43_nphy_op_get_default_chan (struct b43_wldev *dev)
Variables
struct b43_phy_operations b43_phyops_n
Enumeration Type Documentation
enum b43_nphy_rf_sequence
Enumerator:
B43_RFSEQ_RX2TX
B43_RFSEQ_TX2RX
B43_RFSEQ_RESET2RX
B43_RFSEQ_UPDATE_GAINH
B43_RFSEQ_UPDATE_GAINL
B43_RFSEQ_UPDATE_GAINU
Definition at line 62 of file phy_n.c.
enum b43_nphy_rssi_type
Enumerator:
B43_NPHY_RSSI_X
B43_NPHY_RSSI_Y
B43_NPHY_RSSI_Z
B43_NPHY_RSSI_PWRDET
B43_NPHY_RSSI_TSSI_I
B43_NPHY_RSSI_TSSI_Q
B43_NPHY_RSSI_TBD
Definition at line 71 of file phy_n.c.
Function Documentation
static void b43_chantab_phy_upload (struct b43_wldev * dev, const struct b43_phy_n_sfo_cfg * e) [static]
Definition at line 245 of file phy_n.c.
References B43_NPHY_BW1A, B43_NPHY_BW2, B43_NPHY_BW3, B43_NPHY_BW4, B43_NPHY_BW5, B43_NPHY_BW6, b43_phy_write(), b43_phy_n_sfo_cfg::phy_bw1a, b43_phy_n_sfo_cfg::phy_bw2, b43_phy_n_sfo_cfg::phy_bw3, b43_phy_n_sfo_cfg::phy_bw4, b43_phy_n_sfo_cfg::phy_bw5, and b43_phy_n_sfo_cfg::phy_bw6.
Referenced by b43_nphy_channel_setup().
static void b43_chantab_radio_2056_upload (struct b43_wldev * dev, const struct b43_nphy_channeltab_entry_rev3 * e) [static]
Definition at line 152 of file phy_n.c.
References B2056_RX0, B2056_RX1, B2056_RX_LNAA_TUNE, B2056_RX_LNAG_TUNE, B2056_SYN_LOGEN_BUF3, B2056_SYN_LOGEN_BUF4, B2056_SYN_LOGEN_MIXER2, B2056_SYN_LOGEN_VCOBUF1, B2056_SYN_PLL_LOOPFILTER1, B2056_SYN_PLL_LOOPFILTER2, B2056_SYN_PLL_LOOPFILTER3, B2056_SYN_PLL_LOOPFILTER4, B2056_SYN_PLL_LOOPFILTER5, B2056_SYN_PLL_MMD1, B2056_SYN_PLL_MMD2, B2056_SYN_PLL_REFDIV, B2056_SYN_PLL_VCOCAL1, B2056_SYN_PLL_VCOCAL2, B2056_SYN_RESERVED_ADDR27, B2056_SYN_RESERVED_ADDR28, B2056_SYN_RESERVED_ADDR29, B2056_TX0, B2056_TX1, B2056_TX_INTPAA_BOOST_TUNE, B2056_TX_INTPAG_BOOST_TUNE, B2056_TX_MIXA_BOOST_TUNE, B2056_TX_MIXG_BOOST_TUNE, B2056_TX_PADA_BOOST_TUNE, B2056_TX_PADG_BOOST_TUNE, B2056_TX_PGAA_BOOST_TUNE, B2056_TX_PGAG_BOOST_TUNE, b43_radio_write(), b43_nphy_channeltab_entry_rev3::radio_rx0_lnaa_tune, b43_nphy_channeltab_entry_rev3::radio_rx0_lnag_tune, b43_nphy_channeltab_entry_rev3::radio_rx1_lnaa_tune, b43_nphy_channeltab_entry_rev3::radio_rx1_lnag_tune, b43_nphy_channeltab_entry_rev3::radio_syn_logen_buf3, b43_nphy_channeltab_entry_rev3::radio_syn_logen_buf4, b43_nphy_channeltab_entry_rev3::radio_syn_logen_mixer2, b43_nphy_channeltab_entry_rev3::radio_syn_logen_vcobuf1, b43_nphy_channeltab_entry_rev3::radio_syn_pll_loopfilter1, b43_nphy_channeltab_entry_rev3::radio_syn_pll_loopfilter2, b43_nphy_channeltab_entry_rev3::radio_syn_pll_loopfilter3, b43_nphy_channeltab_entry_rev3::radio_syn_pll_loopfilter4, b43_nphy_channeltab_entry_rev3::radio_syn_pll_loopfilter5, b43_nphy_channeltab_entry_rev3::radio_syn_pll_mmd1, b43_nphy_channeltab_entry_rev3::radio_syn_pll_mmd2, b43_nphy_channeltab_entry_rev3::radio_syn_pll_refdiv, b43_nphy_channeltab_entry_rev3::radio_syn_pll_vcocal1, b43_nphy_channeltab_entry_rev3::radio_syn_pll_vcocal2, b43_nphy_channeltab_entry_rev3::radio_syn_reserved_addr27, b43_nphy_channeltab_entry_rev3::radio_syn_reserved_addr28, b43_nphy_channeltab_entry_rev3::radio_syn_reserved_addr29, b43_nphy_channeltab_entry_rev3::radio_tx0_intpaa_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx0_intpag_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx0_mixa_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx0_mixg_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx0_pada_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx0_padg_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx0_pgaa_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx0_pgag_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx1_intpaa_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx1_intpag_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx1_mixa_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx1_mixg_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx1_pada_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx1_padg_boost_tune, b43_nphy_channeltab_entry_rev3::radio_tx1_pgaa_boost_tune, and b43_nphy_channeltab_entry_rev3::radio_tx1_pgag_boost_tune.
Referenced by b43_radio_2056_setup().
static void b43_chantab_radio_upload (struct b43_wldev * dev, const struct b43_nphy_channeltab_entry_rev2 * e) [static]
Definition at line 115 of file phy_n.c.
References B2055_C1_LGBUF_ATUNE, B2055_C1_LGBUF_GTUNE, B2055_C1_RX_RFR1, B2055_C1_TX_MXBGTRIM, B2055_C1_TX_PGAPADTN, B2055_C2_LGBUF_ATUNE, B2055_C2_LGBUF_GTUNE, B2055_C2_RX_RFR1, B2055_C2_TX_MXBGTRIM, B2055_C2_TX_PGAPADTN, B2055_LGBUF_CENBUF, B2055_LGEN_TUNE1, B2055_LGEN_TUNE2, B2055_PLL_LFC1, B2055_PLL_LFC2, B2055_PLL_LFR1, B2055_PLL_REF, B2055_RF_PLLMOD0, B2055_RF_PLLMOD1, B2055_VCO_CAL1, B2055_VCO_CAL2, B2055_VCO_CAPTAIL, B43_MMIO_MACCTL, b43_radio_write(), b43_read32(), b43_nphy_channeltab_entry_rev2::radio_c1_lgbuf_atune, b43_nphy_channeltab_entry_rev2::radio_c1_lgbuf_gtune, b43_nphy_channeltab_entry_rev2::radio_c1_rx_rfr1, b43_nphy_channeltab_entry_rev2::radio_c1_tx_mxbgtrim, b43_nphy_channeltab_entry_rev2::radio_c1_tx_pgapadtn, b43_nphy_channeltab_entry_rev2::radio_c2_lgbuf_atune, b43_nphy_channeltab_entry_rev2::radio_c2_lgbuf_gtune, b43_nphy_channeltab_entry_rev2::radio_c2_rx_rfr1, b43_nphy_channeltab_entry_rev2::radio_c2_tx_mxbgtrim, b43_nphy_channeltab_entry_rev2::radio_c2_tx_pgapadtn, b43_nphy_channeltab_entry_rev2::radio_lgbuf_cenbuf, b43_nphy_channeltab_entry_rev2::radio_lgen_tune1, b43_nphy_channeltab_entry_rev2::radio_lgen_tune2, b43_nphy_channeltab_entry_rev2::radio_pll_lfc1, b43_nphy_channeltab_entry_rev2::radio_pll_lfc2, b43_nphy_channeltab_entry_rev2::radio_pll_lfr1, b43_nphy_channeltab_entry_rev2::radio_pll_ref, b43_nphy_channeltab_entry_rev2::radio_rf_pllmod0, b43_nphy_channeltab_entry_rev2::radio_rf_pllmod1, b43_nphy_channeltab_entry_rev2::radio_vco_cal1, b43_nphy_channeltab_entry_rev2::radio_vco_cal2, and b43_nphy_channeltab_entry_rev2::radio_vco_captail.
Referenced by b43_radio_2055_setup().
static void b43_nphy_adjust_lna_gain_table (struct b43_wldev * dev) [static]
Definition at line 1229 of file phy_n.c.
References b43_current_band(), B43_NPHY_C1_MINGAIN, B43_NPHY_C1_MINGAIN_SHIFT, B43_NPHY_C1_MINMAX_GAIN, B43_NPHY_C2_MINGAIN, B43_NPHY_C2_MINGAIN_SHIFT, B43_NPHY_C2_MINMAX_GAIN, b43_nphy_stay_in_carrier_search(), B43_NTAB16, b43_ntab_write_bulk(), b43_phy_maskset(), b43_phy::channel, b43_phy_n::elna_gain_config, b43_phy_n::gain_boost, b43_phy_n::hang_avoid, b43_phy::n, b43_wldev::phy, and b43_wldev::wl.
Referenced by b43_nphy_channel_setup(), and b43_nphy_gain_ctrl_workarounds().
static void b43_nphy_bphy_init (struct b43_wldev * dev) [static]
Definition at line 2150 of file phy_n.c.
References B43_PHY_N_BMODE, and b43_phy_write().
Referenced by b43_phy_initn().
static int b43_nphy_cal_rx_iq (struct b43_wldev * dev, struct nphy_txgains target, u8 type, bool debug) [static]
Definition at line 3684 of file phy_n.c.
References b43_nphy_rev2_cal_rx_iq(), b43_nphy_rev3_cal_rx_iq(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_initn().
static int b43_nphy_cal_tx_iq_lo (struct b43_wldev * dev, struct nphy_txgains target, bool full, bool mphase) [static]
Definition at line 3236 of file phy_n.c.
References b43_current_band(), b43_nphy_iq_cal_gain_params(), B43_NPHY_IQLOCAL_CMD, B43_NPHY_IQLOCAL_CMDGCTL, B43_NPHY_IQLOCAL_CMDNNUM, b43_nphy_run_samples(), b43_nphy_stay_in_carrier_search(), b43_nphy_stop_playback(), b43_nphy_tx_cal_phy_cleanup(), b43_nphy_tx_cal_phy_setup(), b43_nphy_tx_cal_radio_setup(), b43_nphy_tx_iq_workaround(), b43_nphy_tx_tone(), b43_nphy_update_tx_cal_ladder(), B43_NTAB16, b43_ntab_read(), b43_ntab_read_bulk(), B43_NTAB_TX_IQLO_CAL_CMDS_FULLCAL, B43_NTAB_TX_IQLO_CAL_CMDS_FULLCAL_REV3, B43_NTAB_TX_IQLO_CAL_CMDS_RECAL, B43_NTAB_TX_IQLO_CAL_CMDS_RECAL_REV3, B43_NTAB_TX_IQLO_CAL_STARTCOEFS, B43_NTAB_TX_IQLO_CAL_STARTCOEFS_REV3, b43_ntab_write(), b43_ntab_write_bulk(), b43_phy_read(), b43_phy_write(), nphy_iqcal_params::cal_gain, b43_chanspec::center_freq, b43_phy::channel_freq, b43_phy::channel_type, b43_chanspec::channel_type, b43_phy_n::hang_avoid, b43_phy_n::ipa2g_on, b43_phy::is_40mhz, b43_phy_n::mphase_cal_phase_id, b43_phy_n::mphase_txcal_bestcoeffs, b43_phy_n::mphase_txcal_cmdidx, b43_phy_n::mphase_txcal_numcmds, b43_phy::n, nphy_iqcal_params::ncorr, b43_wldev::phy, b43_phy::rev, tbl_tx_iqlo_cal_cmds_fullcal, tbl_tx_iqlo_cal_cmds_fullcal_nphyrev3, tbl_tx_iqlo_cal_cmds_recal, tbl_tx_iqlo_cal_cmds_recal_nphyrev3, tbl_tx_iqlo_cal_iqimb_ladder_20, tbl_tx_iqlo_cal_iqimb_ladder_40, tbl_tx_iqlo_cal_loft_ladder_20, tbl_tx_iqlo_cal_loft_ladder_40, tbl_tx_iqlo_cal_startcoefs, tbl_tx_iqlo_cal_startcoefs_nphyrev3, b43_phy_n::txiqlocal_bestc, b43_phy_n::txiqlocal_chanspec, b43_phy_n::txiqlocal_coeffsvalid, and b43_wldev::wl.
Referenced by b43_phy_initn().
static void b43_nphy_calc_rx_iq_comp (struct b43_wldev * dev, u8 mask) [static]
Definition at line 926 of file phy_n.c.
References b43_nphy_rx_iq_coeffs(), b43_nphy_rx_iq_est(), nphy_iq_est::i0_pwr, nphy_iq_est::i1_pwr, nphy_iq_est::iq0_prod, nphy_iq_est::iq1_prod, b43_wldev::phy, nphy_iq_est::q0_pwr, nphy_iq_est::q1_pwr, and b43_phy::rev.
Referenced by b43_nphy_rev2_cal_rx_iq().
static void b43_nphy_channel_setup (struct b43_wldev * dev, const struct b43_phy_n_sfo_cfg * e, struct ieee80211_channel * new_channel) [static]
Definition at line 3932 of file phy_n.c.
References b43_chantab_phy_upload(), B43_MMIO_PSM_PHY_HDR, b43_nphy_adjust_lna_gain_table(), B43_NPHY_BANDCTL, B43_NPHY_BANDCTL_5GHZ, b43_nphy_classifier(), B43_NPHY_NDATAT_DUP40, b43_nphy_spur_workaround(), b43_nphy_tx_lp_fbw(), b43_nphy_tx_power_fix(), B43_PHY_B_BBCFG, B43_PHY_B_TEST, b43_phy_mask(), b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_read32(), b43_write32(), b43_phy::n, b43_wldev::phy, b43_phy::rev, and b43_phy_n::txpwrctrl.
Referenced by b43_nphy_set_channel().
static u16 b43_nphy_classifier (struct b43_wldev * dev, u16 mask, u16 val) [static]
Definition at line 1099 of file phy_n.c.
References b43_mac_enable(), b43_mac_suspend(), B43_NPHY_CLASSCTL, B43_NPHY_CLASSCTL_CCKEN, B43_NPHY_CLASSCTL_OFDMEN, B43_NPHY_CLASSCTL_WAITEDEN, b43_phy_maskset(), b43_phy_read(), b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_nphy_channel_setup(), b43_nphy_rev2_rssi_cal(), b43_nphy_stay_in_carrier_search(), b43_nphy_workarounds(), and b43_phy_initn().
static void b43_nphy_ext_pa_set_tx_dig_filters (struct b43_wldev * dev) [static]
Definition at line 2906 of file phy_n.c.
References B43_PHY_N, b43_phy_write(), and tbl_tx_filter_coef_rev4.
Referenced by b43_phy_initn().
static void b43_nphy_force_rf_sequence (struct b43_wldev * dev, enum b43_nphy_rf_sequence seq) [static]
Definition at line 1946 of file phy_n.c.
References B43_NPHY_RFSEQMODE, B43_NPHY_RFSEQMODE_CAOVER, B43_NPHY_RFSEQMODE_TROVER, B43_NPHY_RFSEQST, B43_NPHY_RFSEQTR, B43_NPHY_RFSEQTR_RST2RX, B43_NPHY_RFSEQTR_RX2TX, B43_NPHY_RFSEQTR_TX2RX, B43_NPHY_RFSEQTR_UPGH, B43_NPHY_RFSEQTR_UPGL, B43_NPHY_RFSEQTR_UPGU, b43_phy_read(), b43_phy_set(), b43_phy_write(), B43_RFSEQ_RESET2RX, B43_RFSEQ_RX2TX, B43_RFSEQ_TX2RX, B43_RFSEQ_UPDATE_GAINH, B43_RFSEQ_UPDATE_GAINL, B43_RFSEQ_UPDATE_GAINU, B43_WARN_ON, b43err(), and b43_wldev::wl.
Referenced by b43_nphy_reset_cca(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_rf_control_intc_override(), b43_nphy_set_rx_core_state(), and b43_phy_initn().
static void b43_nphy_gain_ctrl_workarounds (struct b43_wldev * dev) [static]
Definition at line 1285 of file phy_n.c.
References B2056_RX0, B2056_RX1, B2056_RX_BIASPOLE_LNAA1_IDAC, B2056_RX_BIASPOLE_LNAG1_IDAC, B2056_RX_LNAA2_IDAC, B2056_RX_LNAG2_IDAC, B2056_RX_RSSI_GAIN, B2056_RX_RSSI_POLE, B43_BFL_EXTLNA, b43_current_band(), b43_nphy_adjust_lna_gain_table(), B43_NPHY_BANDCTL, B43_NPHY_BANDCTL_5GHZ, B43_NPHY_C1_CCK_CGAINI, B43_NPHY_C1_CCK_CGAINI_GAINBKOFF, B43_NPHY_C1_CGAINI, B43_NPHY_C1_CGAINI_CL2DETECT, B43_NPHY_C1_CGAINI_GAINBKOFF, B43_NPHY_C1_CLIP1_MEDGAIN, B43_NPHY_C1_CLIP2_GAIN, B43_NPHY_C1_CLIPWBTHRES, B43_NPHY_C1_CLIPWBTHRES_CLIP2, B43_NPHY_C1_INITGAIN, B43_NPHY_C1_INITGAIN_HPVGA2, B43_NPHY_C1_INITGAIN_HPVGA2_SHIFT, B43_NPHY_C1_NBCLIPTHRES, B43_NPHY_C2_CCK_CGAINI, B43_NPHY_C2_CCK_CGAINI_GAINBKOFF, B43_NPHY_C2_CGAINI, B43_NPHY_C2_CGAINI_CL2DETECT, B43_NPHY_C2_CGAINI_GAINBKOFF, B43_NPHY_C2_CLIP1_HIGAIN, B43_NPHY_C2_CLIPWBTHRES, B43_NPHY_C2_CLIPWBTHRES_CLIP2, B43_NPHY_C2_INITGAIN, B43_NPHY_C2_INITGAIN_HPVGA2, B43_NPHY_C2_INITGAIN_HPVGA2_SHIFT, B43_NPHY_C2_NBCLIPTHRES, B43_NPHY_CCK_SHIFTB_REF, B43_NPHY_CLIP1_NBDWELL_LEN, B43_NPHY_CLIP2_NBDWELL_LEN, b43_nphy_get_gain_ctl_workaround_ent(), B43_NPHY_OVER_DGAIN1, B43_NPHY_OVER_DGAIN_CCKDGECV, B43_NPHY_OVER_DGAIN_CCKDGECV_SHIFT, B43_NPHY_RXCTL, b43_nphy_set_rf_sequence(), B43_NPHY_TABLE_ADDR, B43_NPHY_TABLE_DATALO, B43_NPHY_W1CLIP1_DWELL_LEN, B43_NPHY_W1CLIP2_DWELL_LEN, B43_NTAB16, B43_NTAB8, b43_ntab_write_bulk(), b43_phy_maskset(), B43_PHY_N, b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_radio_write(), b43_bus_dev::bus_sprom, nphy_gain_ctl_workaround_entry::cliphi_gain, nphy_gain_ctl_workaround_entry::cliplo_gain, nphy_gain_ctl_workaround_entry::clipmd_gain, nphy_gain_ctl_workaround_entry::crsmin, nphy_gain_ctl_workaround_entry::crsminl, nphy_gain_ctl_workaround_entry::crsminu, b43_wldev::dev, b43_phy_n::elna_gain_config, nphy_gain_ctl_workaround_entry::gain_bits, b43_phy_n::gain_boost, nphy_gain_ctl_workaround_entry::gain_db, nphy_gain_ctl_workaround_entry::init_gain, b43_phy::is_40mhz, nphy_gain_ctl_workaround_entry::lna1_gain, nphy_gain_ctl_workaround_entry::lna2_gain, b43_phy::n, nphy_gain_ctl_workaround_entry::nbclip, b43_wldev::phy, b43_phy::rev, nphy_gain_ctl_workaround_entry::rfseq_init, b43_wldev::wl, and nphy_gain_ctl_workaround_entry::wlclip.
Referenced by b43_nphy_workarounds_rev1_2(), and b43_nphy_workarounds_rev3plus().
static u16 b43_nphy_gen_load_samples (struct b43_wldev * dev, u32 freq, u16 max, bool test) [static]
Definition at line 1737 of file phy_n.c.
References b43_cordic(), B43_NPHY_BBCFG, B43_NPHY_BBCFG_RSTRX, b43_nphy_load_samples(), b43_phy_read(), b43err(), CORDIC_CONVERT, b43_c32::i, b43_phy::is_40mhz, b43_wldev::phy, b43_c32::q, and b43_wldev::wl.
Referenced by b43_nphy_tx_tone().
static const u32 * b43_nphy_get_ipa_gain_table (struct b43_wldev * dev) [static]
Definition at line 2733 of file phy_n.c.
References b43_current_band(), b43_bus_dev::chip_id, b43_wldev::dev, b43_wldev::phy, b43_phy::rev, txpwrctrl_tx_gain_ipa, txpwrctrl_tx_gain_ipa_5g, txpwrctrl_tx_gain_ipa_rev5, txpwrctrl_tx_gain_ipa_rev6, and b43_wldev::wl.
Referenced by b43_nphy_get_tx_gains(), and b43_nphy_tx_gain_table_upload().
static struct nphy_txgains b43_nphy_get_tx_gains (struct b43_wldev * dev) [static, read]
Definition at line 2943 of file phy_n.c.
References b43_current_band(), B43_NPHY_C1_TXPCTL_STAT, B43_NPHY_C2_TXPCTL_STAT, b43_nphy_get_ipa_gain_table(), b43_nphy_ipa(), b43_nphy_stay_in_carrier_search(), B43_NPHY_TXPCTL_STAT_BIDX, B43_NPHY_TXPCTL_STAT_BIDX_SHIFT, B43_NTAB16, b43_ntab_read_bulk(), b43_ntab_tx_gain_rev0_1_2, b43_ntab_tx_gain_rev3_5ghz, b43_ntab_tx_gain_rev3plus_2ghz, b43_ntab_tx_gain_rev4_5ghz, b43_ntab_tx_gain_rev5plus_5ghz, b43_phy_read(), b43_phy_n::hang_avoid, nphy_txgains::ipa, b43_phy::n, nphy_txgains::pad, nphy_txgains::pga, b43_wldev::phy, b43_phy::rev, nphy_txgains::txgm, b43_phy_n::txpwrctrl, and b43_wldev::wl.
Referenced by b43_phy_initn().
static void b43_nphy_int_pa_set_tx_dig_filters (struct b43_wldev * dev) [static]
Definition at line 2915 of file phy_n.c.
References b43_current_band(), B43_PHY_N, b43_phy_write(), b43_phy::channel, b43_phy::is_40mhz, b43_wldev::phy, tbl_tx_filter_coef_rev4, and b43_wldev::wl.
Referenced by b43_phy_initn().
static bool b43_nphy_ipa (struct b43_wldev * dev) [inline, static]
Definition at line 94 of file phy_n.c.
References b43_current_band(), b43_phy_n::ipa2g_on, b43_phy_n::ipa5g_on, b43_phy::n, b43_wldev::phy, and b43_wldev::wl.
Referenced by b43_nphy_get_tx_gains(), b43_nphy_rev3_rssi_select(), b43_nphy_tx_gain_table_upload(), b43_nphy_tx_lp_fbw(), b43_nphy_tx_power_ctrl(), b43_nphy_tx_power_fix(), b43_nphy_workarounds_rev3plus(), and b43_phy_initn().
static void b43_nphy_iq_cal_gain_params (struct b43_wldev * dev, u16 core, struct nphy_txgains target, struct nphy_iqcal_params * params) [static]
Definition at line 2845 of file phy_n.c.
References b43_current_band(), nphy_iqcal_params::cal_gain, nphy_txgains::ipa, nphy_iqcal_params::ipa, nphy_iqcal_params::ncorr, nphy_txgains::pad, nphy_iqcal_params::pad, nphy_txgains::pga, nphy_iqcal_params::pga, b43_wldev::phy, b43_phy::rev, tbl_iqcal_gainparams, nphy_txgains::txgm, nphy_iqcal_params::txgm, and b43_wldev::wl.
Referenced by b43_nphy_cal_tx_iq_lo(), and b43_nphy_rev2_cal_rx_iq().
static int b43_nphy_load_samples (struct b43_wldev * dev, struct b43_c32 * samples, u16 len) [static]
Definition at line 1710 of file phy_n.c.
References b43_nphy_stay_in_carrier_search(), B43_NTAB32, b43_ntab_write_bulk(), b43err(), b43_phy_n::hang_avoid, b43_c32::i, b43_phy::n, b43_wldev::phy, b43_c32::q, and b43_wldev::wl.
Referenced by b43_nphy_gen_load_samples().
static void b43_nphy_op_adjust_txpower (struct b43_wldev * dev) [static]
Definition at line 105 of file phy_n.c.
static int b43_nphy_op_allocate (struct b43_wldev * dev) [static]
Definition at line 4042 of file phy_n.c.
References b43_phy::n, and b43_wldev::phy.
static void b43_nphy_op_free (struct b43_wldev * dev) [static]
Definition at line 4072 of file phy_n.c.
References b43_phy::n, and b43_wldev::phy.
static unsigned int b43_nphy_op_get_default_chan (struct b43_wldev * dev) [static]
Definition at line 4224 of file phy_n.c.
References b43_current_band(), and b43_wldev::wl.
static int b43_nphy_op_init (struct b43_wldev * dev) [static]
Definition at line 4081 of file phy_n.c.
References b43_phy_initn().
static void b43_nphy_op_maskset (struct b43_wldev * dev, u16 reg, u16 mask, u16 set) [static]
Definition at line 4118 of file phy_n.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), b43_write16(), and check_phyreg().
static void b43_nphy_op_prepare_structs (struct b43_wldev * dev) [static]
Definition at line 4054 of file phy_n.c.
References b43_phy_n::gain_boost, b43_phy_n::hang_avoid, b43_phy::n, b43_phy_n::perical, b43_wldev::phy, b43_phy_n::phyrxchain, b43_phy::rev, b43_phy_n::tx_pwr_idx, and b43_phy_n::txrx_chain.
static u16 b43_nphy_op_radio_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 4127 of file phy_n.c.
References B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_LOW, b43_read16(), B43_WARN_ON, and b43_write16().
static void b43_nphy_op_radio_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 4138 of file phy_n.c.
References B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_LOW, B43_WARN_ON, and b43_write16().
static u16 b43_nphy_op_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 4104 of file phy_n.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), b43_write16(), and check_phyreg().
static enum b43_txpwr_result b43_nphy_op_recalc_txpower (struct b43_wldev * dev, bool ignore_tssi) [static]
Definition at line 109 of file phy_n.c.
References B43_TXPWR_RES_DONE.
static void b43_nphy_op_software_rfkill (struct b43_wldev * dev, bool blocked) [static]
Definition at line 4148 of file phy_n.c.
References B43_MACCTL_ENABLED, B43_MMIO_MACCTL, B43_NPHY_RFCTL_CMD, B43_NPHY_RFCTL_CMD_CHIP0PU, b43_phy_mask(), b43_radio_init2055(), b43_radio_init2056(), b43_radio_mask(), b43_radio_write(), b43_read32(), b43_switch_channel(), b43err(), b43_phy::channel, b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
static void b43_nphy_op_switch_analog (struct b43_wldev * dev, bool on) [static]
Definition at line 4185 of file phy_n.c.
References B43_NPHY_AFECTL_C1, B43_NPHY_AFECTL_C2, B43_NPHY_AFECTL_OVER, B43_NPHY_AFECTL_OVER1, b43_phy_write(), b43_wldev::phy, and b43_phy::rev.
static int b43_nphy_op_switch_channel (struct b43_wldev * dev, unsigned int new_channel) [static]
Definition at line 4207 of file phy_n.c.
References b43_current_band(), b43_nphy_set_channel(), b43_wl::hw, and b43_wldev::wl.
static void b43_nphy_op_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 4111 of file phy_n.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_write16(), and check_phyreg().
static void b43_nphy_pa_override (struct b43_wldev * dev, bool enable) [static]
Definition at line 677 of file phy_n.c.
References b43_current_band(), B43_NPHY_RFCTL_INTC1, B43_NPHY_RFCTL_INTC2, b43_phy_read(), b43_phy_write(), b43_phy::n, b43_wldev::phy, b43_phy::rev, b43_phy_n::rfctrl_intc1_save, b43_phy_n::rfctrl_intc2_save, and b43_wldev::wl.
Referenced by b43_phy_initn().
static int b43_nphy_poll_rssi (struct b43_wldev * dev, u8 type, s32 * buf, u8 nsamp) [static]
Definition at line 2418 of file phy_n.c.
References B43_NPHY_AFECTL_C1, B43_NPHY_AFECTL_C2, B43_NPHY_AFECTL_OVER, B43_NPHY_AFECTL_OVER1, B43_NPHY_GPIO_HIOUT, B43_NPHY_GPIO_LOOUT, B43_NPHY_GPIO_SEL, B43_NPHY_RFCTL_CMD, B43_NPHY_RFCTL_LUT_TRSW_UP1, B43_NPHY_RFCTL_LUT_TRSW_UP2, B43_NPHY_RFCTL_OVER, B43_NPHY_RFCTL_RSSIO1, B43_NPHY_RFCTL_RSSIO2, B43_NPHY_RSSI1, B43_NPHY_RSSI2, b43_nphy_rssi_select(), B43_NPHY_TXF_40CO_B1S0, B43_NPHY_TXF_40CO_B32S1, b43_phy_read(), b43_phy_write(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_nphy_rev2_rssi_cal().
static void b43_nphy_read_clip_detection (struct b43_wldev * dev, u16 * clip_st) [static]
Definition at line 1044 of file phy_n.c.
References B43_NPHY_C1_CLIP1THRES, B43_NPHY_C2_CLIP1THRES, and b43_phy_read().
Referenced by b43_nphy_rev2_rssi_cal(), b43_nphy_stay_in_carrier_search(), and b43_phy_initn().
static void b43_nphy_reapply_tx_cal_coeffs (struct b43_wldev * dev) [static]
Definition at line 3462 of file phy_n.c.
References B43_NTAB16, b43_ntab_read_bulk(), b43_ntab_write_bulk(), b43_chanspec::center_freq, b43_phy::channel_freq, b43_phy::channel_type, b43_chanspec::channel_type, b43_phy::n, b43_wldev::phy, b43_phy_n::txiqlocal_bestc, b43_phy_n::txiqlocal_chanspec, and b43_phy_n::txiqlocal_coeffsvalid.
Referenced by b43_nphy_rev2_cal_rx_iq().
static void b43_nphy_reset_cca (struct b43_wldev * dev) [static]
Definition at line 729 of file phy_n.c.
References B43_NPHY_BBCFG, B43_NPHY_BBCFG_RSTCCA, b43_nphy_force_rf_sequence(), b43_phy_force_clock(), b43_phy_read(), b43_phy_write(), and B43_RFSEQ_RESET2RX.
Referenced by b43_nphy_rev2_rssi_cal(), b43_nphy_stay_in_carrier_search(), and b43_nphy_tx_cal_phy_cleanup().
static void b43_nphy_restore_cal (struct b43_wldev * dev) [static]
Definition at line 3168 of file phy_n.c.
References b43_current_band(), b43_nphy_rx_iq_coeffs(), b43_nphy_tx_iq_workaround(), B43_NTAB16, b43_ntab_write_bulk(), b43_radio_write(), b43_phy_n::cal_cache, b43_chanspec::center_freq, b43_phy_n::iqcal_chanspec_2G, b43_phy_n::iqcal_chanspec_5G, b43_phy::n, b43_wldev::phy, b43_phy::rev, b43_phy_n_cal_cache::rxcal_coeffs_2G, b43_phy_n_cal_cache::rxcal_coeffs_5G, b43_phy_n_cal_cache::txcal_coeffs_2G, b43_phy_n_cal_cache::txcal_coeffs_5G, b43_phy_n_cal_cache::txcal_radio_regs_2G, b43_phy_n_cal_cache::txcal_radio_regs_5G, and b43_wldev::wl.
Referenced by b43_phy_initn().
static void b43_nphy_restore_rssi_cal (struct b43_wldev * dev) [static]
Definition at line 2693 of file phy_n.c.
References b43_current_band(), B43_NPHY_RSSIMC_0I_RSSI_X, B43_NPHY_RSSIMC_0I_RSSI_Y, B43_NPHY_RSSIMC_0I_RSSI_Z, B43_NPHY_RSSIMC_0Q_RSSI_X, B43_NPHY_RSSIMC_0Q_RSSI_Y, B43_NPHY_RSSIMC_0Q_RSSI_Z, B43_NPHY_RSSIMC_1I_RSSI_X, B43_NPHY_RSSIMC_1I_RSSI_Y, B43_NPHY_RSSIMC_1I_RSSI_Z, B43_NPHY_RSSIMC_1Q_RSSI_X, B43_NPHY_RSSIMC_1Q_RSSI_Y, B43_NPHY_RSSIMC_1Q_RSSI_Z, b43_phy_write(), b43_radio_maskset(), b43_chanspec::center_freq, b43_phy::n, b43_wldev::phy, b43_phy_n::rssical_cache, b43_phy_n::rssical_chanspec_2G, b43_phy_n::rssical_chanspec_5G, b43_phy_n_rssical_cache::rssical_phy_regs_2G, b43_phy_n_rssical_cache::rssical_phy_regs_5G, b43_phy_n_rssical_cache::rssical_radio_regs_2G, b43_phy_n_rssical_cache::rssical_radio_regs_5G, and b43_wldev::wl.
Referenced by b43_phy_initn().
static int b43_nphy_rev2_cal_rx_iq (struct b43_wldev * dev, struct nphy_txgains target, u8 type, bool debug) [static]
Definition at line 3497 of file phy_n.c.
References B2055_C1_GENSPARE2, B2055_C2_GENSPARE2, b43_current_band(), B43_NPHY_AFECTL_C1, B43_NPHY_AFECTL_C2, B43_NPHY_AFECTL_OVER, b43_nphy_calc_rx_iq_comp(), b43_nphy_force_rf_sequence(), b43_nphy_iq_cal_gain_params(), b43_nphy_reapply_tx_cal_coeffs(), b43_nphy_rf_control_override(), B43_NPHY_RFCTL_INTC1, B43_NPHY_RFCTL_INTC2, B43_NPHY_RFSEQCA, B43_NPHY_RFSEQCA_RXDIS, B43_NPHY_RFSEQCA_RXDIS_SHIFT, B43_NPHY_RFSEQCA_TXEN, b43_nphy_run_samples(), b43_nphy_rx_iq_est(), b43_nphy_stay_in_carrier_search(), b43_nphy_stop_playback(), b43_nphy_tx_tone(), B43_NTAB16, b43_ntab_read_bulk(), b43_ntab_write_bulk(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_radio_mask(), b43_radio_maskset(), B43_RFSEQ_RESET2RX, nphy_iqcal_params::cal_gain, nphy_iq_est::i0_pwr, nphy_iq_est::i1_pwr, b43_phy::n, b43_wldev::phy, nphy_iq_est::q0_pwr, nphy_iq_est::q1_pwr, b43_phy::rev, b43_phy_n::rxcalparams, and b43_wldev::wl.
Referenced by b43_nphy_cal_rx_iq().
static void b43_nphy_rev2_rssi_cal (struct b43_wldev * dev, u8 type) [static]
Definition at line 2505 of file phy_n.c.
References B2055_C1_PD_RSSIMISC, B2055_C1_PD_RXTX, B2055_C1_SP_RSSI, B2055_C2_PD_RSSIMISC, B2055_C2_PD_RXTX, B2055_C2_SP_RSSI, b43_current_band(), b43_nphy_classifier(), b43_nphy_poll_rssi(), b43_nphy_read_clip_detection(), b43_nphy_reset_cca(), B43_NPHY_RFCTL_INTC1, B43_NPHY_RFCTL_INTC2, b43_nphy_rssi_select(), b43_nphy_scale_offset_rssi(), b43_nphy_set_rssi_2055_vcm(), b43_nphy_write_clip_detection(), b43_phy_read(), b43_phy_write(), b43_radio_mask(), b43_radio_maskset(), b43_radio_read16, b43_radio_write16, and B43_WARN_ON.
Referenced by b43_nphy_rssi_cal().
static void b43_nphy_rev2_rssi_select (struct b43_wldev * dev, u8 code, u8 type) [static]
Definition at line 2236 of file phy_n.c.
References B43_NPHY_AFECTL_C1, B43_NPHY_AFECTL_C2, B43_NPHY_AFECTL_OVER, B43_NPHY_RFCTL_CMD, B43_NPHY_RFCTL_CMD_CORESEL, B43_NPHY_RFCTL_CMD_CORESEL_SHIFT, B43_NPHY_RFCTL_CMD_RXEN, B43_NPHY_RFCTL_CMD_START, B43_NPHY_RFCTL_OVER, B43_NPHY_RFCTL_RSSIO1, B43_NPHY_RFCTL_RSSIO2, b43_phy_mask(), b43_phy_maskset(), and b43_phy_set().
Referenced by b43_nphy_rssi_select().
static int b43_nphy_rev3_cal_rx_iq (struct b43_wldev * dev, struct nphy_txgains target, u8 type, bool debug) [static]
Definition at line 3677 of file phy_n.c.
Referenced by b43_nphy_cal_rx_iq().
static void b43_nphy_rev3_rssi_cal (struct b43_wldev * dev) [static]
Definition at line 2669 of file phy_n.c.
Referenced by b43_nphy_rssi_cal().
static void b43_nphy_rev3_rssi_select (struct b43_wldev * dev, u8 code, u8 type) [static]
Definition at line 2297 of file phy_n.c.
References B2055_PADDRV, b43_current_band(), B43_NPHY_AFECTL_C1, B43_NPHY_AFECTL_C2, B43_NPHY_AFECTL_OVER, B43_NPHY_AFECTL_OVER1, b43_nphy_ipa(), B43_NPHY_RFCTL_LUT_TRSW_UP1, B43_NPHY_RFCTL_LUT_TRSW_UP2, B43_NPHY_TXF_40CO_B1S0, B43_NPHY_TXF_40CO_B32S1, b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_radio_write16, and b43_wldev::wl.
Referenced by b43_nphy_rssi_select().
static void b43_nphy_rf_control_intc_override (struct b43_wldev * dev, u8 field, u16 value, u8 core) [static]
Definition at line 2052 of file phy_n.c.
References b43_current_band(), b43_nphy_force_rf_sequence(), B43_NPHY_RFCTL_CMD, B43_NPHY_RFCTL_CMD_RXTX, B43_NPHY_RFCTL_CMD_START, B43_NPHY_RFCTL_INTC1, B43_NPHY_RFCTL_INTC2, B43_NPHY_RFCTL_OVER, B43_NPHY_TXF_40CO_B1S1, b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), B43_RFSEQ_RESET2RX, B43_WARN_ON, b43err(), b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by b43_nphy_tx_cal_phy_setup().
static void b43_nphy_rf_control_override (struct b43_wldev * dev, u16 field, u16 value, u8 core, bool off) [static]
Definition at line 1976 of file phy_n.c.
References nphy_rf_control_override_rev2::addr0, nphy_rf_control_override_rev2::addr1, B43_NPHY_RFCTL_CMD, B43_NPHY_RFCTL_CMD_START, B43_NPHY_RFCTL_OVER, b43_phy_mask(), b43_phy_maskset(), B43_PHY_N, b43_phy_set(), B43_WARN_ON, b43err(), nphy_rf_control_override_rev2::bmask, nphy_rf_control_override_rev3::en_addr0, nphy_rf_control_override_rev3::en_addr1, b43_wldev::phy, b43_phy::rev, nphy_rf_control_override_rev2::shift, tbl_rf_control_override_rev2, tbl_rf_control_override_rev3, nphy_rf_control_override_rev3::val_addr0, nphy_rf_control_override_rev3::val_addr1, nphy_rf_control_override_rev3::val_mask, nphy_rf_control_override_rev3::val_shift, and b43_wldev::wl.
Referenced by b43_nphy_rev2_cal_rx_iq().
static void b43_nphy_rssi_cal (struct b43_wldev * dev) [static]
Definition at line 2678 of file phy_n.c.
References b43_nphy_rev2_rssi_cal(), b43_nphy_rev3_rssi_cal(), B43_NPHY_RSSI_X, B43_NPHY_RSSI_Y, B43_NPHY_RSSI_Z, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_initn().
static void b43_nphy_rssi_select (struct b43_wldev * dev, u8 code, u8 type) [static]
Definition at line 2381 of file phy_n.c.
References b43_nphy_rev2_rssi_select(), b43_nphy_rev3_rssi_select(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_nphy_poll_rssi(), and b43_nphy_rev2_rssi_cal().
static void b43_nphy_run_samples (struct b43_wldev * dev, u16 samps, u16 loops, u16 wait, bool iqmode, bool dac_test) [static]
Definition at line 1781 of file phy_n.c.
References B43_NPHY_IQLOCAL_CMDGCTL, B43_NPHY_RFSEQMODE, B43_NPHY_RFSEQMODE_CAOVER, B43_NPHY_RFSEQST, B43_NPHY_SAMP_CMD, B43_NPHY_SAMP_DEPCNT, B43_NPHY_SAMP_LOOPCNT, B43_NPHY_SAMP_WAITCNT, b43_nphy_stay_in_carrier_search(), B43_NTAB16, b43_ntab_read(), b43_ntab_write(), b43_phy_mask(), b43_phy_read(), b43_phy_set(), b43_phy_write(), b43err(), b43_phy_n::bb_mult_save, b43_phy_n::hang_avoid, b43_phy::is_40mhz, b43_phy::n, b43_wldev::phy, and b43_wldev::wl.
Referenced by b43_nphy_cal_tx_iq_lo(), b43_nphy_rev2_cal_rx_iq(), and b43_nphy_tx_tone().
static void b43_nphy_rx_iq_coeffs (struct b43_wldev * dev, bool write, struct b43_phy_n_iq_comp * pcomp) [static]
Definition at line 824 of file phy_n.c.
References b43_phy_n_iq_comp::a0, b43_phy_n_iq_comp::a1, b43_phy_n_iq_comp::b0, b43_phy_n_iq_comp::b1, B43_NPHY_C1_RXIQ_COMPA0, B43_NPHY_C1_RXIQ_COMPB0, B43_NPHY_C2_RXIQ_COMPA1, B43_NPHY_C2_RXIQ_COMPB1, b43_phy_read(), and b43_phy_write().
Referenced by b43_nphy_calc_rx_iq_comp(), b43_nphy_restore_cal(), and b43_nphy_save_cal().
static void b43_nphy_rx_iq_est (struct b43_wldev * dev, struct nphy_iq_est * est, u16 samps, u8 time, bool wait) [static]
Definition at line 785 of file phy_n.c.
References B43_NPHY_IQEST_CMD, B43_NPHY_IQEST_CMD_MODE, B43_NPHY_IQEST_CMD_START, B43_NPHY_IQEST_IPACC_HI0, B43_NPHY_IQEST_IPACC_HI1, B43_NPHY_IQEST_IPACC_LO0, B43_NPHY_IQEST_IPACC_LO1, B43_NPHY_IQEST_IQACC_HI0, B43_NPHY_IQEST_IQACC_HI1, B43_NPHY_IQEST_IQACC_LO0, B43_NPHY_IQEST_IQACC_LO1, B43_NPHY_IQEST_QPACC_HI0, B43_NPHY_IQEST_QPACC_HI1, B43_NPHY_IQEST_QPACC_LO0, B43_NPHY_IQEST_QPACC_LO1, B43_NPHY_IQEST_SAMCNT, B43_NPHY_IQEST_WT, B43_NPHY_IQEST_WT_VAL, b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), nphy_iq_est::i0_pwr, nphy_iq_est::i1_pwr, nphy_iq_est::iq0_prod, nphy_iq_est::iq1_prod, nphy_iq_est::q0_pwr, and nphy_iq_est::q1_pwr.
Referenced by b43_nphy_calc_rx_iq_comp(), and b43_nphy_rev2_cal_rx_iq().
static void b43_nphy_save_cal (struct b43_wldev * dev) [static]
Definition at line 3118 of file phy_n.c.
References b43_current_band(), b43_nphy_rx_iq_coeffs(), b43_nphy_stay_in_carrier_search(), B43_NTAB16, b43_ntab_read_bulk(), b43_radio_read(), b43_phy_n::cal_cache, b43_chanspec::center_freq, b43_phy::channel_freq, b43_phy::channel_type, b43_chanspec::channel_type, b43_phy_n::hang_avoid, b43_phy_n::iqcal_chanspec_2G, b43_phy_n::iqcal_chanspec_5G, b43_phy::n, b43_wldev::phy, b43_phy::rev, b43_phy_n_cal_cache::rxcal_coeffs_2G, b43_phy_n_cal_cache::rxcal_coeffs_5G, b43_phy_n_cal_cache::txcal_coeffs_2G, b43_phy_n_cal_cache::txcal_coeffs_5G, b43_phy_n_cal_cache::txcal_radio_regs_2G, b43_phy_n_cal_cache::txcal_radio_regs_5G, and b43_wldev::wl.
Referenced by b43_phy_initn().
static void b43_nphy_scale_offset_rssi (struct b43_wldev * dev, u16 scale, s8 offset, u8 core, u8 rail, enum b43_nphy_rssi_type type) [static]
Definition at line 2169 of file phy_n.c.
References B43_NPHY_RSSI_PWRDET, B43_NPHY_RSSI_TBD, B43_NPHY_RSSI_TSSI_I, B43_NPHY_RSSI_TSSI_Q, B43_NPHY_RSSI_X, B43_NPHY_RSSI_Y, B43_NPHY_RSSI_Z, B43_NPHY_RSSIMC_0I_PWRDET, B43_NPHY_RSSIMC_0I_RSSI_X, B43_NPHY_RSSIMC_0I_RSSI_Y, B43_NPHY_RSSIMC_0I_RSSI_Z, B43_NPHY_RSSIMC_0I_TBD, B43_NPHY_RSSIMC_0I_TSSI, B43_NPHY_RSSIMC_0Q_PWRDET, B43_NPHY_RSSIMC_0Q_RSSI_X, B43_NPHY_RSSIMC_0Q_RSSI_Y, B43_NPHY_RSSIMC_0Q_RSSI_Z, B43_NPHY_RSSIMC_0Q_TBD, B43_NPHY_RSSIMC_0Q_TSSI, B43_NPHY_RSSIMC_1I_PWRDET, B43_NPHY_RSSIMC_1I_RSSI_X, B43_NPHY_RSSIMC_1I_RSSI_Y, B43_NPHY_RSSIMC_1I_RSSI_Z, B43_NPHY_RSSIMC_1I_TBD, B43_NPHY_RSSIMC_1I_TSSI, B43_NPHY_RSSIMC_1Q_PWRDET, B43_NPHY_RSSIMC_1Q_RSSI_X, B43_NPHY_RSSIMC_1Q_RSSI_Y, B43_NPHY_RSSIMC_1Q_RSSI_Z, B43_NPHY_RSSIMC_1Q_TBD, B43_NPHY_RSSIMC_1Q_TSSI, and b43_phy_write().
Referenced by b43_nphy_rev2_rssi_cal().
static int b43_nphy_set_channel (struct b43_wldev * dev, struct ieee80211_channel * channel, enum nl80211_channel_type channel_type) [static]
Definition at line 3988 of file phy_n.c.
References B2055_MASTER1, b43_channel_type_is_40mhz(), b43_nphy_channel_setup(), b43_nphy_get_chantabent_rev2(), b43_nphy_get_chantabent_rev3(), B43_NPHY_RXCTL, B43_NPHY_RXCTL_BSELU20, b43_phy_mask(), b43_phy_set(), b43_radio_2055_setup(), b43_radio_2056_setup(), b43_radio_maskset(), b43_phy::channel, b43_phy::channel_freq, b43_phy::channel_type, b43_wldev::phy, b43_nphy_channeltab_entry_rev2::phy_regs, b43_nphy_channeltab_entry_rev3::phy_regs, and b43_phy::rev.
Referenced by b43_nphy_op_switch_channel().
static void b43_nphy_set_rf_sequence (struct b43_wldev * dev, u8 cmd, u8 * events, u8 * delays, u8 length) [static]
Definition at line 1921 of file phy_n.c.
References b43_nphy_stay_in_carrier_search(), B43_NTAB8, b43_ntab_write(), b43_ntab_write_bulk(), b43_phy_n::hang_avoid, b43_phy::n, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_nphy_gain_ctrl_workarounds(), b43_nphy_workarounds_rev1_2(), and b43_nphy_workarounds_rev3plus().
static void b43_nphy_set_rssi_2055_vcm (struct b43_wldev * dev, u8 type, u8 * buf) [static]
Definition at line 2390 of file phy_n.c.
References B2055_C1_B0NB_RSSIVCM, B2055_C1_RX_BB_RSSICTL5, B2055_C2_B0NB_RSSIVCM, B2055_C2_RX_BB_RSSICTL5, and b43_radio_maskset().
Referenced by b43_nphy_rev2_rssi_cal().
static void b43_nphy_set_rx_core_state (struct b43_wldev * dev, u8 mask) [static]
Definition at line 3694 of file phy_n.c.
References b43_mac_enable(), b43_mac_suspend(), b43_nphy_force_rf_sequence(), B43_NPHY_HPANT_SWTHRES, B43_NPHY_RFSEQCA, B43_NPHY_RFSEQCA_RXEN, B43_NPHY_RFSEQCA_RXEN_SHIFT, b43_nphy_stay_in_carrier_search(), b43_phy_maskset(), b43_phy_write(), B43_RFSEQ_RESET2RX, b43_phy_n::hang_avoid, b43_phy::n, b43_wldev::phy, b43_phy_n::phyrxchain, and b43_phy::rev.
Referenced by b43_phy_initn().
void b43_nphy_set_rxantenna (struct b43_wldev * dev, int antenna)
Definition at line 101 of file phy_n.c.
static void b43_nphy_spur_workaround (struct b43_wldev * dev) [static]
Definition at line 1170 of file phy_n.c.
References b43_phy_n::aband_spurwar_en, b43_nphy_stay_in_carrier_search(), B43_WARN_ON, b43_phy::channel, b43_phy_n::gband_spurwar_en, b43_phy_n::hang_avoid, b43_phy::is_40mhz, b43_phy::n, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_nphy_channel_setup(), and b43_phy_initn().
static void b43_nphy_stay_in_carrier_search (struct b43_wldev * dev, bool enable) [static]
Definition at line 1120 of file phy_n.c.
References b43_nphy_classifier(), b43_nphy_read_clip_detection(), b43_nphy_reset_cca(), b43_nphy_write_clip_detection(), b43_phy_n::classifier_state, b43_phy_n::clip_state, b43_phy_n::deaf_count, b43_phy::n, and b43_wldev::phy.
Referenced by b43_nphy_adjust_lna_gain_table(), b43_nphy_cal_tx_iq_lo(), b43_nphy_get_tx_gains(), b43_nphy_load_samples(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_run_samples(), b43_nphy_save_cal(), b43_nphy_set_rf_sequence(), b43_nphy_set_rx_core_state(), b43_nphy_spur_workaround(), b43_nphy_stop_playback(), b43_nphy_tx_power_ctrl(), b43_nphy_tx_power_fix(), b43_nphy_tx_pwr_ctrl_coef_setup(), and b43_nphy_workarounds().
static void b43_nphy_stop_playback (struct b43_wldev * dev) [static]
Definition at line 1143 of file phy_n.c.
References B43_NPHY_IQLOCAL_CMDGCTL, B43_NPHY_SAMP_CMD, B43_NPHY_SAMP_CMD_STOP, B43_NPHY_SAMP_STAT, b43_nphy_stay_in_carrier_search(), B43_NTAB16, b43_ntab_write(), b43_phy_mask(), b43_phy_read(), b43_phy_set(), b43_phy_n::bb_mult_save, b43_phy_n::hang_avoid, b43_phy::n, and b43_wldev::phy.
Referenced by b43_nphy_cal_tx_iq_lo(), and b43_nphy_rev2_cal_rx_iq().
static void b43_nphy_superswitch_init (struct b43_wldev * dev, bool init) [static]
Definition at line 1051 of file phy_n.c.
References B43_BUS_SSB, B43_MACCTL_GPOUTSMSK, B43_MMIO_GPIO_CONTROL, B43_MMIO_GPIO_MASK, B43_MMIO_MACCTL, B43_NPHY_GPIO_HIOEN, B43_NPHY_GPIO_LOOEN, B43_NPHY_RFCTL_LUT_TRSW_LO1, B43_NPHY_RFCTL_LUT_TRSW_LO2, B43_NPHY_RFCTL_LUT_TRSW_UP1, B43_NPHY_RFCTL_LUT_TRSW_UP2, B43_NTAB16, b43_ntab_write(), b43_phy_write(), b43_read16(), b43_read32(), b43_write16(), b43_write32(), b43_bus_dev::bdev, b43_bus_dev::bus_type, b43_wldev::dev, b43_wldev::phy, b43_phy::rev, and b43_bus_dev::sdev.
Referenced by b43_phy_initn().
static void b43_nphy_tables_init (struct b43_wldev * dev) [static]
Definition at line 668 of file phy_n.c.
References b43_nphy_rev0_1_2_tables_init(), b43_nphy_rev3plus_tables_init(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_initn().
static void b43_nphy_tx_cal_phy_cleanup (struct b43_wldev * dev) [static]
Definition at line 3022 of file phy_n.c.
References B43_NPHY_AFECTL_C1, B43_NPHY_AFECTL_C2, B43_NPHY_AFECTL_OVER, B43_NPHY_AFECTL_OVER1, B43_NPHY_BBCFG, B43_NPHY_PAPD_EN0, B43_NPHY_PAPD_EN1, b43_nphy_reset_cca(), B43_NPHY_RFCTL_INTC1, B43_NPHY_RFCTL_INTC2, B43_NTAB16, b43_ntab_write(), b43_phy_maskset(), b43_phy_write(), b43_phy::n, b43_wldev::phy, b43_phy::rev, and b43_phy_n::tx_rx_cal_phy_saveregs.
Referenced by b43_nphy_cal_tx_iq_lo().
static void b43_nphy_tx_cal_phy_setup (struct b43_wldev * dev) [static]
Definition at line 3051 of file phy_n.c.
References b43_current_band(), B43_NPHY_AFECTL_C1, B43_NPHY_AFECTL_C2, B43_NPHY_AFECTL_OVER, B43_NPHY_AFECTL_OVER1, B43_NPHY_BBCFG, B43_NPHY_BBCFG_RSTRX, B43_NPHY_PAPD_EN0, B43_NPHY_PAPD_EN1, b43_nphy_rf_control_intc_override(), B43_NPHY_RFCTL_INTC1, B43_NPHY_RFCTL_INTC2, B43_NTAB16, b43_ntab_read(), b43_ntab_write(), b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_write(), b43_phy::n, b43_wldev::phy, b43_phy::rev, b43_phy_n::tx_rx_cal_phy_saveregs, and b43_wldev::wl.
Referenced by b43_nphy_cal_tx_iq_lo().
static void b43_nphy_tx_cal_radio_setup (struct b43_wldev * dev) [static]
Definition at line 2751 of file phy_n.c.
References B2055_C1_PWRDET_RXTX, B2055_C1_TX_BB_MXGM, B2055_C1_TX_RF_IQCAL1, B2055_C1_TX_RF_IQCAL2, B2055_C2_PWRDET_RXTX, B2055_C2_TX_BB_MXGM, B2055_C2_TX_RF_IQCAL1, B2055_C2_TX_RF_IQCAL2, B2055_CAL_LPOCTL, B2055_CAL_RCALRTS, B2055_CAL_RCCALRTS, B2055_CAL_RVARCTL, B2055_CAL_TS, B2055_PADDRV, B2055_PLL_LFC1, B2055_XOCTL1, B2055_XOCTL2, B2055_XOMISC, B2055_XOREGUL, b43_current_band(), B43_NPHY_BANDCTL, B43_NPHY_BANDCTL_5GHZ, b43_phy_read(), b43_radio_mask(), b43_radio_read16, b43_radio_set(), b43_radio_write16, b43_phy_n::ipa2g_on, b43_phy_n::ipa5g_on, b43_phy::n, b43_wldev::phy, b43_phy::rev, b43_phy_n::tx_rx_cal_radio_saveregs, and b43_wldev::wl.
Referenced by b43_nphy_cal_tx_iq_lo().
static void b43_nphy_tx_gain_table_upload (struct b43_wldev * dev) [static]
Definition at line 474 of file phy_n.c.
References b43_current_band(), b43_nphy_get_ipa_gain_table(), b43_nphy_ipa(), B43_NTAB32, b43_ntab_tx_gain_rev0_1_2, b43_ntab_tx_gain_rev3_5ghz, b43_ntab_tx_gain_rev3plus_2ghz, b43_ntab_tx_gain_rev4_5ghz, b43_ntab_tx_gain_rev5plus_5ghz, b43_ntab_write(), b43_ntab_write_bulk(), b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by b43_phy_initn().
static void b43_nphy_tx_iq_workaround (struct b43_wldev * dev) [static]
Definition at line 1024 of file phy_n.c.
References B43_NTAB16, b43_ntab_read_bulk(), B43_SHM_SH_NPHY_TXIQW0, B43_SHM_SH_NPHY_TXIQW1, B43_SHM_SH_NPHY_TXIQW2, B43_SHM_SH_NPHY_TXIQW3, B43_SHM_SHARED, and b43_shm_write16().
Referenced by b43_nphy_cal_tx_iq_lo(), and b43_nphy_restore_cal().
static void b43_nphy_tx_lp_fbw (struct b43_wldev * dev) [static]
Definition at line 711 of file phy_n.c.
References b43_nphy_ipa(), B43_NPHY_TXF_40CO_B1S2, B43_NPHY_TXF_40CO_B32S2, b43_phy_write(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_nphy_channel_setup(), and b43_phy_initn().
static void b43_nphy_tx_power_ctrl (struct b43_wldev * dev, bool enable) [static]
Definition at line 257 of file phy_n.c.
References b43_phy_n::adj_pwr_tbl, b43_current_band(), b43_hf_read(), B43_HF_TSSIRPSMW, b43_hf_write(), B43_NPHY_AFECTL_OVER, B43_NPHY_AFECTL_OVER1, B43_NPHY_BPHY_CTL3, B43_NPHY_BPHY_CTL3_SCALE, B43_NPHY_C1_TXPCTL_STAT, B43_NPHY_C2_TXPCTL_STAT, b43_nphy_ipa(), B43_NPHY_PAPD_EN0, B43_NPHY_PAPD_EN1, b43_nphy_stay_in_carrier_search(), B43_NPHY_TABLE_ADDR, B43_NPHY_TABLE_DATALO, B43_NPHY_TXPCTL_CMD, B43_NPHY_TXPCTL_CMD_COEFF, B43_NPHY_TXPCTL_CMD_HWPCTLEN, B43_NPHY_TXPCTL_CMD_INIT, B43_NPHY_TXPCTL_CMD_PCTLEN, B43_NPHY_TXPCTL_INIT, B43_NPHY_TXPCTL_INIT_PIDXI1, B43_NTAB16, b43_ntab_write_bulk(), b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_phy_n::hang_avoid, b43_phy::is_40mhz, b43_phy::n, b43_wldev::phy, b43_phy::rev, b43_phy_n::tx_pwr_idx, b43_phy_n::txpwrctrl, and b43_wldev::wl.
Referenced by b43_phy_initn().
static void b43_nphy_tx_power_fix (struct b43_wldev * dev) [static]
Definition at line 376 of file phy_n.c.
References b43_current_band(), B43_NPHY_AFECTL_DACGAIN1, B43_NPHY_AFECTL_DACGAIN2, B43_NPHY_AFECTL_OVER, B43_NPHY_AFECTL_OVER1, B43_NPHY_BPHY_CTL2, B43_NPHY_BPHY_CTL2_LUT, b43_nphy_ipa(), B43_NPHY_PAPD_EN0, B43_NPHY_PAPD_EN1, b43_nphy_stay_in_carrier_search(), B43_NTAB16, B43_NTAB32, b43_ntab_read(), b43_ntab_tx_gain_rev0_1_2, b43_ntab_tx_gain_rev3plus_2ghz, b43_ntab_write(), b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy_write(), b43_bus_dev::bus_sprom, b43_phy::channel_freq, b43_wldev::dev, b43_phy_n::hang_avoid, b43_phy::n, b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by b43_nphy_channel_setup(), and b43_phy_initn().
static void b43_nphy_tx_pwr_ctrl_coef_setup (struct b43_wldev * dev) [static]
Definition at line 1855 of file phy_n.c.
References b43_nphy_stay_in_carrier_search(), B43_NPHY_TABLE_ADDR, B43_NPHY_TABLE_DATAHI, B43_NPHY_TABLE_DATALO, B43_NTAB16, b43_ntab_read_bulk(), b43_phy_write(), B43_SHM_SH_NPHY_TXPWR_INDX0, B43_SHM_SH_NPHY_TXPWR_INDX1, B43_SHM_SHARED, b43_shm_write16(), b43_phy_n::hang_avoid, loscale, b43_phy::n, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_initn().
static int b43_nphy_tx_tone (struct b43_wldev * dev, u32 freq, u16 max_val, bool iqmode, bool dac_test) [static]
Definition at line 1844 of file phy_n.c.
References b43_nphy_gen_load_samples(), and b43_nphy_run_samples().
Referenced by b43_nphy_cal_tx_iq_lo(), and b43_nphy_rev2_cal_rx_iq().
static void b43_nphy_update_mimo_config (struct b43_wldev * dev, s32 preamble) [static]
Definition at line 743 of file phy_n.c.
References B43_NPHY_MIMOCFG, B43_NPHY_MIMOCFG_AUTO, B43_NPHY_MIMOCFG_GFMIX, b43_phy_read(), and b43_phy_write().
Referenced by b43_phy_initn().
static void b43_nphy_update_tx_cal_ladder (struct b43_wldev * dev, u16 core) [static]
Definition at line 2883 of file phy_n.c.
References B43_NTAB16, b43_ntab_write(), nphy_txiqcal_ladder::g_env, ladder_iq, ladder_lo, b43_phy::n, nphy_txiqcal_ladder::percent, b43_wldev::phy, and b43_phy_n::txcal_bbmult.
Referenced by b43_nphy_cal_tx_iq_lo().
static void b43_nphy_update_txrx_chain (struct b43_wldev * dev) [static]
Definition at line 757 of file phy_n.c.
References B43_NPHY_RFSEQCA, B43_NPHY_RFSEQCA_RXEN, B43_NPHY_RFSEQCA_TXEN, B43_NPHY_RFSEQMODE, B43_NPHY_RFSEQMODE_CAOVER, b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy::n, b43_wldev::phy, and b43_phy_n::txrx_chain.
Referenced by b43_phy_initn().
static void b43_nphy_workarounds (struct b43_wldev * dev) [static]
Definition at line 1684 of file phy_n.c.
References b43_current_band(), b43_nphy_classifier(), B43_NPHY_IQFLIP, B43_NPHY_IQFLIP_ADC1, B43_NPHY_IQFLIP_ADC2, b43_nphy_stay_in_carrier_search(), b43_nphy_workarounds_rev1_2(), b43_nphy_workarounds_rev3plus(), b43_phy_set(), b43_phy_n::hang_avoid, b43_phy::n, b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by b43_phy_initn().
static void b43_nphy_workarounds_rev1_2 (struct b43_wldev * dev) [static]
Definition at line 1601 of file phy_n.c.
References B2055_C1_TX_RF_SPARE, B2055_C2_TX_RF_SPARE, B43_BFL2_SKWRKFEM_BRD, b43_current_band(), B43_HF_MLADVW, b43_hf_read(), b43_hf_write(), B43_NPHY_CRSCHECK2, B43_NPHY_CRSCHECK3, B43_NPHY_FINERX2_CGC, B43_NPHY_FINERX2_CGC_DECGC, b43_nphy_gain_ctrl_workarounds(), B43_NPHY_PHASETR_A0, B43_NPHY_PHASETR_A1, B43_NPHY_PHASETR_A2, B43_NPHY_PHASETR_B0, B43_NPHY_PHASETR_B1, B43_NPHY_PHASETR_B2, B43_NPHY_PIL_DW1, B43_NPHY_PIL_DW_64QAM, B43_NPHY_RFCTL_LUT_TRSW_LO1, B43_NPHY_RFCTL_LUT_TRSW_LO2, B43_NPHY_RFCTL_LUT_TRSW_UP1, B43_NPHY_RFCTL_LUT_TRSW_UP2, B43_NPHY_RXCTL, B43_NPHY_SCRAM_SIGCTL, B43_NPHY_SCRAM_SIGCTL_SCM, b43_nphy_set_rf_sequence(), B43_NPHY_TXF_20CO_S2B1, B43_NPHY_TXF_20CO_S2B2, B43_NPHY_TXF_20CO_S2B3, B43_NTAB16, b43_ntab_write(), b43_phy_mask(), b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_radio_mask(), b43_radio_set(), b43_phy_n::band5g_pwrgain, b43_bus_dev::board_type, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::n, b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by b43_nphy_workarounds().
static void b43_nphy_workarounds_rev3plus (struct b43_wldev * dev) [static]
Definition at line 1490 of file phy_n.c.
References B2056_RX0, B2056_RX1, B2056_RX_MIXA_BIAS_AUX, B2056_RX_MIXA_BIAS_MAIN, B2056_RX_MIXA_LOB_BIAS, B2056_RX_MIXA_MAST_BIAS, B2056_RX_MIXG_CMFB_IDAC, B2056_TX0, B2056_TX1, B2056_TX_GMBB_IDAC, B43_BFL2_APLL_WAR, B43_BFL2_GPLL_WAR, b43_current_band(), B43_NPHY_C2_CLIP1_MEDGAIN, B43_NPHY_ENDROP_TLEN, b43_nphy_gain_ctrl_workarounds(), b43_nphy_ipa(), B43_NPHY_PHASETR_A0, B43_NPHY_PHASETR_A1, B43_NPHY_PHASETR_A2, B43_NPHY_PHASETR_B0, B43_NPHY_PHASETR_B1, B43_NPHY_PHASETR_B2, b43_nphy_set_rf_sequence(), B43_NTAB32, b43_ntab_read(), b43_ntab_write(), b43_phy_maskset(), b43_phy_write(), b43_radio_write(), b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy_n::hw_phyrxchain, b43_phy_n::hw_phytxchain, b43_phy::n, b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by b43_nphy_workarounds().
static void b43_nphy_write_clip_detection (struct b43_wldev * dev, const u16 * clip_st) [static]
Definition at line 1036 of file phy_n.c.
References B43_NPHY_C1_CLIP1THRES, B43_NPHY_C2_CLIP1THRES, and b43_phy_write().
Referenced by b43_nphy_rev2_rssi_cal(), and b43_nphy_stay_in_carrier_search().
int b43_phy_initn (struct b43_wldev * dev)
Definition at line 3737 of file phy_n.c.
References b43_phy_n::antsel_type, B43_BFL2_SKWRKFEM_BRD, B43_BFL_EXTLNA, B43_BUS_SSB, b43_current_band(), b43_mac_phy_clock_set(), B43_NPHY_AFECTL_OVER, B43_NPHY_AFECTL_OVER1, B43_NPHY_AFESEQ_TX2RX_PUD_20M, B43_NPHY_AFESEQ_TX2RX_PUD_40M, B43_NPHY_BBCFG, B43_NPHY_BBCFG_RSTCCA, B43_NPHY_BPHY_CTL3, B43_NPHY_BPHY_CTL3_SCALE, B43_NPHY_BPHY_CTL3_SCALE_SHIFT, b43_nphy_bphy_init(), b43_nphy_cal_rx_iq(), b43_nphy_cal_tx_iq_lo(), b43_nphy_classifier(), B43_NPHY_DUP40_BL, B43_NPHY_DUP40_GFBL, B43_NPHY_EPS_TABLE_ADJ0, B43_NPHY_EPS_TABLE_ADJ1, b43_nphy_ext_pa_set_tx_dig_filters(), b43_nphy_force_rf_sequence(), b43_nphy_get_tx_gains(), b43_nphy_int_pa_set_tx_dig_filters(), b43_nphy_ipa(), B43_NPHY_MIMO_CRSTXEXT, b43_nphy_pa_override(), B43_NPHY_PAPD_EN0, B43_NPHY_PAPD_EN1, B43_NPHY_PLOAD_CSENSE_EXTLEN, b43_nphy_read_clip_detection(), b43_nphy_restore_cal(), b43_nphy_restore_rssi_cal(), B43_NPHY_RFCTL_INTC1, B43_NPHY_RFCTL_INTC2, B43_NPHY_RFCTL_INTC3, B43_NPHY_RFCTL_INTC4, B43_NPHY_RFCTL_OVER, B43_NPHY_RFSEQMODE, B43_NPHY_RFSEQMODE_CAOVER, B43_NPHY_RFSEQMODE_TROVER, b43_nphy_rssi_cal(), b43_nphy_save_cal(), b43_nphy_set_rx_core_state(), b43_nphy_spur_workaround(), b43_nphy_superswitch_init(), b43_nphy_tables_init(), b43_nphy_tx_gain_table_upload(), b43_nphy_tx_lp_fbw(), b43_nphy_tx_power_ctrl(), b43_nphy_tx_power_fix(), b43_nphy_tx_pwr_ctrl_coef_setup(), B43_NPHY_TXF_40CO_B1S0, B43_NPHY_TXF_40CO_B1S1, B43_NPHY_TXF_40CO_B32S1, B43_NPHY_TXMACDELAY, B43_NPHY_TXMACIF_HOLDOFF, B43_NPHY_TXREALFD, B43_NPHY_TXRIFS_FRDEL, b43_nphy_update_mimo_config(), b43_nphy_update_txrx_chain(), b43_nphy_workarounds(), b43_phy_force_clock(), b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), B43_RFSEQ_RESET2RX, B43_RFSEQ_RX2TX, b43_bus_dev::bdev, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_bus_dev::bus_sprom, b43_bus_dev::bus_type, b43_phy_n::cal_orig_pwr_idx, b43_chanspec::center_freq, b43_phy_n::crsminpwr_adjusted, b43_phy_n::deaf_count, b43_wldev::dev, b43_phy_n_txpwrindex::index_internal, b43_phy_n::iqcal_chanspec_2G, b43_phy_n::iqcal_chanspec_5G, b43_phy_n::measure_hold, b43_phy_n::mphase_cal_phase_id, b43_phy_n::mute, b43_phy::n, b43_phy_n::noisevars_adjusted, b43_phy_n::papd_epsilon_offset, b43_phy_n::perical, b43_wldev::phy, b43_phy_n::phyrxchain, b43_phy_n::preamble_override, b43_phy::rev, b43_phy_n::rssical_chanspec_2G, b43_phy_n::rssical_chanspec_5G, b43_bus_dev::sdev, b43_phy_n::txpwrctrl, b43_phy_n::txpwrindex, and b43_wldev::wl.
Referenced by b43_nphy_op_init().
static void b43_radio_2055_setup (struct b43_wldev * dev, const struct b43_nphy_channeltab_entry_rev2 * e) [static]
Definition at line 527 of file phy_n.c.
References B2055_VCO_CAL10, b43_chantab_radio_upload(), B43_MMIO_MACCTL, b43_radio_write(), b43_read32(), B43_WARN_ON, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_nphy_set_channel().
static void b43_radio_2056_setup (struct b43_wldev * dev, const struct b43_nphy_channeltab_entry_rev3 * e) [static]
Definition at line 228 of file phy_n.c.
References B2056_SYN_PLL_VCOCAL12, B2056_TX_INTPAA_PA_MISC, b43_chantab_radio_2056_upload(), b43_radio_write(), B43_WARN_ON, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_nphy_set_channel().
static void b43_radio_init2055 (struct b43_wldev * dev) [static]
Definition at line 612 of file phy_n.c.
References b2055_upload_inittab(), b43_current_band(), b43_radio_init2055_post(), b43_radio_init2055_pre(), B43_STAT_INITIALIZED, b43_status, and b43_wldev::wl.
Referenced by b43_nphy_op_software_rfkill().
static void b43_radio_init2055_post (struct b43_wldev * dev) [static]
Definition at line 552 of file phy_n.c.
References B2055_C1_LNA_GAINBST, B2055_C1_RX_BB_LPF, B2055_C1_RX_BB_MIDACHP, B2055_C1_RX_BB_REG, B2055_C1_RX_RFSPC1, B2055_C2_LNA_GAINBST, B2055_C2_RX_BB_LPF, B2055_C2_RX_BB_MIDACHP, B2055_C2_RX_BB_REG, B2055_C2_RX_RFSPC1, B2055_CAL_COUT2, B2055_CAL_LPOCTL, B2055_CAL_MISC, B2055_MASTER1, B2055_RRCCAL_NOPTSEL, B43_BFL2_RXBB_INT_REG_DIS, b43_radio_mask(), b43_radio_maskset(), b43_radio_read(), b43_radio_set(), b43_radio_write(), b43_switch_channel(), b43err(), b43_bus_dev::board_rev, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_bus_dev::bus_sprom, b43_phy::channel, b43_wldev::dev, b43_phy_n::gain_boost, b43_phy::n, b43_wldev::phy, and b43_wldev::wl.
Referenced by b43_radio_init2055().
static void b43_radio_init2055_pre (struct b43_wldev * dev) [static]
Definition at line 541 of file phy_n.c.
References B43_NPHY_RFCTL_CMD, B43_NPHY_RFCTL_CMD_CHIP0PU, B43_NPHY_RFCTL_CMD_OEPORFORCE, B43_NPHY_RFCTL_CMD_PORFORCE, b43_phy_mask(), and b43_phy_set().
Referenced by b43_radio_init2055().
static void b43_radio_init2056 (struct b43_wldev * dev) [static]
Definition at line 657 of file phy_n.c.
References b2056_upload_inittabs(), b43_radio_init2056_post(), and b43_radio_init2056_pre().
Referenced by b43_nphy_op_software_rfkill().
static void b43_radio_init2056_post (struct b43_wldev * dev) [static]
Definition at line 638 of file phy_n.c.
References B2056_SYN_COM_CTRL, B2056_SYN_COM_PU, B2056_SYN_COM_RESET, B2056_SYN_PLL_MAST2, B2056_SYN_RCCAL_CTRL0, b43_radio_mask(), and b43_radio_set().
Referenced by b43_radio_init2056().
static void b43_radio_init2056_pre (struct b43_wldev * dev) [static]
Definition at line 625 of file phy_n.c.
References B43_NPHY_RFCTL_CMD, B43_NPHY_RFCTL_CMD_CHIP0PU, B43_NPHY_RFCTL_CMD_OEPORFORCE, b43_phy_mask(), and b43_phy_set().
Referenced by b43_radio_init2056().
static void check_phyreg (struct b43_wldev * dev, u16 offset) [inline, static]
Definition at line 4086 of file phy_n.c.
References B43_PHYROUTE, B43_PHYROUTE_EXT_GPHY, B43_PHYROUTE_OFDM_GPHY, b43err(), and b43_wldev::wl.
Referenced by b43_nphy_op_maskset(), b43_nphy_op_read(), and b43_nphy_op_write().
Variable Documentation
struct b43_phy_operations b43_phyops_n
Initial value:
 {
        .allocate               = b43_nphy_op_allocate,
        .free                   = b43_nphy_op_free,
        .prepare_structs        = b43_nphy_op_prepare_structs,
        .init                   = b43_nphy_op_init,
        .phy_read               = b43_nphy_op_read,
        .phy_write              = b43_nphy_op_write,
        .phy_maskset            = b43_nphy_op_maskset,
        .radio_read             = b43_nphy_op_radio_read,
        .radio_write            = b43_nphy_op_radio_write,
        .software_rfkill        = b43_nphy_op_software_rfkill,
        .switch_analog          = b43_nphy_op_switch_analog,
        .switch_channel         = b43_nphy_op_switch_channel,
        .get_default_chan       = b43_nphy_op_get_default_chan,
        .recalc_txpower         = b43_nphy_op_recalc_txpower,
        .adjust_txpower         = b43_nphy_op_adjust_txpower,
}
Definition at line 4231 of file phy_n.c.
Referenced by b43_phy_allocate().