CompatWireless3.2: drivers/net/wireless/b43/phy_lp.c File Reference
drivers/net/wireless/b43/phy_lp.c File Reference
#include <linux/slab.h>
#include "b43.h"
#include "main.h"
#include "phy_lp.h"
#include "phy_common.h"
#include "tables_lpphy.h"
Data Structures
struct b2062_freqdata
struct lpphy_stx_table_entry
struct lpphy_iq_est
struct lpphy_tx_gains
struct lpphy_rx_iq_comp
struct b206x_channel
Functions
static u16 channel2freq_lp (u8 channel)
static unsigned int b43_lpphy_op_get_default_chan (struct b43_wldev *dev)
static int b43_lpphy_op_allocate (struct b43_wldev *dev)
static void b43_lpphy_op_prepare_structs (struct b43_wldev *dev)
static void b43_lpphy_op_free (struct b43_wldev *dev)
static void lpphy_read_band_sprom (struct b43_wldev *dev)
static void lpphy_adjust_gain_table (struct b43_wldev *dev, u32 freq)
static void lpphy_table_init (struct b43_wldev *dev)
static void lpphy_baseband_rev0_1_init (struct b43_wldev *dev)
static void lpphy_save_dig_flt_state (struct b43_wldev *dev)
static void lpphy_restore_dig_flt_state (struct b43_wldev *dev)
static void lpphy_baseband_rev2plus_init (struct b43_wldev *dev)
static void lpphy_baseband_init (struct b43_wldev *dev)
static void lpphy_2062_init (struct b43_wldev *dev)
static void lpphy_2063_init (struct b43_wldev *dev)
static void lpphy_sync_stx (struct b43_wldev *dev)
static void lpphy_radio_init (struct b43_wldev *dev)
static void lpphy_set_rc_cap (struct b43_wldev *dev)
static u8 lpphy_get_bb_mult (struct b43_wldev *dev)
static void lpphy_set_bb_mult (struct b43_wldev *dev, u8 bb_mult)
static void lpphy_set_deaf (struct b43_wldev *dev, bool user)
static void lpphy_clear_deaf (struct b43_wldev *dev, bool user)
static void lpphy_set_trsw_over (struct b43_wldev *dev, bool tx, bool rx)
static void lpphy_disable_crs (struct b43_wldev *dev, bool user)
static void lpphy_restore_crs (struct b43_wldev *dev, bool user)
static void lpphy_disable_rx_gain_override (struct b43_wldev *dev)
static void lpphy_enable_rx_gain_override (struct b43_wldev *dev)
static void lpphy_disable_tx_gain_override (struct b43_wldev *dev)
static void lpphy_enable_tx_gain_override (struct b43_wldev *dev)
static struct lpphy_tx_gains lpphy_get_tx_gains (struct b43_wldev *dev)
static void lpphy_set_dac_gain (struct b43_wldev *dev, u16 dac)
static u16 lpphy_get_pa_gain (struct b43_wldev *dev)
static void lpphy_set_pa_gain (struct b43_wldev *dev, u16 gain)
static void lpphy_set_tx_gains (struct b43_wldev *dev, struct lpphy_tx_gains gains)
static void lpphy_rev0_1_set_rx_gain (struct b43_wldev *dev, u32 gain)
static void lpphy_rev2plus_set_rx_gain (struct b43_wldev *dev, u32 gain)
static void lpphy_set_rx_gain (struct b43_wldev *dev, u32 gain)
static void lpphy_set_rx_gain_by_index (struct b43_wldev *dev, u16 idx)
static void lpphy_stop_ddfs (struct b43_wldev *dev)
static void lpphy_run_ddfs (struct b43_wldev *dev, int i_on, int q_on, int incr1, int incr2, int scale_idx)
static bool lpphy_rx_iq_est (struct b43_wldev *dev, u16 samples, u8 time, struct lpphy_iq_est *iq_est)
static int lpphy_loopback (struct b43_wldev *dev)
static u32 lpphy_qdiv_roundup (u32 dividend, u32 divisor, u8 precision)
static void lpphy_read_tx_pctl_mode_from_hardware (struct b43_wldev *dev)
static void lpphy_write_tx_pctl_mode_to_hardware (struct b43_wldev *dev)
static void lpphy_set_tx_power_control (struct b43_wldev *dev, enum b43_lpphy_txpctl_mode mode)
static int b43_lpphy_op_switch_channel (struct b43_wldev *dev, unsigned int new_channel)
static void lpphy_rev0_1_rc_calib (struct b43_wldev *dev)
static void lpphy_rev2plus_rc_calib (struct b43_wldev *dev)
static void lpphy_calibrate_rc (struct b43_wldev *dev)
static void b43_lpphy_op_set_rx_antenna (struct b43_wldev *dev, int antenna)
static void lpphy_set_tx_iqcc (struct b43_wldev *dev, u16 a, u16 b)
static void lpphy_set_tx_power_by_index (struct b43_wldev *dev, u8 index)
static void lpphy_btcoex_override (struct b43_wldev *dev)
static void b43_lpphy_op_software_rfkill (struct b43_wldev *dev, bool blocked)
static void lpphy_set_analog_filter (struct b43_wldev *dev, int channel)
static void lpphy_set_tssi_mux (struct b43_wldev *dev, enum tssi_mux_mode mode)
static void lpphy_tx_pctl_init_hw (struct b43_wldev *dev)
static void lpphy_tx_pctl_init_sw (struct b43_wldev *dev)
static void lpphy_tx_pctl_init (struct b43_wldev *dev)
static void lpphy_pr41573_workaround (struct b43_wldev *dev)
static int lpphy_calc_rx_iq_comp (struct b43_wldev *dev, u16 samples)
static void lpphy_run_samples (struct b43_wldev *dev, u16 samples, u16 loops, u16 wait)
static void lpphy_start_tx_tone (struct b43_wldev *dev, s32 freq, u16 max)
static void lpphy_stop_tx_tone (struct b43_wldev *dev)
static void lpphy_papd_cal (struct b43_wldev *dev, struct lpphy_tx_gains gains, int mode, bool useindex, u8 index)
static void lpphy_papd_cal_txpwr (struct b43_wldev *dev)
static int lpphy_rx_iq_cal (struct b43_wldev *dev, bool noise, bool tx, bool rx, bool pa, struct lpphy_tx_gains *gains)
static void lpphy_calibration (struct b43_wldev *dev)
static u16 b43_lpphy_op_read (struct b43_wldev *dev, u16 reg)
static void b43_lpphy_op_write (struct b43_wldev *dev, u16 reg, u16 value)
static void b43_lpphy_op_maskset (struct b43_wldev *dev, u16 reg, u16 mask, u16 set)
static u16 b43_lpphy_op_radio_read (struct b43_wldev *dev, u16 reg)
static void b43_lpphy_op_radio_write (struct b43_wldev *dev, u16 reg, u16 value)
static void lpphy_b2062_reset_pll_bias (struct b43_wldev *dev)
static void lpphy_b2062_vco_calib (struct b43_wldev *dev)
static int lpphy_b2062_tune (struct b43_wldev *dev, unsigned int channel)
static void lpphy_b2063_vco_calib (struct b43_wldev *dev)
static int lpphy_b2063_tune (struct b43_wldev *dev, unsigned int channel)
static int b43_lpphy_op_init (struct b43_wldev *dev)
static void b43_lpphy_op_adjust_txpower (struct b43_wldev *dev)
static enum b43_txpwr_result b43_lpphy_op_recalc_txpower (struct b43_wldev *dev, bool ignore_tssi)
static void b43_lpphy_op_switch_analog (struct b43_wldev *dev, bool on)
static void b43_lpphy_op_pwork_15sec (struct b43_wldev *dev)
Variables
static struct lpphy_stx_table_entry lpphy_stx_table []
static struct lpphy_rx_iq_comp lpphy_5354_iq_table []
static struct lpphy_rx_iq_comp lpphy_rev0_1_iq_table []
static struct lpphy_rx_iq_comp lpphy_rev2plus_iq_comp
static struct b206x_channel b2062_chantbl []
static struct b206x_channel b2063_chantbl []
struct b43_phy_operations b43_phyops_lp
Function Documentation
static void b43_lpphy_op_adjust_txpower (struct b43_wldev * dev) [static]
Definition at line 2690 of file phy_lp.c.
static int b43_lpphy_op_allocate (struct b43_wldev * dev) [static]
Definition at line 54 of file phy_lp.c.
References b43_phy::lp, and b43_wldev::phy.
static void b43_lpphy_op_free (struct b43_wldev * dev) [static]
Definition at line 77 of file phy_lp.c.
References b43_phy::lp, and b43_wldev::phy.
static unsigned int b43_lpphy_op_get_default_chan (struct b43_wldev * dev) [static]
Definition at line 47 of file phy_lp.c.
References b43_current_band(), and b43_wldev::wl.
Referenced by lpphy_table_init().
static int b43_lpphy_op_init (struct b43_wldev * dev) [static]
Definition at line 2665 of file phy_lp.c.
References B43_BUS_SSB, b43_lpphy_op_switch_channel(), b43dbg(), b43err(), b43_bus_dev::bus_type, b43_wldev::dev, lpphy_baseband_init(), lpphy_calibrate_rc(), lpphy_calibration(), lpphy_radio_init(), lpphy_read_band_sprom(), lpphy_tx_pctl_init(), and b43_wldev::wl.
static void b43_lpphy_op_maskset (struct b43_wldev * dev, u16 reg, u16 mask, u16 set) [static]
Definition at line 2006 of file phy_lp.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), and b43_write16().
static void b43_lpphy_op_prepare_structs (struct b43_wldev * dev) [static]
Definition at line 66 of file phy_lp.c.
References b43_phy_lp::antenna, B43_ANTENNA_DEFAULT, b43_phy::lp, and b43_wldev::phy.
static void b43_lpphy_op_pwork_15sec (struct b43_wldev * dev) [static]
Definition at line 2712 of file phy_lp.c.
static u16 b43_lpphy_op_radio_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 2014 of file phy_lp.c.
References B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_LOW, b43_read16(), B43_WARN_ON, b43_write16(), b43_wldev::phy, and b43_phy::rev.
static void b43_lpphy_op_radio_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 2029 of file phy_lp.c.
References B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_LOW, B43_WARN_ON, and b43_write16().
static u16 b43_lpphy_op_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 1994 of file phy_lp.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), and b43_write16().
static enum b43_txpwr_result b43_lpphy_op_recalc_txpower (struct b43_wldev * dev, bool ignore_tssi) [static]
Definition at line 2695 of file phy_lp.c.
References B43_TXPWR_RES_DONE.
static void b43_lpphy_op_set_rx_antenna (struct b43_wldev * dev, int antenna) [static]
Definition at line 1360 of file phy_lp.c.
References b43_phy_lp::antenna, B43_ANTENNA_AUTO1, B43_HF_ANTDIVHELP, b43_hf_read(), b43_hf_write(), B43_LPPHY_CRSGAIN_CTL, b43_phy_maskset(), B43_WARN_ON, b43_phy::lp, b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_pr41573_workaround().
static void b43_lpphy_op_software_rfkill (struct b43_wldev * dev, bool blocked) [static]
Definition at line 1435 of file phy_lp.c.
References B43_LPPHY_AFE_DDFS, B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_2, B43_LPPHY_RF_OVERRIDE_2_VAL, B43_LPPHY_RF_OVERRIDE_VAL_0, b43_phy_mask(), b43_phy_set(), b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_pr41573_workaround().
static void b43_lpphy_op_switch_analog (struct b43_wldev * dev, bool on) [static]
Definition at line 2702 of file phy_lp.c.
References B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_AFE_CTL_OVRVAL, b43_phy_mask(), and b43_phy_set().
static int b43_lpphy_op_switch_channel (struct b43_wldev * dev, unsigned int new_channel) [static]
Definition at line 2641 of file phy_lp.c.
References B43_MMIO_CHANNEL, b43_write16(), b43_phy_lp::channel, channel2freq_lp(), b43_phy::lp, lpphy_adjust_gain_table(), lpphy_b2062_tune(), lpphy_b2063_tune(), lpphy_set_analog_filter(), b43_wldev::phy, and b43_phy::radio_ver.
Referenced by b43_lpphy_op_init(), and lpphy_rev0_1_rc_calib().
static void b43_lpphy_op_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 2000 of file phy_lp.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, and b43_write16().
static u16 channel2freq_lp (u8 channel) [inline, static]
Definition at line 35 of file phy_lp.c.
Referenced by b43_lpphy_op_switch_channel(), lpphy_b2062_tune(), and lpphy_table_init().
static void lpphy_2062_init (struct b43_wldev * dev) [static]
Definition at line 519 of file phy_lp.c.
References B2062_N_CALIB_TS, B2062_N_COMM2, B2062_N_PDN_CTL0, B2062_N_TSSI_CTL0, B2062_N_TX_CTL3, B2062_N_TX_CTL4, B2062_N_TX_CTL5, B2062_N_TX_CTL6, B2062_S_BG_CTL1, B2062_S_RFPLL_CTL1, B2062_S_RFPLL_CTL10, B2062_S_RFPLL_CTL11, B2062_S_RFPLL_CTL18, B2062_S_RFPLL_CTL19, B2062_S_RFPLL_CTL7, B2062_S_RFPLL_CTL8, B2062_S_RFPLL_CTL9, b2062_upload_init_table(), b43_current_band(), b43_radio_mask(), b43_radio_read(), b43_radio_set(), b43_radio_write(), B43_WARN_ON, b43dbg(), b2062_freqdata::data, b43_wldev::dev, b2062_freqdata::freq, b43_phy::lp, b43_phy_lp::pdiv, b43_wldev::phy, b43_phy::rev, b43_bus_dev::sdev, and b43_wldev::wl.
Referenced by lpphy_radio_init().
static void lpphy_2063_init (struct b43_wldev * dev) [static]
Definition at line 609 of file phy_lp.c.
References B2063_COMM8, B2063_LOGEN_SP5, B2063_PA_SP2, B2063_PA_SP3, B2063_PA_SP4, B2063_PA_SP7, B2063_REG_SP1, B2063_RX_BB_CTL2, B2063_TX_RF_SP6, B2063_TX_RF_SP9, b2063_upload_init_table(), b43_radio_mask(), b43_radio_set(), b43_radio_write(), b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_radio_init().
static void lpphy_adjust_gain_table (struct b43_wldev * dev, u32 freq) [static]
Definition at line 175 of file phy_lp.c.
References b43_current_band(), B43_LPTAB16, b43_lptab_write_bulk(), B43_WARN_ON, b43_phy::lp, b43_wldev::phy, b43_phy::rev, b43_phy_lp::tx_isolation_hi_band, b43_phy_lp::tx_isolation_low_band, b43_phy_lp::tx_isolation_med_band, and b43_wldev::wl.
Referenced by b43_lpphy_op_switch_channel(), and lpphy_table_init().
static void lpphy_b2062_reset_pll_bias (struct b43_wldev * dev) [static]
Definition at line 2407 of file phy_lp.c.
References B2062_N_COMM1, B2062_S_RFPLL_CTL2, b43_radio_write(), b43_bus_dev::chip_id, and b43_wldev::dev.
Referenced by lpphy_b2062_tune().
static int lpphy_b2062_tune (struct b43_wldev * dev, unsigned int channel) [static]
Definition at line 2427 of file phy_lp.c.
References B2062_N_LGENA_CTL5, B2062_N_LGENA_CTL6, B2062_N_LGENA_TUNE0, B2062_N_LGENA_TUNE2, B2062_N_LGENA_TUNE3, B2062_N_TX_PAD, B2062_N_TX_PGA, B2062_N_TX_TUNE, B2062_S_LGENG_CTL1, B2062_S_RFPLL_CTL14, B2062_S_RFPLL_CTL19, B2062_S_RFPLL_CTL23, B2062_S_RFPLL_CTL24, B2062_S_RFPLL_CTL26, B2062_S_RFPLL_CTL27, B2062_S_RFPLL_CTL28, B2062_S_RFPLL_CTL29, B2062_S_RFPLL_CTL3, B2062_S_RFPLL_CTL33, B2062_S_RFPLL_CTL34, b43_radio_mask(), b43_radio_read(), b43_radio_set(), b43_radio_write(), B43_WARN_ON, channel2freq_lp(), b206x_channel::data, b43_wldev::dev, b43_phy::lp, lpphy_b2062_reset_pll_bias(), lpphy_b2062_vco_calib(), b43_phy_lp::pdiv, b43_wldev::phy, and b43_bus_dev::sdev.
Referenced by b43_lpphy_op_switch_channel().
static void lpphy_b2062_vco_calib (struct b43_wldev * dev) [static]
Definition at line 2420 of file phy_lp.c.
References B2062_S_RFPLL_CTL21, and b43_radio_write().
Referenced by lpphy_b2062_tune().
static int lpphy_b2063_tune (struct b43_wldev * dev, unsigned int channel) [static]
Definition at line 2518 of file phy_lp.c.
References B2063_A_RX_1ST3, B2063_A_RX_2ND1, B2063_A_RX_2ND4, B2063_A_RX_2ND7, B2063_A_RX_PS6, B2063_COMM15, B2063_LOGEN_BUF2, B2063_LOGEN_MIXER2, B2063_LOGEN_RCCR1, B2063_LOGEN_VCOBUF1, B2063_PA_CTL11, B2063_PLL_JTAG_PLL_CP2, B2063_PLL_JTAG_PLL_CP3, B2063_PLL_JTAG_PLL_LF1, B2063_PLL_JTAG_PLL_LF2, B2063_PLL_JTAG_PLL_LF3, B2063_PLL_JTAG_PLL_LF4, B2063_PLL_JTAG_PLL_SG1, B2063_PLL_JTAG_PLL_SG2, B2063_PLL_JTAG_PLL_SG3, B2063_PLL_JTAG_PLL_SG4, B2063_PLL_JTAG_PLL_VCO1, B2063_PLL_JTAG_PLL_VCO_CALIB3, B2063_PLL_JTAG_PLL_VCO_CALIB5, B2063_PLL_JTAG_PLL_VCO_CALIB6, B2063_PLL_JTAG_PLL_VCO_CALIB7, B2063_PLL_JTAG_PLL_VCO_CALIB8, B2063_PLL_JTAG_PLL_XTAL_12, B2063_PLL_SP2, B2063_TX_RF_CTL2, B2063_TX_RF_CTL5, b43_radio_mask(), b43_radio_maskset(), b43_radio_read(), b43_radio_set(), b43_radio_write(), B43_WARN_ON, b206x_channel::data, b43_wldev::dev, b206x_channel::freq, lpphy_b2063_vco_calib(), lpphy_qdiv_roundup(), and b43_bus_dev::sdev.
Referenced by b43_lpphy_op_switch_channel().
static void lpphy_b2063_vco_calib (struct b43_wldev * dev) [static]
Definition at line 2501 of file phy_lp.c.
References B2063_PLL_JTAG_CALNRST, B2063_PLL_SP1, b43_radio_mask(), b43_radio_read(), b43_radio_set(), and b43_radio_write().
Referenced by lpphy_b2063_tune().
static void lpphy_baseband_init (struct b43_wldev * dev) [static]
Definition at line 504 of file phy_lp.c.
References lpphy_baseband_rev0_1_init(), lpphy_baseband_rev2plus_init(), lpphy_table_init(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_lpphy_op_init(), and lpphy_pr41573_workaround().
static void lpphy_baseband_rev0_1_init (struct b43_wldev * dev) [static]
Definition at line 215 of file phy_lp.c.
References B43_BFH_FEM_BT, B43_BFH_PAREF, B43_BFH_RSSIINV, B43_BFL_FEM, b43_current_band(), B43_HF_PR45960W, b43_hf_read(), b43_hf_write(), B43_LPPHY_4C3, B43_LPPHY_4C4, B43_LPPHY_4C5, B43_LPPHY_ADC_COMPENSATION_CTL, B43_LPPHY_AFE_ADC_CTL_0, B43_LPPHY_AFE_CTL, B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_AFE_DAC_CTL, B43_LPPHY_AFE_RSSI_CTL_0, B43_LPPHY_AFE_RSSI_CTL_1, B43_LPPHY_CLIPCTRTHRESH, B43_LPPHY_CRS_ED_THRESH, B43_LPPHY_CRSGAIN_CTL, B43_LPPHY_DSSS_CONFIRM_CNT, B43_LPPHY_GAIN_MISMATCH_LIMIT, B43_LPPHY_GAINDIRECTMISMATCH, B43_LPPHY_GPIO_OUTEN, B43_LPPHY_GPIO_SELECT, B43_LPPHY_HIGAINDB, B43_LPPHY_IDLEAFTERPKTRXTO, B43_LPPHY_INPUT_PWRDB, B43_LPPHY_LOWGAINDB, B43_LPPHY_LP_PHY_CTL, B43_LPPHY_LP_RF_SIGNAL_LUT, B43_LPPHY_MINPWR_LEVEL, B43_LPPHY_OFDMSYNCTHRESH0, B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_2, B43_LPPHY_RX_RADIO_CTL, B43_LPPHY_SYNCPEAKCNT, B43_LPPHY_TR_LOOKUP_1, B43_LPPHY_TR_LOOKUP_2, B43_LPPHY_TR_LOOKUP_3, B43_LPPHY_TR_LOOKUP_4, B43_LPPHY_TR_LOOKUP_5, B43_LPPHY_TR_LOOKUP_6, B43_LPPHY_TR_LOOKUP_7, B43_LPPHY_TR_LOOKUP_8, B43_LPPHY_VERYLOWGAINDB, B43_LPTAB16, b43_lptab_write(), b43_phy_copy(), b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_bus_dev::board_type, b43_bus_dev::bus_sprom, b43_phy_lp::bx_arch, b43_bus_dev::chip_id, b43_bus_dev::chip_pkg, b43_wldev::dev, b43_phy::lp, b43_wldev::phy, b43_phy::rev, b43_phy_lp::rssi_vc, b43_phy_lp::rssi_vf, b43_phy_lp::rx_pwr_offset, b43_bus_dev::sdev, and b43_wldev::wl.
Referenced by lpphy_baseband_init().
static void lpphy_baseband_rev2plus_init (struct b43_wldev * dev) [static]
Definition at line 414 of file phy_lp.c.
References b43_current_band(), B43_LPPHY_ADC_COMPENSATION_CTL, B43_LPPHY_AFE_ADC_CTL_0, B43_LPPHY_AFE_ADC_CTL_1, B43_LPPHY_AFE_CTL, B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_AFE_CTL_OVRVAL, B43_LPPHY_AFE_DAC_CTL, B43_LPPHY_AFE_RSSI_CTL_0, B43_LPPHY_AFE_RSSI_CTL_1, B43_LPPHY_CLIPCTRTHRESH, B43_LPPHY_CLIPTHRESH, B43_LPPHY_CRS_ED_THRESH, B43_LPPHY_CRSGAIN_CTL, B43_LPPHY_DCOFFSETTRANSIENT, B43_LPPHY_GAINDIRECTMISMATCH, B43_LPPHY_GAINMISMATCH, B43_LPPHY_HIGAINDB, B43_LPPHY_IDLEAFTERPKTRXTO, B43_LPPHY_INPUT_PWRDB, B43_LPPHY_LOWGAINDB, B43_LPPHY_MINPWR_LEVEL, B43_LPPHY_OFDMSYNCTHRESH0, B43_LPPHY_PREAMBLECONFIRMTO, B43_LPPHY_PWR_THRESH1, B43_LPPHY_RESET_CTL, B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_2, B43_LPPHY_SYNCPEAKCNT, B43_LPPHY_TR_LOOKUP_1, B43_LPPHY_VERYLOWGAINDB, B43_LPTAB16, B43_LPTAB32, b43_lptab_write(), b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM, b43_phy_set(), b43_phy_write(), b43_bus_dev::board_rev, b43_bus_dev::chip_id, b43_bus_dev::chip_rev, b43_wldev::dev, b43_phy::lp, lpphy_save_dig_flt_state(), b43_wldev::phy, b43_phy_lp::rssi_gs, b43_phy_lp::rssi_vc, b43_phy_lp::rssi_vf, b43_phy_lp::rx_pwr_offset, and b43_wldev::wl.
Referenced by lpphy_baseband_init().
static void lpphy_btcoex_override (struct b43_wldev * dev) [static]
Definition at line 1429 of file phy_lp.c.
References B43_MMIO_BTCOEX_CTL, B43_MMIO_BTCOEX_TXCTL, and b43_write16().
Referenced by lpphy_calibration().
static int lpphy_calc_rx_iq_comp (struct b43_wldev * dev, u16 samples) [static]
Definition at line 1715 of file phy_lp.c.
References B43_LPPHY_RX_COMP_COEFF_S, b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), lpphy_iq_est::i_pwr, lpphy_iq_est::iq_prod, lpphy_rx_iq_est(), and lpphy_iq_est::q_pwr.
Referenced by lpphy_rx_iq_cal().
static void lpphy_calibrate_rc (struct b43_wldev * dev) [static]
Definition at line 1346 of file phy_lp.c.
References b43_current_band(), b43_phy::lp, lpphy_rev0_1_rc_calib(), lpphy_rev2plus_rc_calib(), lpphy_set_rc_cap(), b43_wldev::phy, b43_phy_lp::rc_cap, b43_phy::rev, and b43_wldev::wl.
Referenced by b43_lpphy_op_init().
static void lpphy_calibration (struct b43_wldev * dev) [static]
Definition at line 1961 of file phy_lp.c.
References B43_LPPHY_TXPCTL_OFF, b43_mac_enable(), b43_mac_suspend(), b43_phy_lp::channel, b43_phy_lp::full_calib_chan, b43_phy::lp, lpphy_btcoex_override(), lpphy_papd_cal_txpwr(), lpphy_pr41573_workaround(), lpphy_read_tx_pctl_mode_from_hardware(), lpphy_restore_dig_flt_state(), lpphy_rx_iq_cal(), lpphy_save_dig_flt_state(), lpphy_set_tx_power_control(), b43_wldev::phy, b43_phy::rev, and b43_phy_lp::txpctl_mode.
Referenced by b43_lpphy_op_init().
static void lpphy_clear_deaf (struct b43_wldev * dev, bool user) [static]
Definition at line 745 of file phy_lp.c.
References b43_current_band(), B43_LPPHY_CRSGAIN_CTL, b43_phy_maskset(), b43_phy_lp::crs_sys_disable, b43_phy_lp::crs_usr_disable, b43_phy::lp, b43_wldev::phy, and b43_wldev::wl.
Referenced by lpphy_restore_crs(), and lpphy_rx_iq_cal().
static void lpphy_disable_crs (struct b43_wldev * dev, bool user) [static]
Definition at line 771 of file phy_lp.c.
References B43_LPPHY_PS_CTL_OVERRIDE_VAL0, B43_LPPHY_PS_CTL_OVERRIDE_VAL1, B43_LPPHY_PS_CTL_OVERRIDE_VAL2, B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_2, B43_LPPHY_RF_OVERRIDE_2_VAL, B43_LPPHY_RF_OVERRIDE_VAL_0, B43_LPPHY_RX_GAIN_CTL_OVERRIDE_VAL, B43_LPPHY_TX_GAIN_CTL_OVERRIDE_VAL, b43_phy_mask(), b43_phy_set(), b43_phy_write(), lpphy_set_deaf(), and lpphy_set_trsw_over().
Referenced by lpphy_rev0_1_rc_calib().
static void lpphy_disable_rx_gain_override (struct b43_wldev * dev) [static]
Definition at line 809 of file phy_lp.c.
References b43_current_band(), B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_2, b43_phy_mask(), B43_PHY_OFDM, b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by lpphy_rx_iq_cal().
static void lpphy_disable_tx_gain_override (struct b43_wldev * dev) [static]
Definition at line 841 of file phy_lp.c.
References B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_RF_OVERRIDE_2, b43_phy_mask(), b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_rx_iq_cal(), and lpphy_set_tx_power_control().
static void lpphy_enable_rx_gain_override (struct b43_wldev * dev) [static]
Definition at line 825 of file phy_lp.c.
References b43_current_band(), B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_2, B43_PHY_OFDM, b43_phy_set(), b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by lpphy_set_rx_gain().
static void lpphy_enable_tx_gain_override (struct b43_wldev * dev) [static]
Definition at line 852 of file phy_lp.c.
References B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_RF_OVERRIDE_2, b43_phy_set(), b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_set_tx_gains(), and lpphy_set_tx_power_by_index().
static u8 lpphy_get_bb_mult (struct b43_wldev * dev) [static]
Definition at line 724 of file phy_lp.c.
References B43_LPTAB16, and b43_lptab_read().
Referenced by lpphy_papd_cal_txpwr(), and lpphy_rev0_1_rc_calib().
static u16 lpphy_get_pa_gain (struct b43_wldev * dev) [static]
Definition at line 892 of file phy_lp.c.
References B43_PHY_OFDM, and b43_phy_read().
Referenced by lpphy_set_tx_gains().
static struct lpphy_tx_gains lpphy_get_tx_gains (struct b43_wldev * dev) [static, read]
Definition at line 863 of file phy_lp.c.
References B43_LPPHY_AFE_DAC_CTL, B43_LPPHY_TX_GAIN_CTL_OVERRIDE_VAL, B43_PHY_OFDM, b43_phy_read(), lpphy_tx_gains::dac, lpphy_tx_gains::gm, lpphy_tx_gains::pad, and lpphy_tx_gains::pga.
Referenced by lpphy_papd_cal_txpwr(), lpphy_rev0_1_rc_calib(), and lpphy_rx_iq_cal().
static int lpphy_loopback (struct b43_wldev * dev) [static]
Definition at line 1044 of file phy_lp.c.
References B2062_N_TX_CTL_A, B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_AFE_CTL_OVRVAL, B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_VAL_0, b43_phy_mask(), b43_phy_set(), b43_radio_write(), lpphy_iq_est::i_pwr, lpphy_run_ddfs(), lpphy_rx_iq_est(), lpphy_set_rx_gain_by_index(), lpphy_set_trsw_over(), lpphy_stop_ddfs(), and lpphy_iq_est::q_pwr.
Referenced by lpphy_rev0_1_rc_calib().
static void lpphy_papd_cal (struct b43_wldev * dev, struct lpphy_tx_gains gains, int mode, bool useindex, u8 index) [static]
Definition at line 1834 of file phy_lp.c.
Referenced by lpphy_papd_cal_txpwr().
static void lpphy_papd_cal_txpwr (struct b43_wldev * dev) [static]
Definition at line 1840 of file phy_lp.c.
References B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_RF_PWR_OVERRIDE, B43_LPPHY_TXPCTL_OFF, b43_phy_maskset(), b43_phy_read(), b43_bus_dev::chip_id, b43_bus_dev::chip_rev, b43_wldev::dev, b43_phy::lp, lpphy_get_bb_mult(), lpphy_get_tx_gains(), lpphy_papd_cal(), lpphy_read_tx_pctl_mode_from_hardware(), lpphy_set_bb_mult(), lpphy_set_tx_gains(), lpphy_set_tx_power_control(), b43_wldev::phy, and b43_phy_lp::txpctl_mode.
Referenced by lpphy_calibration().
static void lpphy_pr41573_workaround (struct b43_wldev * dev) [static]
Definition at line 1582 of file phy_lp.c.
References b43_phy_lp::antenna, b43_lpphy_op_set_rx_antenna(), b43_lpphy_op_software_rfkill(), B43_LPPHY_TXPCTL_OFF, B43_LPTAB32, b43_lptab_read_bulk(), b43_lptab_write_bulk(), B43_MMIO_CHANNEL, b43_write16(), b43err(), b43_phy_lp::channel, b43_phy::lp, lpphy_baseband_init(), lpphy_read_tx_pctl_mode_from_hardware(), lpphy_set_analog_filter(), lpphy_set_rc_cap(), lpphy_set_tx_power_by_index(), lpphy_set_tx_power_control(), lpphy_table_init(), lpphy_tx_pctl_init(), b43_wldev::phy, b43_phy_lp::rc_cap, b43_phy::rev, b43_phy_lp::tssi_idx, b43_phy_lp::tssi_npt, b43_phy_lp::tx_pwr_idx_over, b43_phy_lp::txpctl_mode, and b43_wldev::wl.
Referenced by lpphy_calibration().
static u32 lpphy_qdiv_roundup (u32 dividend, u32 divisor, u8 precision) [static]
Definition at line 1078 of file phy_lp.c.
Referenced by lpphy_b2063_tune(), and lpphy_rev0_1_rc_calib().
static void lpphy_radio_init (struct b43_wldev * dev) [static]
Definition at line 685 of file phy_lp.c.
References B43_LPPHY_FOURWIRE_CTL, b43_phy_mask(), B43_PHY_OFDM, b43_phy_set(), b43_phy_write(), b43_bus_dev::chip_id, b43_wldev::dev, lpphy_2062_init(), lpphy_2063_init(), lpphy_sync_stx(), b43_wldev::phy, and b43_phy::radio_ver.
Referenced by b43_lpphy_op_init().
static void lpphy_read_band_sprom (struct b43_wldev * dev) [static]
Definition at line 86 of file phy_lp.c.
References b43_current_band(), B43_WARN_ON, b43_bus_dev::bus_sprom, b43_phy_lp::bx_arch, b43_wldev::dev, b43_phy::lp, b43_phy_lp::max_tx_pwr_hi_band, b43_phy_lp::max_tx_pwr_low_band, b43_phy_lp::max_tx_pwr_med_band, b43_wldev::phy, b43_phy_lp::rssi_gs, b43_phy_lp::rssi_vc, b43_phy_lp::rssi_vf, b43_phy_lp::rx_pwr_offset, b43_phy_lp::tx_isolation_hi_band, b43_phy_lp::tx_isolation_low_band, b43_phy_lp::tx_isolation_med_band, b43_phy_lp::tx_max_rate, b43_phy_lp::tx_max_rateh, b43_phy_lp::tx_max_ratel, b43_phy_lp::txpa, b43_phy_lp::txpah, b43_phy_lp::txpal, and b43_wldev::wl.
Referenced by b43_lpphy_op_init().
static void lpphy_read_tx_pctl_mode_from_hardware (struct b43_wldev * dev) [static]
Definition at line 1104 of file phy_lp.c.
References B43_LPPHY_TX_PWR_CTL_CMD, B43_LPPHY_TX_PWR_CTL_CMD_MODE, B43_LPPHY_TX_PWR_CTL_CMD_MODE_HW, B43_LPPHY_TX_PWR_CTL_CMD_MODE_OFF, B43_LPPHY_TX_PWR_CTL_CMD_MODE_SW, B43_LPPHY_TXPCTL_HW, B43_LPPHY_TXPCTL_OFF, B43_LPPHY_TXPCTL_SW, B43_LPPHY_TXPCTL_UNKNOWN, b43_phy_read(), B43_WARN_ON, b43_phy::lp, b43_wldev::phy, and b43_phy_lp::txpctl_mode.
Referenced by lpphy_calibration(), lpphy_papd_cal_txpwr(), lpphy_pr41573_workaround(), lpphy_rev0_1_rc_calib(), lpphy_set_tx_power_by_index(), and lpphy_set_tx_power_control().
static void lpphy_restore_crs (struct b43_wldev * dev, bool user) [static]
Definition at line 800 of file phy_lp.c.
References B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_2, b43_phy_mask(), and lpphy_clear_deaf().
Referenced by lpphy_rev0_1_rc_calib().
static void lpphy_restore_dig_flt_state (struct b43_wldev * dev) [static]
Definition at line 393 of file phy_lp.c.
References B43_PHY_OFDM, b43_phy_write(), b43_phy_lp::dig_flt_state, b43_phy::lp, and b43_wldev::phy.
Referenced by lpphy_calibration().
static void lpphy_rev0_1_rc_calib (struct b43_wldev * dev) [static]
Definition at line 1190 of file phy_lp.c.
References B2062_N_RXBB_CALIB2, B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_AFE_CTL_OVRVAL, B43_LPPHY_LP_PHY_CTL, b43_lpphy_op_switch_channel(), B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_2, B43_LPPHY_RF_OVERRIDE_2_VAL, B43_LPPHY_RF_OVERRIDE_VAL_0, B43_LPPHY_TXPCTL_OFF, b43_phy_maskset(), b43_phy_read(), b43_phy_write(), b43_radio_write(), b43dbg(), lpphy_iq_est::i_pwr, b43_phy::lp, lpphy_disable_crs(), lpphy_get_bb_mult(), lpphy_get_tx_gains(), lpphy_loopback(), lpphy_qdiv_roundup(), lpphy_read_tx_pctl_mode_from_hardware(), lpphy_restore_crs(), lpphy_run_ddfs(), lpphy_rx_iq_est(), lpphy_set_bb_mult(), lpphy_set_rc_cap(), lpphy_set_rx_gain_by_index(), lpphy_set_tx_gains(), lpphy_set_tx_power_control(), lpphy_stop_ddfs(), b43_wldev::phy, lpphy_iq_est::q_pwr, b43_phy_lp::rc_cap, b43_phy_lp::txpctl_mode, and b43_wldev::wl.
Referenced by lpphy_calibrate_rc().
static void lpphy_rev0_1_set_rx_gain (struct b43_wldev * dev, u32 gain) [static]
Definition at line 931 of file phy_lp.c.
References B43_LPPHY_RF_OVERRIDE_2_VAL, B43_LPPHY_RF_OVERRIDE_VAL_0, B43_LPPHY_RX_GAIN_CTL_OVERRIDE_VAL, b43_phy_maskset(), and b43_phy_write().
Referenced by lpphy_set_rx_gain().
static void lpphy_rev2plus_rc_calib (struct b43_wldev * dev) [static]
Definition at line 1290 of file phy_lp.c.
References B2063_PA_SP7, B2063_PLL_SP1, B2063_RC_CALIB_CTL1, B2063_RC_CALIB_CTL2, B2063_RC_CALIB_CTL3, B2063_RC_CALIB_CTL4, B2063_RC_CALIB_CTL5, B2063_RC_CALIB_CTL6, B2063_RX_BB_SP8, B2063_TX_BB_SP3, b43_radio_mask(), b43_radio_read(), b43_radio_write(), b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by lpphy_calibrate_rc().
static void lpphy_rev2plus_set_rx_gain (struct b43_wldev * dev, u32 gain) [static]
Definition at line 945 of file phy_lp.c.
References b43_current_band(), B43_LPPHY_AFE_DDFS, B43_LPPHY_RF_OVERRIDE_2_VAL, B43_LPPHY_RF_OVERRIDE_VAL_0, B43_LPPHY_RX_GAIN_CTL_OVERRIDE_VAL, b43_phy_maskset(), B43_PHY_OFDM, b43_phy_write(), and b43_wldev::wl.
Referenced by lpphy_set_rx_gain().
static void lpphy_run_ddfs (struct b43_wldev * dev, int i_on, int q_on, int incr1, int incr2, int scale_idx) [static]
Definition at line 989 of file phy_lp.c.
References B43_LPPHY_AFE_DDFS, B43_LPPHY_AFE_DDFS_INCR_INIT, B43_LPPHY_AFE_DDFS_POINTER_INIT, B43_LPPHY_LP_PHY_CTL, b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), and lpphy_stop_ddfs().
Referenced by lpphy_loopback(), and lpphy_rev0_1_rc_calib().
static void lpphy_run_samples (struct b43_wldev * dev, u16 samples, u16 loops, u16 wait) [static]
Definition at line 1772 of file phy_lp.c.
References B43_LPPHY_A_PHY_CTL_ADDR, B43_LPPHY_SMPL_PLAY_BUFFER_CTL, B43_LPPHY_SMPL_PLAY_COUNT, b43_phy_maskset(), and b43_phy_set().
Referenced by lpphy_start_tx_tone().
static int lpphy_rx_iq_cal (struct b43_wldev * dev, bool noise, bool tx, bool rx, bool pa, struct lpphy_tx_gains * gains) [static]
Definition at line 1868 of file phy_lp.c.
References b43_current_band(), B43_LPPHY_AFE_CTL_OVR, B43_LPPHY_AFE_CTL_OVRVAL, B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_VAL_0, B43_LPPHY_RX_COMP_COEFF_S, b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), B43_WARN_ON, lpphy_rx_iq_comp::c0, lpphy_rx_iq_comp::c1, b43_phy_lp::channel, b43_bus_dev::chip_id, b43_wldev::dev, b43_phy::lp, lpphy_calc_rx_iq_comp(), lpphy_clear_deaf(), lpphy_disable_rx_gain_override(), lpphy_disable_tx_gain_override(), lpphy_get_tx_gains(), lpphy_set_deaf(), lpphy_set_rx_gain(), lpphy_set_trsw_over(), lpphy_set_tx_gains(), lpphy_start_tx_tone(), lpphy_stop_tx_tone(), b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by lpphy_calibration().
static bool lpphy_rx_iq_est (struct b43_wldev * dev, u16 samples, u8 time, struct lpphy_iq_est * iq_est) [static]
Definition at line 1005 of file phy_lp.c.
References B43_LPPHY_CRSGAIN_CTL, B43_LPPHY_IQ_ACC_HI_ADDR, B43_LPPHY_IQ_ACC_LO_ADDR, B43_LPPHY_IQ_ENABLE_WAIT_TIME_ADDR, B43_LPPHY_IQ_I_PWR_ACC_HI_ADDR, B43_LPPHY_IQ_I_PWR_ACC_LO_ADDR, B43_LPPHY_IQ_NUM_SMPLS_ADDR, B43_LPPHY_IQ_Q_PWR_ACC_HI_ADDR, B43_LPPHY_IQ_Q_PWR_ACC_LO_ADDR, b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), lpphy_iq_est::i_pwr, lpphy_iq_est::iq_prod, and lpphy_iq_est::q_pwr.
Referenced by lpphy_calc_rx_iq_comp(), lpphy_loopback(), and lpphy_rev0_1_rc_calib().
static void lpphy_save_dig_flt_state (struct b43_wldev * dev) [static]
Definition at line 364 of file phy_lp.c.
References B43_PHY_OFDM, b43_phy_read(), b43_phy_write(), b43_phy_lp::dig_flt_state, b43_phy::lp, and b43_wldev::phy.
Referenced by lpphy_baseband_rev2plus_init(), and lpphy_calibration().
static void lpphy_set_analog_filter (struct b43_wldev * dev, int channel) [static]
Definition at line 1462 of file phy_lp.c.
References B2063_TX_BB_SP3, B43_LPPHY_LP_PHY_CTL, b43_phy_maskset(), b43_radio_write(), b43_phy::lp, lpphy_set_rc_cap(), b43_wldev::phy, b43_phy_lp::rc_cap, and b43_phy::rev.
Referenced by b43_lpphy_op_switch_channel(), and lpphy_pr41573_workaround().
static void lpphy_set_bb_mult (struct b43_wldev * dev, u8 bb_mult) [static]
Definition at line 729 of file phy_lp.c.
References B43_LPTAB16, and b43_lptab_write().
Referenced by lpphy_papd_cal_txpwr(), lpphy_rev0_1_rc_calib(), lpphy_set_tx_power_by_index(), and lpphy_tx_pctl_init_sw().
static void lpphy_set_dac_gain (struct b43_wldev * dev, u16 dac) [static]
Definition at line 885 of file phy_lp.c.
References B43_LPPHY_AFE_DAC_CTL, b43_phy_maskset(), and b43_phy_read().
Referenced by lpphy_set_tx_gains(), and lpphy_set_tx_power_by_index().
static void lpphy_set_deaf (struct b43_wldev * dev, bool user) [static]
Definition at line 734 of file phy_lp.c.
References B43_LPPHY_CRSGAIN_CTL, b43_phy_maskset(), b43_phy_lp::crs_sys_disable, b43_phy_lp::crs_usr_disable, b43_phy::lp, and b43_wldev::phy.
Referenced by lpphy_disable_crs(), and lpphy_rx_iq_cal().
static void lpphy_set_pa_gain (struct b43_wldev * dev, u16 gain) [static]
Definition at line 897 of file phy_lp.c.
References b43_phy_maskset(), and B43_PHY_OFDM.
Referenced by lpphy_set_tx_power_by_index().
static void lpphy_set_rc_cap (struct b43_wldev * dev) [static]
Definition at line 708 of file phy_lp.c.
References B2062_N_RXBB_CALIB2, B2062_N_TX_CTL_A, B2062_S_RXG_CNT16, b43_radio_write(), b43_phy::lp, b43_wldev::phy, b43_phy_lp::rc_cap, and b43_phy::rev.
Referenced by lpphy_calibrate_rc(), lpphy_pr41573_workaround(), lpphy_rev0_1_rc_calib(), and lpphy_set_analog_filter().
static void lpphy_set_rx_gain (struct b43_wldev * dev, u32 gain) [static]
Definition at line 968 of file phy_lp.c.
References lpphy_enable_rx_gain_override(), lpphy_rev0_1_set_rx_gain(), lpphy_rev2plus_set_rx_gain(), b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_rx_iq_cal(), and lpphy_set_rx_gain_by_index().
static void lpphy_set_rx_gain_by_index (struct b43_wldev * dev, u16 idx) [static]
Definition at line 977 of file phy_lp.c.
References B43_LPTAB16, b43_lptab_read(), and lpphy_set_rx_gain().
Referenced by lpphy_loopback(), and lpphy_rev0_1_rc_calib().
static void lpphy_set_trsw_over (struct b43_wldev * dev, bool tx, bool rx) [static]
Definition at line 764 of file phy_lp.c.
References B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_VAL_0, b43_phy_maskset(), and b43_phy_set().
Referenced by lpphy_disable_crs(), lpphy_loopback(), and lpphy_rx_iq_cal().
static void lpphy_set_tssi_mux (struct b43_wldev * dev, enum tssi_mux_mode mode) [static]
Definition at line 1476 of file phy_lp.c.
References B2063_PA_CTL10, B2063_PA_SP1, B43_LPPHY_AFE_CTL_OVRVAL, b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM, b43_phy_set(), b43_radio_mask(), b43_radio_maskset(), b43_radio_set(), b43_radio_write(), B43_WARN_ON, TSSI_MUX_EXT, and TSSI_MUX_POSTPA.
Referenced by lpphy_tx_pctl_init_hw().
static void lpphy_set_tx_gains (struct b43_wldev * dev, struct lpphy_tx_gains gains) [static]
Definition at line 903 of file phy_lp.c.
References B43_LPPHY_TX_GAIN_CTL_OVERRIDE_VAL, b43_phy_maskset(), B43_PHY_OFDM, b43_phy_write(), lpphy_tx_gains::dac, lpphy_tx_gains::gm, lpphy_enable_tx_gain_override(), lpphy_get_pa_gain(), lpphy_set_dac_gain(), lpphy_tx_gains::pad, lpphy_tx_gains::pga, b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_papd_cal_txpwr(), lpphy_rev0_1_rc_calib(), lpphy_rx_iq_cal(), lpphy_set_tx_power_by_index(), and lpphy_tx_pctl_init_sw().
static void lpphy_set_tx_iqcc (struct b43_wldev * dev, u16 a, u16 b) [static]
Definition at line 1378 of file phy_lp.c.
References B43_LPTAB16, and b43_lptab_write_bulk().
Referenced by lpphy_set_tx_power_by_index().
static void lpphy_set_tx_power_by_index (struct b43_wldev * dev, u8 index) [static]
Definition at line 1387 of file phy_lp.c.
References B43_LPPHY_RF_PWR_OVERRIDE, B43_LPPHY_TX_GAIN_CTL_OVERRIDE_VAL, B43_LPPHY_TXPCTL_OFF, B43_LPPHY_TXPCTL_SW, B43_LPTAB16, B43_LPTAB32, b43_lptab_read(), b43_lptab_write(), b43_phy_maskset(), lpphy_tx_gains::dac, lpphy_tx_gains::gm, b43_phy::lp, lpphy_enable_tx_gain_override(), lpphy_read_tx_pctl_mode_from_hardware(), lpphy_set_bb_mult(), lpphy_set_dac_gain(), lpphy_set_pa_gain(), lpphy_set_tx_gains(), lpphy_set_tx_iqcc(), lpphy_set_tx_power_control(), lpphy_tx_gains::pad, lpphy_tx_gains::pga, b43_wldev::phy, b43_phy::rev, b43_phy_lp::tx_pwr_idx_over, and b43_phy_lp::txpctl_mode.
Referenced by lpphy_pr41573_workaround(), and lpphy_tx_pctl_init_hw().
static void lpphy_set_tx_power_control (struct b43_wldev * dev, enum b43_lpphy_txpctl_mode mode) [static]
Definition at line 1151 of file phy_lp.c.
References B43_LPPHY_TX_PWR_CTL_CMD, B43_LPPHY_TX_PWR_CTL_NNUM, B43_LPPHY_TXPCTL_HW, b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM, b43_phy_set(), b43_phy::lp, lpphy_disable_tx_gain_override(), lpphy_read_tx_pctl_mode_from_hardware(), lpphy_write_tx_pctl_mode_to_hardware(), b43_wldev::phy, b43_phy::rev, b43_phy_lp::tssi_idx, b43_phy_lp::tssi_npt, b43_phy_lp::tx_pwr_idx_over, and b43_phy_lp::txpctl_mode.
Referenced by lpphy_calibration(), lpphy_papd_cal_txpwr(), lpphy_pr41573_workaround(), lpphy_rev0_1_rc_calib(), and lpphy_set_tx_power_by_index().
static void lpphy_start_tx_tone (struct b43_wldev * dev, s32 freq, u16 max) [static]
Definition at line 1785 of file phy_lp.c.
References b43_cordic(), B43_LPTAB16, b43_lptab_write_bulk(), B43_WARN_ON, CORDIC_CONVERT, b43_c32::i, b43_phy::lp, lpphy_run_samples(), b43_wldev::phy, b43_c32::q, and b43_phy_lp::tx_tone_freq.
Referenced by lpphy_rx_iq_cal().
static void lpphy_stop_ddfs (struct b43_wldev * dev) [static]
Definition at line 983 of file phy_lp.c.
References B43_LPPHY_AFE_DDFS, B43_LPPHY_LP_PHY_CTL, and b43_phy_mask().
Referenced by lpphy_loopback(), lpphy_rev0_1_rc_calib(), and lpphy_run_ddfs().
static void lpphy_stop_tx_tone (struct b43_wldev * dev) [static]
Definition at line 1818 of file phy_lp.c.
References B43_LPPHY_A_PHY_CTL_ADDR, B43_LPPHY_SMPL_PLAY_COUNT, b43_phy_mask(), b43_phy_read(), b43_phy::lp, b43_wldev::phy, and b43_phy_lp::tx_tone_freq.
Referenced by lpphy_rx_iq_cal().
static void lpphy_sync_stx (struct b43_wldev * dev) [static]
Definition at line 669 of file phy_lp.c.
References b43_phy_maskset(), B43_PHY_OFDM, b43_radio_read(), lpphy_stx_table_entry::mask, lpphy_stx_table_entry::phy_offset, lpphy_stx_table_entry::phy_shift, lpphy_stx_table_entry::rf_addr, and lpphy_stx_table_entry::rf_shift.
Referenced by lpphy_radio_init().
static void lpphy_table_init (struct b43_wldev * dev) [static]
Definition at line 200 of file phy_lp.c.
References b43_lpphy_op_get_default_chan(), channel2freq_lp(), lpphy_adjust_gain_table(), lpphy_init_tx_gain_table(), lpphy_rev0_1_table_init(), lpphy_rev2plus_table_init(), b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_baseband_init(), and lpphy_pr41573_workaround().
static void lpphy_tx_pctl_init (struct b43_wldev * dev) [static]
Definition at line 1573 of file phy_lp.c.
References lpphy_tx_pctl_init_hw(), and lpphy_tx_pctl_init_sw().
Referenced by b43_lpphy_op_init(), and lpphy_pr41573_workaround().
static void lpphy_tx_pctl_init_hw (struct b43_wldev * dev) [static]
Definition at line 1495 of file phy_lp.c.
References B2063_IQ_CALIB_CTL2, b43_dummy_transmission(), B43_LPPHY_LP_PHY_CTL, B43_LPPHY_RF_OVERRIDE_0, B43_LPPHY_RF_OVERRIDE_VAL_0, B43_LPPHY_TX_PWR_CTL_CMD, B43_LPPHY_TX_PWR_CTL_CMD_MODE, B43_LPPHY_TX_PWR_CTL_CMD_MODE_OFF, B43_LPPHY_TX_PWR_CTL_CMD_MODE_SW, B43_LPPHY_TX_PWR_CTL_DELTAPWR_LIMIT, B43_LPPHY_TX_PWR_CTL_IDLETSSI, B43_LPPHY_TX_PWR_CTL_NNUM, B43_LPPHY_TX_PWR_CTL_STAT, B43_LPTAB32, b43_lptab_write(), b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM, b43_phy_read(), b43_phy_write(), b43_radio_maskset(), lpphy_set_tssi_mux(), lpphy_set_tx_power_by_index(), b43_wldev::phy, b43_phy::rev, and TSSI_MUX_POSTPA.
Referenced by lpphy_tx_pctl_init().
static void lpphy_tx_pctl_init_sw (struct b43_wldev * dev) [static]
Definition at line 1553 of file phy_lp.c.
References b43_current_band(), lpphy_tx_gains::dac, lpphy_tx_gains::gm, lpphy_set_bb_mult(), lpphy_set_tx_gains(), lpphy_tx_gains::pad, lpphy_tx_gains::pga, and b43_wldev::wl.
Referenced by lpphy_tx_pctl_init().
static void lpphy_write_tx_pctl_mode_to_hardware (struct b43_wldev * dev) [static]
Definition at line 1128 of file phy_lp.c.
References B43_LPPHY_TX_PWR_CTL_CMD, B43_LPPHY_TX_PWR_CTL_CMD_MODE, B43_LPPHY_TX_PWR_CTL_CMD_MODE_HW, B43_LPPHY_TX_PWR_CTL_CMD_MODE_OFF, B43_LPPHY_TX_PWR_CTL_CMD_MODE_SW, B43_LPPHY_TXPCTL_HW, B43_LPPHY_TXPCTL_OFF, B43_LPPHY_TXPCTL_SW, b43_phy_maskset(), B43_WARN_ON, b43_phy::lp, b43_wldev::phy, and b43_phy_lp::txpctl_mode.
Referenced by lpphy_set_tx_power_control().
Variable Documentation
struct b206x_channel b2062_chantbl[] [static]
Definition at line 2044 of file phy_lp.c.
struct b206x_channel b2063_chantbl[] [static]
Definition at line 2200 of file phy_lp.c.
struct b43_phy_operations b43_phyops_lp
Initial value:
 {
        .allocate               = b43_lpphy_op_allocate,
        .free                   = b43_lpphy_op_free,
        .prepare_structs        = b43_lpphy_op_prepare_structs,
        .init                   = b43_lpphy_op_init,
        .phy_read               = b43_lpphy_op_read,
        .phy_write              = b43_lpphy_op_write,
        .phy_maskset            = b43_lpphy_op_maskset,
        .radio_read             = b43_lpphy_op_radio_read,
        .radio_write            = b43_lpphy_op_radio_write,
        .software_rfkill        = b43_lpphy_op_software_rfkill,
        .switch_analog          = b43_lpphy_op_switch_analog,
        .switch_channel         = b43_lpphy_op_switch_channel,
        .get_default_chan       = b43_lpphy_op_get_default_chan,
        .set_rx_antenna         = b43_lpphy_op_set_rx_antenna,
        .recalc_txpower         = b43_lpphy_op_recalc_txpower,
        .adjust_txpower         = b43_lpphy_op_adjust_txpower,
        .pwork_15sec            = b43_lpphy_op_pwork_15sec,
        .pwork_60sec            = lpphy_calibration,
}
Definition at line 2717 of file phy_lp.c.
Referenced by b43_phy_allocate().
struct lpphy_rx_iq_comp lpphy_5354_iq_table[] [static]
Initial value:
 {
        { .chan = 1, .c1 = -66, .c0 = 15, },
        { .chan = 2, .c1 = -66, .c0 = 15, },
        { .chan = 3, .c1 = -66, .c0 = 15, },
        { .chan = 4, .c1 = -66, .c0 = 15, },
        { .chan = 5, .c1 = -66, .c0 = 15, },
        { .chan = 6, .c1 = -66, .c0 = 15, },
        { .chan = 7, .c1 = -66, .c0 = 14, },
        { .chan = 8, .c1 = -66, .c0 = 14, },
        { .chan = 9, .c1 = -66, .c0 = 14, },
        { .chan = 10, .c1 = -66, .c0 = 14, },
        { .chan = 11, .c1 = -66, .c0 = 14, },
        { .chan = 12, .c1 = -66, .c0 = 13, },
        { .chan = 13, .c1 = -66, .c0 = 13, },
        { .chan = 14, .c1 = -66, .c0 = 13, },
}
Definition at line 1638 of file phy_lp.c.
struct lpphy_rx_iq_comp lpphy_rev0_1_iq_table[] [static]
Definition at line 1655 of file phy_lp.c.
struct lpphy_rx_iq_comp lpphy_rev2plus_iq_comp [static]
Initial value:
 {
        .chan = 0,
        .c1 = -64,
        .c0 = 0,
}
Definition at line 1709 of file phy_lp.c.
struct lpphy_stx_table_entry lpphy_stx_table[] [static]
Definition at line 637 of file phy_lp.c.