CompatWireless3.2: drivers/net/wireless/b43/phy_ht.c File Reference
drivers/net/wireless/b43/phy_ht.c File Reference
#include <linux/slab.h>
#include "b43.h"
#include "phy_ht.h"
#include "tables_phy_ht.h"
#include <linux/types.h>
#include "main.h"
Functions
static void b43_radio_2059_channel_setup (struct b43_wldev *dev, const struct b43_phy_ht_channeltab_e_radio2059 *e)
static void b43_radio_2059_init (struct b43_wldev *dev)
static void b43_phy_ht_zero_extg (struct b43_wldev *dev)
static void b43_phy_ht_afe_unk1 (struct b43_wldev *dev)
static void b43_phy_ht_force_rf_sequence (struct b43_wldev *dev, u16 rf_seq)
static void b43_phy_ht_read_clip_detection (struct b43_wldev *dev, u16 *clip_st)
static void b43_phy_ht_bphy_init (struct b43_wldev *dev)
static void b43_phy_ht_channel_setup (struct b43_wldev *dev, const struct b43_phy_ht_channeltab_e_phy *e, struct ieee80211_channel *new_channel)
static int b43_phy_ht_set_channel (struct b43_wldev *dev, struct ieee80211_channel *channel, enum nl80211_channel_type channel_type)
static int b43_phy_ht_op_allocate (struct b43_wldev *dev)
static void b43_phy_ht_op_prepare_structs (struct b43_wldev *dev)
static int b43_phy_ht_op_init (struct b43_wldev *dev)
static void b43_phy_ht_op_free (struct b43_wldev *dev)
static void b43_phy_ht_op_software_rfkill (struct b43_wldev *dev, bool blocked)
static void b43_phy_ht_op_switch_analog (struct b43_wldev *dev, bool on)
static int b43_phy_ht_op_switch_channel (struct b43_wldev *dev, unsigned int new_channel)
static unsigned int b43_phy_ht_op_get_default_chan (struct b43_wldev *dev)
static u16 b43_phy_ht_op_read (struct b43_wldev *dev, u16 reg)
static void b43_phy_ht_op_write (struct b43_wldev *dev, u16 reg, u16 value)
static void b43_phy_ht_op_maskset (struct b43_wldev *dev, u16 reg, u16 mask, u16 set)
static u16 b43_phy_ht_op_radio_read (struct b43_wldev *dev, u16 reg)
static void b43_phy_ht_op_radio_write (struct b43_wldev *dev, u16 reg, u16 value)
static enum b43_txpwr_result b43_phy_ht_op_recalc_txpower (struct b43_wldev *dev, bool ignore_tssi)
static void b43_phy_ht_op_adjust_txpower (struct b43_wldev *dev)
Variables
struct b43_phy_operations b43_phyops_ht
Function Documentation
static void b43_phy_ht_afe_unk1 (struct b43_wldev * dev) [static]
Definition at line 175 of file phy_ht.c.
References B43_HTTAB16, b43_httab_write(), B43_PHY_HT_AFE_CTL1, B43_PHY_HT_AFE_CTL2, B43_PHY_HT_AFE_CTL3, B43_PHY_HT_AFE_CTL4, B43_PHY_HT_AFE_CTL5, B43_PHY_HT_AFE_CTL6, b43_phy_mask(), and b43_phy_set().
Referenced by b43_phy_ht_op_init().
static void b43_phy_ht_bphy_init (struct b43_wldev * dev) [static]
Definition at line 224 of file phy_ht.c.
References B43_PHY_N_BMODE, and b43_phy_write().
Referenced by b43_phy_ht_op_init().
static void b43_phy_ht_channel_setup (struct b43_wldev * dev, const struct b43_phy_ht_channeltab_e_phy * e, struct ieee80211_channel * new_channel) [static]
Definition at line 246 of file phy_ht.c.
References B43_HTTAB16, B43_HTTAB32, B43_HTTAB8, b43_httab_read(), b43_httab_write(), B43_PHY_EXTG, B43_PHY_HT_BANDCTL, B43_PHY_HT_BW1, B43_PHY_HT_BW2, B43_PHY_HT_BW3, B43_PHY_HT_BW4, B43_PHY_HT_BW5, B43_PHY_HT_BW6, b43_phy_mask(), b43_phy_read(), b43_phy_write(), b43_phy_ht_channeltab_e_phy::bw1, b43_phy_ht_channeltab_e_phy::bw2, b43_phy_ht_channeltab_e_phy::bw3, b43_phy_ht_channeltab_e_phy::bw4, b43_phy_ht_channeltab_e_phy::bw5, and b43_phy_ht_channeltab_e_phy::bw6.
Referenced by b43_phy_ht_set_channel().
static void b43_phy_ht_force_rf_sequence (struct b43_wldev * dev, u16 rf_seq) [static]
Definition at line 196 of file phy_ht.c.
References B43_PHY_HT_RF_SEQ_MODE, B43_PHY_HT_RF_SEQ_STATUS, B43_PHY_HT_RF_SEQ_TRIG, b43_phy_read(), b43_phy_set(), b43_phy_write(), b43err(), and b43_wldev::wl.
Referenced by b43_phy_ht_op_init().
static void b43_phy_ht_op_adjust_txpower (struct b43_wldev * dev) [static]
Definition at line 594 of file phy_ht.c.
static int b43_phy_ht_op_allocate (struct b43_wldev * dev) [static]
Definition at line 324 of file phy_ht.c.
References b43_phy::ht, and b43_wldev::phy.
static void b43_phy_ht_op_free (struct b43_wldev * dev) [static]
Definition at line 468 of file phy_ht.c.
References b43_phy::ht, and b43_wldev::phy.
static unsigned int b43_phy_ht_op_get_default_chan (struct b43_wldev * dev) [static]
Definition at line 541 of file phy_ht.c.
References b43_current_band(), and b43_wldev::wl.
static int b43_phy_ht_op_init (struct b43_wldev * dev) [static]
Definition at line 344 of file phy_ht.c.
References b43_current_band(), B43_HTTAB16, B43_HTTAB32, b43_httab_0x1a_0xc0_late, B43_HTTAB_1A_C0_LATE_SIZE, b43_httab_read(), b43_httab_write(), b43_httab_write_bulk(), b43_httab_write_few(), b43_mac_phy_clock_set(), B43_PHY_EXTG, b43_phy_force_clock(), B43_PHY_HT_AFE_CTL1, B43_PHY_HT_AFE_CTL3, B43_PHY_HT_AFE_CTL5, b43_phy_ht_afe_unk1(), B43_PHY_HT_BBCFG, B43_PHY_HT_BBCFG_RSTCCA, b43_phy_ht_bphy_init(), b43_phy_ht_force_rf_sequence(), b43_phy_ht_read_clip_detection(), B43_PHY_HT_RF_SEQ_TRIG_RST2RX, B43_PHY_HT_RF_SEQ_TRIG_RX2TX, b43_phy_ht_tables_init(), b43_phy_ht_zero_extg(), b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM, b43_phy_read(), b43_phy_set(), b43_phy_write(), and b43_wldev::wl.
static void b43_phy_ht_op_maskset (struct b43_wldev * dev, u16 reg, u16 mask, u16 set) [static]
Definition at line 564 of file phy_ht.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), and b43_write16().
static void b43_phy_ht_op_prepare_structs (struct b43_wldev * dev) [static]
Definition at line 336 of file phy_ht.c.
References b43_phy::ht, and b43_wldev::phy.
static u16 b43_phy_ht_op_radio_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 572 of file phy_ht.c.
References B43_MMIO_RADIO24_CONTROL, B43_MMIO_RADIO24_DATA, b43_read16(), and b43_write16().
static void b43_phy_ht_op_radio_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 581 of file phy_ht.c.
References B43_MMIO_RADIO24_CONTROL, B43_MMIO_RADIO24_DATA, and b43_write16().
static u16 b43_phy_ht_op_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 552 of file phy_ht.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), and b43_write16().
static enum b43_txpwr_result b43_phy_ht_op_recalc_txpower (struct b43_wldev * dev, bool ignore_tssi) [static]
Definition at line 589 of file phy_ht.c.
References B43_TXPWR_RES_DONE.
static void b43_phy_ht_op_software_rfkill (struct b43_wldev * dev, bool blocked) [static]
Definition at line 478 of file phy_ht.c.
References B43_MACCTL_ENABLED, B43_MMIO_MACCTL, B43_PHY_HT_RF_CTL1, b43_phy_mask(), b43_phy_maskset(), b43_radio_2059_init(), b43_read32(), b43_switch_channel(), B43_WARN_ON, b43err(), b43_phy::channel, b43_wldev::phy, b43_phy::radio_ver, and b43_wldev::wl.
static void b43_phy_ht_op_switch_analog (struct b43_wldev * dev, bool on) [static]
Definition at line 506 of file phy_ht.c.
References B43_PHY_HT_AFE_CTL1, B43_PHY_HT_AFE_CTL2, B43_PHY_HT_AFE_CTL3, B43_PHY_HT_AFE_CTL4, B43_PHY_HT_AFE_CTL5, B43_PHY_HT_AFE_CTL6, and b43_phy_write().
static int b43_phy_ht_op_switch_channel (struct b43_wldev * dev, unsigned int new_channel) [static]
Definition at line 525 of file phy_ht.c.
References b43_current_band(), b43_phy_ht_set_channel(), b43_wl::hw, and b43_wldev::wl.
static void b43_phy_ht_op_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 558 of file phy_ht.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, and b43_write16().
static void b43_phy_ht_read_clip_detection (struct b43_wldev * dev, u16 * clip_st) [static]
Definition at line 217 of file phy_ht.c.
References B43_PHY_HT_C1_CLIP1THRES, B43_PHY_HT_C2_CLIP1THRES, B43_PHY_HT_C3_CLIP1THRES, and b43_phy_read().
Referenced by b43_phy_ht_op_init().
static int b43_phy_ht_set_channel (struct b43_wldev * dev, struct ieee80211_channel * channel, enum nl80211_channel_type channel_type) [static]
Definition at line 290 of file phy_ht.c.
References b43_phy_ht_channel_setup(), b43_phy_ht_get_channeltab_e_r2059(), b43_radio_2059_channel_setup(), b43_wldev::phy, b43_phy_ht_channeltab_e_radio2059::phy_regs, and b43_phy::radio_ver.
Referenced by b43_phy_ht_op_switch_channel().
static void b43_phy_ht_zero_extg (struct b43_wldev * dev) [static]
Definition at line 160 of file phy_ht.c.
References B43_PHY_EXTG, and b43_phy_write().
Referenced by b43_phy_ht_op_init().
static void b43_radio_2059_channel_setup (struct b43_wldev * dev, const struct b43_phy_ht_channeltab_e_radio2059 * e) [static]
Definition at line 37 of file phy_ht.c.
References b43_radio_mask(), b43_radio_set(), b43_radio_write(), R2059_RXRX1, R2059_TXRX0, b43_phy_ht_channeltab_e_radio2059::radio_rxtx4a, b43_phy_ht_channeltab_e_radio2059::radio_rxtx58, b43_phy_ht_channeltab_e_radio2059::radio_rxtx5a, b43_phy_ht_channeltab_e_radio2059::radio_rxtx6a, b43_phy_ht_channeltab_e_radio2059::radio_rxtx6d, b43_phy_ht_channeltab_e_radio2059::radio_rxtx6e, b43_phy_ht_channeltab_e_radio2059::radio_rxtx92, b43_phy_ht_channeltab_e_radio2059::radio_rxtx98, b43_phy_ht_channeltab_e_radio2059::radio_syn16, b43_phy_ht_channeltab_e_radio2059::radio_syn17, b43_phy_ht_channeltab_e_radio2059::radio_syn22, b43_phy_ht_channeltab_e_radio2059::radio_syn25, b43_phy_ht_channeltab_e_radio2059::radio_syn27, b43_phy_ht_channeltab_e_radio2059::radio_syn28, b43_phy_ht_channeltab_e_radio2059::radio_syn29, b43_phy_ht_channeltab_e_radio2059::radio_syn2c, b43_phy_ht_channeltab_e_radio2059::radio_syn2d, b43_phy_ht_channeltab_e_radio2059::radio_syn37, b43_phy_ht_channeltab_e_radio2059::radio_syn41, b43_phy_ht_channeltab_e_radio2059::radio_syn43, b43_phy_ht_channeltab_e_radio2059::radio_syn47, b43_phy_ht_channeltab_e_radio2059::radio_syn4a, b43_phy_ht_channeltab_e_radio2059::radio_syn58, b43_phy_ht_channeltab_e_radio2059::radio_syn5a, b43_phy_ht_channeltab_e_radio2059::radio_syn6a, b43_phy_ht_channeltab_e_radio2059::radio_syn6d, b43_phy_ht_channeltab_e_radio2059::radio_syn6e, b43_phy_ht_channeltab_e_radio2059::radio_syn92, and b43_phy_ht_channeltab_e_radio2059::radio_syn98.
Referenced by b43_phy_ht_set_channel().
static void b43_radio_2059_init (struct b43_wldev * dev) [static]
Definition at line 88 of file phy_ht.c.
References b43_radio_mask(), b43_radio_maskset(), b43_radio_read(), b43_radio_set(), b43_radio_write(), b43err(), R2059_ALL, R2059_RXRX1, R2059_SYN, R2059_TXRX0, and b43_wldev::wl.
Referenced by b43_phy_ht_op_software_rfkill().
Variable Documentation
struct b43_phy_operations b43_phyops_ht
Initial value:
 {
        .allocate               = b43_phy_ht_op_allocate,
        .free                   = b43_phy_ht_op_free,
        .prepare_structs        = b43_phy_ht_op_prepare_structs,
        .init                   = b43_phy_ht_op_init,
        .phy_read               = b43_phy_ht_op_read,
        .phy_write              = b43_phy_ht_op_write,
        .phy_maskset            = b43_phy_ht_op_maskset,
        .radio_read             = b43_phy_ht_op_radio_read,
        .radio_write            = b43_phy_ht_op_radio_write,
        .software_rfkill        = b43_phy_ht_op_software_rfkill,
        .switch_analog          = b43_phy_ht_op_switch_analog,
        .switch_channel         = b43_phy_ht_op_switch_channel,
        .get_default_chan       = b43_phy_ht_op_get_default_chan,
        .recalc_txpower         = b43_phy_ht_op_recalc_txpower,
        .adjust_txpower         = b43_phy_ht_op_adjust_txpower,
}
Definition at line 602 of file phy_ht.c.
Referenced by b43_phy_allocate().