CompatWireless3.2: drivers/net/wireless/b43/phy_g.c File Reference
drivers/net/wireless/b43/phy_g.c File Reference
#include "b43.h"
#include "phy_g.h"
#include "phy_common.h"
#include "lo.h"
#include "main.h"
#include <linux/bitrev.h>
#include <linux/slab.h>
Data Structures
struct init2050_saved_values
Defines
#define bitrev4(tmp) (bitrev8(tmp) >> 4)
#define phy_stacksave(offset)
#define phy_stackrestore(offset)
#define radio_stacksave(offset)
#define radio_stackrestore(offset)
#define ofdmtab_stacksave(table, offset)
#define ofdmtab_stackrestore(table, offset)
#define LPD(L, P, D) (((L) << 2) | ((P) << 1) | ((D) << 0))
Functions
static void b43_calc_nrssi_threshold (struct b43_wldev *dev)
static u16 channel2freq_bg (u8 channel)
static void generate_rfatt_list (struct b43_wldev *dev, struct b43_rfatt_list *list)
static void generate_bbatt_list (struct b43_wldev *dev, struct b43_bbatt_list *list)
static void b43_shm_clear_tssi (struct b43_wldev *dev)
static void b43_synth_pu_workaround (struct b43_wldev *dev, u8 channel)
void b43_gphy_set_baseband_attenuation (struct b43_wldev *dev, u16 baseband_attenuation)
static void b43_set_txpower_g (struct b43_wldev *dev, const struct b43_bbatt *bbatt, const struct b43_rfatt *rfatt, u8 tx_control)
static void b43_gphy_tssi_power_lt_init (struct b43_wldev *dev)
static void b43_gphy_gain_lt_init (struct b43_wldev *dev)
static void b43_set_all_gains (struct b43_wldev *dev, s16 first, s16 second, s16 third)
static void b43_set_original_gains (struct b43_wldev *dev)
static void b43_nrssi_hw_write (struct b43_wldev *dev, u16 offset, s16 val)
static s16 b43_nrssi_hw_read (struct b43_wldev *dev, u16 offset)
static void b43_nrssi_hw_update (struct b43_wldev *dev, u16 val)
static void b43_nrssi_mem_update (struct b43_wldev *dev)
static void b43_calc_nrssi_offset (struct b43_wldev *dev)
static void b43_calc_nrssi_slope (struct b43_wldev *dev)
static void _stack_save (u32 *_stackptr, size_t *stackidx, u8 id, u16 offset, u16 value)
static u16 _stack_restore (u32 *stackptr, u8 id, u16 offset)
static void b43_radio_interference_mitigation_enable (struct b43_wldev *dev, int mode)
static void b43_radio_interference_mitigation_disable (struct b43_wldev *dev, int mode)
static u16 b43_radio_core_calibration_value (struct b43_wldev *dev)
static u16 radio2050_rfover_val (struct b43_wldev *dev, u16 phy_register, unsigned int lpd)
static u16 b43_radio_init2050 (struct b43_wldev *dev)
static void b43_phy_initb5 (struct b43_wldev *dev)
static void b43_phy_initb6 (struct b43_wldev *dev)
static void b43_calc_loopback_gain (struct b43_wldev *dev)
static void b43_hardware_pctl_early_init (struct b43_wldev *dev)
static void b43_hardware_pctl_init_gphy (struct b43_wldev *dev)
static void b43_phy_init_pctl (struct b43_wldev *dev)
static void b43_phy_initg (struct b43_wldev *dev)
void b43_gphy_channel_switch (struct b43_wldev *dev, unsigned int channel, bool synthetic_pu_workaround)
static void default_baseband_attenuation (struct b43_wldev *dev, struct b43_bbatt *bb)
static void default_radio_attenuation (struct b43_wldev *dev, struct b43_rfatt *rf)
static u16 default_tx_control (struct b43_wldev *dev)
static u8 b43_gphy_aci_detect (struct b43_wldev *dev, u8 channel)
static u8 b43_gphy_aci_scan (struct b43_wldev *dev)
static s32 b43_tssi2dbm_ad (s32 num, s32 den)
static s8 b43_tssi2dbm_entry (s8 entry[], u8 index, s16 pab0, s16 pab1, s16 pab2)
u8 * b43_generate_dyn_tssi2dbm_tab (struct b43_wldev *dev, s16 pab0, s16 pab1, s16 pab2)
static int b43_gphy_init_tssi2dbm_table (struct b43_wldev *dev)
static int b43_gphy_op_allocate (struct b43_wldev *dev)
static void b43_gphy_op_prepare_structs (struct b43_wldev *dev)
static void b43_gphy_op_free (struct b43_wldev *dev)
static int b43_gphy_op_prepare_hardware (struct b43_wldev *dev)
static int b43_gphy_op_init (struct b43_wldev *dev)
static void b43_gphy_op_exit (struct b43_wldev *dev)
static u16 b43_gphy_op_read (struct b43_wldev *dev, u16 reg)
static void b43_gphy_op_write (struct b43_wldev *dev, u16 reg, u16 value)
static u16 b43_gphy_op_radio_read (struct b43_wldev *dev, u16 reg)
static void b43_gphy_op_radio_write (struct b43_wldev *dev, u16 reg, u16 value)
static bool b43_gphy_op_supports_hwpctl (struct b43_wldev *dev)
static void b43_gphy_op_software_rfkill (struct b43_wldev *dev, bool blocked)
static int b43_gphy_op_switch_channel (struct b43_wldev *dev, unsigned int new_channel)
static unsigned int b43_gphy_op_get_default_chan (struct b43_wldev *dev)
static void b43_gphy_op_set_rx_antenna (struct b43_wldev *dev, int antenna)
static int b43_gphy_op_interf_mitigation (struct b43_wldev *dev, enum b43_interference_mitigation mode)
static s8 b43_gphy_estimate_power_out (struct b43_wldev *dev, s8 tssi)
static void b43_put_attenuation_into_ranges (struct b43_wldev *dev, int *_bbatt, int *_rfatt)
static void b43_gphy_op_adjust_txpower (struct b43_wldev *dev)
static enum b43_txpwr_result b43_gphy_op_recalc_txpower (struct b43_wldev *dev, bool ignore_tssi)
static void b43_gphy_op_pwork_15sec (struct b43_wldev *dev)
static void b43_gphy_op_pwork_60sec (struct b43_wldev *dev)
Variables
static const s8 b43_tssi2dbm_g_table []
static const u8 b43_radio_channel_codes_bg []
struct b43_phy_operations b43_phyops_g
Define Documentation
#define bitrev4 (tmp) (bitrev8(tmp) >> 4)
Definition at line 69 of file phy_g.c.
Referenced by b43_radio_init2050(), and b43_radio_interference_mitigation_enable().
#define LPD (L, P, D) (((L) << 2) | ((P) << 1) | ((D) << 0))
Definition at line 1111 of file phy_g.c.
Referenced by b43_radio_init2050(), and radio2050_rfover_val().
#define ofdmtab_stackrestore (table, offset)
Value:
do {                                                    \
                b43_ofdmtab_write16(dev, (table),       (offset),       \
                                  _stack_restore(stack, 0x3,    \
                                                 (offset)|(table)));    \
        } while (0)
Definition at line 830 of file phy_g.c.
Referenced by b43_radio_interference_mitigation_disable().
#define ofdmtab_stacksave (table, offset)
Value:
do {                                                    \
                _stack_save(stack, &stackidx, 0x3, (offset)|(table),    \
                            b43_ofdmtab_read16(dev, (table), (offset)));        \
        } while (0)
Definition at line 825 of file phy_g.c.
Referenced by b43_radio_interference_mitigation_enable().
#define phy_stackrestore (offset)
Value:
do {                                                    \
                b43_phy_write(dev, (offset),            \
                                  _stack_restore(stack, 0x1,    \
                                                 (offset)));    \
        } while (0)
Definition at line 808 of file phy_g.c.
Referenced by b43_radio_interference_mitigation_disable().
#define phy_stacksave (offset)
Value:
do {                                                    \
                _stack_save(stack, &stackidx, 0x1, (offset),    \
                            b43_phy_read(dev, (offset)));       \
        } while (0)
Definition at line 803 of file phy_g.c.
Referenced by b43_radio_interference_mitigation_enable().
#define radio_stackrestore (offset)
Value:
do {                                                            \
                b43_radio_write16(dev, (offset),                        \
                                      _stack_restore(stack, 0x2,        \
                                                     (offset)));        \
        } while (0)
Definition at line 819 of file phy_g.c.
Referenced by b43_radio_interference_mitigation_disable().
#define radio_stacksave (offset)
Value:
do {                                                            \
                _stack_save(stack, &stackidx, 0x2, (offset),            \
                            b43_radio_read16(dev, (offset)));   \
        } while (0)
Definition at line 814 of file phy_g.c.
Referenced by b43_radio_interference_mitigation_enable().
Function Documentation
static u16 _stack_restore (u32 * stackptr, u8 id, u16 offset) [static]
Definition at line 785 of file phy_g.c.
References B43_INTERFSTACK_SIZE, and B43_WARN_ON.
static void _stack_save (u32 * _stackptr, size_t * stackidx, u8 id, u16 offset, u16 value) [static]
Definition at line 771 of file phy_g.c.
References B43_INTERFSTACK_SIZE, and B43_WARN_ON.
static void b43_calc_loopback_gain (struct b43_wldev * dev) [static]
Definition at line 1707 of file phy_g.c.
References b43_bbatt::att, B43_BFL_EXTLNA, b43_gphy_set_baseband_attenuation(), B43_PHY_ANALOGOVER, B43_PHY_ANALOGOVERVAL, B43_PHY_CCK, B43_PHY_CCKBBANDCFG, B43_PHY_CRS0, B43_PHY_LO_CTL, B43_PHY_LO_LEAKAGE, B43_PHY_LO_MASK, b43_phy_mask(), b43_phy_maskset(), B43_PHY_PGACTL, b43_phy_read(), B43_PHY_RFOVER, B43_PHY_RFOVERVAL, b43_phy_set(), b43_phy_write(), b43_radio_mask(), b43_radio_maskset(), b43_radio_read16, b43_radio_write16, b43_phy_g::bbatt, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::g, b43_phy_g::max_lb_gain, b43_wldev::phy, b43_phy::radio_rev, b43_phy::rev, and b43_phy_g::trsw_rx_gain.
Referenced by b43_phy_initg().
static void b43_calc_nrssi_offset (struct b43_wldev * dev) [static]
Definition at line 421 of file phy_g.c.
References b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_radio_mask(), b43_radio_maskset(), b43_radio_read16, b43_radio_set(), b43_radio_write16, b43_set_all_gains(), b43_set_original_gains(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_calc_nrssi_slope().
static void b43_calc_nrssi_slope (struct b43_wldev * dev) [static]
Definition at line 568 of file phy_g.c.
References b43_calc_nrssi_offset(), b43_calc_nrssi_threshold(), B43_MMIO_CHANNEL_EXT, b43_nrssi_mem_update(), B43_PHY_G_CRS, B43_PHY_G_LO_CONTROL, b43_phy_mask(), b43_phy_maskset(), b43_phy_read(), b43_phy_set(), b43_phy_write(), B43_PHYTYPE_G, b43_radio_mask(), b43_radio_read16, b43_radio_set(), b43_radio_write16, b43_read16(), b43_set_all_gains(), b43_set_original_gains(), b43_synth_pu_workaround(), B43_WARN_ON, b43_write16(), b43_phy::channel, b43_phy::g, b43_phy_g::nrssi, b43_phy_g::nrssislope, b43_wldev::phy, b43_phy::radio_rev, b43_phy::rev, and b43_phy::type.
Referenced by b43_gphy_op_pwork_60sec(), b43_phy_initg(), b43_radio_interference_mitigation_disable(), and b43_radio_interference_mitigation_enable().
static void b43_calc_nrssi_threshold (struct b43_wldev * dev) [static]
Definition at line 710 of file phy_g.c.
References b43_phy_g::aci_enable, b43_phy_g::aci_wlan_automatic, B43_BFL_RSSI, B43_INTERFMODE_NONWLAN, b43_nrssi_hw_read(), b43_phy_maskset(), b43_phy_read(), b43_phy_write(), B43_PHYTYPE_G, B43_WARN_ON, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::g, b43_phy::gmode, b43_phy_g::interfmode, b43_phy_g::nrssi, b43_wldev::phy, and b43_phy::type.
Referenced by b43_calc_nrssi_slope(), b43_phy_initg(), b43_radio_interference_mitigation_disable(), and b43_radio_interference_mitigation_enable().
u8* b43_generate_dyn_tssi2dbm_tab (struct b43_wldev * dev, s16 pab0, s16 pab1, s16 pab2)
Definition at line 2352 of file phy_g.c.
References b43_tssi2dbm_entry(), b43err(), and b43_wldev::wl.
Referenced by b43_aphy_init_tssi2dbm_table(), and b43_gphy_init_tssi2dbm_table().
static u8 b43_gphy_aci_detect (struct b43_wldev * dev, u8 channel) [static]
Definition at line 2250 of file phy_g.c.
References b43_phy_g::aci_hw_rssi, b43_phy_read(), b43_phy_write(), b43_switch_channel(), b43_phy::g, and b43_wldev::phy.
Referenced by b43_gphy_aci_scan().
static u8 b43_gphy_aci_scan (struct b43_wldev * dev) [static]
Definition at line 2282 of file phy_g.c.
References b43_gphy_aci_detect(), B43_PHY_G_CRS, b43_phy_lock(), b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy_unlock(), B43_PHYTYPE_G, b43_radio_lock(), b43_radio_unlock(), b43_set_all_gains(), b43_set_original_gains(), b43_switch_channel(), b43_phy::channel, b43_wldev::phy, b43_phy::rev, and b43_phy::type.
Referenced by b43_gphy_op_pwork_15sec().
void b43_gphy_channel_switch (struct b43_wldev * dev, unsigned int channel, bool synthetic_pu_workaround)
Definition at line 2096 of file phy_g.c.
References B43_HF_ACPR, b43_hf_read(), b43_hf_write(), B43_MMIO_CHANNEL, B43_MMIO_CHANNEL_EXT, b43_read16(), b43_synth_pu_workaround(), b43_write16(), b43_bus_dev::bus_sprom, channel2freq_bg(), and b43_wldev::dev.
Referenced by b43_gphy_op_software_rfkill(), b43_gphy_op_switch_channel(), b43_phy_initb5(), b43_phy_initb6(), lo_measure_restore(), and lo_measure_setup().
static s8 b43_gphy_estimate_power_out (struct b43_wldev * dev, s8 tssi) [static]
Definition at line 2750 of file phy_g.c.
References b43_phy_g::cur_idle_tssi, b43_phy::g, b43_wldev::phy, b43_phy_g::tgt_idle_tssi, and b43_phy_g::tssi2dbm.
Referenced by b43_gphy_op_recalc_txpower().
static void b43_gphy_gain_lt_init (struct b43_wldev * dev) [static]
Definition at line 282 of file phy_g.c.
References b43_rfatt::att, b43_bbatt::att, b43_phy_write(), b43_txpower_lo_control::bbatt_list, b43_phy::g, b43_bbatt_list::len, b43_rfatt_list::len, b43_rfatt_list::list, b43_bbatt_list::list, b43_phy_g::lo_control, b43_wldev::phy, b43_phy::radio_rev, and b43_txpower_lo_control::rfatt_list.
Referenced by b43_hardware_pctl_init_gphy().
static int b43_gphy_init_tssi2dbm_table (struct b43_wldev * dev) [static]
Definition at line 2379 of file phy_g.c.
References b43_generate_dyn_tssi2dbm_tab(), b43_tssi2dbm_g_table, B43_WARN_ON, b43_bus_dev::bus_sprom, b43_bus_dev::chip_id, b43_wldev::dev, b43_phy_g::dyn_tssi_tbl, b43_phy::g, b43_wldev::phy, b43_phy::radio_ver, b43_phy_g::tgt_idle_tssi, and b43_phy_g::tssi2dbm.
Referenced by b43_gphy_op_allocate().
static void b43_gphy_op_adjust_txpower (struct b43_wldev * dev) [static]
Definition at line 2816 of file phy_g.c.
References b43_rfatt::att, b43_bbatt::att, B43_BFL_PACTRL, B43_DBG_XMITPOWER, b43_debug(), b43_mac_enable(), b43_mac_suspend(), b43_phy_lock(), b43_phy_unlock(), b43_put_attenuation_into_ranges(), b43_radio_lock(), b43_radio_unlock(), b43_set_txpower_g(), B43_TXCTL_PA2DB, B43_TXCTL_TXMIX, b43dbg(), b43_phy_g::bbatt, b43_phy_g::bbatt_delta, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::g, b43_wldev::phy, b43_phy::radio_rev, b43_phy::radio_ver, b43_phy_g::rfatt, b43_phy_g::rfatt_delta, b43_phy_g::tx_control, and b43_wldev::wl.
static int b43_gphy_op_allocate (struct b43_wldev * dev) [static]
Definition at line 2417 of file phy_g.c.
References b43_gphy_init_tssi2dbm_table(), b43_phy::g, b43_phy_g::lo_control, and b43_wldev::phy.
static void b43_gphy_op_exit (struct b43_wldev * dev) [static]
Definition at line 2551 of file phy_g.c.
References b43_lo_g_cleanup().
static void b43_gphy_op_free (struct b43_wldev * dev) [static]
Definition at line 2498 of file phy_g.c.
References b43_phy_g::dyn_tssi_tbl, b43_phy::g, b43_phy_g::lo_control, b43_wldev::phy, and b43_phy_g::tssi2dbm.
static unsigned int b43_gphy_op_get_default_chan (struct b43_wldev * dev) [static]
Definition at line 2645 of file phy_g.c.
static int b43_gphy_op_init (struct b43_wldev * dev) [static]
Definition at line 2544 of file phy_g.c.
References b43_phy_initg().
static int b43_gphy_op_interf_mitigation (struct b43_wldev * dev, enum b43_interference_mitigation mode) [static]
Definition at line 2703 of file phy_g.c.
References b43_phy_g::aci_enable, b43_phy_g::aci_hw_rssi, b43_phy_g::aci_wlan_automatic, B43_INTERFMODE_AUTOWLAN, B43_INTERFMODE_MANUALWLAN, B43_INTERFMODE_NONE, B43_INTERFMODE_NONWLAN, B43_PHYTYPE_G, b43_radio_interference_mitigation_disable(), b43_radio_interference_mitigation_enable(), B43_WARN_ON, b43_phy::g, b43_phy::gmode, b43_phy_g::interfmode, b43_wldev::phy, b43_phy::rev, and b43_phy::type.
static int b43_gphy_op_prepare_hardware (struct b43_wldev * dev) [static]
Definition at line 2514 of file phy_g.c.
References B43_MMIO_MACCTL, b43_phy_initg(), B43_PHYTYPE_G, b43_read32(), B43_WARN_ON, b43_wireless_core_reset(), b43_phy_g::bbatt, b43_txpower_lo_control::bbatt_list, default_baseband_attenuation(), default_radio_attenuation(), default_tx_control(), b43_phy::g, generate_bbatt_list(), generate_rfatt_list(), b43_phy::gmode, b43_phy_g::lo_control, b43_wldev::phy, b43_phy::rev, b43_phy_g::rfatt, b43_txpower_lo_control::rfatt_list, b43_phy_g::tx_control, and b43_phy::type.
static void b43_gphy_op_prepare_structs (struct b43_wldev * dev) [static]
Definition at line 2451 of file phy_g.c.
References b43_phy_g::average_tssi, B43_INTERFMODE_NONE, b43_txpower_lo_control::calib_list, b43_phy::g, b43_phy_g::initval, b43_phy_g::interfmode, b43_phy_g::lo_control, b43_phy_g::lofcal, b43_phy_g::minlowsig, b43_phy_g::nrssi, b43_phy_g::nrssi_lt, b43_phy_g::ofdmtab_addr_direction, b43_wldev::phy, b43_phy_g::tgt_idle_tssi, b43_phy_g::tssi2dbm, and b43_txpower_lo_control::tx_bias.
static void b43_gphy_op_pwork_15sec (struct b43_wldev * dev) [static]
Definition at line 2986 of file phy_g.c.
References b43_phy_g::aci_enable, b43_phy_g::aci_wlan_automatic, b43_gphy_aci_scan(), B43_INTERFMODE_MANUALWLAN, B43_INTERFMODE_NONE, B43_INTERFMODE_NONWLAN, b43_lo_g_maintanance_work(), b43_mac_enable(), b43_mac_suspend(), b43_phy::g, b43_phy_operations::interf_mitigation, b43_phy_g::interfmode, b43_phy::ops, b43_wldev::phy, and b43_phy::rev.
static void b43_gphy_op_pwork_60sec (struct b43_wldev * dev) [static]
Definition at line 3011 of file phy_g.c.
References B43_BFL_RSSI, b43_calc_nrssi_slope(), b43_mac_enable(), b43_mac_suspend(), b43_switch_channel(), b43_bus_dev::bus_sprom, b43_phy::channel, b43_wldev::dev, b43_wldev::phy, b43_phy::radio_rev, and b43_phy::radio_ver.
static u16 b43_gphy_op_radio_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 2568 of file phy_g.c.
References B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_LOW, b43_read16(), B43_WARN_ON, and b43_write16().
static void b43_gphy_op_radio_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 2579 of file phy_g.c.
References B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_LOW, B43_WARN_ON, and b43_write16().
static u16 b43_gphy_op_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 2556 of file phy_g.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), and b43_write16().
static enum b43_txpwr_result b43_gphy_op_recalc_txpower (struct b43_wldev * dev, bool ignore_tssi) [static]
Definition at line 2878 of file phy_g.c.
References b43_phy_g::average_tssi, B43_BFL_PACTRL, B43_DBG_XMITPOWER, b43_debug(), b43_gphy_estimate_power_out(), b43_phy_shm_tssi_read(), B43_PHYTYPE_G, B43_SHM_SH_TSSI_CCK, B43_SHM_SH_TSSI_OFDM_G, B43_TSSI_MAX, B43_TXPWR_RES_DONE, B43_TXPWR_RES_NEED_ADJUST, B43_WARN_ON, b43dbg(), b43warn(), b43_phy_g::bbatt_delta, b43_bus_dev::bus_sprom, b43_phy::desired_txpower, b43_wldev::dev, b43_phy::g, INT_TO_Q52, b43_wldev::phy, Q52_ARG, Q52_FMT, b43_phy_g::rfatt_delta, b43_phy::type, and b43_wldev::wl.
static void b43_gphy_op_set_rx_antenna (struct b43_wldev * dev, int antenna) [static]
Definition at line 2650 of file phy_g.c.
References B43_ANTENNA_AUTO0, B43_ANTENNA_AUTO1, B43_HF_ANTDIVHELP, b43_hf_read(), b43_hf_write(), B43_PHY_ADIVRELATED, B43_PHY_ANTDWELL, B43_PHY_ANTDWELL_AUTODIV1, B43_PHY_ANTWRSETT, B43_PHY_ANTWRSETT_ARXDIV, B43_PHY_BBANDCFG, B43_PHY_BBANDCFG_RXANT, B43_PHY_BBANDCFG_RXANT_SHIFT, B43_PHY_DIVSRCHGAINBACK, b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM61, B43_PHY_OFDM61_10, B43_PHY_OFDM9B, b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_wldev::phy, and b43_phy::rev.
static void b43_gphy_op_software_rfkill (struct b43_wldev * dev, bool blocked) [static]
Definition at line 2593 of file phy_g.c.
References b43_gphy_channel_switch(), b43_phy_read(), B43_PHY_RFOVER, B43_PHY_RFOVERVAL, b43_phy_write(), b43_phy::channel, b43_phy::g, b43_phy::gmode, b43_wldev::phy, b43_phy_g::radio_off_context, b43_phy::radio_on, b43_phy_g::rfover, b43_phy_g::rfoverval, and b43_phy_g::valid.
static bool b43_gphy_op_supports_hwpctl (struct b43_wldev * dev) [static]
Definition at line 2588 of file phy_g.c.
References b43_wldev::phy, and b43_phy::rev.
static int b43_gphy_op_switch_channel (struct b43_wldev * dev, unsigned int new_channel) [static]
Definition at line 2635 of file phy_g.c.
References b43_gphy_channel_switch().
static void b43_gphy_op_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 2562 of file phy_g.c.
References B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, and b43_write16().
void b43_gphy_set_baseband_attenuation (struct b43_wldev * dev, u16 baseband_attenuation)
Definition at line 198 of file phy_g.c.
References b43_phy::analog, B43_MMIO_PHY0, B43_PHY_DACCTL, b43_phy_maskset(), b43_read16(), b43_write16(), and b43_wldev::phy.
Referenced by b43_calc_loopback_gain(), b43_calibrate_lo_setting(), b43_set_txpower_g(), and lo_measure_txctl_values().
static void b43_gphy_tssi_power_lt_init (struct b43_wldev * dev) [static]
Definition at line 264 of file phy_g.c.
References b43_ofdmtab_write16(), b43_phy_write(), b43_phy::g, b43_wldev::phy, and b43_phy_g::tssi2dbm.
Referenced by b43_hardware_pctl_init_gphy().
static void b43_hardware_pctl_early_init (struct b43_wldev * dev) [static]
Definition at line 1861 of file phy_g.c.
References b43_has_hardware_pctl(), b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy_write(), b43_wldev::phy, b43_phy::radio_rev, and b43_phy::radio_ver.
Referenced by b43_phy_init_pctl().
static void b43_hardware_pctl_init_gphy (struct b43_wldev * dev) [static]
Definition at line 1892 of file phy_g.c.
References b43_gphy_dc_lt_init(), b43_gphy_gain_lt_init(), b43_gphy_tssi_power_lt_init(), b43_has_hardware_pctl(), B43_HF_HWPCTL, b43_hf_read(), b43_hf_write(), b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy_write(), B43_WARN_ON, b43_phy_g::cur_idle_tssi, b43_phy::g, b43_wldev::phy, b43_phy::rev, and b43_phy_g::tgt_idle_tssi.
Referenced by b43_phy_init_pctl().
static s16 b43_nrssi_hw_read (struct b43_wldev * dev, u16 offset) [static]
Definition at line 380 of file phy_g.c.
References B43_PHY_NRSSILT_CTRL, B43_PHY_NRSSILT_DATA, b43_phy_read(), and b43_phy_write().
Referenced by b43_calc_nrssi_threshold(), and b43_nrssi_hw_update().
static void b43_nrssi_hw_update (struct b43_wldev * dev, u16 val) [static]
Definition at line 391 of file phy_g.c.
References b43_nrssi_hw_read(), and b43_nrssi_hw_write().
Referenced by b43_phy_initg().
static void b43_nrssi_hw_write (struct b43_wldev * dev, u16 offset, s16 val) [static]
Definition at line 373 of file phy_g.c.
References B43_PHY_NRSSILT_CTRL, B43_PHY_NRSSILT_DATA, and b43_phy_write().
Referenced by b43_nrssi_hw_update().
static void b43_nrssi_mem_update (struct b43_wldev * dev) [static]
Definition at line 405 of file phy_g.c.
References b43_phy::g, b43_phy_g::nrssi, b43_phy_g::nrssi_lt, b43_phy_g::nrssislope, and b43_wldev::phy.
Referenced by b43_calc_nrssi_slope().
static void b43_phy_init_pctl (struct b43_wldev * dev) [static]
Definition at line 1922 of file phy_g.c.
References b43_phy::analog, b43_rfatt::att, b43_bbatt::att, B43_DEBUG, b43_dummy_transmission(), b43_hardware_pctl_early_init(), b43_hardware_pctl_init_gphy(), B43_MMIO_PHY0, B43_PHY_ITSSI, b43_phy_read(), b43_phy_write(), B43_PHYTYPE_G, b43_radio_mask(), b43_radio_maskset(), b43_read16(), b43_set_txpower_g(), b43_shm_clear_tssi(), B43_WARN_ON, b43_write16(), b43dbg(), b43_phy_g::bbatt, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_phy_g::cur_idle_tssi, b43_wldev::dev, b43_phy::g, b43_phy::gmode, b43_wldev::phy, b43_phy::radio_rev, b43_phy::radio_ver, b43_phy_g::rfatt, b43_phy_g::tgt_idle_tssi, b43_phy_g::tx_control, b43_phy::type, b43_rfatt::with_padmix, and b43_wldev::wl.
Referenced by b43_phy_initg().
static void b43_phy_initb5 (struct b43_wldev * dev) [static]
Definition at line 1492 of file phy_g.c.
References b43_phy::analog, b43_gphy_channel_switch(), B43_MMIO_PHY_RADIO, b43_phy_maskset(), B43_PHY_RADIO_BITFIELD, b43_phy_set(), b43_phy_write(), b43_radio_set(), b43_radio_write16, b43_read16(), b43_set_txpower_g(), b43_write16(), b43_wldev::bad_frames_preempt, b43_phy_g::bbatt, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_phy::channel, b43_wldev::dev, b43_phy::g, b43_phy::gmode, b43_wldev::phy, b43_phy::radio_ver, b43_phy::rev, b43_phy_g::rfatt, and b43_phy_g::tx_control.
Referenced by b43_phy_initg().
static void b43_phy_initb6 (struct b43_wldev * dev) [static]
Definition at line 1590 of file phy_g.c.
References b43_phy::analog, B43_BFL_ALTIQ, b43_gphy_channel_switch(), b43_hf_read(), B43_HF_TSSIRPSMW, b43_hf_write(), b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy_write(), B43_PHYTYPE_B, B43_PHYTYPE_G, b43_radio_maskset(), b43_radio_read16, b43_radio_set(), b43_radio_write16, b43_set_txpower_g(), B43_WARN_ON, b43_write16(), b43_phy_g::bbatt, b43_bus_dev::bus_sprom, b43_phy::channel, b43_wldev::dev, b43_phy::g, b43_wldev::phy, b43_phy::radio_rev, b43_phy_g::rfatt, b43_phy_g::tx_control, and b43_phy::type.
Referenced by b43_phy_initg().
static void b43_phy_initg (struct b43_wldev * dev) [static]
Definition at line 1990 of file phy_g.c.
References B43_BFL_PACTRL, B43_BFL_RSSI, b43_calc_loopback_gain(), b43_calc_nrssi_slope(), b43_calc_nrssi_threshold(), b43_lo_g_adjust(), b43_lo_g_init(), b43_nrssi_hw_update(), B43_PHY_ANALOGOVER, B43_PHY_ANALOGOVERVAL, B43_PHY_CCK, B43_PHY_CRS0, B43_PHY_EXTG, b43_phy_init_pctl(), b43_phy_inita(), b43_phy_initb5(), b43_phy_initb6(), B43_PHY_LO_MASK, b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM, B43_PHY_PGACTL, b43_phy_read(), B43_PHY_RFOVER, b43_phy_set(), B43_PHY_VERSION_OFDM, b43_phy_write(), B43_PHYVER_VERSION, b43_radio_init2050(), b43_radio_maskset(), b43_radio_read16, b43_radio_write16, B43_WARN_ON, b43_bus_dev::bus_sprom, b43_bus_dev::chip_id, b43_bus_dev::chip_pkg, b43_wldev::dev, b43_phy::g, b43_phy::gmode, has_loopback_gain, has_tx_magnification, b43_phy_g::initval, b43_phy_g::lo_control, b43_phy_g::nrssi, b43_wldev::phy, b43_phy::radio_rev, b43_phy::rev, b43_txpower_lo_control::tx_bias, and b43_txpower_lo_control::tx_magn.
Referenced by b43_gphy_op_init(), and b43_gphy_op_prepare_hardware().
static void b43_put_attenuation_into_ranges (struct b43_wldev * dev, int * _bbatt, int * _rfatt) [static]
Definition at line 2763 of file phy_g.c.
References b43_phy_g::bbatt, b43_txpower_lo_control::bbatt_list, b43_phy::g, b43_phy_g::lo_control, b43_bbatt_list::max_val, b43_rfatt_list::max_val, b43_bbatt_list::min_val, b43_rfatt_list::min_val, b43_wldev::phy, b43_phy_g::rfatt, and b43_txpower_lo_control::rfatt_list.
Referenced by b43_gphy_op_adjust_txpower().
static u16 b43_radio_core_calibration_value (struct b43_wldev * dev) [static]
Definition at line 1091 of file phy_g.c.
References b43_radio_read16.
Referenced by b43_radio_init2050().
static u16 b43_radio_init2050 (struct b43_wldev * dev) [static]
Definition at line 1257 of file phy_g.c.
References b43_phy::analog, B43_MMIO_CHANNEL_EXT, B43_MMIO_PHY_RADIO, B43_PHY_ANALOGOVER, B43_PHY_ANALOGOVERVAL, B43_PHY_CCK, B43_PHY_CLASSCTL, B43_PHY_CRS0, B43_PHY_LO_CTL, B43_PHY_LO_LEAKAGE, B43_PHY_LO_MASK, b43_phy_mask(), b43_phy_maskset(), B43_PHY_PGACTL, b43_phy_read(), B43_PHY_RFOVER, B43_PHY_RFOVERVAL, b43_phy_set(), B43_PHY_SYNCCTL, b43_phy_write(), B43_PHYTYPE_B, b43_radio_core_calibration_value(), b43_radio_maskset(), b43_radio_read16, b43_radio_set(), b43_radio_write16, b43_read16(), b43_synth_pu_workaround(), b43_write16(), bitrev4, b43_phy::channel, b43_phy::gmode, has_loopback_gain, LPD, b43_wldev::phy, init2050_saved_values::phy_analogover, init2050_saved_values::phy_analogoverval, init2050_saved_values::phy_cck_30, init2050_saved_values::phy_cck_58, init2050_saved_values::phy_cck_59, init2050_saved_values::phy_cck_5A, init2050_saved_values::phy_classctl, init2050_saved_values::phy_crs0, init2050_saved_values::phy_lo_ctl, init2050_saved_values::phy_lo_mask, init2050_saved_values::phy_pgactl, init2050_saved_values::phy_rfover, init2050_saved_values::phy_rfoverval, init2050_saved_values::phy_syncctl, radio2050_rfover_val(), init2050_saved_values::radio_43, init2050_saved_values::radio_51, init2050_saved_values::radio_52, b43_phy::radio_rev, init2050_saved_values::reg_3E6, init2050_saved_values::reg_3EC, init2050_saved_values::reg_3F4, b43_phy::rev, and b43_phy::type.
Referenced by b43_phy_initg().
static void b43_radio_interference_mitigation_disable (struct b43_wldev * dev, int mode) [static]
Definition at line 1004 of file phy_g.c.
References b43_phy_g::aci_enable, b43_calc_nrssi_slope(), b43_calc_nrssi_threshold(), B43_HF_ACIW, b43_hf_read(), b43_hf_write(), B43_INTERFMODE_MANUALWLAN, B43_INTERFMODE_NONWLAN, B43_PHY_G_CRS, b43_phy_mask(), B43_PHY_RADIO_BITFIELD, b43_phy_read(), b43_phy_set(), B43_WARN_ON, b43_wldev::bad_frames_preempt, b43_phy::g, b43_phy_g::interfstack, ofdmtab_stackrestore, b43_wldev::phy, phy_stackrestore, radio_stackrestore, and b43_phy::rev.
Referenced by b43_gphy_op_interf_mitigation().
static void b43_radio_interference_mitigation_enable (struct b43_wldev * dev, int mode) [static]
Definition at line 838 of file phy_g.c.
References b43_phy_g::aci_enable, b43_calc_nrssi_slope(), b43_calc_nrssi_threshold(), B43_HF_ACIW, b43_hf_read(), b43_hf_write(), B43_INTERFMODE_MANUALWLAN, B43_INTERFMODE_NONWLAN, b43_ofdmtab_write16(), B43_PHY_G_CRS, b43_phy_mask(), b43_phy_maskset(), B43_PHY_RADIO_BITFIELD, b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_radio_read16, b43_radio_write16, B43_WARN_ON, bitrev4, b43_phy::g, b43_phy_g::interfstack, ofdmtab_stacksave, b43_wldev::phy, phy_stacksave, radio_stacksave, and b43_phy::rev.
Referenced by b43_gphy_op_interf_mitigation().
static void b43_set_all_gains (struct b43_wldev * dev, s16 first, s16 second, s16 third) [static]
Definition at line 308 of file phy_g.c.
References b43_dummy_transmission(), B43_OFDMTAB_GAINX, B43_OFDMTAB_GAINX_R1, b43_ofdmtab_write16(), b43_phy_maskset(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), and b43_gphy_aci_scan().
static void b43_set_original_gains (struct b43_wldev * dev) [static]
Definition at line 340 of file phy_g.c.
References b43_dummy_transmission(), B43_OFDMTAB_GAINX, B43_OFDMTAB_GAINX_R1, b43_ofdmtab_write16(), b43_phy_maskset(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), and b43_gphy_aci_scan().
static void b43_set_txpower_g (struct b43_wldev * dev, const struct b43_bbatt * bbatt, const struct b43_rfatt * rfatt, u8 tx_control) [static]
Definition at line 215 of file phy_g.c.
References b43_rfatt::att, b43_bbatt::att, B43_DBG_XMITPOWER, b43_debug(), b43_gphy_set_baseband_attenuation(), b43_lo_g_adjust(), b43_radio_maskset(), b43_radio_write16, B43_SHM_SH_RFATT, B43_SHM_SHARED, b43_shm_write16(), B43_TXCTL_TXMIX, b43dbg(), b43_phy_g::bbatt, b43_phy::g, has_tx_magnification, b43_phy_g::lo_control, b43_wldev::phy, b43_phy::radio_rev, b43_phy::radio_ver, b43_phy_g::rfatt, b43_txpower_lo_control::tx_bias, b43_phy_g::tx_control, b43_txpower_lo_control::tx_magn, b43_rfatt::with_padmix, and b43_wldev::wl.
Referenced by b43_gphy_op_adjust_txpower(), b43_phy_init_pctl(), b43_phy_initb5(), and b43_phy_initb6().
static void b43_shm_clear_tssi (struct b43_wldev * dev) [static]
Definition at line 167 of file phy_g.c.
References B43_SHM_SHARED, and b43_shm_write16().
Referenced by b43_phy_init_pctl().
static void b43_synth_pu_workaround (struct b43_wldev * dev, u8 channel) [static]
Definition at line 176 of file phy_g.c.
References B43_MMIO_CHANNEL, b43_write16(), channel2freq_bg(), b43_wldev::phy, b43_phy::radio_rev, and b43_phy::radio_ver.
Referenced by b43_calc_nrssi_slope(), b43_gphy_channel_switch(), and b43_radio_init2050().
static s32 b43_tssi2dbm_ad (s32 num, s32 den) [static]
Definition at line 2323 of file phy_g.c.
Referenced by b43_tssi2dbm_entry().
static s8 b43_tssi2dbm_entry (s8 entry[], u8 index, s16 pab0, s16 pab1, s16 pab2) [static]
Definition at line 2331 of file phy_g.c.
References b43_tssi2dbm_ad().
Referenced by b43_generate_dyn_tssi2dbm_tab().
static u16 channel2freq_bg (u8 channel) [inline, static]
Definition at line 73 of file phy_g.c.
References b43_radio_channel_codes_bg, and B43_WARN_ON.
Referenced by b43_gphy_channel_switch(), and b43_synth_pu_workaround().
static void default_baseband_attenuation (struct b43_wldev * dev, struct b43_bbatt * bb) [static]
Definition at line 2123 of file phy_g.c.
References b43_bbatt::att, b43_wldev::phy, b43_phy::radio_rev, and b43_phy::radio_ver.
Referenced by b43_gphy_op_prepare_hardware().
static void default_radio_attenuation (struct b43_wldev * dev, struct b43_rfatt * rf) [static]
Definition at line 2134 of file phy_g.c.
References b43_rfatt::att, B43_PHYTYPE_A, B43_PHYTYPE_G, b43_bus_dev::bdev, b43_bus_dev::board_rev, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_bus_dev::chip_id, b43_wldev::dev, b43_wldev::phy, b43_phy::radio_rev, b43_phy::radio_ver, b43_phy::type, and b43_rfatt::with_padmix.
Referenced by b43_gphy_op_prepare_hardware().
static u16 default_tx_control (struct b43_wldev * dev) [static]
Definition at line 2235 of file phy_g.c.
References B43_TXCTL_PA2DB, B43_TXCTL_TXMIX, b43_wldev::phy, b43_phy::radio_rev, and b43_phy::radio_ver.
Referenced by b43_gphy_op_prepare_hardware().
static void generate_bbatt_list (struct b43_wldev * dev, struct b43_bbatt_list * list) [static]
Definition at line 146 of file phy_g.c.
References b43_bbatt::att, b43_bbatt_list::len, b43_bbatt_list::list, b43_bbatt_list::max_val, and b43_bbatt_list::min_val.
Referenced by b43_gphy_op_prepare_hardware().
static void generate_rfatt_list (struct b43_wldev * dev, struct b43_rfatt_list * list) [static]
Definition at line 80 of file phy_g.c.
References b43_rfatt::att, b43_has_hardware_pctl(), b43_rfatt_list::len, b43_rfatt_list::list, b43_rfatt_list::max_val, b43_rfatt_list::min_val, b43_wldev::phy, b43_phy::radio_rev, and b43_phy::radio_ver.
Referenced by b43_gphy_op_prepare_hardware().
static u16 radio2050_rfover_val (struct b43_wldev * dev, u16 phy_register, unsigned int lpd) [static]
Definition at line 1112 of file phy_g.c.
References B43_BFL_EXTLNA, B43_PHY_RFOVER, B43_PHY_RFOVERVAL, B43_WARN_ON, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::g, b43_phy::gmode, has_loopback_gain, LPD, b43_phy_g::max_lb_gain, b43_wldev::phy, b43_phy::radio_rev, and b43_phy::rev.
Referenced by b43_radio_init2050().
Variable Documentation
struct b43_phy_operations b43_phyops_g
Initial value:
 {
        .allocate               = b43_gphy_op_allocate,
        .free                   = b43_gphy_op_free,
        .prepare_structs        = b43_gphy_op_prepare_structs,
        .prepare_hardware       = b43_gphy_op_prepare_hardware,
        .init                   = b43_gphy_op_init,
        .exit                   = b43_gphy_op_exit,
        .phy_read               = b43_gphy_op_read,
        .phy_write              = b43_gphy_op_write,
        .radio_read             = b43_gphy_op_radio_read,
        .radio_write            = b43_gphy_op_radio_write,
        .supports_hwpctl        = b43_gphy_op_supports_hwpctl,
        .software_rfkill        = b43_gphy_op_software_rfkill,
        .switch_analog          = b43_phyop_switch_analog_generic,
        .switch_channel         = b43_gphy_op_switch_channel,
        .get_default_chan       = b43_gphy_op_get_default_chan,
        .set_rx_antenna         = b43_gphy_op_set_rx_antenna,
        .interf_mitigation      = b43_gphy_op_interf_mitigation,
        .recalc_txpower         = b43_gphy_op_recalc_txpower,
        .adjust_txpower         = b43_gphy_op_adjust_txpower,
        .pwork_15sec            = b43_gphy_op_pwork_15sec,
        .pwork_60sec            = b43_gphy_op_pwork_60sec,
}
Definition at line 3033 of file phy_g.c.
Referenced by b43_phy_allocate().
const u8 b43_radio_channel_codes_bg[] [static]
Initial value:
 {
        12, 17, 22, 27,
        32, 37, 42, 47,
        52, 57, 62, 67,
        72, 84,
}
Definition at line 58 of file phy_g.c.
Referenced by channel2freq_bg().
const s8 b43_tssi2dbm_g_table[] [static]
Initial value:
 {
        77, 77, 77, 76,
        76, 76, 75, 75,
        74, 74, 73, 73,
        73, 72, 72, 71,
        71, 70, 70, 69,
        68, 68, 67, 67,
        66, 65, 65, 64,
        63, 63, 62, 61,
        60, 59, 58, 57,
        56, 55, 54, 53,
        52, 50, 49, 47,
        45, 43, 40, 37,
        33, 28, 22, 14,
        5, -7, -20, -20,
        -20, -20, -20, -20,
        -20, -20, -20, -20,
}
Definition at line 39 of file phy_g.c.
Referenced by b43_gphy_init_tssi2dbm_table().