CompatWireless3.2: drivers/net/wireless/b43/phy_common.h File Reference
drivers/net/wireless/b43/phy_common.h File Reference
#include <linux/types.h>
#include <linux/nl80211.h>
#include <asm/atomic.h>
Data Structures
struct b43_c32
struct b43_phy_operations
struct b43_phy
Defines
#define CORDIC_CONVERT(value)
#define B43_PHYROUTE 0x0C00
#define B43_PHYROUTE_BASE 0x0000
#define B43_PHYROUTE_OFDM_GPHY 0x0400
#define B43_PHYROUTE_EXT_GPHY 0x0800
#define B43_PHYROUTE_N_BMODE 0x0C00
#define B43_PHY_CCK(reg) ((reg) | B43_PHYROUTE_BASE)
#define B43_PHY_N(reg) ((reg) | B43_PHYROUTE_BASE)
#define B43_PHY_N_BMODE(reg) ((reg) | B43_PHYROUTE_N_BMODE)
#define B43_PHY_OFDM(reg) ((reg) | B43_PHYROUTE_OFDM_GPHY)
#define B43_PHY_EXTG(reg) ((reg) | B43_PHYROUTE_EXT_GPHY)
#define B43_PHYVER_ANALOG 0xF000
#define B43_PHYVER_ANALOG_SHIFT 12
#define B43_PHYVER_TYPE 0x0F00
#define B43_PHYVER_TYPE_SHIFT 8
#define B43_PHYVER_VERSION 0x00FF
#define B43_MAX_WRITES_IN_ROW 24
#define b43_radio_read16 b43_radio_read
#define b43_radio_write16 b43_radio_write
#define B43_DEFAULT_CHANNEL UINT_MAX
Enumerations
enum b43_interference_mitigation { B43_INTERFMODE_NONE, B43_INTERFMODE_NONWLAN, B43_INTERFMODE_MANUALWLAN, B43_INTERFMODE_AUTOWLAN }
enum {
B43_ANTENNA0 = 0, B43_ANTENNA1 = 1, B43_ANTENNA_AUTO0 = 2, B43_ANTENNA_AUTO1 = 3,
B43_ANTENNA2 = 4, B43_ANTENNA3 = 8, B43_ANTENNA_AUTO = B43_ANTENNA_AUTO0, B43_ANTENNA_DEFAULT = B43_ANTENNA_AUTO
}
enum b43_txpwr_result { B43_TXPWR_RES_NEED_ADJUST, B43_TXPWR_RES_DONE }
enum b43_phy_txpower_check_flags { B43_TXPWR_IGNORE_TIME = (1 << 0), B43_TXPWR_IGNORE_TSSI = (1 << 1) }
Functions
int b43_phy_allocate (struct b43_wldev *dev)
void b43_phy_free (struct b43_wldev *dev)
int b43_phy_init (struct b43_wldev *dev)
void b43_phy_exit (struct b43_wldev *dev)
bool b43_has_hardware_pctl (struct b43_wldev *dev)
u16 b43_phy_read (struct b43_wldev *dev, u16 reg)
void b43_phy_write (struct b43_wldev *dev, u16 reg, u16 value)
void b43_phy_copy (struct b43_wldev *dev, u16 destreg, u16 srcreg)
void b43_phy_mask (struct b43_wldev *dev, u16 offset, u16 mask)
void b43_phy_set (struct b43_wldev *dev, u16 offset, u16 set)
void b43_phy_maskset (struct b43_wldev *dev, u16 offset, u16 mask, u16 set)
u16 b43_radio_read (struct b43_wldev *dev, u16 reg)
void b43_radio_write (struct b43_wldev *dev, u16 reg, u16 value)
void b43_radio_mask (struct b43_wldev *dev, u16 offset, u16 mask)
void b43_radio_set (struct b43_wldev *dev, u16 offset, u16 set)
void b43_radio_maskset (struct b43_wldev *dev, u16 offset, u16 mask, u16 set)
void b43_radio_lock (struct b43_wldev *dev)
void b43_radio_unlock (struct b43_wldev *dev)
void b43_phy_lock (struct b43_wldev *dev)
void b43_phy_unlock (struct b43_wldev *dev)
int b43_switch_channel (struct b43_wldev *dev, unsigned int new_channel)
void b43_software_rfkill (struct b43_wldev *dev, bool blocked)
void b43_phy_txpower_check (struct b43_wldev *dev, unsigned int flags)
void b43_phy_txpower_adjust_work (struct work_struct *work)
int b43_phy_shm_tssi_read (struct b43_wldev *dev, u16 shm_offset)
void b43_phyop_switch_analog_generic (struct b43_wldev *dev, bool on)
bool b43_channel_type_is_40mhz (enum nl80211_channel_type channel_type)
void b43_phy_force_clock (struct b43_wldev *dev, bool force)
struct b43_c32 b43_cordic (int theta)
Define Documentation
#define B43_DEFAULT_CHANNEL UINT_MAX
B43_DEFAULT_CHANNEL - Switch to the default channel.
Definition at line 397 of file phy_common.h.
Referenced by b43_switch_channel().
#define B43_MAX_WRITES_IN_ROW 24
Definition at line 46 of file phy_common.h.
Referenced by b43_phy_write().
#define B43_PHY_CCK (reg) ((reg) | B43_PHYROUTE_BASE)
Definition at line 27 of file phy_common.h.
Referenced by b43_calc_loopback_gain(), b43_phy_initg(), b43_radio_init2050(), lo_measure_restore(), and lo_measure_setup().
#define B43_PHY_EXTG (reg) ((reg) | B43_PHYROUTE_EXT_GPHY)
Definition at line 35 of file phy_common.h.
Referenced by b43_phy_ht_channel_setup(), b43_phy_ht_op_init(), b43_phy_ht_zero_extg(), b43_phy_initg(), b43_wa_boards_g(), lo_measure_restore(), and lo_measure_setup().
#define B43_PHY_N (reg) ((reg) | B43_PHYROUTE_BASE)
Definition at line 29 of file phy_common.h.
Referenced by b43_nphy_ext_pa_set_tx_dig_filters(), b43_nphy_gain_ctrl_workarounds(), b43_nphy_int_pa_set_tx_dig_filters(), and b43_nphy_rf_control_override().
#define B43_PHY_N_BMODE (reg) ((reg) | B43_PHYROUTE_N_BMODE)
Definition at line 31 of file phy_common.h.
Referenced by b43_nphy_bphy_init(), and b43_phy_ht_bphy_init().
#define B43_PHY_OFDM (reg) ((reg) | B43_PHYROUTE_OFDM_GPHY)
Definition at line 33 of file phy_common.h.
Referenced by b43_phy_ht_op_init(), b43_phy_inita(), b43_phy_initg(), b43_phy_ww(), b43_wa_altagc(), b43_wa_auxclipthr(), b43_wa_crs_blank(), b43_wa_crs_ed(), lpphy_baseband_rev2plus_init(), lpphy_disable_rx_gain_override(), lpphy_enable_rx_gain_override(), lpphy_get_pa_gain(), lpphy_get_tx_gains(), lpphy_radio_init(), lpphy_restore_dig_flt_state(), lpphy_rev2plus_set_rx_gain(), lpphy_save_dig_flt_state(), lpphy_set_pa_gain(), lpphy_set_tssi_mux(), lpphy_set_tx_gains(), lpphy_set_tx_power_control(), lpphy_sync_stx(), and lpphy_tx_pctl_init_hw().
#define B43_PHYROUTE 0x0C00
Definition at line 20 of file phy_common.h.
Referenced by adjust_phyreg(), and check_phyreg().
#define B43_PHYROUTE_BASE 0x0000
Definition at line 21 of file phy_common.h.
Referenced by adjust_phyreg().
#define B43_PHYROUTE_EXT_GPHY 0x0800
Definition at line 23 of file phy_common.h.
Referenced by adjust_phyreg(), and check_phyreg().
#define B43_PHYROUTE_N_BMODE 0x0C00
Definition at line 24 of file phy_common.h.
Referenced by adjust_phyreg().
#define B43_PHYROUTE_OFDM_GPHY 0x0400
Definition at line 22 of file phy_common.h.
Referenced by adjust_phyreg(), and check_phyreg().
#define B43_PHYVER_ANALOG 0xF000
Definition at line 39 of file phy_common.h.
Referenced by b43_phy_versioning().
#define B43_PHYVER_ANALOG_SHIFT 12
Definition at line 40 of file phy_common.h.
Referenced by b43_phy_versioning().
#define B43_PHYVER_TYPE 0x0F00
Definition at line 41 of file phy_common.h.
Referenced by b43_phy_versioning().
#define B43_PHYVER_TYPE_SHIFT 8
Definition at line 42 of file phy_common.h.
Referenced by b43_phy_versioning().
#define B43_PHYVER_VERSION 0x00FF
Definition at line 43 of file phy_common.h.
Referenced by b43_phy_initg(), b43_phy_versioning(), and b43_wa_analog().
#define b43_radio_read16 b43_radio_read
Definition at line 347 of file phy_common.h.
Referenced by aphy_channel_switch(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_nphy_rev2_rssi_cal(), b43_nphy_tx_cal_radio_setup(), b43_phy_initb6(), b43_phy_initg(), b43_radio_core_calibration_value(), b43_radio_init2050(), b43_radio_init2060(), b43_radio_interference_mitigation_enable(), b43_radio_mask(), b43_radio_maskset(), b43_radio_set(), b43_radio_set_tx_iq(), lo_measure_gain_values(), lo_measure_setup(), and lo_measure_txctl_values().
#define b43_radio_write16 b43_radio_write
Definition at line 353 of file phy_common.h.
Referenced by aphy_channel_switch(), b2055_upload_inittab(), b43_aphy_op_software_rfkill(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_dummy_transmission(), b43_nphy_rev2_rssi_cal(), b43_nphy_rev3_rssi_select(), b43_nphy_tx_cal_radio_setup(), b43_phy_initb5(), b43_phy_initb6(), b43_phy_initg(), b43_phy_ww(), b43_radio_init2050(), b43_radio_init2060(), b43_radio_interference_mitigation_enable(), b43_radio_mask(), b43_radio_maskset(), b43_radio_set(), b43_set_txpower_g(), b43_wa_initgains(), lo_measure_gain_values(), lo_measure_restore(), lo_measure_setup(), and lo_measure_txctl_values().
#define CORDIC_CONVERT (value)
Value:
(((value) >= 0) ? \
                                 ((((value) >> 15) + 1) >> 1) : \
                                 -((((-(value)) >> 15) + 1) >> 1))
Definition at line 15 of file phy_common.h.
Referenced by b43_nphy_gen_load_samples(), and lpphy_start_tx_tone().
Enumeration Type Documentation
anonymous enum
Enumerator:
B43_ANTENNA0
B43_ANTENNA1
B43_ANTENNA_AUTO0
B43_ANTENNA_AUTO1
B43_ANTENNA2
B43_ANTENNA3
B43_ANTENNA_AUTO
B43_ANTENNA_DEFAULT
Definition at line 64 of file phy_common.h.
enum b43_interference_mitigation
enum b43_interference_mitigation - Interference Mitigation mode
: Disabled : Non-WLAN Interference Mitigation : WLAN Interference Mitigation : Automatic WLAN Interference Mitigation
Enumerator:
B43_INTERFMODE_NONE
B43_INTERFMODE_NONWLAN
B43_INTERFMODE_MANUALWLAN
B43_INTERFMODE_AUTOWLAN
Definition at line 56 of file phy_common.h.
enum b43_phy_txpower_check_flags
enum b43_phy_txpower_check_flags - Flags for b43_phy_txpower_check()
: Ignore the schedule time and force-redo the check now. : Redo the recalculation, even if the average TSSI did not change.
Enumerator:
B43_TXPWR_IGNORE_TIME
B43_TXPWR_IGNORE_TSSI
Definition at line 422 of file phy_common.h.
enum b43_txpwr_result
enum b43_txpwr_result - Return value for the recalc_txpower PHY op.
: Values changed. Hardware adjustment is needed. : No more work to do. Everything is done.
Enumerator:
B43_TXPWR_RES_NEED_ADJUST
B43_TXPWR_RES_DONE
Definition at line 82 of file phy_common.h.
Function Documentation
bool b43_channel_type_is_40mhz (enum nl80211_channel_type channel_type)
Definition at line 445 of file phy_common.c.
Referenced by b43_nphy_set_channel().
struct b43_c32 b43_cordic (int theta) [read]
Definition at line 484 of file phy_common.c.
References b43_c32::i, and b43_c32::q.
Referenced by b43_nphy_gen_load_samples(), and lpphy_start_tx_tone().
bool b43_has_hardware_pctl (struct b43_wldev * dev)
b43_has_hardware_pctl - Hardware Power Control supported? Returns a boolean, whether hardware power control is supported.
Definition at line 133 of file phy_common.c.
References b43_phy::hardware_power_control, b43_phy::ops, b43_wldev::phy, and b43_phy_operations::supports_hwpctl.
Referenced by b43_hardware_pctl_early_init(), b43_hardware_pctl_init_gphy(), b43_lo_g_init(), b43_lo_g_maintanance_work(), generate_rfatt_list(), lo_measure_restore(), and lo_measure_setup().
int b43_phy_allocate (struct b43_wldev * dev)
b43_phy_allocate - Allocate PHY structs Allocate the PHY data structures, based on the current dev->phy.type
Definition at line 40 of file phy_common.c.
References b43_phy_operations::allocate, b43_phyops_a, b43_phyops_g, b43_phyops_ht, b43_phyops_lcn, b43_phyops_lp, b43_phyops_n, B43_PHYTYPE_A, B43_PHYTYPE_G, B43_PHYTYPE_HT, B43_PHYTYPE_LCN, B43_PHYTYPE_LP, B43_PHYTYPE_N, B43_WARN_ON, b43_phy::ops, b43_wldev::phy, and b43_phy::type.
Referenced by b43_wireless_core_attach().
void b43_phy_copy (struct b43_wldev * dev, u16 destreg, u16 srcreg)
b43_phy_copy - copy contents of 16bit PHY register to another
Definition at line 260 of file phy_common.c.
References assert_mac_suspended(), b43_phy::ops, b43_wldev::phy, b43_phy_operations::phy_read, and b43_phy_operations::phy_write.
Referenced by lpphy_baseband_rev0_1_init().
void b43_phy_exit (struct b43_wldev * dev)
b43_phy_exit - Cleanup PHY
Definition at line 124 of file phy_common.c.
References b43_phy_operations::exit, b43_phy::ops, b43_wldev::phy, and b43_phy_operations::software_rfkill.
Referenced by b43_chip_exit().
void b43_phy_force_clock (struct b43_wldev * dev, bool force)
Definition at line 452 of file phy_common.c.
References B43_BUS_SSB, B43_PHYTYPE_HT, B43_PHYTYPE_N, b43_bus_dev::bdev, b43_bus_dev::bus_type, b43_wldev::dev, b43_wldev::phy, b43_bus_dev::sdev, and b43_phy::type.
Referenced by b43_nphy_reset_cca(), b43_phy_ht_op_init(), and b43_phy_initn().
void b43_phy_free (struct b43_wldev * dev)
b43_phy_free - Free PHY structs
Definition at line 85 of file phy_common.c.
References b43_phy_operations::free, b43_phy::ops, and b43_wldev::phy.
Referenced by b43_wireless_core_attach(), and b43_wireless_core_detach().
int b43_phy_init (struct b43_wldev * dev)
b43_phy_init - Initialise the PHY
Definition at line 91 of file phy_common.c.
References b43_switch_channel(), b43err(), b43_phy::channel, b43_phy_operations::exit, b43_phy_operations::get_default_chan, b43_phy_operations::init, b43_phy::ops, b43_wldev::phy, b43_phy_operations::software_rfkill, and b43_wldev::wl.
Referenced by b43_chip_init().
void b43_phy_lock (struct b43_wldev * dev)
b43_phy_lock - Lock firmware PHY register access
Definition at line 177 of file phy_common.c.
References b43_is_mode(), b43_power_saving_ctl_bits(), B43_PS_AWAKE, B43_WARN_ON, b43_bus_dev::core_rev, b43_wldev::dev, b43_wldev::phy, and b43_wldev::wl.
Referenced by b43_gphy_aci_scan(), and b43_gphy_op_adjust_txpower().
void b43_phy_mask (struct b43_wldev * dev, u16 offset, u16 mask)
b43_phy_mask - Mask a PHY register with a mask
Definition at line 267 of file phy_common.c.
References assert_mac_suspended(), b43_phy_read(), b43_phy_write(), b43_phy::ops, b43_wldev::phy, and b43_phy_operations::phy_maskset.
Referenced by b43_aphy_op_software_rfkill(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_gphy_aci_scan(), b43_gphy_op_set_rx_antenna(), b43_hardware_pctl_early_init(), b43_hardware_pctl_init_gphy(), b43_lpphy_op_software_rfkill(), b43_lpphy_op_switch_analog(), b43_nphy_channel_setup(), b43_nphy_op_software_rfkill(), b43_nphy_rev2_rssi_select(), b43_nphy_rev3_rssi_select(), b43_nphy_rf_control_intc_override(), b43_nphy_rf_control_override(), b43_nphy_run_samples(), b43_nphy_rx_iq_est(), b43_nphy_set_channel(), b43_nphy_stop_playback(), b43_nphy_tx_cal_phy_setup(), b43_nphy_tx_power_ctrl(), b43_nphy_tx_power_fix(), b43_nphy_update_txrx_chain(), b43_nphy_workarounds_rev1_2(), b43_phy_ht_afe_unk1(), b43_phy_ht_channel_setup(), b43_phy_ht_op_init(), b43_phy_ht_op_software_rfkill(), b43_phy_inita(), b43_phy_initb6(), b43_phy_initg(), b43_phy_initn(), b43_phy_lcn_op_init(), b43_phy_lcn_op_software_rfkill(), b43_phy_lcn_op_switch_analog(), b43_phy_lcn_sense_setup(), b43_phy_ww(), b43_radio_2064_init(), b43_radio_init2050(), b43_radio_init2055_pre(), b43_radio_init2056_pre(), b43_radio_interference_mitigation_disable(), b43_radio_interference_mitigation_enable(), b43_wa_altagc(), b43_wa_boards_g(), b43_wa_divider(), b43_wa_initgains(), lo_measure_setup(), lpphy_baseband_rev0_1_init(), lpphy_baseband_rev2plus_init(), lpphy_calc_rx_iq_comp(), lpphy_disable_crs(), lpphy_disable_rx_gain_override(), lpphy_disable_tx_gain_override(), lpphy_loopback(), lpphy_radio_init(), lpphy_restore_crs(), lpphy_run_ddfs(), lpphy_rx_iq_cal(), lpphy_rx_iq_est(), lpphy_set_tssi_mux(), lpphy_set_tx_power_control(), lpphy_stop_ddfs(), lpphy_stop_tx_tone(), and lpphy_tx_pctl_init_hw().
void b43_phy_maskset (struct b43_wldev * dev, u16 offset, u16 mask, u16 set)
b43_phy_maskset - Mask and OR a PHY register with a mask and bitmap
Definition at line 289 of file phy_common.c.
References assert_mac_suspended(), b43_phy_read(), b43_phy_write(), b43_phy::ops, b43_wldev::phy, and b43_phy_operations::phy_maskset.
Referenced by b43_aphy_op_set_rx_antenna(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_calc_nrssi_threshold(), b43_gphy_aci_scan(), b43_gphy_op_set_rx_antenna(), b43_gphy_set_baseband_attenuation(), b43_hardware_pctl_early_init(), b43_hardware_pctl_init_gphy(), b43_lpphy_op_set_rx_antenna(), b43_nphy_adjust_lna_gain_table(), b43_nphy_classifier(), b43_nphy_gain_ctrl_workarounds(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_rev2_rssi_select(), b43_nphy_rev3_rssi_select(), b43_nphy_rf_control_intc_override(), b43_nphy_rf_control_override(), b43_nphy_rx_iq_est(), b43_nphy_set_rx_core_state(), b43_nphy_tx_cal_phy_cleanup(), b43_nphy_tx_cal_phy_setup(), b43_nphy_tx_power_ctrl(), b43_nphy_tx_power_fix(), b43_nphy_update_txrx_chain(), b43_nphy_workarounds_rev3plus(), b43_phy_ht_op_init(), b43_phy_ht_op_software_rfkill(), b43_phy_inita(), b43_phy_initb5(), b43_phy_initb6(), b43_phy_initg(), b43_phy_initn(), b43_phy_lcn_bu_tweaks(), b43_phy_lcn_op_init(), b43_phy_lcn_rev0_baseband_init(), b43_phy_lcn_sense_setup(), b43_phy_lcn_set_channel(), b43_phy_lcn_set_channel_tweaks(), b43_phy_lcn_set_dac_gain(), b43_phy_lcn_set_tx_gain(), b43_phy_lcn_set_tx_gain_override(), b43_phy_ww(), b43_radio_2064_init(), b43_radio_init2050(), b43_radio_interference_mitigation_enable(), b43_set_all_gains(), b43_set_original_gains(), b43_wa_altagc(), b43_wa_crs_thr(), b43_wa_initgains(), b43_wa_lms(), lpphy_baseband_rev0_1_init(), lpphy_baseband_rev2plus_init(), lpphy_calc_rx_iq_comp(), lpphy_clear_deaf(), lpphy_papd_cal_txpwr(), lpphy_rev0_1_rc_calib(), lpphy_rev0_1_set_rx_gain(), lpphy_rev2plus_set_rx_gain(), lpphy_run_ddfs(), lpphy_run_samples(), lpphy_rx_iq_cal(), lpphy_rx_iq_est(), lpphy_set_analog_filter(), lpphy_set_dac_gain(), lpphy_set_deaf(), lpphy_set_pa_gain(), lpphy_set_trsw_over(), lpphy_set_tssi_mux(), lpphy_set_tx_gains(), lpphy_set_tx_power_by_index(), lpphy_set_tx_power_control(), lpphy_sync_stx(), lpphy_tx_pctl_init_hw(), and lpphy_write_tx_pctl_mode_to_hardware().
u16 b43_phy_read (struct b43_wldev * dev, u16 reg)
b43_phy_read - 16bit PHY register read access
Definition at line 243 of file phy_common.c.
References assert_mac_suspended(), b43_phy::ops, b43_wldev::phy, b43_phy_operations::phy_read, and b43_phy::writes_counter.
Referenced by b43_aphy_op_set_rx_antenna(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_calc_nrssi_threshold(), b43_gphy_aci_detect(), b43_gphy_op_set_rx_antenna(), b43_gphy_op_software_rfkill(), b43_gtab_read(), b43_httab_read(), b43_httab_read_bulk(), b43_lcntab_read(), b43_lcntab_read_bulk(), b43_lptab_read(), b43_lptab_read_bulk(), b43_nphy_cal_tx_iq_lo(), b43_nphy_channel_setup(), b43_nphy_classifier(), b43_nphy_force_rf_sequence(), b43_nphy_gain_ctrl_workarounds(), b43_nphy_gen_load_samples(), b43_nphy_get_tx_gains(), b43_nphy_pa_override(), b43_nphy_poll_rssi(), b43_nphy_read_clip_detection(), b43_nphy_reset_cca(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_rev2_rssi_cal(), b43_nphy_rf_control_intc_override(), b43_nphy_run_samples(), b43_nphy_rx_iq_coeffs(), b43_nphy_rx_iq_est(), b43_nphy_stop_playback(), b43_nphy_tx_cal_phy_setup(), b43_nphy_tx_cal_radio_setup(), b43_nphy_tx_power_ctrl(), b43_nphy_update_mimo_config(), b43_nphy_workarounds_rev1_2(), b43_nrssi_hw_read(), b43_ntab_read(), b43_ntab_read_bulk(), b43_ofdmtab_read16(), b43_ofdmtab_read32(), b43_phy_ht_channel_setup(), b43_phy_ht_force_rf_sequence(), b43_phy_ht_op_init(), b43_phy_ht_read_clip_detection(), b43_phy_init_pctl(), b43_phy_inita(), b43_phy_initg(), b43_phy_initn(), b43_phy_lcn_afe_set_unset(), b43_phy_lcn_get_pa_gain(), b43_phy_lcn_sense_setup(), b43_phy_lcn_set_dac_gain(), b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy_ww(), b43_radio_init2050(), b43_radio_interference_mitigation_disable(), b43_radio_interference_mitigation_enable(), b43_wa_altagc(), b43_wa_analog(), b43_wa_nst(), lo_measure_feedthrough(), lo_measure_setup(), lpphy_baseband_rev0_1_init(), lpphy_calc_rx_iq_comp(), lpphy_get_pa_gain(), lpphy_get_tx_gains(), lpphy_papd_cal_txpwr(), lpphy_read_tx_pctl_mode_from_hardware(), lpphy_rev0_1_rc_calib(), lpphy_rx_iq_cal(), lpphy_rx_iq_est(), lpphy_save_dig_flt_state(), lpphy_set_dac_gain(), lpphy_stop_tx_tone(), and lpphy_tx_pctl_init_hw().
void b43_phy_set (struct b43_wldev * dev, u16 offset, u16 set)
b43_phy_set - OR a PHY register with a bitmap
Definition at line 278 of file phy_common.c.
References assert_mac_suspended(), b43_phy_read(), b43_phy_write(), b43_phy::ops, b43_wldev::phy, and b43_phy_operations::phy_maskset.
Referenced by b43_aphy_op_set_rx_antenna(), b43_aphy_op_software_rfkill(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_gphy_aci_scan(), b43_gphy_op_set_rx_antenna(), b43_hardware_pctl_early_init(), b43_hardware_pctl_init_gphy(), b43_lpphy_op_software_rfkill(), b43_lpphy_op_switch_analog(), b43_nphy_channel_setup(), b43_nphy_force_rf_sequence(), b43_nphy_gain_ctrl_workarounds(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_rev2_rssi_select(), b43_nphy_rev3_rssi_select(), b43_nphy_rf_control_intc_override(), b43_nphy_rf_control_override(), b43_nphy_run_samples(), b43_nphy_rx_iq_est(), b43_nphy_set_channel(), b43_nphy_stop_playback(), b43_nphy_tx_power_ctrl(), b43_nphy_tx_power_fix(), b43_nphy_update_txrx_chain(), b43_nphy_workarounds(), b43_nphy_workarounds_rev1_2(), b43_phy_ht_afe_unk1(), b43_phy_ht_force_rf_sequence(), b43_phy_ht_op_init(), b43_phy_inita(), b43_phy_initb5(), b43_phy_initb6(), b43_phy_initg(), b43_phy_initn(), b43_phy_lcn_bu_tweaks(), b43_phy_lcn_op_init(), b43_phy_lcn_op_software_rfkill(), b43_phy_lcn_op_switch_analog(), b43_phy_lcn_rev0_baseband_init(), b43_phy_lcn_sense_setup(), b43_phy_lcn_set_channel(), b43_phy_lcn_set_channel_tweaks(), b43_phy_ww(), b43_radio_init2050(), b43_radio_init2055_pre(), b43_radio_init2056_pre(), b43_radio_interference_mitigation_disable(), b43_radio_interference_mitigation_enable(), b43_wa_crs_ed(), lo_measure_setup(), lpphy_baseband_rev0_1_init(), lpphy_baseband_rev2plus_init(), lpphy_disable_crs(), lpphy_enable_rx_gain_override(), lpphy_enable_tx_gain_override(), lpphy_loopback(), lpphy_radio_init(), lpphy_run_ddfs(), lpphy_run_samples(), lpphy_rx_iq_cal(), lpphy_rx_iq_est(), lpphy_set_trsw_over(), lpphy_set_tssi_mux(), and lpphy_set_tx_power_control().
int b43_phy_shm_tssi_read (struct b43_wldev * dev, u16 shm_offset)
b43_phy_shm_tssi_read - Read the average of the last 4 TSSI from SHM.
: The SHM address to read the values from.
Returns the average of the 4 TSSI values, or a negative error code.
Definition at line 398 of file phy_common.c.
References b43_phy::a, B43_HF_CCKBOOST, b43_shm_read16(), b43_shm_read32(), B43_SHM_SH_HOSTFLO, B43_SHM_SH_TSSI_CCK, B43_SHM_SHARED, b43_shm_write32(), and B43_TSSI_MAX.
Referenced by b43_gphy_op_recalc_txpower().
void b43_phy_txpower_adjust_work (struct work_struct * work)
b43_phy_txpower_adjust_work - TX power workqueue.
Workqueue for updating the TX power parameters in hardware.
Definition at line 354 of file phy_common.c.
References b43_phy_operations::adjust_txpower, B43_STAT_STARTED, b43_status, b43_wl::current_dev, b43_wldev::dev, b43_wl::mutex, b43_phy::ops, b43_wldev::phy, and b43_wl::txpower_adjust_work.
Referenced by b43_wireless_init().
void b43_phy_txpower_check (struct b43_wldev * dev, unsigned int flags)
b43_phy_txpower_check - Check TX power output.
Compare the current TX power output to the desired power emission and schedule an adjustment in case it mismatches.
: OR'ed enum b43_phy_txpower_check_flags flags. See the docs below.
Definition at line 369 of file phy_common.c.
References b43_phy_operations::adjust_txpower, B43_TXPWR_IGNORE_TIME, B43_TXPWR_IGNORE_TSSI, B43_TXPWR_RES_DONE, B43_TXPWR_RES_NEED_ADJUST, B43_WARN_ON, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_wldev::dev, b43_wl::hw, b43_phy::next_txpwr_check_time, b43_phy::ops, b43_wldev::phy, b43_phy_operations::recalc_txpower, b43_wl::txpower_adjust_work, and b43_wldev::wl.
Referenced by b43_handle_txstatus(), b43_op_config(), and b43_periodic_every60sec().
void b43_phy_unlock (struct b43_wldev * dev)
b43_phy_unlock - Unlock firmware PHY register access
Definition at line 189 of file phy_common.c.
References b43_is_mode(), b43_power_saving_ctl_bits(), B43_WARN_ON, b43_bus_dev::core_rev, b43_wldev::dev, b43_wldev::phy, and b43_wldev::wl.
Referenced by b43_gphy_aci_scan(), and b43_gphy_op_adjust_txpower().
void b43_phy_write (struct b43_wldev * dev, u16 reg, u16 value)
b43_phy_write - 16bit PHY register write access
Definition at line 250 of file phy_common.c.
References assert_mac_suspended(), B43_MAX_WRITES_IN_ROW, B43_MMIO_PHY_VER, b43_read16(), b43_phy::ops, b43_wldev::phy, b43_phy_operations::phy_write, and b43_phy::writes_counter.
Referenced by b43_aphy_op_set_rx_antenna(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_calc_nrssi_threshold(), b43_chantab_phy_upload(), b43_gphy_aci_detect(), b43_gphy_dc_lt_init(), b43_gphy_gain_lt_init(), b43_gphy_op_set_rx_antenna(), b43_gphy_op_software_rfkill(), b43_gphy_tssi_power_lt_init(), b43_gtab_read(), b43_gtab_write(), b43_hardware_pctl_early_init(), b43_hardware_pctl_init_gphy(), b43_httab_read(), b43_httab_read_bulk(), b43_httab_write(), b43_httab_write_bulk(), b43_httab_write_few(), b43_lcntab_read(), b43_lcntab_read_bulk(), b43_lcntab_write(), b43_lcntab_write_bulk(), b43_lo_write(), b43_lptab_read(), b43_lptab_read_bulk(), b43_lptab_write(), b43_lptab_write_bulk(), b43_nphy_bphy_init(), b43_nphy_cal_tx_iq_lo(), b43_nphy_channel_setup(), b43_nphy_ext_pa_set_tx_dig_filters(), b43_nphy_force_rf_sequence(), b43_nphy_gain_ctrl_workarounds(), b43_nphy_int_pa_set_tx_dig_filters(), b43_nphy_op_switch_analog(), b43_nphy_pa_override(), b43_nphy_poll_rssi(), b43_nphy_reset_cca(), b43_nphy_restore_rssi_cal(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_rev2_rssi_cal(), b43_nphy_rf_control_intc_override(), b43_nphy_run_samples(), b43_nphy_rx_iq_coeffs(), b43_nphy_rx_iq_est(), b43_nphy_scale_offset_rssi(), b43_nphy_set_rx_core_state(), b43_nphy_superswitch_init(), b43_nphy_tx_cal_phy_cleanup(), b43_nphy_tx_cal_phy_setup(), b43_nphy_tx_lp_fbw(), b43_nphy_tx_power_ctrl(), b43_nphy_tx_power_fix(), b43_nphy_tx_pwr_ctrl_coef_setup(), b43_nphy_update_mimo_config(), b43_nphy_workarounds_rev1_2(), b43_nphy_workarounds_rev3plus(), b43_nphy_write_clip_detection(), b43_nrssi_hw_read(), b43_nrssi_hw_write(), b43_ntab_read(), b43_ntab_read_bulk(), b43_ntab_write(), b43_ntab_write_bulk(), b43_ofdmtab_read16(), b43_ofdmtab_read32(), b43_ofdmtab_write16(), b43_ofdmtab_write32(), b43_phy_ht_bphy_init(), b43_phy_ht_channel_setup(), b43_phy_ht_force_rf_sequence(), b43_phy_ht_op_init(), b43_phy_ht_op_switch_analog(), b43_phy_ht_zero_extg(), b43_phy_init_pctl(), b43_phy_initb5(), b43_phy_initb6(), b43_phy_initg(), b43_phy_initn(), b43_phy_lcn_afe_set_unset(), b43_phy_lcn_bu_tweaks(), b43_phy_lcn_clear_tx_power_offsets(), b43_phy_lcn_load_tx_iir_cck_filter(), b43_phy_lcn_load_tx_iir_ofdm_filter(), b43_phy_lcn_op_init(), b43_phy_lcn_rev0_baseband_init(), b43_phy_lcn_sense_setup(), b43_phy_lcn_set_channel(), b43_phy_lcn_set_channel_tweaks(), b43_phy_lcn_set_tx_gain(), b43_phy_lcn_txrx_spur_avoidance_mode(), b43_phy_mask(), b43_phy_maskset(), b43_phy_set(), b43_phy_ww(), b43_radio_2064_init(), b43_radio_init2050(), b43_radio_init2060(), b43_radio_interference_mitigation_enable(), b43_radio_set_tx_iq(), b43_wa_afcdac(), b43_wa_altagc(), b43_wa_analog(), b43_wa_auxclipthr(), b43_wa_boards_a(), b43_wa_boards_g(), b43_wa_cck_shiftbits(), b43_wa_crs_blank(), b43_wa_crs_ed(), b43_wa_crs_reset(), b43_wa_divider(), b43_wa_initgains(), b43_wa_rssi_adc(), lo_measure_feedthrough(), lo_measure_restore(), lo_measure_setup(), lpphy_baseband_rev0_1_init(), lpphy_baseband_rev2plus_init(), lpphy_disable_crs(), lpphy_radio_init(), lpphy_restore_dig_flt_state(), lpphy_rev0_1_rc_calib(), lpphy_rev0_1_set_rx_gain(), lpphy_rev2plus_set_rx_gain(), lpphy_rx_iq_est(), lpphy_save_dig_flt_state(), lpphy_set_tx_gains(), and lpphy_tx_pctl_init_hw().
void b43_phyop_switch_analog_generic (struct b43_wldev * dev, bool on)
b43_phy_switch_analog_generic - Generic PHY operation for switching the Analog.
It does the switching based on the PHY0 core register. Do _not_ call this directly. Only use it as a switch_analog callback for struct b43_phy_operations.
Definition at line 439 of file phy_common.c.
References B43_MMIO_PHY0, and b43_write16().
void b43_radio_lock (struct b43_wldev * dev)
b43_radio_lock - Lock firmware radio register access
Definition at line 142 of file phy_common.c.
References B43_MACCTL_RADIOLOCK, B43_MMIO_MACCTL, b43_read32(), B43_WARN_ON, b43_write32(), and b43_wldev::phy.
Referenced by b43_gphy_aci_scan(), and b43_gphy_op_adjust_txpower().
void b43_radio_mask (struct b43_wldev * dev, u16 offset, u16 mask)
b43_radio_mask - Mask a 16bit radio register with a mask
Definition at line 225 of file phy_common.c.
References b43_radio_read16, and b43_radio_write16.
Referenced by aphy_channel_switch(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_nphy_op_software_rfkill(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_rev2_rssi_cal(), b43_nphy_tx_cal_radio_setup(), b43_nphy_workarounds_rev1_2(), b43_phy_init_pctl(), b43_phy_lcn_bu_tweaks(), b43_phy_ww(), b43_radio_2059_channel_setup(), b43_radio_2059_init(), b43_radio_2064_init(), b43_radio_init2055_post(), b43_radio_init2056_post(), b43_radio_init2060(), lo_measure_txctl_values(), lpphy_2062_init(), lpphy_2063_init(), lpphy_b2062_tune(), lpphy_b2063_tune(), lpphy_b2063_vco_calib(), lpphy_rev2plus_rc_calib(), and lpphy_set_tssi_mux().
void b43_radio_maskset (struct b43_wldev * dev, u16 offset, u16 mask, u16 set)
b43_radio_maskset - Mask and OR a radio register with a mask and bitmap
Definition at line 237 of file phy_common.c.
References b43_radio_read16, and b43_radio_write16.
Referenced by aphy_channel_switch(), b43_calc_loopback_gain(), b43_calc_nrssi_offset(), b43_calibrate_lo_setting(), b43_nphy_restore_rssi_cal(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_rev2_rssi_cal(), b43_nphy_set_channel(), b43_nphy_set_rssi_2055_vcm(), b43_phy_init_pctl(), b43_phy_initb6(), b43_phy_initg(), b43_phy_lcn_bu_tweaks(), b43_phy_ww(), b43_radio_2059_init(), b43_radio_2064_channel_setup(), b43_radio_init2050(), b43_radio_init2055_post(), b43_radio_init2060(), b43_set_txpower_g(), lo_measure_restore(), lo_measure_txctl_values(), lpphy_b2063_tune(), lpphy_set_tssi_mux(), and lpphy_tx_pctl_init_hw().
u16 b43_radio_read (struct b43_wldev * dev, u16 reg)
b43_radio_read - 16bit Radio register read access
Definition at line 213 of file phy_common.c.
References assert_mac_suspended(), b43_phy::ops, b43_wldev::phy, and b43_phy_operations::radio_read.
Referenced by b43_nphy_save_cal(), b43_phy_lcn_sense_setup(), b43_radio_2059_init(), b43_radio_2064_channel_setup(), b43_radio_2064_init(), b43_radio_init2055_post(), lpphy_2062_init(), lpphy_b2062_tune(), lpphy_b2063_tune(), lpphy_b2063_vco_calib(), lpphy_rev2plus_rc_calib(), and lpphy_sync_stx().
void b43_radio_set (struct b43_wldev * dev, u16 offset, u16 set)
b43_radio_set - OR a 16bit radio register with a bitmap
Definition at line 231 of file phy_common.c.
References b43_radio_read16, and b43_radio_write16.
Referenced by b43_calc_nrssi_offset(), b43_calc_nrssi_slope(), b43_nphy_tx_cal_radio_setup(), b43_nphy_workarounds_rev1_2(), b43_phy_initb5(), b43_phy_initb6(), b43_phy_lcn_bu_tweaks(), b43_phy_lcn_sense_setup(), b43_phy_ww(), b43_radio_2059_channel_setup(), b43_radio_2059_init(), b43_radio_2064_channel_setup(), b43_radio_2064_init(), b43_radio_init2050(), b43_radio_init2055_post(), b43_radio_init2056_post(), b43_wa_altagc(), lpphy_2062_init(), lpphy_2063_init(), lpphy_b2062_tune(), lpphy_b2063_tune(), lpphy_b2063_vco_calib(), and lpphy_set_tssi_mux().
void b43_radio_unlock (struct b43_wldev * dev)
b43_radio_unlock - Unlock firmware radio register access
Definition at line 160 of file phy_common.c.
References B43_MACCTL_RADIOLOCK, B43_MMIO_MACCTL, B43_MMIO_PHY_VER, b43_read16(), b43_read32(), B43_WARN_ON, b43_write32(), and b43_wldev::phy.
Referenced by b43_gphy_aci_scan(), and b43_gphy_op_adjust_txpower().
void b43_radio_write (struct b43_wldev * dev, u16 reg, u16 value)
b43_radio_write - 16bit Radio register write access
Definition at line 219 of file phy_common.c.
References assert_mac_suspended(), b43_phy::ops, b43_wldev::phy, and b43_phy_operations::radio_write.
Referenced by b2056_upload_inittab(), b2062_upload_init_table(), b2063_upload_init_table(), b43_chantab_radio_2056_upload(), b43_chantab_radio_upload(), b43_nphy_gain_ctrl_workarounds(), b43_nphy_op_software_rfkill(), b43_nphy_restore_cal(), b43_nphy_workarounds_rev3plus(), b43_phy_lcn_rev0_baseband_init(), b43_phy_lcn_sense_setup(), b43_radio_2055_setup(), b43_radio_2056_setup(), b43_radio_2059_channel_setup(), b43_radio_2059_init(), b43_radio_2064_channel_setup(), b43_radio_2064_init(), b43_radio_init2055_post(), lpphy_2062_init(), lpphy_2063_init(), lpphy_b2062_reset_pll_bias(), lpphy_b2062_tune(), lpphy_b2062_vco_calib(), lpphy_b2063_tune(), lpphy_b2063_vco_calib(), lpphy_loopback(), lpphy_rev0_1_rc_calib(), lpphy_rev2plus_rc_calib(), lpphy_set_analog_filter(), lpphy_set_rc_cap(), and lpphy_set_tssi_mux().
void b43_software_rfkill (struct b43_wldev * dev, bool blocked)
b43_software_rfkill - Turn the radio ON or OFF in software.
Definition at line 339 of file phy_common.c.
References b43_mac_enable(), b43_mac_suspend(), b43_phy::ops, b43_wldev::phy, b43_phy::radio_on, and b43_phy_operations::software_rfkill.
Referenced by b43_op_config(), and b43_rfkill_poll().
int b43_switch_channel (struct b43_wldev * dev, unsigned int new_channel)
b43_switch_channel - Switch to another channel
Definition at line 300 of file phy_common.c.
References b43_current_band(), B43_DEFAULT_CHANNEL, b43_shm_read16(), B43_SHM_SH_CHAN, B43_SHM_SH_CHAN_40MHZ, B43_SHM_SH_CHAN_5GHZ, B43_SHM_SHARED, b43_shm_write16(), b43_phy::channel, b43_phy_operations::get_default_chan, b43_phy::ops, b43_wldev::phy, b43_phy_operations::switch_channel, and b43_wldev::wl.
Referenced by b43_gphy_aci_detect(), b43_gphy_aci_scan(), b43_gphy_op_pwork_60sec(), b43_nphy_op_software_rfkill(), b43_op_config(), b43_phy_ht_op_software_rfkill(), b43_phy_init(), b43_phy_lcn_op_init(), and b43_radio_init2055_post().