CompatWireless3.2: drivers/net/wireless/b43/phy_a.c File Reference
drivers/net/wireless/b43/phy_a.c File Reference
#include <linux/slab.h>
#include "b43.h"
#include "phy_a.h"
#include "phy_common.h"
#include "wa.h"
#include "main.h"
Functions
static u16 channel2freq_a (u8 channel)
static u16 freq_r3A_value (u16 frequency)
static void b43_radio_set_tx_iq (struct b43_wldev *dev)
static void aphy_channel_switch (struct b43_wldev *dev, unsigned int channel)
static void b43_radio_init2060 (struct b43_wldev *dev)
static void b43_phy_rssiagc (struct b43_wldev *dev, u8 enable)
static void b43_phy_ww (struct b43_wldev *dev)
static void hardware_pctl_init_aphy (struct b43_wldev *dev)
void b43_phy_inita (struct b43_wldev *dev)
static int b43_aphy_init_tssi2dbm_table (struct b43_wldev *dev)
static int b43_aphy_op_allocate (struct b43_wldev *dev)
static void b43_aphy_op_prepare_structs (struct b43_wldev *dev)
static void b43_aphy_op_free (struct b43_wldev *dev)
static int b43_aphy_op_init (struct b43_wldev *dev)
static u16 adjust_phyreg (struct b43_wldev *dev, u16 offset)
static u16 b43_aphy_op_read (struct b43_wldev *dev, u16 reg)
static void b43_aphy_op_write (struct b43_wldev *dev, u16 reg, u16 value)
static u16 b43_aphy_op_radio_read (struct b43_wldev *dev, u16 reg)
static void b43_aphy_op_radio_write (struct b43_wldev *dev, u16 reg, u16 value)
static bool b43_aphy_op_supports_hwpctl (struct b43_wldev *dev)
static void b43_aphy_op_software_rfkill (struct b43_wldev *dev, bool blocked)
static int b43_aphy_op_switch_channel (struct b43_wldev *dev, unsigned int new_channel)
static unsigned int b43_aphy_op_get_default_chan (struct b43_wldev *dev)
static void b43_aphy_op_set_rx_antenna (struct b43_wldev *dev, int antenna)
static void b43_aphy_op_adjust_txpower (struct b43_wldev *dev)
static enum b43_txpwr_result b43_aphy_op_recalc_txpower (struct b43_wldev *dev, bool ignore_tssi)
static void b43_aphy_op_pwork_15sec (struct b43_wldev *dev)
static void b43_aphy_op_pwork_60sec (struct b43_wldev *dev)
Variables
struct b43_phy_operations b43_phyops_a
Function Documentation
static u16 adjust_phyreg (struct b43_wldev * dev, u16 offset) [inline, static]
Definition at line 418 of file phy_a.c.
References B43_PHYROUTE, B43_PHYROUTE_BASE, B43_PHYROUTE_EXT_GPHY, B43_PHYROUTE_N_BMODE, B43_PHYROUTE_OFDM_GPHY, b43err(), and b43_wldev::wl.
Referenced by b43_aphy_op_read(), and b43_aphy_op_write().
static void aphy_channel_switch (struct b43_wldev * dev, unsigned int channel) [static]
Definition at line 100 of file phy_a.c.
References b43_radio_mask(), b43_radio_maskset(), b43_radio_read16, b43_radio_set_tx_iq(), b43_radio_write16, b43_write16(), channel2freq_a(), and freq_r3A_value().
Referenced by b43_aphy_op_switch_channel(), and b43_radio_init2060().
static int b43_aphy_init_tssi2dbm_table (struct b43_wldev * dev) [static]
Definition at line 319 of file phy_a.c.
References b43_phy::a, b43_generate_dyn_tssi2dbm_tab(), b43err(), b43_bus_dev::bus_sprom, b43_wldev::dev, b43_wldev::phy, b43_phy_a::tgt_idle_tssi, b43_phy_a::tssi2dbm, and b43_wldev::wl.
Referenced by b43_aphy_op_allocate().
static void b43_aphy_op_adjust_txpower (struct b43_wldev * dev) [static]
Definition at line 558 of file phy_a.c.
static int b43_aphy_op_allocate (struct b43_wldev * dev) [static]
Definition at line 354 of file phy_a.c.
References b43_phy::a, b43_aphy_init_tssi2dbm_table(), and b43_wldev::phy.
static void b43_aphy_op_free (struct b43_wldev * dev) [static]
Definition at line 399 of file phy_a.c.
References b43_phy::a, b43_wldev::phy, and b43_phy_a::tssi2dbm.
static unsigned int b43_aphy_op_get_default_chan (struct b43_wldev * dev) [static]
Definition at line 514 of file phy_a.c.
static int b43_aphy_op_init (struct b43_wldev * dev) [static]
Definition at line 411 of file phy_a.c.
References b43_phy_inita().
static void b43_aphy_op_prepare_structs (struct b43_wldev * dev) [static]
Definition at line 377 of file phy_a.c.
References b43_phy::a, b43_wldev::phy, b43_phy_a::tgt_idle_tssi, and b43_phy_a::tssi2dbm.
static void b43_aphy_op_pwork_15sec (struct b43_wldev * dev) [static]
Definition at line 568 of file phy_a.c.
static void b43_aphy_op_pwork_60sec (struct b43_wldev * dev) [static]
Definition at line 572 of file phy_a.c.
static u16 b43_aphy_op_radio_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 458 of file phy_a.c.
References B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_LOW, b43_read16(), B43_WARN_ON, and b43_write16().
static void b43_aphy_op_radio_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 469 of file phy_a.c.
References B43_MMIO_RADIO_CONTROL, B43_MMIO_RADIO_DATA_LOW, B43_WARN_ON, and b43_write16().
static u16 b43_aphy_op_read (struct b43_wldev * dev, u16 reg) [static]
Definition at line 444 of file phy_a.c.
References adjust_phyreg(), B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, b43_read16(), and b43_write16().
static enum b43_txpwr_result b43_aphy_op_recalc_txpower (struct b43_wldev * dev, bool ignore_tssi) [static]
Definition at line 562 of file phy_a.c.
References B43_TXPWR_RES_DONE.
static void b43_aphy_op_set_rx_antenna (struct b43_wldev * dev, int antenna) [static]
Definition at line 519 of file phy_a.c.
References B43_ANTENNA_AUTO0, B43_ANTENNA_AUTO1, B43_HF_ANTDIVHELP, b43_hf_read(), b43_hf_write(), B43_PHY_ADIVRELATED, B43_PHY_ANTDWELL, B43_PHY_ANTDWELL_AUTODIV1, B43_PHY_BBANDCFG, B43_PHY_BBANDCFG_RXANT, B43_PHY_BBANDCFG_RXANT_SHIFT, B43_PHY_CLIPPWRDOWNT, b43_phy_maskset(), B43_PHY_OFDM61, b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_wldev::phy, and b43_phy::rev.
static void b43_aphy_op_software_rfkill (struct b43_wldev * dev, bool blocked) [static]
Definition at line 483 of file phy_a.c.
References b43_phy_mask(), b43_phy_set(), b43_radio_init2060(), b43_radio_write16, b43_wldev::phy, and b43_phy::radio_on.
static bool b43_aphy_op_supports_hwpctl (struct b43_wldev * dev) [static]
Definition at line 478 of file phy_a.c.
References b43_wldev::phy, and b43_phy::rev.
static int b43_aphy_op_switch_channel (struct b43_wldev * dev, unsigned int new_channel) [static]
Definition at line 504 of file phy_a.c.
References aphy_channel_switch().
static void b43_aphy_op_write (struct b43_wldev * dev, u16 reg, u16 value) [static]
Definition at line 451 of file phy_a.c.
References adjust_phyreg(), B43_MMIO_PHY_CONTROL, B43_MMIO_PHY_DATA, and b43_write16().
void b43_phy_inita (struct b43_wldev * dev)
b43_phy_inita - Lowlevel A-PHY init routine. This is _only_ used by the G-PHY code.
Definition at line 266 of file phy_a.c.
References B43_BFL_PACTRL, B43_PHY_CRS0, B43_PHY_CRS0_EN, B43_PHY_ENCORE, B43_PHY_ENCORE_EN, b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM, b43_phy_read(), b43_phy_rssiagc(), b43_phy_set(), b43_phy_ww(), B43_PHYTYPE_A, B43_PHYTYPE_G, b43_radio_init2060(), b43_wa_all(), B43_WARN_ON, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::gmode, hardware_pctl_init_aphy(), b43_wldev::phy, b43_phy::rev, and b43_phy::type.
Referenced by b43_aphy_op_init(), and b43_phy_initg().
static void b43_phy_rssiagc (struct b43_wldev * dev, u8 enable) [static]
Definition at line 181 of file phy_a.c.
References B43_OFDMTAB_LNAHPFGAIN1, b43_ofdmtab_write16(), B43_OFDMTAB_WRSSI, b43_tab_rssiagc1, B43_TAB_RSSIAGC1_SIZE, b43_tab_rssiagc2, B43_TAB_RSSIAGC2_SIZE, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_inita().
static void b43_phy_ww (struct b43_wldev * dev) [static]
Definition at line 212 of file phy_a.c.
References B43_OFDMTAB_AGC1, B43_OFDMTAB_AGC1_R1, b43_ofdmtab_write16(), B43_PHY_CRS0, B43_PHY_CRS0_EN, b43_phy_mask(), b43_phy_maskset(), B43_PHY_OFDM, B43_PHY_OFDM61, B43_PHY_OTABLEQ, B43_PHY_PWRDOWN, b43_phy_read(), b43_phy_set(), b43_phy_write(), b43_radio_mask(), b43_radio_maskset(), b43_radio_set(), b43_radio_write16, and b43_wa_initgains().
Referenced by b43_phy_inita().
static void b43_radio_init2060 (struct b43_wldev * dev) [static]
Definition at line 143 of file phy_a.c.
References aphy_channel_switch(), b43_phy_write(), b43_radio_mask(), b43_radio_maskset(), b43_radio_read16, b43_radio_write16, b43_phy_operations::get_default_chan, b43_phy::ops, and b43_wldev::phy.
Referenced by b43_aphy_op_software_rfkill(), and b43_phy_inita().
static void b43_radio_set_tx_iq (struct b43_wldev * dev) [static]
Definition at line 82 of file phy_a.c.
References b43_phy_write(), and b43_radio_read16.
Referenced by aphy_channel_switch().
static u16 channel2freq_a (u8 channel) [inline, static]
Definition at line 40 of file phy_a.c.
References B43_WARN_ON.
Referenced by aphy_channel_switch().
static u16 freq_r3A_value (u16 frequency) [inline, static]
Definition at line 47 of file phy_a.c.
Referenced by aphy_channel_switch().
static void hardware_pctl_init_aphy (struct b43_wldev * dev) [static]
Definition at line 261 of file phy_a.c.
Referenced by b43_phy_inita().
Variable Documentation
struct b43_phy_operations b43_phyops_a
Initial value:
 {
        .allocate               = b43_aphy_op_allocate,
        .free                   = b43_aphy_op_free,
        .prepare_structs        = b43_aphy_op_prepare_structs,
        .init                   = b43_aphy_op_init,
        .phy_read               = b43_aphy_op_read,
        .phy_write              = b43_aphy_op_write,
        .radio_read             = b43_aphy_op_radio_read,
        .radio_write            = b43_aphy_op_radio_write,
        .supports_hwpctl        = b43_aphy_op_supports_hwpctl,
        .software_rfkill        = b43_aphy_op_software_rfkill,
        .switch_analog          = b43_phyop_switch_analog_generic,
        .switch_channel         = b43_aphy_op_switch_channel,
        .get_default_chan       = b43_aphy_op_get_default_chan,
        .set_rx_antenna         = b43_aphy_op_set_rx_antenna,
        .recalc_txpower         = b43_aphy_op_recalc_txpower,
        .adjust_txpower         = b43_aphy_op_adjust_txpower,
        .pwork_15sec            = b43_aphy_op_pwork_15sec,
        .pwork_60sec            = b43_aphy_op_pwork_60sec,
}
Definition at line 576 of file phy_a.c.
Referenced by b43_phy_allocate().