CompatWireless3.2: drivers/net/wireless/b43/pio.c File Reference
drivers/net/wireless/b43/pio.c File Reference
#include "b43.h"
#include "pio.h"
#include "dma.h"
#include "main.h"
#include "xmit.h"
#include <linux/delay.h>
#include <linux/sched.h>
#include <linux/slab.h>
Defines
#define destroy_queue_tx(pio, queue)
#define destroy_queue_rx(pio, queue)
Functions
static u16 generate_cookie (struct b43_pio_txqueue *q, struct b43_pio_txpacket *pack)
static struct b43_pio_txqueue * parse_cookie (struct b43_wldev *dev, u16 cookie, struct b43_pio_txpacket **pack)
static u16 index_to_pioqueue_base (struct b43_wldev *dev, unsigned int index)
static u16 pio_txqueue_offset (struct b43_wldev *dev)
static u16 pio_rxqueue_offset (struct b43_wldev *dev)
static struct b43_pio_txqueue * b43_setup_pioqueue_tx (struct b43_wldev *dev, unsigned int index)
static struct b43_pio_rxqueue * b43_setup_pioqueue_rx (struct b43_wldev *dev, unsigned int index)
static void b43_pio_cancel_tx_packets (struct b43_pio_txqueue *q)
static void b43_destroy_pioqueue_tx (struct b43_pio_txqueue *q, const char *name)
static void b43_destroy_pioqueue_rx (struct b43_pio_rxqueue *q, const char *name)
void b43_pio_free (struct b43_wldev *dev)
int b43_pio_init (struct b43_wldev *dev)
static struct b43_pio_txqueue * select_queue_by_priority (struct b43_wldev *dev, u8 queue_prio)
static u16 tx_write_2byte_queue (struct b43_pio_txqueue *q, u16 ctl, const void *_data, unsigned int data_len)
static void pio_tx_frame_2byte_queue (struct b43_pio_txpacket *pack, const u8 *hdr, unsigned int hdrlen)
static u32 tx_write_4byte_queue (struct b43_pio_txqueue *q, u32 ctl, const void *_data, unsigned int data_len)
static void pio_tx_frame_4byte_queue (struct b43_pio_txpacket *pack, const u8 *hdr, unsigned int hdrlen)
static int pio_tx_frame (struct b43_pio_txqueue *q, struct sk_buff *skb)
int b43_pio_tx (struct b43_wldev *dev, struct sk_buff *skb)
void b43_pio_handle_txstatus (struct b43_wldev *dev, const struct b43_txstatus *status)
static bool pio_rx_frame (struct b43_pio_rxqueue *q)
void b43_pio_rx (struct b43_pio_rxqueue *q)
static void b43_pio_tx_suspend_queue (struct b43_pio_txqueue *q)
static void b43_pio_tx_resume_queue (struct b43_pio_txqueue *q)
void b43_pio_tx_suspend (struct b43_wldev *dev)
void b43_pio_tx_resume (struct b43_wldev *dev)
Define Documentation
#define destroy_queue_rx (pio, queue)
Value:
do {                            \
        b43_destroy_pioqueue_rx((pio)->queue, __stringify(queue));      \
        (pio)->queue = NULL;                                            \
  } while (0)
Definition at line 227 of file pio.c.
Referenced by b43_pio_free().
#define destroy_queue_tx (pio, queue)
Value:
do {                            \
        b43_destroy_pioqueue_tx((pio)->queue, __stringify(queue));      \
        (pio)->queue = NULL;                                            \
  } while (0)
Definition at line 222 of file pio.c.
Referenced by b43_pio_free(), and b43_pio_init().
Function Documentation
static void b43_destroy_pioqueue_rx (struct b43_pio_rxqueue * q, const char * name) [static]
Definition at line 214 of file pio.c.
static void b43_destroy_pioqueue_tx (struct b43_pio_txqueue * q, const char * name) [static]
Definition at line 205 of file pio.c.
References b43_pio_cancel_tx_packets().
static void b43_pio_cancel_tx_packets (struct b43_pio_txqueue * q) [static]
Definition at line 191 of file pio.c.
References b43_pio_txqueue::packets, and b43_pio_txpacket::skb.
Referenced by b43_destroy_pioqueue_tx().
void b43_pio_free (struct b43_wldev * dev)
Definition at line 232 of file pio.c.
References b43_using_pio_transfers(), destroy_queue_rx, destroy_queue_tx, b43_wldev::pio, b43_pio::rx_queue, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, and b43_pio::tx_queue_mcast.
Referenced by b43_wireless_core_exit().
void b43_pio_handle_txstatus (struct b43_wldev * dev, const struct b43_txstatus * status)
Definition at line 576 of file pio.c.
References b43_fill_txstatus_report(), b43_txhdr_size(), B43_WARN_ON, b43_pio_txqueue::buffer_used, b43_txstatus::cookie, b43_pio_txqueue::free_packet_slots, b43_wl::hw, b43_pio_txpacket::list, b43_pio_txqueue::packets_list, parse_cookie(), b43_pio_txqueue::queue_prio, b43_pio_txpacket::skb, b43_pio_txqueue::stopped, and b43_wldev::wl.
Referenced by b43_handle_txstatus().
int b43_pio_init (struct b43_wldev * dev)
Definition at line 248 of file pio.c.
References B43_MACCTL_BE, B43_MMIO_MACCTL, b43_read32(), b43_setup_pioqueue_rx(), b43_setup_pioqueue_tx(), B43_SHM_SH_RXPADOFF, B43_SHM_SHARED, b43_shm_write16(), b43_write32(), b43dbg(), destroy_queue_tx, b43_wldev::pio, b43_pio::rx_queue, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, b43_pio::tx_queue_mcast, and b43_wldev::wl.
Referenced by b43_wireless_core_init().
void b43_pio_rx (struct b43_pio_rxqueue * q)
Definition at line 775 of file pio.c.
References pio_rx_frame().
Referenced by b43_do_interrupt_thread().
int b43_pio_tx (struct b43_wldev * dev, struct sk_buff * skb)
Definition at line 502 of file pio.c.
References b43_txhdr_size(), B43_WARN_ON, b43dbg(), b43err(), b43warn(), b43_pio_txqueue::buffer_size, b43_pio_txqueue::buffer_used, b43_pio_txqueue::free_packet_slots, b43_wl::hw, b43_wldev::pio, pio_tx_frame(), b43_pio_txqueue::queue_prio, select_queue_by_priority(), b43_pio_txqueue::stopped, b43_pio::tx_queue_mcast, and b43_wldev::wl.
Referenced by b43_tx_work().
void b43_pio_tx_resume (struct b43_wldev * dev)
Definition at line 826 of file pio.c.
References b43_pio_tx_resume_queue(), b43_power_saving_ctl_bits(), b43_wldev::pio, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, and b43_pio::tx_queue_mcast.
Referenced by b43_tx_resume().
static void b43_pio_tx_resume_queue (struct b43_pio_txqueue * q) [static]
Definition at line 803 of file pio.c.
References B43_PIO8_TXCTL, B43_PIO8_TXCTL_SUSPREQ, B43_PIO_TXCTL, B43_PIO_TXCTL_SUSPREQ, b43_piotx_read16(), b43_piotx_read32(), b43_piotx_write16(), b43_piotx_write32(), and b43_pio_txqueue::rev.
Referenced by b43_pio_tx_resume().
void b43_pio_tx_suspend (struct b43_wldev * dev)
Definition at line 816 of file pio.c.
References b43_pio_tx_suspend_queue(), b43_power_saving_ctl_bits(), B43_PS_AWAKE, b43_wldev::pio, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, and b43_pio::tx_queue_mcast.
Referenced by b43_tx_suspend().
static void b43_pio_tx_suspend_queue (struct b43_pio_txqueue * q) [static]
Definition at line 790 of file pio.c.
References B43_PIO8_TXCTL, B43_PIO8_TXCTL_SUSPREQ, B43_PIO_TXCTL, B43_PIO_TXCTL_SUSPREQ, b43_piotx_read16(), b43_piotx_read32(), b43_piotx_write16(), b43_piotx_write32(), and b43_pio_txqueue::rev.
Referenced by b43_pio_tx_suspend().
static struct b43_pio_rxqueue* b43_setup_pioqueue_rx (struct b43_wldev * dev, unsigned int index) [static, read]
Definition at line 172 of file pio.c.
References b43_dma_direct_fifo_rx(), b43_bus_dev::core_rev, b43_wldev::dev, b43_pio_rxqueue::dev, index_to_pioqueue_base(), b43_pio_rxqueue::mmio_base, pio_rxqueue_offset(), and b43_pio_rxqueue::rev.
Referenced by b43_pio_init().
static struct b43_pio_txqueue* b43_setup_pioqueue_tx (struct b43_wldev * dev, unsigned int index) [static, read]
Definition at line 136 of file pio.c.
References B43_PIO_MAX_NR_TXPACKETS, B43_PIO_TXQBUFSIZE, b43_piotx_read16(), b43_pio_txqueue::buffer_size, b43_bus_dev::core_rev, b43_wldev::dev, b43_pio_txqueue::dev, b43_pio_txqueue::free_packet_slots, b43_pio_txpacket::index, b43_pio_txqueue::index, index_to_pioqueue_base(), b43_pio_txpacket::list, b43_pio_txqueue::mmio_base, b43_pio_txqueue::packets, b43_pio_txqueue::packets_list, pio_txqueue_offset(), b43_pio_txpacket::queue, and b43_pio_txqueue::rev.
Referenced by b43_pio_init().
static u16 generate_cookie (struct b43_pio_txqueue * q, struct b43_pio_txpacket * pack) [static]
Definition at line 37 of file pio.c.
References b43_pio_txpacket::index, and b43_pio_txqueue::index.
Referenced by pio_tx_frame().
static u16 index_to_pioqueue_base (struct b43_wldev * dev, unsigned int index) [static]
Definition at line 92 of file pio.c.
References B43_MMIO_PIO11_BASE0, B43_MMIO_PIO11_BASE1, B43_MMIO_PIO11_BASE2, B43_MMIO_PIO11_BASE3, B43_MMIO_PIO11_BASE4, B43_MMIO_PIO11_BASE5, B43_MMIO_PIO_BASE0, B43_MMIO_PIO_BASE1, B43_MMIO_PIO_BASE2, B43_MMIO_PIO_BASE3, B43_MMIO_PIO_BASE4, B43_MMIO_PIO_BASE5, B43_MMIO_PIO_BASE6, B43_MMIO_PIO_BASE7, B43_WARN_ON, b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_setup_pioqueue_rx(), and b43_setup_pioqueue_tx().
static struct b43_pio_txqueue* parse_cookie (struct b43_wldev * dev, u16 cookie, struct b43_pio_txpacket ** pack) [static, read]
Definition at line 57 of file pio.c.
References B43_WARN_ON, b43_pio_txqueue::packets, b43_wldev::pio, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, and b43_pio::tx_queue_mcast.
Referenced by b43_pio_handle_txstatus().
static bool pio_rx_frame (struct b43_pio_rxqueue * q) [static]
Definition at line 609 of file pio.c.
References b43_block_read(), B43_FW_HDR_351, B43_FW_HDR_410, B43_FW_HDR_598, B43_PIO8_RXCTL, B43_PIO8_RXCTL_DATARDY, B43_PIO8_RXCTL_FRAMERDY, B43_PIO8_RXDATA, B43_PIO_RXCTL, B43_PIO_RXCTL_DATARDY, B43_PIO_RXCTL_FRAMERDY, B43_PIO_RXDATA, b43_piorx_read16(), b43_piorx_read32(), b43_piorx_write16(), b43_piorx_write32(), b43_rx(), B43_RX_MAC_FCSERR, B43_RX_MAC_PADDING, b43dbg(), b43_pio_rxqueue::dev, b43_wldev::dev, b43_wl::filter_flags, b43_rxhdr_fw4::frame_len, b43_wldev::fw, b43_firmware::hdr_format, b43_rxhdr_fw4::mac_status, b43_pio_rxqueue::mmio_base, b43_pio_rxqueue::rev, and b43_wldev::wl.
Referenced by b43_pio_rx().
static u16 pio_rxqueue_offset (struct b43_wldev * dev) [static]
Definition at line 129 of file pio.c.
References b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_setup_pioqueue_rx().
static int pio_tx_frame (struct b43_pio_txqueue * q, struct sk_buff * skb) [static]
Definition at line 453 of file pio.c.
References b43_generate_txhdr(), B43_SHM_SH_MCASTCOOKIE, B43_SHM_SHARED, b43_shm_write16(), b43_txhdr_size(), B43_WARN_ON, b43_pio_txqueue::buffer_used, b43_pio_txqueue::dev, b43_wldev::dev, b43_pio_txqueue::free_packet_slots, generate_cookie(), b43_pio_txpacket::list, b43_pio_txqueue::packets_list, pio_tx_frame_2byte_queue(), pio_tx_frame_4byte_queue(), b43_pio_txqueue::rev, b43_pio_txpacket::skb, and b43_wldev::wl.
Referenced by b43_pio_tx().
static void pio_tx_frame_2byte_queue (struct b43_pio_txpacket * pack, const u8 * hdr, unsigned int hdrlen) [static]
Definition at line 362 of file pio.c.
References B43_PIO_TXCTL, B43_PIO_TXCTL_EOF, B43_PIO_TXCTL_FREADY, b43_piotx_read16(), b43_piotx_write16(), b43_pio_txpacket::queue, b43_pio_txpacket::skb, and tx_write_2byte_queue().
Referenced by pio_tx_frame().
static void pio_tx_frame_4byte_queue (struct b43_pio_txpacket * pack, const u8 * hdr, unsigned int hdrlen) [static]
Definition at line 432 of file pio.c.
References B43_PIO8_TXCTL, B43_PIO8_TXCTL_EOF, B43_PIO8_TXCTL_FREADY, B43_PIO_TXCTL, b43_piotx_read32(), b43_piotx_write32(), b43_pio_txpacket::queue, b43_pio_txpacket::skb, and tx_write_4byte_queue().
Referenced by pio_tx_frame().
static u16 pio_txqueue_offset (struct b43_wldev * dev) [static]
Definition at line 122 of file pio.c.
References b43_bus_dev::core_rev, and b43_wldev::dev.
Referenced by b43_setup_pioqueue_tx().
static struct b43_pio_txqueue* select_queue_by_priority (struct b43_wldev * dev, u8 queue_prio) [static, read]
Definition at line 300 of file pio.c.
References B43_WARN_ON, b43_wldev::pio, b43_wldev::qos_enabled, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, and b43_pio::tx_queue_AC_VO.
Referenced by b43_pio_tx().
static u16 tx_write_2byte_queue (struct b43_pio_txqueue * q, u16 ctl, const void * _data, unsigned int data_len) [static]
Definition at line 330 of file pio.c.
References b43_block_write(), B43_PIO_TXCTL, B43_PIO_TXCTL_WRITEHI, B43_PIO_TXCTL_WRITELO, B43_PIO_TXDATA, b43_piotx_write16(), b43_pio_txqueue::dev, b43_wldev::dev, b43_pio_txqueue::mmio_base, and b43_wldev::wl.
Referenced by pio_tx_frame_2byte_queue().
static u32 tx_write_4byte_queue (struct b43_pio_txqueue * q, u32 ctl, const void * _data, unsigned int data_len) [static]
Definition at line 383 of file pio.c.
References b43_block_write(), B43_PIO8_TXCTL, B43_PIO8_TXCTL_0_7, B43_PIO8_TXCTL_16_23, B43_PIO8_TXCTL_24_31, B43_PIO8_TXCTL_8_15, B43_PIO8_TXDATA, b43_piotx_write32(), b43_pio_txqueue::dev, b43_wldev::dev, b43_pio_txqueue::mmio_base, and b43_wldev::wl.
Referenced by pio_tx_frame_4byte_queue().