CompatWireless3.2: drivers/net/wireless/b43/pio.h File Reference
drivers/net/wireless/b43/pio.h File Reference
#include "b43.h"
#include <linux/interrupt.h>
#include <linux/io.h>
#include <linux/list.h>
#include <linux/skbuff.h>
Data Structures
struct b43_pio_txpacket
struct b43_pio_txqueue
struct b43_pio_rxqueue
Defines
#define B43_PIO_TXCTL 0x00
#define B43_PIO_TXCTL_WRITELO 0x0001
#define B43_PIO_TXCTL_WRITEHI 0x0002
#define B43_PIO_TXCTL_EOF 0x0004
#define B43_PIO_TXCTL_FREADY 0x0008
#define B43_PIO_TXCTL_FLUSHREQ 0x0020
#define B43_PIO_TXCTL_FLUSHPEND 0x0040
#define B43_PIO_TXCTL_SUSPREQ 0x0080
#define B43_PIO_TXCTL_QSUSP 0x0100
#define B43_PIO_TXCTL_COMMCNT 0xFC00
#define B43_PIO_TXCTL_COMMCNT_SHIFT 10
#define B43_PIO_TXDATA 0x02
#define B43_PIO_TXQBUFSIZE 0x04
#define B43_PIO_RXCTL 0x00
#define B43_PIO_RXCTL_FRAMERDY 0x0001
#define B43_PIO_RXCTL_DATARDY 0x0002
#define B43_PIO_RXDATA 0x02
#define B43_PIO8_TXCTL 0x00
#define B43_PIO8_TXCTL_0_7 0x00000001
#define B43_PIO8_TXCTL_8_15 0x00000002
#define B43_PIO8_TXCTL_16_23 0x00000004
#define B43_PIO8_TXCTL_24_31 0x00000008
#define B43_PIO8_TXCTL_EOF 0x00000010
#define B43_PIO8_TXCTL_FREADY 0x00000080
#define B43_PIO8_TXCTL_SUSPREQ 0x00000100
#define B43_PIO8_TXCTL_QSUSP 0x00000200
#define B43_PIO8_TXCTL_FLUSHREQ 0x00000400
#define B43_PIO8_TXCTL_FLUSHPEND 0x00000800
#define B43_PIO8_TXDATA 0x04
#define B43_PIO8_RXCTL 0x00
#define B43_PIO8_RXCTL_FRAMERDY 0x00000001
#define B43_PIO8_RXCTL_DATARDY 0x00000002
#define B43_PIO8_RXDATA 0x04
#define B43_PIO_MAX_NR_TXPACKETS 32
Functions
static u16 b43_piotx_read16 (struct b43_pio_txqueue *q, u16 offset)
static u32 b43_piotx_read32 (struct b43_pio_txqueue *q, u16 offset)
static void b43_piotx_write16 (struct b43_pio_txqueue *q, u16 offset, u16 value)
static void b43_piotx_write32 (struct b43_pio_txqueue *q, u16 offset, u32 value)
static u16 b43_piorx_read16 (struct b43_pio_rxqueue *q, u16 offset)
static u32 b43_piorx_read32 (struct b43_pio_rxqueue *q, u16 offset)
static void b43_piorx_write16 (struct b43_pio_rxqueue *q, u16 offset, u16 value)
static void b43_piorx_write32 (struct b43_pio_rxqueue *q, u16 offset, u32 value)
int b43_pio_init (struct b43_wldev *dev)
void b43_pio_free (struct b43_wldev *dev)
int b43_pio_tx (struct b43_wldev *dev, struct sk_buff *skb)
void b43_pio_handle_txstatus (struct b43_wldev *dev, const struct b43_txstatus *status)
void b43_pio_rx (struct b43_pio_rxqueue *q)
void b43_pio_tx_suspend (struct b43_wldev *dev)
void b43_pio_tx_resume (struct b43_wldev *dev)
Define Documentation
#define B43_PIO8_RXCTL 0x00
Definition at line 48 of file pio.h.
Referenced by pio_rx_frame().
#define B43_PIO8_RXCTL_DATARDY 0x00000002
Definition at line 50 of file pio.h.
Referenced by pio_rx_frame().
#define B43_PIO8_RXCTL_FRAMERDY 0x00000001
Definition at line 49 of file pio.h.
Referenced by pio_rx_frame().
#define B43_PIO8_RXDATA 0x04
Definition at line 51 of file pio.h.
Referenced by pio_rx_frame().
#define B43_PIO8_TXCTL 0x00
Definition at line 35 of file pio.h.
Referenced by b43_pio_tx_resume_queue(), b43_pio_tx_suspend_queue(), pio_tx_frame_4byte_queue(), and tx_write_4byte_queue().
#define B43_PIO8_TXCTL_0_7 0x00000001
Definition at line 36 of file pio.h.
Referenced by tx_write_4byte_queue().
#define B43_PIO8_TXCTL_16_23 0x00000004
Definition at line 38 of file pio.h.
Referenced by tx_write_4byte_queue().
#define B43_PIO8_TXCTL_24_31 0x00000008
Definition at line 39 of file pio.h.
Referenced by tx_write_4byte_queue().
#define B43_PIO8_TXCTL_8_15 0x00000002
Definition at line 37 of file pio.h.
Referenced by tx_write_4byte_queue().
#define B43_PIO8_TXCTL_EOF 0x00000010
Definition at line 40 of file pio.h.
Referenced by pio_tx_frame_4byte_queue().
#define B43_PIO8_TXCTL_FLUSHPEND 0x00000800
Definition at line 45 of file pio.h.
#define B43_PIO8_TXCTL_FLUSHREQ 0x00000400
Definition at line 44 of file pio.h.
#define B43_PIO8_TXCTL_FREADY 0x00000080
Definition at line 41 of file pio.h.
Referenced by pio_tx_frame_4byte_queue().
#define B43_PIO8_TXCTL_QSUSP 0x00000200
Definition at line 43 of file pio.h.
#define B43_PIO8_TXCTL_SUSPREQ 0x00000100
Definition at line 42 of file pio.h.
Referenced by b43_pio_tx_resume_queue(), and b43_pio_tx_suspend_queue().
#define B43_PIO8_TXDATA 0x04
Definition at line 46 of file pio.h.
Referenced by tx_write_4byte_queue().
#define B43_PIO_MAX_NR_TXPACKETS 32
Definition at line 55 of file pio.h.
Referenced by b43_setup_pioqueue_tx().
#define B43_PIO_RXCTL 0x00
Definition at line 28 of file pio.h.
Referenced by pio_rx_frame().
#define B43_PIO_RXCTL_DATARDY 0x0002
Definition at line 30 of file pio.h.
Referenced by pio_rx_frame().
#define B43_PIO_RXCTL_FRAMERDY 0x0001
Definition at line 29 of file pio.h.
Referenced by pio_rx_frame().
#define B43_PIO_RXDATA 0x02
Definition at line 31 of file pio.h.
Referenced by pio_rx_frame().
#define B43_PIO_TXCTL 0x00
Definition at line 14 of file pio.h.
Referenced by b43_pio_tx_resume_queue(), b43_pio_tx_suspend_queue(), pio_tx_frame_2byte_queue(), pio_tx_frame_4byte_queue(), and tx_write_2byte_queue().
#define B43_PIO_TXCTL_COMMCNT 0xFC00
Definition at line 23 of file pio.h.
#define B43_PIO_TXCTL_COMMCNT_SHIFT 10
Definition at line 24 of file pio.h.
#define B43_PIO_TXCTL_EOF 0x0004
Definition at line 17 of file pio.h.
Referenced by pio_tx_frame_2byte_queue().
#define B43_PIO_TXCTL_FLUSHPEND 0x0040
Definition at line 20 of file pio.h.
#define B43_PIO_TXCTL_FLUSHREQ 0x0020
Definition at line 19 of file pio.h.
#define B43_PIO_TXCTL_FREADY 0x0008
Definition at line 18 of file pio.h.
Referenced by pio_tx_frame_2byte_queue().
#define B43_PIO_TXCTL_QSUSP 0x0100
Definition at line 22 of file pio.h.
#define B43_PIO_TXCTL_SUSPREQ 0x0080
Definition at line 21 of file pio.h.
Referenced by b43_pio_tx_resume_queue(), and b43_pio_tx_suspend_queue().
#define B43_PIO_TXCTL_WRITEHI 0x0002
Definition at line 16 of file pio.h.
Referenced by tx_write_2byte_queue().
#define B43_PIO_TXCTL_WRITELO 0x0001
Definition at line 15 of file pio.h.
Referenced by tx_write_2byte_queue().
#define B43_PIO_TXDATA 0x02
Definition at line 25 of file pio.h.
Referenced by tx_write_2byte_queue().
#define B43_PIO_TXQBUFSIZE 0x04
Definition at line 26 of file pio.h.
Referenced by b43_setup_pioqueue_tx().
Function Documentation
void b43_pio_free (struct b43_wldev * dev)
Definition at line 232 of file pio.c.
References b43_using_pio_transfers(), destroy_queue_rx, destroy_queue_tx, b43_wldev::pio, b43_pio::rx_queue, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, and b43_pio::tx_queue_mcast.
Referenced by b43_wireless_core_exit().
void b43_pio_handle_txstatus (struct b43_wldev * dev, const struct b43_txstatus * status)
Definition at line 576 of file pio.c.
References b43_fill_txstatus_report(), b43_txhdr_size(), B43_WARN_ON, b43_pio_txqueue::buffer_used, b43_txstatus::cookie, b43_pio_txqueue::free_packet_slots, b43_wl::hw, b43_pio_txpacket::list, b43_pio_txqueue::packets_list, parse_cookie(), b43_pio_txqueue::queue_prio, b43_pio_txpacket::skb, b43_pio_txqueue::stopped, and b43_wldev::wl.
Referenced by b43_handle_txstatus().
int b43_pio_init (struct b43_wldev * dev)
Definition at line 248 of file pio.c.
References B43_MACCTL_BE, B43_MMIO_MACCTL, b43_read32(), b43_setup_pioqueue_rx(), b43_setup_pioqueue_tx(), B43_SHM_SH_RXPADOFF, B43_SHM_SHARED, b43_shm_write16(), b43_write32(), b43dbg(), destroy_queue_tx, b43_wldev::pio, b43_pio::rx_queue, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, b43_pio::tx_queue_mcast, and b43_wldev::wl.
Referenced by b43_wireless_core_init().
void b43_pio_rx (struct b43_pio_rxqueue * q)
Definition at line 775 of file pio.c.
References pio_rx_frame().
Referenced by b43_do_interrupt_thread().
int b43_pio_tx (struct b43_wldev * dev, struct sk_buff * skb)
Definition at line 502 of file pio.c.
References b43_txhdr_size(), B43_WARN_ON, b43dbg(), b43err(), b43warn(), b43_pio_txqueue::buffer_size, b43_pio_txqueue::buffer_used, b43_pio_txqueue::free_packet_slots, b43_wl::hw, b43_wldev::pio, pio_tx_frame(), b43_pio_txqueue::queue_prio, select_queue_by_priority(), b43_pio_txqueue::stopped, b43_pio::tx_queue_mcast, and b43_wldev::wl.
Referenced by b43_tx_work().
void b43_pio_tx_resume (struct b43_wldev * dev)
Definition at line 826 of file pio.c.
References b43_pio_tx_resume_queue(), b43_power_saving_ctl_bits(), b43_wldev::pio, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, and b43_pio::tx_queue_mcast.
Referenced by b43_tx_resume().
void b43_pio_tx_suspend (struct b43_wldev * dev)
Definition at line 816 of file pio.c.
References b43_pio_tx_suspend_queue(), b43_power_saving_ctl_bits(), B43_PS_AWAKE, b43_wldev::pio, b43_pio::tx_queue_AC_BE, b43_pio::tx_queue_AC_BK, b43_pio::tx_queue_AC_VI, b43_pio::tx_queue_AC_VO, and b43_pio::tx_queue_mcast.
Referenced by b43_tx_suspend().
static u16 b43_piorx_read16 (struct b43_pio_rxqueue * q, u16 offset) [inline, static]
Definition at line 131 of file pio.h.
References b43_read16(), b43_pio_rxqueue::dev, and b43_pio_rxqueue::mmio_base.
Referenced by pio_rx_frame().
static u32 b43_piorx_read32 (struct b43_pio_rxqueue * q, u16 offset) [inline, static]
Definition at line 136 of file pio.h.
References b43_read32(), b43_pio_rxqueue::dev, and b43_pio_rxqueue::mmio_base.
Referenced by pio_rx_frame().
static void b43_piorx_write16 (struct b43_pio_rxqueue * q, u16 offset, u16 value) [inline, static]
Definition at line 141 of file pio.h.
References b43_write16(), b43_pio_rxqueue::dev, and b43_pio_rxqueue::mmio_base.
Referenced by pio_rx_frame().
static void b43_piorx_write32 (struct b43_pio_rxqueue * q, u16 offset, u32 value) [inline, static]
Definition at line 147 of file pio.h.
References b43_write32(), b43_pio_rxqueue::dev, and b43_pio_rxqueue::mmio_base.
Referenced by pio_rx_frame().
static u16 b43_piotx_read16 (struct b43_pio_txqueue * q, u16 offset) [inline, static]
Definition at line 108 of file pio.h.
References b43_read16(), b43_pio_txqueue::dev, and b43_pio_txqueue::mmio_base.
Referenced by b43_pio_tx_resume_queue(), b43_pio_tx_suspend_queue(), b43_setup_pioqueue_tx(), and pio_tx_frame_2byte_queue().
static u32 b43_piotx_read32 (struct b43_pio_txqueue * q, u16 offset) [inline, static]
Definition at line 113 of file pio.h.
References b43_read32(), b43_pio_txqueue::dev, and b43_pio_txqueue::mmio_base.
Referenced by b43_pio_tx_resume_queue(), b43_pio_tx_suspend_queue(), and pio_tx_frame_4byte_queue().
static void b43_piotx_write16 (struct b43_pio_txqueue * q, u16 offset, u16 value) [inline, static]
Definition at line 118 of file pio.h.
References b43_write16(), b43_pio_txqueue::dev, and b43_pio_txqueue::mmio_base.
Referenced by b43_pio_tx_resume_queue(), b43_pio_tx_suspend_queue(), pio_tx_frame_2byte_queue(), and tx_write_2byte_queue().
static void b43_piotx_write32 (struct b43_pio_txqueue * q, u16 offset, u32 value) [inline, static]
Definition at line 124 of file pio.h.
References b43_write32(), b43_pio_txqueue::dev, and b43_pio_txqueue::mmio_base.
Referenced by b43_pio_tx_resume_queue(), b43_pio_tx_suspend_queue(), pio_tx_frame_4byte_queue(), and tx_write_4byte_queue().