CompatWireless3.2: drivers/net/wireless/b43/radio_2056.c File Reference
drivers/net/wireless/b43/radio_2056.c File Reference
#include "b43.h"
#include "radio_2056.h"
#include "phy_common.h"
Data Structures
struct b2056_inittab_entry
struct b2056_inittabs_pts
Defines
#define B2056_INITTAB_ENTRY_OK 0x01
#define B2056_INITTAB_UPLOAD 0x02
#define UPLOAD .flags = B2056_INITTAB_ENTRY_OK | B2056_INITTAB_UPLOAD
#define NOUPLOAD .flags = B2056_INITTAB_ENTRY_OK
#define INITTABSPTS(prefix)
#define RADIOREGS3(r00, r01, r02, r03, r04, r05, r06, r07, r08, r09, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28, r29, r30, r31, r32, r33, r34, r35, r36)
#define PHYREGS(r0, r1, r2, r3, r4, r5)
Functions
static void b2056_upload_inittab (struct b43_wldev *dev, bool ghz5, bool ignore_uploadflag, u16 routing, const struct b2056_inittab_entry *e, unsigned int length)
void b2056_upload_inittabs (struct b43_wldev *dev, bool ghz5, bool ignore_uploadflag)
struct
b43_nphy_channeltab_entry_rev3 * b43_nphy_get_chantabent_rev3 (struct b43_wldev *dev, u16 freq)
Variables
static struct b2056_inittab_entry b2056_inittab_rev3_syn []
static struct b2056_inittab_entry b2056_inittab_rev3_tx []
static struct b2056_inittab_entry b2056_inittab_rev3_rx []
static struct b2056_inittab_entry b2056_inittab_rev4_syn []
static struct b2056_inittab_entry b2056_inittab_rev4_tx []
static struct b2056_inittab_entry b2056_inittab_rev4_rx []
static struct b2056_inittab_entry b2056_inittab_rev5_syn []
static struct b2056_inittab_entry b2056_inittab_rev5_tx []
static struct b2056_inittab_entry b2056_inittab_rev5_rx []
static struct b2056_inittab_entry b2056_inittab_rev6_syn []
static struct b2056_inittab_entry b2056_inittab_rev6_tx []
static struct b2056_inittab_entry b2056_inittab_rev6_rx []
static struct b2056_inittab_entry b2056_inittab_rev7_syn []
static struct b2056_inittab_entry b2056_inittab_rev7_tx []
static struct b2056_inittab_entry b2056_inittab_rev7_rx []
static struct b2056_inittab_entry b2056_inittab_rev8_syn []
static struct b2056_inittab_entry b2056_inittab_rev8_tx []
static struct b2056_inittab_entry b2056_inittab_rev8_rx []
struct b2056_inittabs_pts b2056_inittabs []
static struct
b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev3 []
static struct
b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev4 []
static struct
b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev5 []
static struct
b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev6 []
static struct
b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev7_9 []
static struct
b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev8 []
Define Documentation
#define B2056_INITTAB_ENTRY_OK 0x01
Definition at line 37 of file radio_2056.c.
Referenced by b2056_upload_inittab().
#define B2056_INITTAB_UPLOAD 0x02
Definition at line 38 of file radio_2056.c.
Referenced by b2056_upload_inittab().
#define INITTABSPTS (prefix)
Value:
.syn            = prefix##_syn,                 \
        .syn_length     = ARRAY_SIZE(prefix##_syn),     \
        .tx             = prefix##_tx,                  \
        .tx_length      = ARRAY_SIZE(prefix##_tx),      \
        .rx             = prefix##_rx,                  \
        .rx_length      = ARRAY_SIZE(prefix##_rx)
Definition at line 2975 of file radio_2056.c.
#define NOUPLOAD .flags = B2056_INITTAB_ENTRY_OK
Definition at line 40 of file radio_2056.c.
#define PHYREGS (r0, r1, r2, r3, r4, r5)
Value:
.phy_regs.phy_bw1a      = r0,   \
        .phy_regs.phy_bw2       = r1,   \
        .phy_regs.phy_bw3       = r2,   \
        .phy_regs.phy_bw4       = r3,   \
        .phy_regs.phy_bw5       = r4,   \
        .phy_regs.phy_bw6       = r5
Definition at line 3035 of file radio_2056.c.
#define RADIOREGS3 (r00, r01, r02, r03, r04, r05, r06, r07, r08, r09, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24, r25, r26, r27, r28, r29, r30, r31, r32, r33, r34, r35, r36)
Definition at line 2996 of file radio_2056.c.
#define UPLOAD .flags = B2056_INITTAB_ENTRY_OK | B2056_INITTAB_UPLOAD
Definition at line 39 of file radio_2056.c.
Function Documentation
static void b2056_upload_inittab (struct b43_wldev * dev, bool ghz5, bool ignore_uploadflag, u16 routing, const struct b2056_inittab_entry * e, unsigned int length) [static]
Definition at line 9014 of file radio_2056.c.
References B2056_INITTAB_ENTRY_OK, B2056_INITTAB_UPLOAD, b43_radio_write(), b2056_inittab_entry::flags, b2056_inittab_entry::ghz2, and b2056_inittab_entry::ghz5.
Referenced by b2056_upload_inittabs().
void b2056_upload_inittabs (struct b43_wldev * dev, bool ghz5, bool ignore_uploadflag)
Definition at line 9035 of file radio_2056.c.
References B2056_RX0, B2056_RX1, B2056_SYN, B2056_TX0, B2056_TX1, b2056_upload_inittab(), B43_WARN_ON, b43_wldev::phy, b43_phy::rev, b2056_inittabs_pts::rx, b2056_inittabs_pts::rx_length, b2056_inittabs_pts::syn, b2056_inittabs_pts::syn_length, b2056_inittabs_pts::tx, and b2056_inittabs_pts::tx_length.
Referenced by b43_radio_init2056().
struct b43_nphy_channeltab_entry_rev3* b43_nphy_get_chantabent_rev3 (struct b43_wldev * dev, u16 freq) [read]
Definition at line 9059 of file radio_2056.c.
References B43_WARN_ON, b43_nphy_channeltab_entry_rev3::freq, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_nphy_set_channel().
Variable Documentation
struct b2056_inittab_entry b2056_inittab_rev3_rx[] [static]
Definition at line 383 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev3_syn[] [static]
Definition at line 51 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev3_tx[] [static]
Definition at line 235 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev4_rx[] [static]
Definition at line 865 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev4_syn[] [static]
Definition at line 533 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev4_tx[] [static]
Definition at line 717 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev5_rx[] [static]
Definition at line 1355 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev5_syn[] [static]
Definition at line 1015 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev5_tx[] [static]
Definition at line 1199 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev6_rx[] [static]
Definition at line 1845 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev6_syn[] [static]
Definition at line 1505 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev6_tx[] [static]
Definition at line 1689 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev7_rx[] [static]
Definition at line 2335 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev7_syn[] [static]
Definition at line 1995 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev7_tx[] [static]
Definition at line 2179 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev8_rx[] [static]
Definition at line 2825 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev8_syn[] [static]
Definition at line 2485 of file radio_2056.c.
struct b2056_inittab_entry b2056_inittab_rev8_tx[] [static]
Definition at line 2669 of file radio_2056.c.
struct b2056_inittabs_pts b2056_inittabs[]
Initial value:
 {
        [3] = { INITTABSPTS(b2056_inittab_rev3) },
        [4] = { INITTABSPTS(b2056_inittab_rev4) },
        [5] = { INITTABSPTS(b2056_inittab_rev5) },
        [6] = { INITTABSPTS(b2056_inittab_rev6) },
        [7] = { INITTABSPTS(b2056_inittab_rev7) },
        [8] = { INITTABSPTS(b2056_inittab_rev8) },
        [9] = { INITTABSPTS(b2056_inittab_rev7) },
}
Definition at line 2983 of file radio_2056.c.
struct b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev3[] [static]
Definition at line 3044 of file radio_2056.c.
struct b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev4[] [static]
Definition at line 4039 of file radio_2056.c.
struct b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev5[] [static]
Definition at line 5034 of file radio_2056.c.
struct b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev6[] [static]
Definition at line 6029 of file radio_2056.c.
struct b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev7_9[] [static]
Definition at line 7024 of file radio_2056.c.
struct b43_nphy_channeltab_entry_rev3 b43_nphy_channeltab_rev8[] [static]
Definition at line 8019 of file radio_2056.c.