CompatWireless3.2: drivers/net/wireless/b43/radio_2055.c File Reference
drivers/net/wireless/b43/radio_2055.c File Reference
#include "b43.h"
#include "radio_2055.h"
#include "phy_common.h"
Data Structures
struct b2055_inittab_entry
Defines
#define B2055_INITTAB_ENTRY_OK 0x01
#define B2055_INITTAB_UPLOAD 0x02
#define UPLOAD .flags = B2055_INITTAB_ENTRY_OK | B2055_INITTAB_UPLOAD
#define NOUPLOAD .flags = B2055_INITTAB_ENTRY_OK
#define RADIOREGS(r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21)
#define PHYREGS(r0, r1, r2, r3, r4, r5)
Functions
void b2055_upload_inittab (struct b43_wldev *dev, bool ghz5, bool ignore_uploadflag)
struct
b43_nphy_channeltab_entry_rev2 * b43_nphy_get_chantabent_rev2 (struct b43_wldev *dev, u8 channel)
Variables
static struct b2055_inittab_entry b2055_inittab []
static struct
b43_nphy_channeltab_entry_rev2 b43_nphy_channeltab_rev2 []
Define Documentation
#define B2055_INITTAB_ENTRY_OK 0x01
Definition at line 37 of file radio_2055.c.
Referenced by b2055_upload_inittab().
#define B2055_INITTAB_UPLOAD 0x02
Definition at line 38 of file radio_2055.c.
Referenced by b2055_upload_inittab().
#define NOUPLOAD .flags = B2055_INITTAB_ENTRY_OK
Definition at line 41 of file radio_2055.c.
#define PHYREGS (r0, r1, r2, r3, r4, r5)
Value:
.phy_regs.phy_bw1a      = r0,   \
        .phy_regs.phy_bw2       = r1,   \
        .phy_regs.phy_bw3       = r2,   \
        .phy_regs.phy_bw4       = r3,   \
        .phy_regs.phy_bw5       = r4,   \
        .phy_regs.phy_bw6       = r5
Definition at line 296 of file radio_2055.c.
#define RADIOREGS (r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21)
Value:
.radio_pll_ref          = r0,   \
        .radio_rf_pllmod0       = r1,   \
        .radio_rf_pllmod1       = r2,   \
        .radio_vco_captail      = r3,   \
        .radio_vco_cal1         = r4,   \
        .radio_vco_cal2         = r5,   \
        .radio_pll_lfc1         = r6,   \
        .radio_pll_lfr1         = r7,   \
        .radio_pll_lfc2         = r8,   \
        .radio_lgbuf_cenbuf     = r9,   \
        .radio_lgen_tune1       = r10,  \
        .radio_lgen_tune2       = r11,  \
        .radio_c1_lgbuf_atune   = r12,  \
        .radio_c1_lgbuf_gtune   = r13,  \
        .radio_c1_rx_rfr1       = r14,  \
        .radio_c1_tx_pgapadtn   = r15,  \
        .radio_c1_tx_mxbgtrim   = r16,  \
        .radio_c2_lgbuf_atune   = r17,  \
        .radio_c2_lgbuf_gtune   = r18,  \
        .radio_c2_rx_rfr1       = r19,  \
        .radio_c2_tx_pgapadtn   = r20,  \
        .radio_c2_tx_mxbgtrim   = r21
Definition at line 272 of file radio_2055.c.
#define UPLOAD .flags = B2055_INITTAB_ENTRY_OK | B2055_INITTAB_UPLOAD
Definition at line 40 of file radio_2055.c.
Function Documentation
void b2055_upload_inittab (struct b43_wldev * dev, bool ghz5, bool ignore_uploadflag)
Definition at line 1299 of file radio_2055.c.
References B2055_INITTAB_ENTRY_OK, B2055_INITTAB_UPLOAD, B43_MMIO_MACCTL, b43_radio_write16, b43_read32(), b2055_inittab_entry::flags, b2055_inittab_entry::ghz2, and b2055_inittab_entry::ghz5.
Referenced by b43_radio_init2055().
struct b43_nphy_channeltab_entry_rev2* b43_nphy_get_chantabent_rev2 (struct b43_wldev * dev, u8 channel) [read]
Definition at line 1323 of file radio_2055.c.
References b43_nphy_channeltab_entry_rev2::channel.
Referenced by b43_nphy_set_channel().
Variable Documentation
struct b2055_inittab_entry b2055_inittab[] [static]
Definition at line 43 of file radio_2055.c.
struct b43_nphy_channeltab_entry_rev2 b43_nphy_channeltab_rev2[] [static]
Definition at line 304 of file radio_2055.c.