CompatWireless3.2: drivers/net/wireless/b43/rfkill.h File Reference
drivers/net/wireless/b43/rfkill.h File Reference
Functions
void b43_rfkill_poll (struct ieee80211_hw *hw)
bool b43_is_hw_radio_enabled (struct b43_wldev *dev)
Function Documentation
bool b43_is_hw_radio_enabled (struct b43_wldev * dev)
Definition at line 29 of file rfkill.c.
References B43_MMIO_RADIO_HWENABLED_HI, B43_MMIO_RADIO_HWENABLED_HI_MASK, and b43_read32().
Referenced by b43_leds_init(), and b43_rfkill_poll().
void b43_rfkill_poll (struct ieee80211_hw * hw)
Definition at line 36 of file rfkill.c.
References b43_bus_may_powerdown(), b43_bus_powerup(), b43_device_disable(), b43_device_enable(), b43_is_hw_radio_enabled(), b43_software_rfkill(), B43_STAT_INITIALIZED, b43_status, b43info(), b43_wl::current_dev, b43_wldev::dev, hw_to_b43_wl(), b43_wl::mutex, b43_wldev::phy, b43_wldev::radio_hw_enable, and b43_phy::radio_on.