CompatWireless3.2: drivers/net/wireless/b43/sdio.c File Reference
drivers/net/wireless/b43/sdio.c File Reference
#include <linux/kernel.h>
#include <linux/mmc/card.h>
#include <linux/mmc/sdio_func.h>
#include <linux/mmc/sdio_ids.h>
#include <linux/slab.h>
#include <linux/ssb/ssb.h>
#include "sdio.h"
#include "b43.h"
Data Structures
struct b43_sdio_quirk
Defines
#define HNBU_CHIPID 0x01
#define B43_SDIO_BLOCK_SIZE 64
Functions
static unsigned int b43_sdio_get_quirks (u16 vendor, u16 device)
static void b43_sdio_interrupt_dispatcher (struct sdio_func *func)
int b43_sdio_request_irq (struct b43_wldev *dev, void(*handler)(struct b43_wldev *dev))
void b43_sdio_free_irq (struct b43_wldev *dev)
static int __devinit b43_sdio_probe (struct sdio_func *func, const struct sdio_device_id *id)
static void __devexit b43_sdio_remove (struct sdio_func *func)
int b43_sdio_init (void)
void b43_sdio_exit (void)
Variables
static struct b43_sdio_quirk b43_sdio_quirks []
static struct sdio_device_id b43_sdio_ids []
static struct sdio_driver b43_sdio_driver
Define Documentation
#define B43_SDIO_BLOCK_SIZE 64
Definition at line 28 of file sdio.c.
Referenced by b43_sdio_probe().
#define HNBU_CHIPID 0x01
Definition at line 26 of file sdio.c.
Referenced by b43_sdio_probe().
Function Documentation
void b43_sdio_exit (void)
Definition at line 204 of file sdio.c.
Referenced by b43_exit(), and b43_init().
void b43_sdio_free_irq (struct b43_wldev * dev)
Definition at line 83 of file sdio.c.
References b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_wireless_core_stop().
static unsigned int b43_sdio_get_quirks (u16 vendor, u16 device) [static]
Definition at line 41 of file sdio.c.
References b43_sdio_quirks, b43_sdio_quirk::device, b43_sdio_quirk::quirks, and b43_sdio_quirk::vendor.
Referenced by b43_sdio_probe().
int b43_sdio_init (void)
Definition at line 199 of file sdio.c.
Referenced by b43_init().
static void b43_sdio_interrupt_dispatcher (struct sdio_func * func) [static]
Definition at line 53 of file sdio.c.
References B43_STAT_STARTED, b43_status, and b43_wldev::dev.
Referenced by b43_sdio_request_irq().
static int __devinit b43_sdio_probe (struct sdio_func * func, const struct sdio_device_id * id) [static]
Definition at line 96 of file sdio.c.
References B43_SDIO_BLOCK_SIZE, b43_sdio_get_quirks(), and HNBU_CHIPID.
static void __devexit b43_sdio_remove (struct sdio_func * func) [static]
Definition at line 174 of file sdio.c.
int b43_sdio_request_irq (struct b43_wldev * dev, void(*)(struct b43_wldev *dev) handler)
Definition at line 66 of file sdio.c.
References b43_sdio_interrupt_dispatcher(), b43_wldev::dev, and b43_bus_dev::sdev.
Referenced by b43_wireless_core_start().
Variable Documentation
struct sdio_driver b43_sdio_driver [static]
Initial value:
 {
        .name           = "b43-sdio",
        .id_table       = b43_sdio_ids,
        .probe          = b43_sdio_probe,
        .remove         = b43_sdio_remove,
}
Definition at line 192 of file sdio.c.
struct sdio_device_id b43_sdio_ids[] [static]
Initial value:
 {
        { SDIO_DEVICE(0x02d0, 0x044b) },
        { SDIO_DEVICE(0x0092, 0x0004) },
        { },
}
Definition at line 186 of file sdio.c.
struct b43_sdio_quirk b43_sdio_quirks[] [static]
Referenced by b43_sdio_get_quirks().