CompatWireless3.2: b43_phy_operations Struct Reference
b43_phy_operations Struct Reference
#include <phy_common.h>
Data Fields
int(* allocate)(struct b43_wldev *dev)
void(* free)(struct b43_wldev *dev)
void(* prepare_structs)(struct b43_wldev *dev)
int(* prepare_hardware)(struct b43_wldev *dev)
int(* init)(struct b43_wldev *dev)
void(* exit)(struct b43_wldev *dev)
u16(* phy_read)(struct b43_wldev *dev, u16 reg)
void(* phy_write)(struct b43_wldev *dev, u16 reg, u16 value)
void(* phy_maskset)(struct b43_wldev *dev, u16 reg, u16 mask, u16 set)
u16(* radio_read)(struct b43_wldev *dev, u16 reg)
void(* radio_write)(struct b43_wldev *dev, u16 reg, u16 value)
bool(* supports_hwpctl)(struct b43_wldev *dev)
void(* software_rfkill)(struct b43_wldev *dev, bool blocked)
void(* switch_analog)(struct b43_wldev *dev, bool on)
int(* switch_channel)(struct b43_wldev *dev, unsigned int new_channel)
unsigned int(* get_default_chan)(struct b43_wldev *dev)
void(* set_rx_antenna)(struct b43_wldev *dev, int antenna)
int(* interf_mitigation)(struct b43_wldev *dev, enum b43_interference_mitigation new_mode)
enum b43_txpwr_result(* recalc_txpower)(struct b43_wldev *dev, bool ignore_tssi)
void(* adjust_txpower)(struct b43_wldev *dev)
void(* pwork_15sec)(struct b43_wldev *dev)
void(* pwork_60sec)(struct b43_wldev *dev)
Detailed Description
struct b43_phy_operations - Function pointers for PHY ops.
: Allocate and initialise the PHY data structures. Must not be NULL. : Destroy and free the PHY data structures. Must not be NULL.
: Prepare the PHY data structures. The data structures allocated in are initialized here. Must not be NULL. : Prepare the PHY. This is called before b43_chip_init to do some early early PHY hardware init. Can be NULL, if not required. : Initialize the PHY. Must not be NULL. : Shutdown the PHY. Can be NULL, if not required.
: Read from a PHY register. Must not be NULL. : Write to a PHY register. Must not be NULL. : Maskset a PHY register, taking shortcuts. If it is NULL, a generic algorithm is used. : Read from a Radio register. Must not be NULL. : Write to a Radio register. Must not be NULL.
: Returns a boolean whether Hardware Power Control is supported or not. If NULL, hwpctl is assumed to be never supported. : Turn the radio ON or OFF. Possible state values are RFKILL_STATE_SOFT_BLOCKED or RFKILL_STATE_UNBLOCKED Must not be NULL. : Turn the Analog on/off. Must not be NULL. : Switch the radio to another channel. Must not be NULL. : Just returns the default channel number. Must not be NULL. : Set the antenna used for RX. Can be NULL, if not supported. : Switch the Interference Mitigation mode. Can be NULL, if not supported.
: Recalculate the transmission power parameters. This callback has to recalculate the TX power settings, but does not need to write them to the hardware, yet. Returns enum b43_txpwr_result to indicate whether the hardware needs to be adjusted. If B43_TXPWR_NEED_ADJUST is returned, will be called later. If the parameter "ignore_tssi" is true, the TSSI values should be ignored and a recalculation of the power settings should be done even if the TSSI values did not change. This function may sleep, but should not. Must not be NULL. : Write the previously calculated TX power settings (from) to the hardware. This function may sleep. Can be NULL, if (and ONLY if) _always_ returns B43_TXPWR_RES_DONE.
: Periodic work. Called every 15 seconds. Can be NULL, if not required. : Periodic work. Called every 60 seconds. Can be NULL, if not required.
Definition at line 160 of file phy_common.h.
Field Documentation
void(* b43_phy_operations::adjust_txpower)(struct b43_wldev *dev)
Definition at line 189 of file phy_common.h.
Referenced by b43_phy_txpower_adjust_work(), and b43_phy_txpower_check().
int(* b43_phy_operations::allocate)(struct b43_wldev *dev)
Definition at line 162 of file phy_common.h.
Referenced by b43_phy_allocate().
void(* b43_phy_operations::exit)(struct b43_wldev *dev)
Definition at line 167 of file phy_common.h.
Referenced by b43_phy_exit(), and b43_phy_init().
void(* b43_phy_operations::free)(struct b43_wldev *dev)
Definition at line 163 of file phy_common.h.
Referenced by b43_phy_free().
unsigned int(* b43_phy_operations::get_default_chan)(struct b43_wldev *dev)
Definition at line 181 of file phy_common.h.
Referenced by b43_phy_init(), b43_radio_init2060(), and b43_switch_channel().
int(* b43_phy_operations::init)(struct b43_wldev *dev)
Definition at line 166 of file phy_common.h.
Referenced by b43_phy_init().
int(* b43_phy_operations::interf_mitigation)(struct b43_wldev *dev, enum b43_interference_mitigation new_mode)
Definition at line 183 of file phy_common.h.
Referenced by b43_attr_interfmode_store(), b43_chip_init(), and b43_gphy_op_pwork_15sec().
void(* b43_phy_operations::phy_maskset)(struct b43_wldev *dev, u16 reg, u16 mask, u16 set)
Definition at line 172 of file phy_common.h.
Referenced by b43_phy_mask(), b43_phy_maskset(), and b43_phy_set().
u16(* b43_phy_operations::phy_read)(struct b43_wldev *dev, u16 reg)
Definition at line 170 of file phy_common.h.
Referenced by b43_phy_copy(), and b43_phy_read().
void(* b43_phy_operations::phy_write)(struct b43_wldev *dev, u16 reg, u16 value)
Definition at line 171 of file phy_common.h.
Referenced by b43_phy_copy(), and b43_phy_write().
int(* b43_phy_operations::prepare_hardware)(struct b43_wldev *dev)
Definition at line 165 of file phy_common.h.
Referenced by b43_wireless_core_init().
void(* b43_phy_operations::prepare_structs)(struct b43_wldev *dev)
Definition at line 164 of file phy_common.h.
Referenced by b43_wireless_core_init().
void(* b43_phy_operations::pwork_15sec)(struct b43_wldev *dev)
Definition at line 192 of file phy_common.h.
Referenced by b43_periodic_every15sec().
void(* b43_phy_operations::pwork_60sec)(struct b43_wldev *dev)
Definition at line 193 of file phy_common.h.
Referenced by b43_periodic_every60sec().
u16(* b43_phy_operations::radio_read)(struct b43_wldev *dev, u16 reg)
Definition at line 173 of file phy_common.h.
Referenced by b43_radio_read().
void(* b43_phy_operations::radio_write)(struct b43_wldev *dev, u16 reg, u16 value)
Definition at line 174 of file phy_common.h.
Referenced by b43_radio_write().
enum b43_txpwr_result(* b43_phy_operations::recalc_txpower)(struct b43_wldev *dev, bool ignore_tssi)
Definition at line 187 of file phy_common.h.
Referenced by b43_phy_txpower_check().
void(* b43_phy_operations::set_rx_antenna)(struct b43_wldev *dev, int antenna)
Definition at line 182 of file phy_common.h.
Referenced by b43_chip_init(), and b43_op_config().
void(* b43_phy_operations::software_rfkill)(struct b43_wldev *dev, bool blocked)
Definition at line 178 of file phy_common.h.
Referenced by b43_phy_exit(), b43_phy_init(), and b43_software_rfkill().
bool(* b43_phy_operations::supports_hwpctl)(struct b43_wldev *dev)
Definition at line 177 of file phy_common.h.
Referenced by b43_has_hardware_pctl().
void(* b43_phy_operations::switch_analog)(struct b43_wldev *dev, bool on)
Definition at line 179 of file phy_common.h.
Referenced by b43_chip_init(), b43_wireless_core_attach(), b43_wireless_core_exit(), and b43_wireless_core_reset().
int(* b43_phy_operations::switch_channel)(struct b43_wldev *dev, unsigned int new_channel)
Definition at line 180 of file phy_common.h.
Referenced by b43_switch_channel().
The documentation for this struct was generated from the following file:
drivers/net/wireless/b43/phy_common.h