CompatWireless3.2: b43_dma_ops Struct Reference
b43_dma_ops Struct Reference
#include <dma.h>
Data Fields
struct b43_dmadesc_generic *(* idx2desc)(struct b43_dmaring *ring, int slot, struct b43_dmadesc_meta **meta)
void(* fill_descriptor)(struct b43_dmaring *ring, struct b43_dmadesc_generic *desc, dma_addr_t dmaaddr, u16 bufsize, int start, int end, int irq)
void(* poke_tx)(struct b43_dmaring *ring, int slot)
void(* tx_suspend)(struct b43_dmaring *ring)
void(* tx_resume)(struct b43_dmaring *ring)
int(* get_current_rxslot)(struct b43_dmaring *ring)
void(* set_current_rxslot)(struct b43_dmaring *ring, int slot)
Detailed Description
Definition at line 197 of file dma.h.
Field Documentation
void(* b43_dma_ops::fill_descriptor)(struct b43_dmaring *ring, struct b43_dmadesc_generic *desc, dma_addr_t dmaaddr, u16 bufsize, int start, int end, int irq)
Definition at line 202 of file dma.h.
Referenced by dma_tx_fragment(), and setup_rx_descbuffer().
int(* b43_dma_ops::get_current_rxslot)(struct b43_dmaring *ring)
Definition at line 209 of file dma.h.
Referenced by b43_dma_rx().
struct b43_dmadesc_generic*(* b43_dma_ops::idx2desc)(struct b43_dmaring *ring, int slot, struct b43_dmadesc_meta **meta) [read]
Definition at line 198 of file dma.h.
Referenced by alloc_initial_descbuffers(), b43_dma_handle_txstatus(), dma_rx(), dma_tx_fragment(), and free_all_descbuffers().
void(* b43_dma_ops::poke_tx)(struct b43_dmaring *ring, int slot)
Definition at line 206 of file dma.h.
Referenced by dma_tx_fragment().
void(* b43_dma_ops::set_current_rxslot)(struct b43_dmaring *ring, int slot)
Definition at line 210 of file dma.h.
Referenced by b43_dma_rx().
void(* b43_dma_ops::tx_resume)(struct b43_dmaring *ring)
Definition at line 208 of file dma.h.
Referenced by b43_dma_tx_resume_ring().
void(* b43_dma_ops::tx_suspend)(struct b43_dmaring *ring)
Definition at line 207 of file dma.h.
Referenced by b43_dma_tx_suspend_ring().
The documentation for this struct was generated from the following file:
drivers/net/wireless/b43/dma.h