CompatWireless3.2: drivers/net/wireless/b43/sysfs.c File Reference
drivers/net/wireless/b43/sysfs.c File Reference
#include <linux/capability.h>
#include <linux/io.h>
#include "b43.h"
#include "sysfs.h"
#include "main.h"
#include "phy_common.h"
Defines
#define GENERIC_FILESIZE 64
Functions
static int get_integer (const char *buf, size_t count)
static ssize_t b43_attr_interfmode_show (struct device *dev, struct device_attribute *attr, char *buf)
static ssize_t b43_attr_interfmode_store (struct device *dev, struct device_attribute *attr, const char *buf, size_t count)
static DEVICE_ATTR (interference, 0644, b43_attr_interfmode_show, b43_attr_interfmode_store)
int b43_sysfs_register (struct b43_wldev *wldev)
void b43_sysfs_unregister (struct b43_wldev *wldev)
Define Documentation
#define GENERIC_FILESIZE 64
Definition at line 34 of file sysfs.c.
Function Documentation
static ssize_t b43_attr_interfmode_show (struct device * dev, struct device_attribute * attr, char * buf) [static]
Definition at line 50 of file sysfs.c.
References B43_INTERFMODE_MANUALWLAN, B43_INTERFMODE_NONE, B43_INTERFMODE_NONWLAN, B43_PHYTYPE_G, B43_WARN_ON, dev_to_b43_wldev(), b43_phy::g, b43_phy_g::interfmode, b43_wl::mutex, b43_wldev::phy, b43_phy::type, and b43_wldev::wl.
static ssize_t b43_attr_interfmode_store (struct device * dev, struct device_attribute * attr, const char * buf, size_t count) [static]
Definition at line 92 of file sysfs.c.
References B43_INTERFMODE_AUTOWLAN, B43_INTERFMODE_MANUALWLAN, B43_INTERFMODE_NONE, B43_INTERFMODE_NONWLAN, b43err(), dev_to_b43_wldev(), get_integer(), b43_phy_operations::interf_mitigation, b43_wl::mutex, b43_phy::ops, b43_wldev::phy, and b43_wldev::wl.
int b43_sysfs_register (struct b43_wldev * wldev)
Definition at line 141 of file sysfs.c.
References B43_STAT_INITIALIZED, b43_status, B43_WARN_ON, b43_bus_dev::dev, and b43_wldev::dev.
void b43_sysfs_unregister (struct b43_wldev * wldev)
Definition at line 150 of file sysfs.c.
References b43_bus_dev::dev, and b43_wldev::dev.
static DEVICE_ATTR (interference , 0644 , b43_attr_interfmode_show , b43_attr_interfmode_store) [static]
static int get_integer (const char * buf, size_t count) [static]
Definition at line 36 of file sysfs.c.
Referenced by b43_attr_interfmode_store().