CompatWireless3.2: drivers/net/wireless/b43/tables_lpphy.h File Reference
drivers/net/wireless/b43/tables_lpphy.h File Reference
Data Structures
struct lpphy_tx_gain_table_entry
Defines
#define B43_LPTAB_TYPEMASK 0xF0000000
#define B43_LPTAB_8BIT 0x10000000
#define B43_LPTAB_16BIT 0x20000000
#define B43_LPTAB_32BIT 0x30000000
#define B43_LPTAB8(table, offset) (((table) << 10) | (offset) | B43_LPTAB_8BIT)
#define B43_LPTAB16(table, offset) (((table) << 10) | (offset) | B43_LPTAB_16BIT)
#define B43_LPTAB32(table, offset) (((table) << 10) | (offset) | B43_LPTAB_32BIT)
#define B43_LPTAB_TXPWR_R2PLUS B43_LPTAB32(0x07, 0)
#define B43_LPTAB_TXPWR_R0_1 B43_LPTAB32(0xA0, 0)
Functions
u32 b43_lptab_read (struct b43_wldev *dev, u32 offset)
void b43_lptab_write (struct b43_wldev *dev, u32 offset, u32 value)
void b43_lptab_read_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, void *data)
void b43_lptab_write_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, const void *data)
void b2062_upload_init_table (struct b43_wldev *dev)
void b2063_upload_init_table (struct b43_wldev *dev)
void lpphy_write_gain_table (struct b43_wldev *dev, int offset, struct lpphy_tx_gain_table_entry data)
void lpphy_write_gain_table_bulk (struct b43_wldev *dev, int offset, int count, struct lpphy_tx_gain_table_entry *table)
void lpphy_rev0_1_table_init (struct b43_wldev *dev)
void lpphy_rev2plus_table_init (struct b43_wldev *dev)
void lpphy_init_tx_gain_table (struct b43_wldev *dev)
Define Documentation
#define B43_LPTAB16 (table, offset) (((table) << 10) | (offset) | B43_LPTAB_16BIT)
Definition at line 10 of file tables_lpphy.h.
Referenced by lpphy_adjust_gain_table(), lpphy_baseband_rev0_1_init(), lpphy_baseband_rev2plus_init(), lpphy_get_bb_mult(), lpphy_rev0_1_table_init(), lpphy_rev2plus_table_init(), lpphy_set_bb_mult(), lpphy_set_rx_gain_by_index(), lpphy_set_tx_iqcc(), lpphy_set_tx_power_by_index(), and lpphy_start_tx_tone().
#define B43_LPTAB32 (table, offset) (((table) << 10) | (offset) | B43_LPTAB_32BIT)
Definition at line 11 of file tables_lpphy.h.
Referenced by lpphy_baseband_rev2plus_init(), lpphy_pr41573_workaround(), lpphy_rev0_1_table_init(), lpphy_rev0_1_write_gain_table(), lpphy_rev2plus_table_init(), lpphy_rev2plus_write_gain_table(), lpphy_set_tx_power_by_index(), and lpphy_tx_pctl_init_hw().
#define B43_LPTAB8 (table, offset) (((table) << 10) | (offset) | B43_LPTAB_8BIT)
Definition at line 9 of file tables_lpphy.h.
Referenced by lpphy_rev0_1_table_init(), and lpphy_rev2plus_table_init().
#define B43_LPTAB_16BIT 0x20000000
Definition at line 7 of file tables_lpphy.h.
Referenced by b43_lptab_read(), b43_lptab_read_bulk(), b43_lptab_write(), and b43_lptab_write_bulk().
#define B43_LPTAB_32BIT 0x30000000
Definition at line 8 of file tables_lpphy.h.
Referenced by b43_lptab_read(), b43_lptab_read_bulk(), b43_lptab_write(), and b43_lptab_write_bulk().
#define B43_LPTAB_8BIT 0x10000000
Definition at line 6 of file tables_lpphy.h.
Referenced by b43_lptab_read(), b43_lptab_read_bulk(), b43_lptab_write(), and b43_lptab_write_bulk().
#define B43_LPTAB_TXPWR_R0_1 B43_LPTAB32(0xA0, 0)
Definition at line 15 of file tables_lpphy.h.
#define B43_LPTAB_TXPWR_R2PLUS B43_LPTAB32(0x07, 0)
Definition at line 14 of file tables_lpphy.h.
#define B43_LPTAB_TYPEMASK 0xF0000000
Definition at line 5 of file tables_lpphy.h.
Referenced by b43_lptab_read(), b43_lptab_read_bulk(), b43_lptab_write(), and b43_lptab_write_bulk().
Function Documentation
void b2062_upload_init_table (struct b43_wldev * dev)
Definition at line 556 of file tables_lpphy.c.
References B206X_FLAG_A, B206X_FLAG_G, b43_current_band(), b43_radio_write(), b206x_init_tab_entry::flags, b206x_init_tab_entry::offset, b206x_init_tab_entry::value_a, b206x_init_tab_entry::value_g, and b43_wldev::wl.
Referenced by lpphy_2062_init().
void b2063_upload_init_table (struct b43_wldev * dev)
Definition at line 575 of file tables_lpphy.c.
References B206X_FLAG_A, B206X_FLAG_G, b43_current_band(), b43_radio_write(), b206x_init_tab_entry::flags, b206x_init_tab_entry::offset, b206x_init_tab_entry::value_a, b206x_init_tab_entry::value_g, and b43_wldev::wl.
Referenced by lpphy_2063_init().
u32 b43_lptab_read (struct b43_wldev * dev, u32 offset)
Definition at line 594 of file tables_lpphy.c.
References B43_LPPHY_TABLE_ADDR, B43_LPPHY_TABLEDATAHI, B43_LPPHY_TABLEDATALO, B43_LPTAB_16BIT, B43_LPTAB_32BIT, B43_LPTAB_8BIT, B43_LPTAB_TYPEMASK, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by lpphy_get_bb_mult(), lpphy_set_rx_gain_by_index(), and lpphy_set_tx_power_by_index().
void b43_lptab_read_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, void * data)
Definition at line 625 of file tables_lpphy.c.
References B43_LPPHY_TABLE_ADDR, B43_LPPHY_TABLEDATAHI, B43_LPPHY_TABLEDATALO, B43_LPTAB_16BIT, B43_LPTAB_32BIT, B43_LPTAB_8BIT, B43_LPTAB_TYPEMASK, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by lpphy_pr41573_workaround().
void b43_lptab_write (struct b43_wldev * dev, u32 offset, u32 value)
Definition at line 660 of file tables_lpphy.c.
References B43_LPPHY_TABLE_ADDR, B43_LPPHY_TABLEDATAHI, B43_LPPHY_TABLEDATALO, B43_LPTAB_16BIT, B43_LPTAB_32BIT, B43_LPTAB_8BIT, B43_LPTAB_TYPEMASK, b43_phy_write(), and B43_WARN_ON.
Referenced by lpphy_baseband_rev0_1_init(), lpphy_baseband_rev2plus_init(), lpphy_rev0_1_write_gain_table(), lpphy_rev2plus_table_init(), lpphy_rev2plus_write_gain_table(), lpphy_set_bb_mult(), lpphy_set_tx_power_by_index(), and lpphy_tx_pctl_init_hw().
void b43_lptab_write_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, const void * data)
Definition at line 689 of file tables_lpphy.c.
References B43_LPPHY_TABLE_ADDR, B43_LPPHY_TABLEDATAHI, B43_LPPHY_TABLEDATALO, B43_LPTAB_16BIT, B43_LPTAB_32BIT, B43_LPTAB_8BIT, B43_LPTAB_TYPEMASK, b43_phy_write(), and B43_WARN_ON.
Referenced by lpphy_adjust_gain_table(), lpphy_pr41573_workaround(), lpphy_rev0_1_table_init(), lpphy_rev2plus_table_init(), lpphy_set_tx_iqcc(), and lpphy_start_tx_tone().
void lpphy_init_tx_gain_table (struct b43_wldev * dev)
Definition at line 2416 of file tables_lpphy.c.
References B43_BFH_NOPA, B43_BFL_HGPA, b43_current_band(), b43_bus_dev::bus_sprom, b43_wldev::dev, lpphy_write_gain_table_bulk(), b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by lpphy_table_init().
void lpphy_rev0_1_table_init (struct b43_wldev * dev)
Definition at line 2270 of file tables_lpphy.c.
References B43_LPTAB16, B43_LPTAB32, B43_LPTAB8, b43_lptab_write_bulk(), B43_WARN_ON, lpphy_crs_gain_nft_table, lpphy_gain_delta_table, lpphy_iqlo_cal_table, lpphy_min_sig_sq_table, lpphy_pll_fraction_table, lpphy_rev01_filter_control_table, lpphy_rev01_noise_scale_table, lpphy_rev01_ps_control_table, lpphy_rev0_ofdm_cck_gain_table, lpphy_rev1_ofdm_cck_gain_table, lpphy_tx_power_control_table, b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_table_init().
void lpphy_rev2plus_table_init (struct b43_wldev * dev)
Definition at line 2305 of file tables_lpphy.c.
References B43_LPTAB16, B43_LPTAB32, B43_LPTAB8, b43_lptab_write(), b43_lptab_write_bulk(), B43_WARN_ON, b43_bus_dev::chip_id, b43_bus_dev::chip_rev, b43_wldev::dev, lpphy_a0_aux_gain_idx_table, lpphy_a0_gain_idx_table, lpphy_a0_gain_table, lpphy_a0_gain_value_table, lpphy_aux_gain_idx_table, lpphy_gain_idx_table, lpphy_gain_table, lpphy_gain_value_table, lpphy_hf_table, lpphy_iqlo_cal_table, lpphy_min_sig_sq_table, lpphy_papd_eps_table, lpphy_papd_mult_table, lpphy_pll_fraction_table, lpphy_rev2plus_filter_control_table, lpphy_rev2plus_noise_scale_table, lpphy_rev2plus_ps_control_table, lpphy_sw_control_table, b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_table_init().
void lpphy_write_gain_table (struct b43_wldev * dev, int offset, struct lpphy_tx_gain_table_entry data)
Definition at line 2398 of file tables_lpphy.c.
References lpphy_rev0_1_write_gain_table(), lpphy_rev2plus_write_gain_table(), b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_write_gain_table_bulk().
void lpphy_write_gain_table_bulk (struct b43_wldev * dev, int offset, int count, struct lpphy_tx_gain_table_entry * table)
Definition at line 2407 of file tables_lpphy.c.
References lpphy_write_gain_table().
Referenced by lpphy_init_tx_gain_table().