CompatWireless3.2: drivers/net/wireless/b43/tables_nphy.c File Reference
drivers/net/wireless/b43/tables_nphy.c File Reference
#include "b43.h"
#include "tables_nphy.h"
#include "phy_common.h"
#include "phy_n.h"
Defines
#define check(table, size) BUILD_BUG_ON(ARRAY_SIZE(b43_ntab_##table) != B43_NTAB_##size##_SIZE)
#define ntab_upload(dev, offset, data)
#define ntab_upload_r3(dev, offset, data)
Functions
static void assert_ntab_array_sizes (void)
u32 b43_ntab_read (struct b43_wldev *dev, u32 offset)
void b43_ntab_read_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, void *_data)
void b43_ntab_write (struct b43_wldev *dev, u32 offset, u32 value)
void b43_ntab_write_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, const void *_data)
void b43_nphy_rev0_1_2_tables_init (struct b43_wldev *dev)
void b43_nphy_rev3plus_tables_init (struct b43_wldev *dev)
struct
nphy_gain_ctl_workaround_entry * b43_nphy_get_gain_ctl_workaround_ent (struct b43_wldev *dev, bool ghz5, bool ext_lna)
Variables
static const u8 b43_ntab_adjustpower0 []
static const u8 b43_ntab_adjustpower1 []
static const u16 b43_ntab_bdi []
static const u32 b43_ntab_channelest []
static const u8 b43_ntab_estimatepowerlt0 []
static const u8 b43_ntab_estimatepowerlt1 []
static const u8 b43_ntab_framelookup []
static const u32 b43_ntab_framestruct []
static const u32 b43_ntab_gainctl0 []
static const u32 b43_ntab_gainctl1 []
static const u32 b43_ntab_intlevel []
static const u32 b43_ntab_iqlt0 []
static const u32 b43_ntab_iqlt1 []
static const u16 b43_ntab_loftlt0 []
static const u16 b43_ntab_loftlt1 []
static const u8 b43_ntab_mcs []
static const u32 b43_ntab_noisevar10 []
static const u32 b43_ntab_noisevar11 []
static const u16 b43_ntab_pilot []
static const u32 b43_ntab_pilotlt []
static const u32 b43_ntab_tdi20a0 []
static const u32 b43_ntab_tdi20a1 []
static const u32 b43_ntab_tdi40a0 []
static const u32 b43_ntab_tdi40a1 []
static const u32 b43_ntab_tdtrn []
static const u32 b43_ntab_tmap []
static const u32 b43_ntab_framestruct_r3 []
static const u16 b43_ntab_pilot_r3 []
static const u32 b43_ntab_tmap_r3 []
static const u32 b43_ntab_intlevel_r3 []
static const u32 b43_ntab_tdtrn_r3 []
static const u32 b43_ntab_noisevar0_r3 []
static const u32 b43_ntab_noisevar1_r3 []
static const u16 b43_ntab_mcs_r3 []
static const u32 b43_ntab_tdi20a0_r3 []
static const u32 b43_ntab_tdi20a1_r3 []
static const u32 b43_ntab_tdi40a0_r3 []
static const u32 b43_ntab_tdi40a1_r3 []
static const u32 b43_ntab_pilotlt_r3 []
static const u32 b43_ntab_channelest_r3 []
static const u8 b43_ntab_framelookup_r3 []
static const u8 b43_ntab_estimatepowerlt0_r3 []
static const u8 b43_ntab_estimatepowerlt1_r3 []
static const u8 b43_ntab_adjustpower0_r3 []
static const u8 b43_ntab_adjustpower1_r3 []
static const u32 b43_ntab_gainctl0_r3 []
static const u32 b43_ntab_gainctl1_r3 []
static const u32 b43_ntab_iqlt0_r3 []
static const u32 b43_ntab_iqlt1_r3 []
static const u16 b43_ntab_loftlt0_r3 []
static const u16 b43_ntab_loftlt1_r3 []
const u32 b43_ntab_tx_gain_rev0_1_2 []
const u32 b43_ntab_tx_gain_rev3plus_2ghz []
const u32 b43_ntab_tx_gain_rev3_5ghz []
const u32 b43_ntab_tx_gain_rev4_5ghz []
const u32 b43_ntab_tx_gain_rev5plus_5ghz []
const u32 txpwrctrl_tx_gain_ipa []
const u32 txpwrctrl_tx_gain_ipa_rev5 []
const u32 txpwrctrl_tx_gain_ipa_rev6 []
const u32 txpwrctrl_tx_gain_ipa_5g []
const u16 tbl_iqcal_gainparams [2][9][8]
struct nphy_txiqcal_ladder ladder_lo []
struct nphy_txiqcal_ladder ladder_iq []
const u16 loscale []
const u16 tbl_tx_iqlo_cal_loft_ladder_40 []
const u16 tbl_tx_iqlo_cal_loft_ladder_20 []
const u16 tbl_tx_iqlo_cal_iqimb_ladder_40 []
const u16 tbl_tx_iqlo_cal_iqimb_ladder_20 []
const u16 tbl_tx_iqlo_cal_startcoefs_nphyrev3 [B43_NTAB_TX_IQLO_CAL_STARTCOEFS_REV3] = { }
const u16 tbl_tx_iqlo_cal_startcoefs [B43_NTAB_TX_IQLO_CAL_STARTCOEFS] = { }
const u16 tbl_tx_iqlo_cal_cmds_recal_nphyrev3 []
const u16 tbl_tx_iqlo_cal_cmds_recal []
const u16 tbl_tx_iqlo_cal_cmds_fullcal []
const u16 tbl_tx_iqlo_cal_cmds_fullcal_nphyrev3 []
const s16 tbl_tx_filter_coef_rev4 [7][15]
struct
nphy_rf_control_override_rev2 tbl_rf_control_override_rev2 []
struct
nphy_rf_control_override_rev3 tbl_rf_control_override_rev3 []
struct
nphy_gain_ctl_workaround_entry nphy_gain_ctl_workaround [2][3]
Define Documentation
#define check (table, size) BUILD_BUG_ON(ARRAY_SIZE(b43_ntab_##table) != B43_NTAB_##size##_SIZE)
Referenced by assert_ntab_array_sizes().
#define ntab_upload (dev, offset, data)
Value:
do { \
                b43_ntab_write_bulk(dev, offset, offset##_SIZE, data);  \
        } while (0)
Definition at line 2961 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
#define ntab_upload_r3 (dev, offset, data)
Value:
do { \
                b43_ntab_write_bulk(dev, offset, ARRAY_SIZE(data), data); \
        } while (0)
Definition at line 2997 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
Function Documentation
static void assert_ntab_array_sizes (void) [inline, static]
Definition at line 2786 of file tables_nphy.c.
References check.
Referenced by b43_ntab_write().
struct nphy_gain_ctl_workaround_entry* b43_nphy_get_gain_ctl_workaround_ent (struct b43_wldev * dev, bool ghz5, bool ext_lna) [read]
Definition at line 3035 of file tables_nphy.c.
References B43_WARN_ON, nphy_gain_ctl_workaround_entry::init_gain, b43_wldev::phy, b43_phy::rev, and nphy_gain_ctl_workaround_entry::rfseq_init.
Referenced by b43_nphy_gain_ctrl_workarounds().
void b43_nphy_rev0_1_2_tables_init (struct b43_wldev * dev)
Definition at line 2964 of file tables_nphy.c.
References b43_ntab_adjustpower0, b43_ntab_adjustpower1, b43_ntab_bdi, B43_NTAB_BDI, B43_NTAB_C0_ADJPLT, B43_NTAB_C0_ESTPLT, B43_NTAB_C0_GAINCTL, B43_NTAB_C0_IQLT, B43_NTAB_C0_LOFEEDTH, B43_NTAB_C1_ADJPLT, B43_NTAB_C1_ESTPLT, B43_NTAB_C1_GAINCTL, B43_NTAB_C1_IQLT, B43_NTAB_C1_LOFEEDTH, B43_NTAB_CHANEST, b43_ntab_channelest, b43_ntab_estimatepowerlt0, b43_ntab_estimatepowerlt1, b43_ntab_framelookup, B43_NTAB_FRAMELT, b43_ntab_framestruct, B43_NTAB_FRAMESTRUCT, b43_ntab_gainctl0, b43_ntab_gainctl1, b43_ntab_intlevel, B43_NTAB_INTLEVEL, b43_ntab_iqlt0, b43_ntab_iqlt1, b43_ntab_loftlt0, b43_ntab_loftlt1, b43_ntab_mcs, B43_NTAB_MCS, b43_ntab_noisevar10, B43_NTAB_NOISEVAR10, b43_ntab_noisevar11, B43_NTAB_NOISEVAR11, b43_ntab_pilot, B43_NTAB_PILOT, b43_ntab_pilotlt, B43_NTAB_PILOTLT, b43_ntab_tdi20a0, B43_NTAB_TDI20A0, b43_ntab_tdi20a1, B43_NTAB_TDI20A1, b43_ntab_tdi40a0, B43_NTAB_TDI40A0, b43_ntab_tdi40a1, B43_NTAB_TDI40A1, b43_ntab_tdtrn, B43_NTAB_TDTRN, b43_ntab_tmap, B43_NTAB_TMAP, and ntab_upload.
Referenced by b43_nphy_tables_init().
void b43_nphy_rev3plus_tables_init (struct b43_wldev * dev)
Definition at line 3000 of file tables_nphy.c.
References b43_ntab_adjustpower0_r3, b43_ntab_adjustpower1_r3, B43_NTAB_C0_ADJPLT_R3, B43_NTAB_C0_ESTPLT_R3, B43_NTAB_C0_GAINCTL_R3, B43_NTAB_C0_IQLT_R3, B43_NTAB_C0_LOFEEDTH_R3, B43_NTAB_C1_ADJPLT_R3, B43_NTAB_C1_ESTPLT_R3, B43_NTAB_C1_GAINCTL_R3, B43_NTAB_C1_IQLT_R3, B43_NTAB_C1_LOFEEDTH_R3, B43_NTAB_CHANEST_R3, b43_ntab_channelest_r3, b43_ntab_estimatepowerlt0_r3, b43_ntab_estimatepowerlt1_r3, b43_ntab_framelookup_r3, B43_NTAB_FRAMELT_R3, b43_ntab_framestruct_r3, B43_NTAB_FRAMESTRUCT_R3, b43_ntab_gainctl0_r3, b43_ntab_gainctl1_r3, b43_ntab_intlevel_r3, B43_NTAB_INTLEVEL_R3, b43_ntab_iqlt0_r3, b43_ntab_iqlt1_r3, b43_ntab_loftlt0_r3, b43_ntab_loftlt1_r3, b43_ntab_mcs_r3, B43_NTAB_MCS_R3, b43_ntab_noisevar0_r3, B43_NTAB_NOISEVAR0_R3, b43_ntab_noisevar1_r3, B43_NTAB_NOISEVAR1_R3, b43_ntab_pilot_r3, B43_NTAB_PILOT_R3, b43_ntab_pilotlt_r3, B43_NTAB_PILOTLT_R3, b43_ntab_tdi20a0_r3, B43_NTAB_TDI20A0_R3, b43_ntab_tdi20a1_r3, B43_NTAB_TDI20A1_R3, b43_ntab_tdi40a0_r3, B43_NTAB_TDI40A0_R3, b43_ntab_tdi40a1_r3, B43_NTAB_TDI40A1_R3, b43_ntab_tdtrn_r3, B43_NTAB_TDTRN_R3, b43_ntab_tmap_r3, B43_NTAB_TMAP_R3, and ntab_upload_r3.
Referenced by b43_nphy_tables_init().
u32 b43_ntab_read (struct b43_wldev * dev, u32 offset)
Definition at line 2822 of file tables_nphy.c.
References B43_NPHY_TABLE_ADDR, B43_NPHY_TABLE_DATAHI, B43_NPHY_TABLE_DATALO, B43_NTAB_16BIT, B43_NTAB_32BIT, B43_NTAB_8BIT, B43_NTAB_TYPEMASK, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by b43_nphy_cal_tx_iq_lo(), b43_nphy_run_samples(), b43_nphy_tx_cal_phy_setup(), b43_nphy_tx_power_fix(), and b43_nphy_workarounds_rev3plus().
void b43_ntab_read_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, void * _data)
Definition at line 2853 of file tables_nphy.c.
References B43_NPHY_TABLE_ADDR, B43_NPHY_TABLE_DATAHI, B43_NPHY_TABLE_DATALO, B43_NTAB_16BIT, B43_NTAB_32BIT, B43_NTAB_8BIT, B43_NTAB_TYPEMASK, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by b43_nphy_cal_tx_iq_lo(), b43_nphy_get_tx_gains(), b43_nphy_reapply_tx_cal_coeffs(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_save_cal(), b43_nphy_tx_iq_workaround(), and b43_nphy_tx_pwr_ctrl_coef_setup().
void b43_ntab_write (struct b43_wldev * dev, u32 offset, u32 value)
Definition at line 2888 of file tables_nphy.c.
References assert_ntab_array_sizes(), B43_NPHY_TABLE_ADDR, B43_NPHY_TABLE_DATAHI, B43_NPHY_TABLE_DATALO, B43_NTAB_16BIT, B43_NTAB_32BIT, B43_NTAB_8BIT, B43_NTAB_TYPEMASK, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_nphy_cal_tx_iq_lo(), b43_nphy_run_samples(), b43_nphy_set_rf_sequence(), b43_nphy_stop_playback(), b43_nphy_superswitch_init(), b43_nphy_tx_cal_phy_cleanup(), b43_nphy_tx_cal_phy_setup(), b43_nphy_tx_gain_table_upload(), b43_nphy_tx_power_fix(), b43_nphy_update_tx_cal_ladder(), b43_nphy_workarounds_rev1_2(), and b43_nphy_workarounds_rev3plus().
void b43_ntab_write_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, const void * _data)
Definition at line 2921 of file tables_nphy.c.
References B43_NPHY_TABLE_ADDR, B43_NPHY_TABLE_DATAHI, B43_NPHY_TABLE_DATALO, B43_NTAB_16BIT, B43_NTAB_32BIT, B43_NTAB_8BIT, B43_NTAB_TYPEMASK, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_nphy_adjust_lna_gain_table(), b43_nphy_cal_tx_iq_lo(), b43_nphy_gain_ctrl_workarounds(), b43_nphy_load_samples(), b43_nphy_reapply_tx_cal_coeffs(), b43_nphy_restore_cal(), b43_nphy_rev2_cal_rx_iq(), b43_nphy_set_rf_sequence(), b43_nphy_tx_gain_table_upload(), and b43_nphy_tx_power_ctrl().
Variable Documentation
const u8 b43_ntab_adjustpower0[] [static]
Initial value:
 {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
}
Definition at line 31 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u8 b43_ntab_adjustpower0_r3[] [static]
Initial value:
 {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
}
Definition at line 1946 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u8 b43_ntab_adjustpower1[] [static]
Initial value:
 {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
}
Definition at line 50 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u8 b43_ntab_adjustpower1_r3[] [static]
Initial value:
 {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
}
Definition at line 1965 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u16 b43_ntab_bdi[] [static]
Initial value:
 {
        0x0070, 0x0126, 0x012C, 0x0246, 0x048D, 0x04D2,
}
Definition at line 69 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_channelest[] [static]
Initial value:
 {
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
}
Definition at line 73 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_channelest_r3[] [static]
Initial value:
 {
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x44444444, 0x44444444, 0x44444444, 0x44444444,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
        0x10101010, 0x10101010, 0x10101010, 0x10101010,
}
Definition at line 1890 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u8 b43_ntab_estimatepowerlt0[] [static]
Initial value:
 {
        0x50, 0x4F, 0x4E, 0x4D, 0x4C, 0x4B, 0x4A, 0x49,
        0x48, 0x47, 0x46, 0x45, 0x44, 0x43, 0x42, 0x41,
        0x40, 0x3F, 0x3E, 0x3D, 0x3C, 0x3B, 0x3A, 0x39,
        0x38, 0x37, 0x36, 0x35, 0x34, 0x33, 0x32, 0x31,
        0x30, 0x2F, 0x2E, 0x2D, 0x2C, 0x2B, 0x2A, 0x29,
        0x28, 0x27, 0x26, 0x25, 0x24, 0x23, 0x22, 0x21,
        0x20, 0x1F, 0x1E, 0x1D, 0x1C, 0x1B, 0x1A, 0x19,
        0x18, 0x17, 0x16, 0x15, 0x14, 0x13, 0x12, 0x11,
}
Definition at line 100 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u8 b43_ntab_estimatepowerlt0_r3[] [static]
Initial value:
 {
        0x55, 0x54, 0x54, 0x53, 0x52, 0x52, 0x51, 0x51,
        0x50, 0x4f, 0x4f, 0x4e, 0x4e, 0x4d, 0x4c, 0x4c,
        0x4b, 0x4a, 0x49, 0x49, 0x48, 0x47, 0x46, 0x46,
        0x45, 0x44, 0x43, 0x42, 0x41, 0x40, 0x40, 0x3f,
        0x3e, 0x3d, 0x3c, 0x3a, 0x39, 0x38, 0x37, 0x36,
        0x35, 0x33, 0x32, 0x31, 0x2f, 0x2e, 0x2c, 0x2b,
        0x29, 0x27, 0x25, 0x23, 0x21, 0x1f, 0x1d, 0x1a,
        0x18, 0x15, 0x12, 0x0e, 0x0b, 0x07, 0x02, 0xfd,
}
Definition at line 1924 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u8 b43_ntab_estimatepowerlt1[] [static]
Initial value:
 {
        0x50, 0x4F, 0x4E, 0x4D, 0x4C, 0x4B, 0x4A, 0x49,
        0x48, 0x47, 0x46, 0x45, 0x44, 0x43, 0x42, 0x41,
        0x40, 0x3F, 0x3E, 0x3D, 0x3C, 0x3B, 0x3A, 0x39,
        0x38, 0x37, 0x36, 0x35, 0x34, 0x33, 0x32, 0x31,
        0x30, 0x2F, 0x2E, 0x2D, 0x2C, 0x2B, 0x2A, 0x29,
        0x28, 0x27, 0x26, 0x25, 0x24, 0x23, 0x22, 0x21,
        0x20, 0x1F, 0x1E, 0x1D, 0x1C, 0x1B, 0x1A, 0x19,
        0x18, 0x17, 0x16, 0x15, 0x14, 0x13, 0x12, 0x11,
}
Definition at line 111 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u8 b43_ntab_estimatepowerlt1_r3[] [static]
Initial value:
 {
        0x55, 0x54, 0x54, 0x53, 0x52, 0x52, 0x51, 0x51,
        0x50, 0x4f, 0x4f, 0x4e, 0x4e, 0x4d, 0x4c, 0x4c,
        0x4b, 0x4a, 0x49, 0x49, 0x48, 0x47, 0x46, 0x46,
        0x45, 0x44, 0x43, 0x42, 0x41, 0x40, 0x40, 0x3f,
        0x3e, 0x3d, 0x3c, 0x3a, 0x39, 0x38, 0x37, 0x36,
        0x35, 0x33, 0x32, 0x31, 0x2f, 0x2e, 0x2c, 0x2b,
        0x29, 0x27, 0x25, 0x23, 0x21, 0x1f, 0x1d, 0x1a,
        0x18, 0x15, 0x12, 0x0e, 0x0b, 0x07, 0x02, 0xfd,
}
Definition at line 1935 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u8 b43_ntab_framelookup[] [static]
Initial value:
 {
        0x02, 0x04, 0x14, 0x14, 0x03, 0x05, 0x16, 0x16,
        0x0A, 0x0C, 0x1C, 0x1C, 0x0B, 0x0D, 0x1E, 0x1E,
        0x06, 0x08, 0x18, 0x18, 0x07, 0x09, 0x1A, 0x1A,
        0x0E, 0x10, 0x20, 0x28, 0x0F, 0x11, 0x22, 0x2A,
}
Definition at line 122 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u8 b43_ntab_framelookup_r3[] [static]
Initial value:
 {
        0x02, 0x04, 0x14, 0x14, 0x03, 0x05, 0x16, 0x16,
        0x0a, 0x0c, 0x1c, 0x1c, 0x0b, 0x0d, 0x1e, 0x1e,
        0x06, 0x08, 0x18, 0x18, 0x07, 0x09, 0x1a, 0x1a,
        0x0e, 0x10, 0x20, 0x28, 0x0f, 0x11, 0x22, 0x2a,
}
Definition at line 1917 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_framestruct[] [static]
Definition at line 129 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_framestruct_r3[] [static]
Definition at line 1102 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_gainctl0[] [static]
Definition at line 340 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_gainctl0_r3[] [static]
Definition at line 1984 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_gainctl1[] [static]
Definition at line 375 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_gainctl1_r3[] [static]
Definition at line 2019 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_intlevel[] [static]
Initial value:
 {
        0x00802070, 0x0671188D, 0x0A60192C, 0x0A300E46,
        0x00C1188D, 0x080024D2, 0x00000070,
}
Definition at line 410 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_intlevel_r3[] [static]
Initial value:
 {
        0x00802070, 0x0671188d, 0x0a60192c, 0x0a300e46,
        0x00c1188d, 0x080024d2, 0x00000070,
}
Definition at line 1446 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_iqlt0[] [static]
Definition at line 415 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_iqlt0_r3[] [static]
Definition at line 2054 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_iqlt1[] [static]
Definition at line 450 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_iqlt1_r3[] [static]
Definition at line 2089 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u16 b43_ntab_loftlt0[] [static]
Initial value:
 {
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103,
}
Definition at line 485 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u16 b43_ntab_loftlt0_r3[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000,
}
Definition at line 2124 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u16 b43_ntab_loftlt1[] [static]
Initial value:
 {
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103, 0x0000, 0x0101, 0x0002, 0x0103,
        0x0000, 0x0101, 0x0002, 0x0103, 0x0000, 0x0101,
        0x0002, 0x0103,
}
Definition at line 510 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u16 b43_ntab_loftlt1_r3[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000,
}
Definition at line 2149 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u8 b43_ntab_mcs[] [static]
Initial value:
 {
        0x00, 0x08, 0x0A, 0x10, 0x12, 0x19, 0x1A, 0x1C,
        0x40, 0x48, 0x4A, 0x50, 0x52, 0x59, 0x5A, 0x5C,
        0x80, 0x88, 0x8A, 0x90, 0x92, 0x99, 0x9A, 0x9C,
        0xC0, 0xC8, 0xCA, 0xD0, 0xD2, 0xD9, 0xDA, 0xDC,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x01, 0x02, 0x04, 0x08, 0x09, 0x0A, 0x0C,
        0x10, 0x11, 0x12, 0x14, 0x18, 0x19, 0x1A, 0x1C,
        0x20, 0x21, 0x22, 0x24, 0x40, 0x41, 0x42, 0x44,
        0x48, 0x49, 0x4A, 0x4C, 0x50, 0x51, 0x52, 0x54,
        0x58, 0x59, 0x5A, 0x5C, 0x60, 0x61, 0x62, 0x64,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
}
Definition at line 535 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u16 b43_ntab_mcs_r3[] [static]
Initial value:
 {
        0x0000, 0x0008, 0x000a, 0x0010, 0x0012, 0x0019,
        0x001a, 0x001c, 0x0080, 0x0088, 0x008a, 0x0090,
        0x0092, 0x0099, 0x009a, 0x009c, 0x0100, 0x0108,
        0x010a, 0x0110, 0x0112, 0x0119, 0x011a, 0x011c,
        0x0180, 0x0188, 0x018a, 0x0190, 0x0192, 0x0199,
        0x019a, 0x019c, 0x0000, 0x0098, 0x00a0, 0x00a8,
        0x009a, 0x00a2, 0x00aa, 0x0120, 0x0128, 0x0128,
        0x0130, 0x0138, 0x0138, 0x0140, 0x0122, 0x012a,
        0x012a, 0x0132, 0x013a, 0x013a, 0x0142, 0x01a8,
        0x01b0, 0x01b8, 0x01b0, 0x01b8, 0x01c0, 0x01c8,
        0x01c0, 0x01c8, 0x01d0, 0x01d0, 0x01d8, 0x01aa,
        0x01b2, 0x01ba, 0x01b2, 0x01ba, 0x01c2, 0x01ca,
        0x01c2, 0x01ca, 0x01d2, 0x01d2, 0x01da, 0x0001,
        0x0002, 0x0004, 0x0009, 0x000c, 0x0011, 0x0014,
        0x0018, 0x0020, 0x0021, 0x0022, 0x0024, 0x0081,
        0x0082, 0x0084, 0x0089, 0x008c, 0x0091, 0x0094,
        0x0098, 0x00a0, 0x00a1, 0x00a2, 0x00a4, 0x0007,
        0x0007, 0x0007, 0x0007, 0x0007, 0x0007, 0x0007,
        0x0007, 0x0007, 0x0007, 0x0007, 0x0007, 0x0007,
        0x0007, 0x0007, 0x0007, 0x0007, 0x0007, 0x0007,
        0x0007, 0x0007, 0x0007, 0x0007, 0x0007, 0x0007,
        0x0007, 0x0007,
}
Definition at line 1764 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_noisevar0_r3[] [static]
Definition at line 1630 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_noisevar10[] [static]
Definition at line 554 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_noisevar11[] [static]
Definition at line 621 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_noisevar1_r3[] [static]
Definition at line 1697 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u16 b43_ntab_pilot[] [static]
Initial value:
 {
        0xFF08, 0xFF08, 0xFF08, 0xFF08, 0xFF08, 0xFF08,
        0xFF08, 0xFF08, 0x80D5, 0x80D5, 0x80D5, 0x80D5,
        0x80D5, 0x80D5, 0x80D5, 0x80D5, 0xFF0A, 0xFF82,
        0xFFA0, 0xFF28, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF,
        0xFF82, 0xFFA0, 0xFF28, 0xFF0A, 0xFFFF, 0xFFFF,
        0xFFFF, 0xFFFF, 0xF83F, 0xFA1F, 0xFA97, 0xFAB5,
        0xF2BD, 0xF0BF, 0xFFFF, 0xFFFF, 0xF017, 0xF815,
        0xF215, 0xF095, 0xF035, 0xF01D, 0xFFFF, 0xFFFF,
        0xFF08, 0xFF02, 0xFF80, 0xFF20, 0xFF08, 0xFF02,
        0xFF80, 0xFF20, 0xF01F, 0xF817, 0xFA15, 0xF295,
        0xF0B5, 0xF03D, 0xFFFF, 0xFFFF, 0xF82A, 0xFA0A,
        0xFA82, 0xFAA0, 0xF2A8, 0xF0AA, 0xFFFF, 0xFFFF,
        0xF002, 0xF800, 0xF200, 0xF080, 0xF020, 0xF008,
        0xFFFF, 0xFFFF, 0xF00A, 0xF802, 0xFA00, 0xF280,
        0xF0A0, 0xF028, 0xFFFF, 0xFFFF,
}
Definition at line 688 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u16 b43_ntab_pilot_r3[] [static]
Initial value:
 {
        0xff08, 0xff08, 0xff08, 0xff08, 0xff08, 0xff08,
        0xff08, 0xff08, 0x80d5, 0x80d5, 0x80d5, 0x80d5,
        0x80d5, 0x80d5, 0x80d5, 0x80d5, 0xff0a, 0xff82,
        0xffa0, 0xff28, 0xffff, 0xffff, 0xffff, 0xffff,
        0xff82, 0xffa0, 0xff28, 0xff0a, 0xffff, 0xffff,
        0xffff, 0xffff, 0xf83f, 0xfa1f, 0xfa97, 0xfab5,
        0xf2bd, 0xf0bf, 0xffff, 0xffff, 0xf017, 0xf815,
        0xf215, 0xf095, 0xf035, 0xf01d, 0xffff, 0xffff,
        0xff08, 0xff02, 0xff80, 0xff20, 0xff08, 0xff02,
        0xff80, 0xff20, 0xf01f, 0xf817, 0xfa15, 0xf295,
        0xf0b5, 0xf03d, 0xffff, 0xffff, 0xf82a, 0xfa0a,
        0xfa82, 0xfaa0, 0xf2a8, 0xf0aa, 0xffff, 0xffff,
        0xf002, 0xf800, 0xf200, 0xf080, 0xf020, 0xf008,
        0xffff, 0xffff, 0xf00a, 0xf802, 0xfa00, 0xf280,
        0xf0a0, 0xf028, 0xffff, 0xffff,
}
Definition at line 1313 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_pilotlt[] [static]
Initial value:
 {
        0x76540123, 0x62407351, 0x76543201, 0x76540213,
        0x76540123, 0x76430521,
}
Definition at line 706 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_pilotlt_r3[] [static]
Initial value:
 {
        0x76540213, 0x62407351, 0x76543210, 0x76540213,
        0x76540213, 0x76430521,
}
Definition at line 1885 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_tdi20a0[] [static]
Initial value:
 {
        0x00091226, 0x000A1429, 0x000B56AD, 0x000C58B0,
        0x000D5AB3, 0x000E9CB6, 0x000F9EBA, 0x0000C13D,
        0x00020301, 0x00030504, 0x00040708, 0x0005090B,
        0x00064B8E, 0x00095291, 0x000A5494, 0x000B9718,
        0x000C9927, 0x000D9B2A, 0x000EDD2E, 0x000FDF31,
        0x000101B4, 0x000243B7, 0x000345BB, 0x000447BE,
        0x00058982, 0x00068C05, 0x00099309, 0x000A950C,
        0x000BD78F, 0x000CD992, 0x000DDB96, 0x000F1D99,
        0x00005FA8, 0x0001422C, 0x0002842F, 0x00038632,
        0x00048835, 0x0005CA38, 0x0006CCBC, 0x0009D3BF,
        0x000B1603, 0x000C1806, 0x000D1A0A, 0x000E1C0D,
        0x000F5E10, 0x00008093, 0x00018297, 0x0002C49A,
        0x0003C680, 0x0004C880, 0x00060B00, 0x00070D00,
        0x00000000, 0x00000000, 0x00000000,
}
Definition at line 711 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_tdi20a0_r3[] [static]
Initial value:
 {
        0x00091226, 0x000a1429, 0x000b56ad, 0x000c58b0,
        0x000d5ab3, 0x000e9cb6, 0x000f9eba, 0x0000c13d,
        0x00020301, 0x00030504, 0x00040708, 0x0005090b,
        0x00064b8e, 0x00095291, 0x000a5494, 0x000b9718,
        0x000c9927, 0x000d9b2a, 0x000edd2e, 0x000fdf31,
        0x000101b4, 0x000243b7, 0x000345bb, 0x000447be,
        0x00058982, 0x00068c05, 0x00099309, 0x000a950c,
        0x000bd78f, 0x000cd992, 0x000ddb96, 0x000f1d99,
        0x00005fa8, 0x0001422c, 0x0002842f, 0x00038632,
        0x00048835, 0x0005ca38, 0x0006ccbc, 0x0009d3bf,
        0x000b1603, 0x000c1806, 0x000d1a0a, 0x000e1c0d,
        0x000f5e10, 0x00008093, 0x00018297, 0x0002c49a,
        0x0003c680, 0x0004c880, 0x00060b00, 0x00070d00,
        0x00000000, 0x00000000, 0x00000000,
}
Definition at line 1789 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_tdi20a1[] [static]
Initial value:
 {
        0x00014B26, 0x00028D29, 0x000393AD, 0x00049630,
        0x0005D833, 0x0006DA36, 0x00099C3A, 0x000A9E3D,
        0x000BC081, 0x000CC284, 0x000DC488, 0x000F068B,
        0x0000488E, 0x00018B91, 0x0002D214, 0x0003D418,
        0x0004D6A7, 0x000618AA, 0x00071AAE, 0x0009DCB1,
        0x000B1EB4, 0x000C0137, 0x000D033B, 0x000E053E,
        0x000F4702, 0x00008905, 0x00020C09, 0x0003128C,
        0x0004148F, 0x00051712, 0x00065916, 0x00091B19,
        0x000A1D28, 0x000B5F2C, 0x000C41AF, 0x000D43B2,
        0x000E85B5, 0x000F87B8, 0x0000C9BC, 0x00024CBF,
        0x00035303, 0x00045506, 0x0005978A, 0x0006998D,
        0x00095B90, 0x000A5D93, 0x000B9F97, 0x000C821A,
        0x000D8400, 0x000EC600, 0x000FC800, 0x00010A00,
        0x00000000, 0x00000000, 0x00000000,
}
Definition at line 728 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_tdi20a1_r3[] [static]
Initial value:
 {
        0x00014b26, 0x00028d29, 0x000393ad, 0x00049630,
        0x0005d833, 0x0006da36, 0x00099c3a, 0x000a9e3d,
        0x000bc081, 0x000cc284, 0x000dc488, 0x000f068b,
        0x0000488e, 0x00018b91, 0x0002d214, 0x0003d418,
        0x0004d6a7, 0x000618aa, 0x00071aae, 0x0009dcb1,
        0x000b1eb4, 0x000c0137, 0x000d033b, 0x000e053e,
        0x000f4702, 0x00008905, 0x00020c09, 0x0003128c,
        0x0004148f, 0x00051712, 0x00065916, 0x00091b19,
        0x000a1d28, 0x000b5f2c, 0x000c41af, 0x000d43b2,
        0x000e85b5, 0x000f87b8, 0x0000c9bc, 0x00024cbf,
        0x00035303, 0x00045506, 0x0005978a, 0x0006998d,
        0x00095b90, 0x000a5d93, 0x000b9f97, 0x000c821a,
        0x000d8400, 0x000ec600, 0x000fc800, 0x00010a00,
        0x00000000, 0x00000000, 0x00000000,
}
Definition at line 1806 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_tdi40a0[] [static]
Initial value:
 {
        0x0011A346, 0x00136CCF, 0x0014F5D9, 0x001641E2,
        0x0017CB6B, 0x00195475, 0x001B2383, 0x001CAD0C,
        0x001E7616, 0x0000821F, 0x00020BA8, 0x0003D4B2,
        0x00056447, 0x00072DD0, 0x0008B6DA, 0x000A02E3,
        0x000B8C6C, 0x000D15F6, 0x0011E484, 0x0013AE0D,
        0x00153717, 0x00168320, 0x00180CA9, 0x00199633,
        0x001B6548, 0x001CEED1, 0x001EB7DB, 0x0000C3E4,
        0x00024D6D, 0x000416F7, 0x0005A585, 0x00076F0F,
        0x0008F818, 0x000A4421, 0x000BCDAB, 0x000D9734,
        0x00122649, 0x0013EFD2, 0x001578DC, 0x0016C4E5,
        0x00184E6E, 0x001A17F8, 0x001BA686, 0x001D3010,
        0x001EF999, 0x00010522, 0x00028EAC, 0x00045835,
        0x0005E74A, 0x0007B0D3, 0x00093A5D, 0x000A85E6,
        0x000C0F6F, 0x000DD8F9, 0x00126787, 0x00143111,
        0x0015BA9A, 0x00170623, 0x00188FAD, 0x001A5936,
        0x001BE84B, 0x001DB1D4, 0x001F3B5E, 0x000146E7,
        0x00031070, 0x000499FA, 0x00062888, 0x0007F212,
        0x00097B9B, 0x000AC7A4, 0x000C50AE, 0x000E1A37,
        0x0012A94C, 0x001472D5, 0x0015FC5F, 0x00174868,
        0x0018D171, 0x001A9AFB, 0x001C2989, 0x001DF313,
        0x001F7C9C, 0x000188A5, 0x000351AF, 0x0004DB38,
        0x0006AA4D, 0x000833D7, 0x0009BD60, 0x000B0969,
        0x000C9273, 0x000E5BFC, 0x00132A8A, 0x0014B414,
        0x00163D9D, 0x001789A6, 0x001912B0, 0x001ADC39,
        0x001C6BCE, 0x001E34D8, 0x001FBE61, 0x0001CA6A,
        0x00039374, 0x00051CFD, 0x0006EC0B, 0x00087515,
        0x0009FE9E, 0x000B4AA7, 0x000CD3B1, 0x000E9D3A,
        0x00000000, 0x00000000,
}
Definition at line 745 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_tdi40a0_r3[] [static]
Initial value:
 {
        0x0011a346, 0x00136ccf, 0x0014f5d9, 0x001641e2,
        0x0017cb6b, 0x00195475, 0x001b2383, 0x001cad0c,
        0x001e7616, 0x0000821f, 0x00020ba8, 0x0003d4b2,
        0x00056447, 0x00072dd0, 0x0008b6da, 0x000a02e3,
        0x000b8c6c, 0x000d15f6, 0x0011e484, 0x0013ae0d,
        0x00153717, 0x00168320, 0x00180ca9, 0x00199633,
        0x001b6548, 0x001ceed1, 0x001eb7db, 0x0000c3e4,
        0x00024d6d, 0x000416f7, 0x0005a585, 0x00076f0f,
        0x0008f818, 0x000a4421, 0x000bcdab, 0x000d9734,
        0x00122649, 0x0013efd2, 0x001578dc, 0x0016c4e5,
        0x00184e6e, 0x001a17f8, 0x001ba686, 0x001d3010,
        0x001ef999, 0x00010522, 0x00028eac, 0x00045835,
        0x0005e74a, 0x0007b0d3, 0x00093a5d, 0x000a85e6,
        0x000c0f6f, 0x000dd8f9, 0x00126787, 0x00143111,
        0x0015ba9a, 0x00170623, 0x00188fad, 0x001a5936,
        0x001be84b, 0x001db1d4, 0x001f3b5e, 0x000146e7,
        0x00031070, 0x000499fa, 0x00062888, 0x0007f212,
        0x00097b9b, 0x000ac7a4, 0x000c50ae, 0x000e1a37,
        0x0012a94c, 0x001472d5, 0x0015fc5f, 0x00174868,
        0x0018d171, 0x001a9afb, 0x001c2989, 0x001df313,
        0x001f7c9c, 0x000188a5, 0x000351af, 0x0004db38,
        0x0006aa4d, 0x000833d7, 0x0009bd60, 0x000b0969,
        0x000c9273, 0x000e5bfc, 0x00132a8a, 0x0014b414,
        0x00163d9d, 0x001789a6, 0x001912b0, 0x001adc39,
        0x001c6bce, 0x001e34d8, 0x001fbe61, 0x0001ca6a,
        0x00039374, 0x00051cfd, 0x0006ec0b, 0x00087515,
        0x0009fe9e, 0x000b4aa7, 0x000cd3b1, 0x000e9d3a,
        0x00000000, 0x00000000,
}
Definition at line 1823 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_tdi40a1[] [static]
Initial value:
 {
        0x001EDB36, 0x000129CA, 0x0002B353, 0x00047CDD,
        0x0005C8E6, 0x000791EF, 0x00091BF9, 0x000AAA07,
        0x000C3391, 0x000DFD1A, 0x00120923, 0x0013D22D,
        0x00155C37, 0x0016EACB, 0x00187454, 0x001A3DDE,
        0x001B89E7, 0x001D12F0, 0x001F1CFA, 0x00016B88,
        0x00033492, 0x0004BE1B, 0x00060A24, 0x0007D32E,
        0x00095D38, 0x000AEC4C, 0x000C7555, 0x000E3EDF,
        0x00124AE8, 0x001413F1, 0x0015A37B, 0x00172C89,
        0x0018B593, 0x001A419C, 0x001BCB25, 0x001D942F,
        0x001F63B9, 0x0001AD4D, 0x00037657, 0x0004C260,
        0x00068BE9, 0x000814F3, 0x0009A47C, 0x000B2D8A,
        0x000CB694, 0x000E429D, 0x00128C26, 0x001455B0,
        0x0015E4BA, 0x00176E4E, 0x0018F758, 0x001A8361,
        0x001C0CEA, 0x001DD674, 0x001FA57D, 0x0001EE8B,
        0x0003B795, 0x0005039E, 0x0006CD27, 0x000856B1,
        0x0009E5C6, 0x000B6F4F, 0x000CF859, 0x000E8462,
        0x00130DEB, 0x00149775, 0x00162603, 0x0017AF8C,
        0x00193896, 0x001AC49F, 0x001C4E28, 0x001E17B2,
        0x0000A6C7, 0x00023050, 0x0003F9DA, 0x00054563,
        0x00070EEC, 0x00089876, 0x000A2704, 0x000BB08D,
        0x000D3A17, 0x001185A0, 0x00134F29, 0x0014D8B3,
        0x001667C8, 0x0017F151, 0x00197ADB, 0x001B0664,
        0x001C8FED, 0x001E5977, 0x0000E805, 0x0002718F,
        0x00043B18, 0x000586A1, 0x0007502B, 0x0008D9B4,
        0x000A68C9, 0x000BF252, 0x000DBBDC, 0x0011C7E5,
        0x001390EE, 0x00151A78, 0x0016A906, 0x00183290,
        0x0019BC19, 0x001B4822, 0x001CD12C, 0x001E9AB5,
        0x00000000, 0x00000000,
}
Definition at line 776 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_tdi40a1_r3[] [static]
Initial value:
 {
        0x001edb36, 0x000129ca, 0x0002b353, 0x00047cdd,
        0x0005c8e6, 0x000791ef, 0x00091bf9, 0x000aaa07,
        0x000c3391, 0x000dfd1a, 0x00120923, 0x0013d22d,
        0x00155c37, 0x0016eacb, 0x00187454, 0x001a3dde,
        0x001b89e7, 0x001d12f0, 0x001f1cfa, 0x00016b88,
        0x00033492, 0x0004be1b, 0x00060a24, 0x0007d32e,
        0x00095d38, 0x000aec4c, 0x000c7555, 0x000e3edf,
        0x00124ae8, 0x001413f1, 0x0015a37b, 0x00172c89,
        0x0018b593, 0x001a419c, 0x001bcb25, 0x001d942f,
        0x001f63b9, 0x0001ad4d, 0x00037657, 0x0004c260,
        0x00068be9, 0x000814f3, 0x0009a47c, 0x000b2d8a,
        0x000cb694, 0x000e429d, 0x00128c26, 0x001455b0,
        0x0015e4ba, 0x00176e4e, 0x0018f758, 0x001a8361,
        0x001c0cea, 0x001dd674, 0x001fa57d, 0x0001ee8b,
        0x0003b795, 0x0005039e, 0x0006cd27, 0x000856b1,
        0x0009e5c6, 0x000b6f4f, 0x000cf859, 0x000e8462,
        0x00130deb, 0x00149775, 0x00162603, 0x0017af8c,
        0x00193896, 0x001ac49f, 0x001c4e28, 0x001e17b2,
        0x0000a6c7, 0x00023050, 0x0003f9da, 0x00054563,
        0x00070eec, 0x00089876, 0x000a2704, 0x000bb08d,
        0x000d3a17, 0x001185a0, 0x00134f29, 0x0014d8b3,
        0x001667c8, 0x0017f151, 0x00197adb, 0x001b0664,
        0x001c8fed, 0x001e5977, 0x0000e805, 0x0002718f,
        0x00043b18, 0x000586a1, 0x0007502b, 0x0008d9b4,
        0x000a68c9, 0x000bf252, 0x000dbbdc, 0x0011c7e5,
        0x001390ee, 0x00151a78, 0x0016a906, 0x00183290,
        0x0019bc19, 0x001b4822, 0x001cd12c, 0x001e9ab5,
        0x00000000, 0x00000000,
}
Definition at line 1854 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_tdtrn[] [static]
Definition at line 807 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_tdtrn_r3[] [static]
Definition at line 1451 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_tmap[] [static]
Definition at line 986 of file tables_nphy.c.
Referenced by b43_nphy_rev0_1_2_tables_init().
const u32 b43_ntab_tmap_r3[] [static]
Definition at line 1331 of file tables_nphy.c.
Referenced by b43_nphy_rev3plus_tables_init().
const u32 b43_ntab_tx_gain_rev0_1_2[]
Definition at line 2175 of file tables_nphy.c.
Referenced by b43_nphy_get_tx_gains(), b43_nphy_tx_gain_table_upload(), and b43_nphy_tx_power_fix().
const u32 b43_ntab_tx_gain_rev3_5ghz[]
Definition at line 2245 of file tables_nphy.c.
Referenced by b43_nphy_get_tx_gains(), and b43_nphy_tx_gain_table_upload().
const u32 b43_ntab_tx_gain_rev3plus_2ghz[]
Definition at line 2210 of file tables_nphy.c.
Referenced by b43_nphy_get_tx_gains(), b43_nphy_tx_gain_table_upload(), and b43_nphy_tx_power_fix().
const u32 b43_ntab_tx_gain_rev4_5ghz[]
Definition at line 2280 of file tables_nphy.c.
Referenced by b43_nphy_get_tx_gains(), and b43_nphy_tx_gain_table_upload().
const u32 b43_ntab_tx_gain_rev5plus_5ghz[]
Definition at line 2315 of file tables_nphy.c.
Referenced by b43_nphy_get_tx_gains(), and b43_nphy_tx_gain_table_upload().
struct nphy_txiqcal_ladder ladder_iq[]
Initial value:
 {
        { 3, 0 },
        { 4, 0 },
        { 6, 0 },
        { 9, 0 },
        { 13, 0 },
        { 18, 0 },
        { 25, 0 },
        { 35, 0 },
        { 50, 0 },
        { 71, 0 },
        { 100, 0 },
        { 100, 1 },
        { 100, 2 },
        { 100, 3 },
        { 100, 4 },
        { 100, 5 },
        { 100, 6 },
        { 100, 7 }
}
Definition at line 2536 of file tables_nphy.c.
Referenced by b43_nphy_update_tx_cal_ladder().
struct nphy_txiqcal_ladder ladder_lo[]
Initial value:
 {
        { 3, 0 },
        { 4, 0 },
        { 6, 0 },
        { 9, 0 },
        { 13, 0 },
        { 18, 0 },
        { 25, 0 },
        { 25, 1 },
        { 25, 2 },
        { 25, 3 },
        { 25, 4 },
        { 25, 5 },
        { 25, 6 },
        { 25, 7 },
        { 35, 7 },
        { 50, 7 },
        { 71, 7 },
        { 100, 7 }
}
Definition at line 2515 of file tables_nphy.c.
Referenced by b43_nphy_update_tx_cal_ladder().
const u16 loscale[]
Definition at line 2557 of file tables_nphy.c.
Referenced by b43_nphy_tx_pwr_ctrl_coef_setup().
struct nphy_gain_ctl_workaround_entry nphy_gain_ctl_workaround[2][3]
Definition at line 2713 of file tables_nphy.c.
const u16 tbl_iqcal_gainparams[2][9][8]
Initial value:
 {
        {
                { 0x000, 0, 0, 2, 0x69, 0x69, 0x69, 0x69 },
                { 0x700, 7, 0, 0, 0x69, 0x69, 0x69, 0x69 },
                { 0x710, 7, 1, 0, 0x68, 0x68, 0x68, 0x68 },
                { 0x720, 7, 2, 0, 0x67, 0x67, 0x67, 0x67 },
                { 0x730, 7, 3, 0, 0x66, 0x66, 0x66, 0x66 },
                { 0x740, 7, 4, 0, 0x65, 0x65, 0x65, 0x65 },
                { 0x741, 7, 4, 1, 0x65, 0x65, 0x65, 0x65 },
                { 0x742, 7, 4, 2, 0x65, 0x65, 0x65, 0x65 },
                { 0x743, 7, 4, 3, 0x65, 0x65, 0x65, 0x65 }
        },
        {
                { 0x000, 7, 0, 0, 0x79, 0x79, 0x79, 0x79 },
                { 0x700, 7, 0, 0, 0x79, 0x79, 0x79, 0x79 },
                { 0x710, 7, 1, 0, 0x79, 0x79, 0x79, 0x79 },
                { 0x720, 7, 2, 0, 0x78, 0x78, 0x78, 0x78 },
                { 0x730, 7, 3, 0, 0x78, 0x78, 0x78, 0x78 },
                { 0x740, 7, 4, 0, 0x78, 0x78, 0x78, 0x78 },
                { 0x741, 7, 4, 1, 0x78, 0x78, 0x78, 0x78 },
                { 0x742, 7, 4, 2, 0x78, 0x78, 0x78, 0x78 },
                { 0x743, 7, 4, 3, 0x78, 0x78, 0x78, 0x78 }
        }
}
Definition at line 2490 of file tables_nphy.c.
Referenced by b43_nphy_iq_cal_gain_params().
struct nphy_rf_control_override_rev2 tbl_rf_control_override_rev2[]
Initial value:
 {
        { 0x78, 0x78, 0x0038,  3 },
        { 0x7A, 0x7D, 0x0001,  0 },
        { 0x7A, 0x7D, 0x0002,  1 },
        { 0x7A, 0x7D, 0x0004,  2 },
        { 0x7A, 0x7D, 0x0030,  4 },
        { 0x7A, 0x7D, 0x00C0,  6 },
        { 0x7A, 0x7D, 0x0100,  8 },
        { 0x7A, 0x7D, 0x0200,  9 },
        { 0x78, 0x78, 0x0004,  2 },
        { 0x7B, 0x7E, 0x01FF,  0 },
        { 0x7C, 0x7F, 0x01FF,  0 },
        { 0x78, 0x78, 0x0100,  8 },
        { 0x78, 0x78, 0x0200,  9 },
        { 0x78, 0x78, 0xF000, 12 }
}
Definition at line 2677 of file tables_nphy.c.
Referenced by b43_nphy_rf_control_override().
struct nphy_rf_control_override_rev3 tbl_rf_control_override_rev3[]
Initial value:
 {
        { 0x8000, 15, 0xE5, 0xF9, 0xE6, 0xFB },
        { 0x0001,  0, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0x0002,  1, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0x0004,  2, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0x0016,  4, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0x0020,  5, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0x0040,  6, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0x0080,  6, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0x0100,  7, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0x0007,  0, 0xE7, 0xF8, 0xEC, 0xFA },
        { 0x0070,  4, 0xE7, 0xF8, 0xEC, 0xFA },
        { 0xE000, 13, 0xE7, 0x7A, 0xEC, 0x7D },
        { 0xFFFF,  0, 0xE7, 0x7B, 0xEC, 0x7E },
        { 0xFFFF,  0, 0xE7, 0x7C, 0xEC, 0x7F },
        { 0x00C0,  6, 0xE7, 0xF9, 0xEC, 0xFB }
}
Definition at line 2695 of file tables_nphy.c.
Referenced by b43_nphy_rf_control_override().
const s16 tbl_tx_filter_coef_rev4[7][15]
Initial value:
 {
        {  -377,   137,  -407,   208, -1527,
            956,    93,   186,    93,   230,
            -44,   230,    20,  -191,   201 },
        {   -77,    20,   -98,    49,   -93,
             60,    56,   111,    56,    26,
             -5,    26,    34,   -32,    34 },
        {  -360,   164,  -376,   164, -1533,
            576,   308,  -314,   308,   121,
            -73,   121,    91,   124,    91 },
        {  -295,   200,  -363,   142, -1391,
            826,   151,   301,   151,   151,
            301,   151,   602,  -752,   602 },
        {   -92,    58,   -96,    49,  -104,
             44,    17,    35,    17,    12,
             25,    12,    13,    27,    13 },
        {  -375,   136,  -399,   209, -1479,
            949,   130,   260,   130,   230,
            -44,   230,   201,  -191,   201 },
        { 0xed9,  0xc8, 0xe95,  0x8e, 0xa91,
          0x33a,  0x97, 0x12d,  0x97,  0x97,
          0x12d,  0x97, 0x25a, 0xd10, 0x25a }
}
Definition at line 2652 of file tables_nphy.c.
Referenced by b43_nphy_ext_pa_set_tx_dig_filters(), and b43_nphy_int_pa_set_tx_dig_filters().
const u16 tbl_tx_iqlo_cal_cmds_fullcal[]
Initial value:
 {
        0x8123, 0x8264, 0x8086, 0x8245,
        0x8056, 0x9123, 0x9264, 0x9086,
        0x9245, 0x9056
}
Definition at line 2640 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_cmds_fullcal_nphyrev3[]
Initial value:
 {
        0x8434, 0x8334, 0x8084, 0x8267,
        0x8056, 0x8234, 0x9434, 0x9334,
        0x9084, 0x9267, 0x9056, 0x9234
}
Definition at line 2646 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_cmds_recal[]
Initial value:
 {
        0x8101, 0x8253, 0x8053, 0x8234,
        0x8034, 0x9101, 0x9253, 0x9053,
        0x9234, 0x9034
}
Definition at line 2634 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_cmds_recal_nphyrev3[]
Initial value:
 {
        0x8423, 0x8323, 0x8073, 0x8256,
        0x8045, 0x8223, 0x9423, 0x9323,
        0x9073, 0x9256, 0x9045, 0x9223
}
Definition at line 2628 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_iqimb_ladder_20[]
Initial value:
 {
        0x0200, 0x0300, 0x0600, 0x0900,
        0x0d00, 0x1100, 0x1900, 0x2400,
        0x3200, 0x4600, 0x6400, 0x6401,
        0x6402, 0x6403, 0x6404, 0x6405,
        0x6406, 0x6407
}
Definition at line 2616 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_iqimb_ladder_40[]
Initial value:
 {
        0x0100, 0x0200, 0x0400, 0x0700,
        0x0900, 0x0c00, 0x1200, 0x1900,
        0x2300, 0x3200, 0x4700, 0x4701,
        0x4702, 0x4703, 0x4704, 0x4705,
        0x4706, 0x4707
}
Definition at line 2608 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_loft_ladder_20[]
Initial value:
 {
        0x0300, 0x0500, 0x0700, 0x0900,
        0x0d00, 0x1100, 0x1900, 0x1901,
        0x1902, 0x1903, 0x1904, 0x1905,
        0x1906, 0x1907, 0x2407, 0x3207,
        0x4607, 0x6407
}
Definition at line 2600 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_loft_ladder_40[]
Initial value:
 {
        0x0200, 0x0300, 0x0400, 0x0700,
        0x0900, 0x0c00, 0x1200, 0x1201,
        0x1202, 0x1203, 0x1204, 0x1205,
        0x1206, 0x1207, 0x1907, 0x2307,
        0x3207, 0x4707
}
Definition at line 2592 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_startcoefs[B43_NTAB_TX_IQLO_CAL_STARTCOEFS] = { }
Definition at line 2626 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u16 tbl_tx_iqlo_cal_startcoefs_nphyrev3[B43_NTAB_TX_IQLO_CAL_STARTCOEFS_REV3] = { }
Definition at line 2624 of file tables_nphy.c.
Referenced by b43_nphy_cal_tx_iq_lo().
const u32 txpwrctrl_tx_gain_ipa[]
Definition at line 2350 of file tables_nphy.c.
Referenced by b43_nphy_get_ipa_gain_table().
const u32 txpwrctrl_tx_gain_ipa_5g[]
Definition at line 2455 of file tables_nphy.c.
Referenced by b43_nphy_get_ipa_gain_table().
const u32 txpwrctrl_tx_gain_ipa_rev5[]
Definition at line 2385 of file tables_nphy.c.
Referenced by b43_nphy_get_ipa_gain_table().
const u32 txpwrctrl_tx_gain_ipa_rev6[]
Definition at line 2420 of file tables_nphy.c.
Referenced by b43_nphy_get_ipa_gain_table().