CompatWireless3.2: drivers/net/wireless/b43/tables_phy_lcn.h File Reference
drivers/net/wireless/b43/tables_phy_lcn.h File Reference
Defines
#define B43_LCNTAB_TYPEMASK 0xF0000000
#define B43_LCNTAB_8BIT 0x10000000
#define B43_LCNTAB_16BIT 0x20000000
#define B43_LCNTAB_32BIT 0x30000000
#define B43_LCNTAB8(table, offset) (((table) << 10) | (offset) | B43_LCNTAB_8BIT)
#define B43_LCNTAB16(table, offset) (((table) << 10) | (offset) | B43_LCNTAB_16BIT)
#define B43_LCNTAB32(table, offset) (((table) << 10) | (offset) | B43_LCNTAB_32BIT)
#define B43_LCNTAB_TX_GAIN_SIZE 128
Functions
u32 b43_lcntab_read (struct b43_wldev *dev, u32 offset)
void b43_lcntab_read_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, void *_data)
void b43_lcntab_write (struct b43_wldev *dev, u32 offset, u32 value)
void b43_lcntab_write_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, const void *_data)
void b43_phy_lcn_tables_init (struct b43_wldev *dev)
Define Documentation
#define B43_LCNTAB16 (table, offset) (((table) << 10) | (offset) | B43_LCNTAB_16BIT)
Definition at line 10 of file tables_phy_lcn.h.
Referenced by b43_phy_lcn_sense_setup(), b43_phy_lcn_set_bbmult(), b43_phy_lcn_tables_init(), b43_phy_lcn_upload_static_tables(), and b43_radio_2064_init().
#define B43_LCNTAB32 (table, offset) (((table) << 10) | (offset) | B43_LCNTAB_32BIT)
Definition at line 11 of file tables_phy_lcn.h.
Referenced by b43_phy_lcn_clean_papd_comp_table(), b43_phy_lcn_load_rfpower(), b43_phy_lcn_load_tx_gain_tab(), b43_phy_lcn_rewrite_rfpower_table(), and b43_phy_lcn_upload_static_tables().
#define B43_LCNTAB8 (table, offset) (((table) << 10) | (offset) | B43_LCNTAB_8BIT)
Definition at line 9 of file tables_phy_lcn.h.
#define B43_LCNTAB_16BIT 0x20000000
Definition at line 7 of file tables_phy_lcn.h.
Referenced by b43_lcntab_read(), b43_lcntab_read_bulk(), b43_lcntab_write(), and b43_lcntab_write_bulk().
#define B43_LCNTAB_32BIT 0x30000000
Definition at line 8 of file tables_phy_lcn.h.
Referenced by b43_lcntab_read(), b43_lcntab_read_bulk(), b43_lcntab_write(), and b43_lcntab_write_bulk().
#define B43_LCNTAB_8BIT 0x10000000
Definition at line 6 of file tables_phy_lcn.h.
Referenced by b43_lcntab_read(), b43_lcntab_read_bulk(), b43_lcntab_write(), and b43_lcntab_write_bulk().
#define B43_LCNTAB_TX_GAIN_SIZE 128
Definition at line 13 of file tables_phy_lcn.h.
Referenced by b43_phy_lcn_load_tx_gain_tab().
#define B43_LCNTAB_TYPEMASK 0xF0000000
Definition at line 5 of file tables_phy_lcn.h.
Referenced by b43_lcntab_read(), b43_lcntab_read_bulk(), b43_lcntab_write(), and b43_lcntab_write_bulk().
Function Documentation
u32 b43_lcntab_read (struct b43_wldev * dev, u32 offset)
Definition at line 470 of file tables_phy_lcn.c.
References B43_LCNTAB_16BIT, B43_LCNTAB_32BIT, B43_LCNTAB_8BIT, B43_LCNTAB_TYPEMASK, B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_lcn_load_rfpower(), b43_phy_lcn_load_tx_gain_tab(), and b43_phy_lcn_rewrite_rfpower_table().
void b43_lcntab_read_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, void * _data)
Definition at line 500 of file tables_phy_lcn.c.
References B43_LCNTAB_16BIT, B43_LCNTAB_32BIT, B43_LCNTAB_8BIT, B43_LCNTAB_TYPEMASK, B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
void b43_lcntab_write (struct b43_wldev * dev, u32 offset, u32 value)
Definition at line 538 of file tables_phy_lcn.c.
References B43_LCNTAB_16BIT, B43_LCNTAB_32BIT, B43_LCNTAB_8BIT, B43_LCNTAB_TYPEMASK, B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_lcn_clean_papd_comp_table(), b43_phy_lcn_load_tx_gain_tab(), b43_phy_lcn_rewrite_rfpower_table(), b43_phy_lcn_sense_setup(), b43_phy_lcn_set_bbmult(), and b43_radio_2064_init().
void b43_lcntab_write_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, const void * _data)
Definition at line 568 of file tables_phy_lcn.c.
References B43_LCNTAB_16BIT, B43_LCNTAB_32BIT, B43_LCNTAB_8BIT, B43_LCNTAB_TYPEMASK, B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_lcn_tables_init().
void b43_phy_lcn_tables_init (struct b43_wldev * dev)
Definition at line 698 of file tables_phy_lcn.c.
References B43_BFH_FEM_BT, B43_BFL_FEM, b43_current_band(), B43_LCNTAB16, b43_lcntab_sw_ctl_4313_epa_rev0, b43_lcntab_write_bulk(), b43_phy_lcn_clean_papd_comp_table(), b43_phy_lcn_load_rfpower(), b43_phy_lcn_load_tx_gain_tab(), b43_phy_lcn_rewrite_rfpower_table(), b43_phy_lcn_upload_static_tables(), b43err(), b43_bus_dev::bus_sprom, b43_wldev::dev, and b43_wldev::wl.
Referenced by b43_phy_lcn_op_init().