CompatWireless3.2: drivers/net/wireless/b43/tables_lpphy.c File Reference
drivers/net/wireless/b43/tables_lpphy.c File Reference
#include "b43.h"
#include "tables_lpphy.h"
#include "phy_common.h"
#include "phy_lp.h"
Data Structures
struct b206x_init_tab_entry
Defines
#define B206X_FLAG_A 0x01
#define B206X_FLAG_G 0x02
Functions
void b2062_upload_init_table (struct b43_wldev *dev)
void b2063_upload_init_table (struct b43_wldev *dev)
u32 b43_lptab_read (struct b43_wldev *dev, u32 offset)
void b43_lptab_read_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, void *_data)
void b43_lptab_write (struct b43_wldev *dev, u32 offset, u32 value)
void b43_lptab_write_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, const void *_data)
void lpphy_rev0_1_table_init (struct b43_wldev *dev)
void lpphy_rev2plus_table_init (struct b43_wldev *dev)
static void lpphy_rev0_1_write_gain_table (struct b43_wldev *dev, int offset, struct lpphy_tx_gain_table_entry data)
static void lpphy_rev2plus_write_gain_table (struct b43_wldev *dev, int offset, struct lpphy_tx_gain_table_entry data)
void lpphy_write_gain_table (struct b43_wldev *dev, int offset, struct lpphy_tx_gain_table_entry data)
void lpphy_write_gain_table_bulk (struct b43_wldev *dev, int offset, int count, struct lpphy_tx_gain_table_entry *table)
void lpphy_init_tx_gain_table (struct b43_wldev *dev)
Variables
static struct b206x_init_tab_entry b2062_init_tab []
static struct b206x_init_tab_entry b2063_init_tab []
static const u8 lpphy_min_sig_sq_table []
static const u16 lpphy_rev01_noise_scale_table []
static const u16 lpphy_rev2plus_noise_scale_table []
static const u16 lpphy_crs_gain_nft_table []
static const u16 lpphy_rev01_filter_control_table []
static const u32 lpphy_rev2plus_filter_control_table []
static const u32 lpphy_rev01_ps_control_table []
static const u32 lpphy_rev2plus_ps_control_table []
static const u8 lpphy_pll_fraction_table []
static const u16 lpphy_iqlo_cal_table []
static const u16 lpphy_rev0_ofdm_cck_gain_table []
static const u16 lpphy_rev1_ofdm_cck_gain_table []
static const u16 lpphy_gain_delta_table []
static const u32 lpphy_tx_power_control_table []
static const u32 lpphy_gain_idx_table []
static const u16 lpphy_aux_gain_idx_table []
static const u32 lpphy_gain_value_table []
static const u16 lpphy_gain_table []
static const u32 lpphy_a0_gain_idx_table []
static const u16 lpphy_a0_aux_gain_idx_table []
static const u32 lpphy_a0_gain_value_table []
static const u16 lpphy_a0_gain_table []
static const u16 lpphy_sw_control_table []
static const u8 lpphy_hf_table []
static const u32 lpphy_papd_eps_table []
static const u32 lpphy_papd_mult_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev0_nopa_tx_gain_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev0_2ghz_tx_gain_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev0_5ghz_tx_gain_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev1_nopa_tx_gain_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev1_2ghz_tx_gain_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev1_5ghz_tx_gain_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev2_nopa_tx_gain_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev2_2ghz_tx_gain_table []
static struct
lpphy_tx_gain_table_entry lpphy_rev2_5ghz_tx_gain_table []
Define Documentation
#define B206X_FLAG_A 0x01
Definition at line 39 of file tables_lpphy.c.
Referenced by b2062_upload_init_table(), and b2063_upload_init_table().
#define B206X_FLAG_G 0x02
Definition at line 40 of file tables_lpphy.c.
Referenced by b2062_upload_init_table(), and b2063_upload_init_table().
Function Documentation
void b2062_upload_init_table (struct b43_wldev * dev)
Definition at line 556 of file tables_lpphy.c.
References B206X_FLAG_A, B206X_FLAG_G, b43_current_band(), b43_radio_write(), b206x_init_tab_entry::flags, b206x_init_tab_entry::offset, b206x_init_tab_entry::value_a, b206x_init_tab_entry::value_g, and b43_wldev::wl.
Referenced by lpphy_2062_init().
void b2063_upload_init_table (struct b43_wldev * dev)
Definition at line 575 of file tables_lpphy.c.
References B206X_FLAG_A, B206X_FLAG_G, b43_current_band(), b43_radio_write(), b206x_init_tab_entry::flags, b206x_init_tab_entry::offset, b206x_init_tab_entry::value_a, b206x_init_tab_entry::value_g, and b43_wldev::wl.
Referenced by lpphy_2063_init().
u32 b43_lptab_read (struct b43_wldev * dev, u32 offset)
Definition at line 594 of file tables_lpphy.c.
References B43_LPPHY_TABLE_ADDR, B43_LPPHY_TABLEDATAHI, B43_LPPHY_TABLEDATALO, B43_LPTAB_16BIT, B43_LPTAB_32BIT, B43_LPTAB_8BIT, B43_LPTAB_TYPEMASK, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by lpphy_get_bb_mult(), lpphy_set_rx_gain_by_index(), and lpphy_set_tx_power_by_index().
void b43_lptab_read_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, void * _data)
Definition at line 625 of file tables_lpphy.c.
References B43_LPPHY_TABLE_ADDR, B43_LPPHY_TABLEDATAHI, B43_LPPHY_TABLEDATALO, B43_LPTAB_16BIT, B43_LPTAB_32BIT, B43_LPTAB_8BIT, B43_LPTAB_TYPEMASK, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by lpphy_pr41573_workaround().
void b43_lptab_write (struct b43_wldev * dev, u32 offset, u32 value)
Definition at line 660 of file tables_lpphy.c.
References B43_LPPHY_TABLE_ADDR, B43_LPPHY_TABLEDATAHI, B43_LPPHY_TABLEDATALO, B43_LPTAB_16BIT, B43_LPTAB_32BIT, B43_LPTAB_8BIT, B43_LPTAB_TYPEMASK, b43_phy_write(), and B43_WARN_ON.
Referenced by lpphy_baseband_rev0_1_init(), lpphy_baseband_rev2plus_init(), lpphy_rev0_1_write_gain_table(), lpphy_rev2plus_table_init(), lpphy_rev2plus_write_gain_table(), lpphy_set_bb_mult(), lpphy_set_tx_power_by_index(), and lpphy_tx_pctl_init_hw().
void b43_lptab_write_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, const void * _data)
Definition at line 689 of file tables_lpphy.c.
References B43_LPPHY_TABLE_ADDR, B43_LPPHY_TABLEDATAHI, B43_LPPHY_TABLEDATALO, B43_LPTAB_16BIT, B43_LPTAB_32BIT, B43_LPTAB_8BIT, B43_LPTAB_TYPEMASK, b43_phy_write(), and B43_WARN_ON.
Referenced by lpphy_adjust_gain_table(), lpphy_pr41573_workaround(), lpphy_rev0_1_table_init(), lpphy_rev2plus_table_init(), lpphy_set_tx_iqcc(), and lpphy_start_tx_tone().
void lpphy_init_tx_gain_table (struct b43_wldev * dev)
Definition at line 2416 of file tables_lpphy.c.
References B43_BFH_NOPA, B43_BFL_HGPA, b43_current_band(), b43_bus_dev::bus_sprom, b43_wldev::dev, lpphy_write_gain_table_bulk(), b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by lpphy_table_init().
void lpphy_rev0_1_table_init (struct b43_wldev * dev)
Definition at line 2270 of file tables_lpphy.c.
References B43_LPTAB16, B43_LPTAB32, B43_LPTAB8, b43_lptab_write_bulk(), B43_WARN_ON, lpphy_crs_gain_nft_table, lpphy_gain_delta_table, lpphy_iqlo_cal_table, lpphy_min_sig_sq_table, lpphy_pll_fraction_table, lpphy_rev01_filter_control_table, lpphy_rev01_noise_scale_table, lpphy_rev01_ps_control_table, lpphy_rev0_ofdm_cck_gain_table, lpphy_rev1_ofdm_cck_gain_table, lpphy_tx_power_control_table, b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_table_init().
static void lpphy_rev0_1_write_gain_table (struct b43_wldev * dev, int offset, struct lpphy_tx_gain_table_entry data) [static]
Definition at line 2355 of file tables_lpphy.c.
References B43_LPTAB32, b43_lptab_write(), B43_WARN_ON, lpphy_tx_gain_table_entry::bb_mult, lpphy_tx_gain_table_entry::dac, lpphy_tx_gain_table_entry::gm, lpphy_tx_gain_table_entry::pad, lpphy_tx_gain_table_entry::pga, b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_write_gain_table().
void lpphy_rev2plus_table_init (struct b43_wldev * dev)
Definition at line 2305 of file tables_lpphy.c.
References B43_LPTAB16, B43_LPTAB32, B43_LPTAB8, b43_lptab_write(), b43_lptab_write_bulk(), B43_WARN_ON, b43_bus_dev::chip_id, b43_bus_dev::chip_rev, b43_wldev::dev, lpphy_a0_aux_gain_idx_table, lpphy_a0_gain_idx_table, lpphy_a0_gain_table, lpphy_a0_gain_value_table, lpphy_aux_gain_idx_table, lpphy_gain_idx_table, lpphy_gain_table, lpphy_gain_value_table, lpphy_hf_table, lpphy_iqlo_cal_table, lpphy_min_sig_sq_table, lpphy_papd_eps_table, lpphy_papd_mult_table, lpphy_pll_fraction_table, lpphy_rev2plus_filter_control_table, lpphy_rev2plus_noise_scale_table, lpphy_rev2plus_ps_control_table, lpphy_sw_control_table, b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_table_init().
static void lpphy_rev2plus_write_gain_table (struct b43_wldev * dev, int offset, struct lpphy_tx_gain_table_entry data) [static]
Definition at line 2371 of file tables_lpphy.c.
References b43_current_band(), B43_LPTAB32, b43_lptab_write(), B43_WARN_ON, lpphy_tx_gain_table_entry::bb_mult, lpphy_tx_gain_table_entry::dac, lpphy_tx_gain_table_entry::gm, lpphy_tx_gain_table_entry::pad, lpphy_tx_gain_table_entry::pga, b43_wldev::phy, b43_phy::rev, and b43_wldev::wl.
Referenced by lpphy_write_gain_table().
void lpphy_write_gain_table (struct b43_wldev * dev, int offset, struct lpphy_tx_gain_table_entry data)
Definition at line 2398 of file tables_lpphy.c.
References lpphy_rev0_1_write_gain_table(), lpphy_rev2plus_write_gain_table(), b43_wldev::phy, and b43_phy::rev.
Referenced by lpphy_write_gain_table_bulk().
void lpphy_write_gain_table_bulk (struct b43_wldev * dev, int offset, int count, struct lpphy_tx_gain_table_entry * table)
Definition at line 2407 of file tables_lpphy.c.
References lpphy_write_gain_table().
Referenced by lpphy_init_tx_gain_table().
Variable Documentation
struct b206x_init_tab_entry b2062_init_tab[] [static]
Definition at line 42 of file tables_lpphy.c.
struct b206x_init_tab_entry b2063_init_tab[] [static]
Definition at line 257 of file tables_lpphy.c.
const u16 lpphy_a0_aux_gain_idx_table[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0002, 0x0014, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0002, 0x0014,
}
Definition at line 1003 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u32 lpphy_a0_gain_idx_table[] [static]
Initial value:
 {
        0x001111e0, 0x00652051, 0x00606055, 0x005b005a, 0x00555060, 0x00511065,
        0x004c806b, 0x0047d072, 0x00444078, 0x00400080, 0x003ca087, 0x0039408f,
        0x0035e098, 0x0032e0a1, 0x003030aa, 0x002d80b4, 0x002ae0bf, 0x002880ca,
        0x002640d6, 0x002410e3, 0x002220f0, 0x002020ff, 0x001e510e, 0x001ca11e,
        0x001b012f, 0x00199140, 0x00182153, 0x0016c168, 0x0015817d, 0x00145193,
        0x001321ab, 0x001211c5, 0x001111e0, 0x001021fc, 0x000f321a, 0x000e523a,
        0x000d925c, 0x000cd27f, 0x000c12a5, 0x000b62cd, 0x000ac2f8, 0x000a2325,
        0x00099355, 0x00091387, 0x000883bd, 0x000813f5, 0x0007a432, 0x00073471,
        0x0006c4b5, 0x000664fc, 0x00061547, 0x0005b598, 0x000565ec, 0x00051646,
        0x0004d6a5, 0x0004870a, 0x00044775, 0x000407e6, 0x0003d85e, 0x000398dd,
        0x00036963, 0x000339f2, 0x00030a89, 0x0002db28,
}
Definition at line 989 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u16 lpphy_a0_gain_table[] [static]
Initial value:
 {
        0x0000, 0x0002, 0x0004, 0x0006, 0x0007, 0x0008, 0x000a, 0x000b, 0x000c,
        0x000e, 0x000f, 0x0010, 0x0012, 0x0013, 0x0014, 0x0016, 0x0017, 0x001a,
        0x001b, 0x001f, 0x0020, 0x0024, 0x0030, 0x0034, 0x0037, 0x003b, 0x003f,
        0x0040, 0x0044, 0x0057, 0x005b, 0x005f, 0x00d7, 0x00db, 0x00df, 0x0157,
        0x015b, 0x015f, 0x0357, 0x035b, 0x035f, 0x075f, 0x0b5f, 0x0f5f, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
}
Definition at line 1024 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u32 lpphy_a0_gain_value_table[] [static]
Initial value:
 {
        0x00000008, 0x0000000e, 0x00000014, 0x0000001a, 0x000000fb, 0x00000004,
        0x00000008, 0x0000000d, 0x00000001, 0x00000004, 0x00000007, 0x0000000a,
        0x0000000d, 0x00000010, 0x00000012, 0x00000015, 0x00000000, 0x00000006,
        0x0000000c, 0x00000000, 0x00000000, 0x00000000, 0x00000012, 0x00000000,
        0x00000000, 0x00000000, 0x00000018, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x0000001e, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000003, 0x00000006, 0x00000009, 0x0000000c, 0x0000000f,
        0x00000012, 0x00000015, 0x00000018, 0x0000001b, 0x0000001e, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x0000000f, 0x000000f7,
        0x00000000, 0x00000000,
}
Definition at line 1009 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u16 lpphy_aux_gain_idx_table[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0001, 0x0002, 0x0004, 0x0016, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0001, 0x0002, 0x0004, 0x0016,
}
Definition at line 954 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u16 lpphy_crs_gain_nft_table[] [static]
Initial value:
 {
        0x0366, 0x036a, 0x036f, 0x0364, 0x0367, 0x036d, 0x0374, 0x037f, 0x036f,
        0x037b, 0x038a, 0x0378, 0x0367, 0x036d, 0x0375, 0x0381, 0x0374, 0x0381,
        0x0392, 0x03a9, 0x03c4, 0x03e1, 0x0001, 0x001f, 0x0040, 0x005e, 0x007f,
        0x009e, 0x00bd, 0x00dd, 0x00fd, 0x011d, 0x013d,
}
Definition at line 755 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init().
const u16 lpphy_gain_delta_table[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
}
Definition at line 823 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init().
const u32 lpphy_gain_idx_table[] [static]
Initial value:
 {
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x10000001, 0x00000000, 0x20000082, 0x00000000, 0x40000104, 0x00000000,
        0x60004207, 0x00000001, 0x7000838a, 0x00000001, 0xd021050d, 0x00000001,
        0xe041c683, 0x00000001, 0x50828805, 0x00000000, 0x80e34288, 0x00000000,
        0xb144040b, 0x00000000, 0xe1a6058e, 0x00000000, 0x12064711, 0x00000001,
        0xb0a18612, 0x00000010, 0xe1024794, 0x00000010, 0x11630915, 0x00000011,
        0x31c3ca1b, 0x00000011, 0xc1848a9c, 0x00000018, 0xf1e50da0, 0x00000018,
        0x22468e21, 0x00000019, 0x4286d023, 0x00000019, 0xa347d0a4, 0x00000019,
        0xb36811a6, 0x00000019, 0xf3e89227, 0x00000019, 0x0408d329, 0x0000001a,
        0x244953aa, 0x0000001a, 0x346994ab, 0x0000001a, 0x54aa152c, 0x0000001a,
        0x64ca55ad, 0x0000001a, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x10000001, 0x00000000, 0x20000082, 0x00000000,
        0x40000104, 0x00000000, 0x60004207, 0x00000001, 0x7000838a, 0x00000001,
        0xd021050d, 0x00000001, 0xe041c683, 0x00000001, 0x50828805, 0x00000000,
        0x80e34288, 0x00000000, 0xb144040b, 0x00000000, 0xe1a6058e, 0x00000000,
        0x12064711, 0x00000001, 0xb0a18612, 0x00000010, 0xe1024794, 0x00000010,
        0x11630915, 0x00000011, 0x31c3ca1b, 0x00000011, 0xc1848a9c, 0x00000018,
        0xf1e50da0, 0x00000018, 0x22468e21, 0x00000019, 0x4286d023, 0x00000019,
        0xa347d0a4, 0x00000019, 0xb36811a6, 0x00000019, 0xf3e89227, 0x00000019,
        0x0408d329, 0x0000001a, 0x244953aa, 0x0000001a, 0x346994ab, 0x0000001a,
        0x54aa152c, 0x0000001a, 0x64ca55ad, 0x0000001a,
}
Definition at line 926 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u16 lpphy_gain_table[] [static]
Initial value:
 {
        0x0000, 0x0400, 0x0800, 0x0802, 0x0804, 0x0806, 0x0807, 0x0808, 0x080a,
        0x080b, 0x080c, 0x080e, 0x080f, 0x0810, 0x0812, 0x0813, 0x0814, 0x0816,
        0x0817, 0x081a, 0x081b, 0x081f, 0x0820, 0x0824, 0x0830, 0x0834, 0x0837,
        0x083b, 0x083f, 0x0840, 0x0844, 0x0857, 0x085b, 0x085f, 0x08d7, 0x08db,
        0x08df, 0x0957, 0x095b, 0x095f, 0x0b57, 0x0b5b, 0x0b5f, 0x0f5f, 0x135f,
        0x175f, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
}
Definition at line 975 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u32 lpphy_gain_value_table[] [static]
Initial value:
 {
        0x00000008, 0x0000000e, 0x00000014, 0x0000001a, 0x000000fb, 0x00000004,
        0x00000008, 0x0000000d, 0x00000001, 0x00000004, 0x00000007, 0x0000000a,
        0x0000000d, 0x00000010, 0x00000012, 0x00000015, 0x00000000, 0x00000006,
        0x0000000c, 0x00000000, 0x00000000, 0x00000000, 0x00000012, 0x00000000,
        0x00000000, 0x00000000, 0x00000018, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x0000001e, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000003, 0x00000006, 0x00000009, 0x0000000c, 0x0000000f,
        0x00000012, 0x00000015, 0x00000018, 0x0000001b, 0x0000001e, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000009, 0x000000f1,
        0x00000000, 0x00000000,
}
Definition at line 960 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u8 lpphy_hf_table[] [static]
Initial value:
 {
        0x4b, 0x36, 0x24, 0x18, 0x49, 0x34, 0x23, 0x17, 0x48,
        0x33, 0x23, 0x17, 0x48, 0x33, 0x23, 0x17,
}
Definition at line 1049 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u16 lpphy_iqlo_cal_table[] [static]
Initial value:
 {
        0x0200, 0x0300, 0x0400, 0x0600, 0x0800, 0x0b00, 0x1000, 0x1001, 0x1002,
        0x1003, 0x1004, 0x1005, 0x1006, 0x1007, 0x1707, 0x2007, 0x2d07, 0x4007,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0200, 0x0300, 0x0400, 0x0600,
        0x0800, 0x0b00, 0x1000, 0x1001, 0x1002, 0x1003, 0x1004, 0x1005, 0x1006,
        0x1007, 0x1707, 0x2007, 0x2d07, 0x4007, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x4000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
}
Definition at line 794 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init(), and lpphy_rev2plus_table_init().
const u8 lpphy_min_sig_sq_table[] [static]
Initial value:
 {
        0xde, 0xdc, 0xda, 0xd8, 0xd6, 0xd4, 0xd2, 0xcf, 0xcd,
        0xca, 0xc7, 0xc4, 0xc1, 0xbe, 0xbe, 0xbe, 0xbe, 0xbe,
        0xbe, 0xbe, 0xbe, 0xbe, 0xbe, 0xbe, 0xbe, 0xbe, 0x00,
        0xbe, 0xbe, 0xbe, 0xbe, 0xbe, 0xbe, 0xbe, 0xbe, 0xbe,
        0xbe, 0xbe, 0xbe, 0xbe, 0xc1, 0xc4, 0xc7, 0xca, 0xcd,
        0xcf, 0xd2, 0xd4, 0xd6, 0xd8, 0xda, 0xdc, 0xde,
}
Definition at line 728 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init(), and lpphy_rev2plus_table_init().
const u32 lpphy_papd_eps_table[] [static]
Initial value:
 {
        0x00000000, 0x00013ffc, 0x0001dff3, 0x0001bff0, 0x00023fe9, 0x00021fdf,
        0x00028fdf, 0x00033fd2, 0x00039fcb, 0x00043fc7, 0x0004efc2, 0x00055fb5,
        0x0005cfb0, 0x00063fa8, 0x00068fa3, 0x00071f98, 0x0007ef92, 0x00084f8b,
        0x0008df82, 0x00097f77, 0x0009df69, 0x000a3f62, 0x000adf57, 0x000b6f4c,
        0x000bff41, 0x000c9f39, 0x000cff30, 0x000dbf27, 0x000e4f1e, 0x000edf16,
        0x000f7f13, 0x00102f11, 0x00110f10, 0x0011df11, 0x0012ef15, 0x00143f1c,
        0x00158f27, 0x00172f35, 0x00193f47, 0x001baf5f, 0x001e6f7e, 0x0021cfa4,
        0x0025bfd2, 0x002a2008, 0x002fb047, 0x00360090, 0x003d40e0, 0x0045c135,
        0x004fb189, 0x005ae1d7, 0x0067221d, 0x0075025a, 0x007ff291, 0x007ff2bf,
        0x007ff2e3, 0x007ff2ff, 0x007ff315, 0x007ff329, 0x007ff33f, 0x007ff356,
        0x007ff36e, 0x007ff39c, 0x007ff441, 0x007ff506,
}
Definition at line 1054 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u32 lpphy_papd_mult_table[] [static]
Initial value:
 {
        0x001111e0, 0x00652051, 0x00606055, 0x005b005a, 0x00555060, 0x00511065,
        0x004c806b, 0x0047d072, 0x00444078, 0x00400080, 0x003ca087, 0x0039408f,
        0x0035e098, 0x0032e0a1, 0x003030aa, 0x002d80b4, 0x002ae0bf, 0x002880ca,
        0x002640d6, 0x002410e3, 0x002220f0, 0x002020ff, 0x001e510e, 0x001ca11e,
        0x001b012f, 0x00199140, 0x00182153, 0x0016c168, 0x0015817d, 0x00145193,
        0x001321ab, 0x001211c5, 0x001111e0, 0x001021fc, 0x000f321a, 0x000e523a,
        0x000d925c, 0x000cd27f, 0x000c12a5, 0x000b62cd, 0x000ac2f8, 0x000a2325,
        0x00099355, 0x00091387, 0x000883bd, 0x000813f5, 0x0007a432, 0x00073471,
        0x0006c4b5, 0x000664fc, 0x00061547, 0x0005b598, 0x000565ec, 0x00051646,
        0x0004d6a5, 0x0004870a, 0x00044775, 0x000407e6, 0x0003d85e, 0x000398dd,
        0x00036963, 0x000339f2, 0x00030a89, 0x0002db28,
}
Definition at line 1068 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u8 lpphy_pll_fraction_table[] [static]
Initial value:
 {
        0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x00, 0x00, 0x80,
        0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80,
}
Definition at line 789 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init(), and lpphy_rev2plus_table_init().
const u16 lpphy_rev01_filter_control_table[] [static]
Initial value:
 {
        0xa0fc, 0x10fc, 0x10db, 0x20b7, 0xff93, 0x10bf, 0x109b, 0x2077, 0xff53,
        0x0127,
}
Definition at line 762 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init().
const u16 lpphy_rev01_noise_scale_table[] [static]
Initial value:
 {
        0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4,
        0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa400, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4,
        0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0xa4a4, 0x00a4,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x4c00, 0x2d36,
        0x0000, 0x0000, 0x4c00, 0x2d36,
}
Definition at line 737 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init().
const u32 lpphy_rev01_ps_control_table[] [static]
Initial value:
 {
        0x00010000, 0x000000a0, 0x00040000, 0x00000048, 0x08080101, 0x00000080,
        0x08080101, 0x00000040, 0x08080101, 0x000000c0, 0x08a81501, 0x000000c0,
        0x0fe8fd01, 0x000000c0, 0x08300105, 0x000000c0, 0x08080201, 0x000000c0,
        0x08280205, 0x000000c0, 0xe80802fe, 0x000000c7, 0x28080206, 0x000000c0,
        0x08080202, 0x000000c0, 0x0ba87602, 0x000000c0, 0x1068013d, 0x000000c0,
        0x10280105, 0x000000c0, 0x08880102, 0x000000c0, 0x08280106, 0x000000c0,
        0xe80801fd, 0x000000c7, 0xa8080115, 0x000000c0,
}
Definition at line 772 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init().
struct lpphy_tx_gain_table_entry lpphy_rev0_2ghz_tx_gain_table[] [static]
Definition at line 1213 of file tables_lpphy.c.
struct lpphy_tx_gain_table_entry lpphy_rev0_5ghz_tx_gain_table[] [static]
Definition at line 1344 of file tables_lpphy.c.
struct lpphy_tx_gain_table_entry lpphy_rev0_nopa_tx_gain_table[] [static]
Definition at line 1082 of file tables_lpphy.c.
const u16 lpphy_rev0_ofdm_cck_gain_table[] [static]
Initial value:
 {
        0x0001, 0x0001, 0x0001, 0x0001, 0x1001, 0x2001, 0x3001, 0x4001, 0x5001,
        0x6001, 0x7001, 0x7011, 0x7021, 0x2035, 0x2045, 0x2055, 0x2065, 0x2075,
        0x006d, 0x007d, 0x014d, 0x015d, 0x115d, 0x035d, 0x135d, 0x055d, 0x155d,
        0x0d5d, 0x1d5d, 0x2d5d, 0x555d, 0x655d, 0x755d,
}
Definition at line 809 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init().
struct lpphy_tx_gain_table_entry lpphy_rev1_2ghz_tx_gain_table[] [static]
Definition at line 1615 of file tables_lpphy.c.
struct lpphy_tx_gain_table_entry lpphy_rev1_5ghz_tx_gain_table[] [static]
Definition at line 1746 of file tables_lpphy.c.
struct lpphy_tx_gain_table_entry lpphy_rev1_nopa_tx_gain_table[] [static]
Definition at line 1475 of file tables_lpphy.c.
const u16 lpphy_rev1_ofdm_cck_gain_table[] [static]
Initial value:
 {
        0x5000, 0x6000, 0x7000, 0x0001, 0x1001, 0x2001, 0x3001, 0x4001, 0x5001,
        0x6001, 0x7001, 0x7011, 0x7021, 0x2035, 0x2045, 0x2055, 0x2065, 0x2075,
        0x006d, 0x007d, 0x014d, 0x015d, 0x115d, 0x035d, 0x135d, 0x055d, 0x155d,
        0x0d5d, 0x1d5d, 0x2d5d, 0x555d, 0x655d, 0x755d,
}
Definition at line 816 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init().
struct lpphy_tx_gain_table_entry lpphy_rev2_2ghz_tx_gain_table[] [static]
Definition at line 2008 of file tables_lpphy.c.
struct lpphy_tx_gain_table_entry lpphy_rev2_5ghz_tx_gain_table[] [static]
Definition at line 2139 of file tables_lpphy.c.
struct lpphy_tx_gain_table_entry lpphy_rev2_nopa_tx_gain_table[] [static]
Definition at line 1877 of file tables_lpphy.c.
const u32 lpphy_rev2plus_filter_control_table[] [static]
Initial value:
 {
        0x000141fc, 0x000021fc, 0x000021b7, 0x0000416f, 0x0001ff27, 0x0000217f,
        0x00002137, 0x000040ef, 0x0001fea7, 0x0000024f,
}
Definition at line 767 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u16 lpphy_rev2plus_noise_scale_table[] [static]
Initial value:
 {
        0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4,
        0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4,
        0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x0000,
        0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4,
        0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4,
        0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4, 0x00a4,
        0x00a4,
}
Definition at line 745 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u32 lpphy_rev2plus_ps_control_table[] [static]
Initial value:
 {
        0x00e38e08, 0x00e08e38, 0x00000000, 0x00000000, 0x00000000, 0x00002080,
        0x00006180, 0x00003002, 0x00000040, 0x00002042, 0x00180047, 0x00080043,
        0x00000041, 0x000020c1, 0x00046006, 0x00042002, 0x00040000, 0x00002003,
        0x00180006, 0x00080002,
}
Definition at line 782 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u16 lpphy_sw_control_table[] [static]
Initial value:
 {
        0x0128, 0x0128, 0x0009, 0x0009, 0x0028, 0x0028, 0x0028, 0x0028, 0x0128,
        0x0128, 0x0009, 0x0009, 0x0028, 0x0028, 0x0028, 0x0028, 0x0009, 0x0009,
        0x0009, 0x0009, 0x0009, 0x0009, 0x0009, 0x0009, 0x0018, 0x0018, 0x0018,
        0x0018, 0x0018, 0x0018, 0x0018, 0x0018, 0x0128, 0x0128, 0x0009, 0x0009,
        0x0028, 0x0028, 0x0028, 0x0028, 0x0128, 0x0128, 0x0009, 0x0009, 0x0028,
        0x0028, 0x0028, 0x0028, 0x0009, 0x0009, 0x0009, 0x0009, 0x0009, 0x0009,
        0x0009, 0x0009, 0x0018, 0x0018, 0x0018, 0x0018, 0x0018, 0x0018, 0x0018,
        0x0018,
}
Definition at line 1038 of file tables_lpphy.c.
Referenced by lpphy_rev2plus_table_init().
const u32 lpphy_tx_power_control_table[] [static]
Definition at line 827 of file tables_lpphy.c.
Referenced by lpphy_rev0_1_table_init().