CompatWireless3.2: drivers/net/wireless/b43/tables.c File Reference
drivers/net/wireless/b43/tables.c File Reference
#include "b43.h"
#include "tables.h"
#include "phy_g.h"
Functions
static void assert_sizes (void)
u16 b43_ofdmtab_read16 (struct b43_wldev *dev, u16 table, u16 offset)
void b43_ofdmtab_write16 (struct b43_wldev *dev, u16 table, u16 offset, u16 value)
u32 b43_ofdmtab_read32 (struct b43_wldev *dev, u16 table, u16 offset)
void b43_ofdmtab_write32 (struct b43_wldev *dev, u16 table, u16 offset, u32 value)
u16 b43_gtab_read (struct b43_wldev *dev, u16 table, u16 offset)
void b43_gtab_write (struct b43_wldev *dev, u16 table, u16 offset, u16 value)
Variables
const u32 b43_tab_rotor []
const u32 b43_tab_retard []
const u16 b43_tab_finefreqa []
const u16 b43_tab_finefreqg []
const u16 b43_tab_noisea2 []
const u16 b43_tab_noisea3 []
const u16 b43_tab_noiseg1 []
const u16 b43_tab_noiseg2 []
const u16 b43_tab_noisescalea2 []
const u16 b43_tab_noisescalea3 []
const u16 b43_tab_noisescaleg1 []
const u16 b43_tab_noisescaleg2 []
const u16 b43_tab_noisescaleg3 []
const u16 b43_tab_sigmasqr1 []
const u16 b43_tab_sigmasqr2 []
const u16 b43_tab_rssiagc1 []
const u16 b43_tab_rssiagc2 []
Function Documentation
static void assert_sizes (void) [inline, static]
Definition at line 353 of file tables.c.
References b43_tab_finefreqa, B43_TAB_FINEFREQA_SIZE, b43_tab_finefreqg, B43_TAB_FINEFREQG_SIZE, b43_tab_noisea2, B43_TAB_NOISEA2_SIZE, b43_tab_noisea3, B43_TAB_NOISEA3_SIZE, b43_tab_noiseg1, B43_TAB_NOISEG1_SIZE, b43_tab_noiseg2, B43_TAB_NOISEG2_SIZE, B43_TAB_NOISESCALE_SIZE, b43_tab_noisescalea2, b43_tab_noisescalea3, b43_tab_noisescaleg1, b43_tab_noisescaleg2, b43_tab_noisescaleg3, b43_tab_retard, B43_TAB_RETARD_SIZE, b43_tab_rotor, B43_TAB_ROTOR_SIZE, b43_tab_rssiagc1, B43_TAB_RSSIAGC1_SIZE, b43_tab_rssiagc2, B43_TAB_RSSIAGC2_SIZE, b43_tab_sigmasqr1, b43_tab_sigmasqr2, and B43_TAB_SIGMASQR_SIZE.
Referenced by b43_ofdmtab_read16().
u16 b43_gtab_read (struct b43_wldev * dev, u16 table, u16 offset)
Definition at line 456 of file tables.c.
References B43_PHY_GTABCTL, B43_PHY_GTABDATA, b43_phy_read(), and b43_phy_write().
void b43_gtab_write (struct b43_wldev * dev, u16 table, u16 offset, u16 value)
Definition at line 462 of file tables.c.
References B43_PHY_GTABCTL, B43_PHY_GTABDATA, and b43_phy_write().
Referenced by b43_wa_tr_ltov().
u16 b43_ofdmtab_read16 (struct b43_wldev * dev, u16 table, u16 offset)
Definition at line 379 of file tables.c.
References assert_sizes(), b43_phy_g::B43_OFDMTAB_DIRECTION_READ, B43_PHY_OTABLECTL, B43_PHY_OTABLEI, b43_phy_read(), b43_phy_write(), b43_phy::g, b43_phy_g::ofdmtab_addr, b43_phy_g::ofdmtab_addr_direction, and b43_wldev::phy.
Referenced by b43_wa_dac(), b43_wa_iqadc(), and b43_wa_papd().
u32 b43_ofdmtab_read32 (struct b43_wldev * dev, u16 table, u16 offset)
Definition at line 416 of file tables.c.
References b43_phy_g::B43_OFDMTAB_DIRECTION_READ, B43_PHY_OTABLECTL, B43_PHY_OTABLEI, B43_PHY_OTABLEQ, b43_phy_read(), b43_phy_write(), b43_phy::g, b43_phy_g::ofdmtab_addr, b43_phy_g::ofdmtab_addr_direction, and b43_wldev::phy.
void b43_ofdmtab_write16 (struct b43_wldev * dev, u16 table, u16 offset, u16 value)
Definition at line 399 of file tables.c.
References b43_phy_g::B43_OFDMTAB_DIRECTION_WRITE, B43_PHY_OTABLECTL, B43_PHY_OTABLEI, b43_phy_write(), b43_phy::g, b43_phy_g::ofdmtab_addr, b43_phy_g::ofdmtab_addr_direction, and b43_wldev::phy.
Referenced by b43_gphy_tssi_power_lt_init(), b43_phy_rssiagc(), b43_phy_ww(), b43_radio_interference_mitigation_enable(), b43_set_all_gains(), b43_set_original_gains(), b43_wa_altagc(), b43_wa_analog(), b43_wa_boards_a(), b43_wa_boards_g(), b43_wa_cpll_nonpilot(), b43_wa_dac(), b43_wa_fft(), b43_wa_gt(), b43_wa_initgains(), b43_wa_iqadc(), b43_wa_mixedsignal(), b43_wa_msst(), b43_wa_nft(), b43_wa_papd(), b43_wa_rssi_lt(), b43_wa_txdc_offset(), b43_wa_txlna_gain(), b43_wa_txpuoff_rxpuon(), b43_wa_wrssi_offset(), b43_write_nst(), and b43_write_null_nst().
void b43_ofdmtab_write32 (struct b43_wldev * dev, u16 table, u16 offset, u32 value)
Definition at line 437 of file tables.c.
References b43_phy_g::B43_OFDMTAB_DIRECTION_WRITE, B43_PHY_OTABLECTL, B43_PHY_OTABLEI, B43_PHY_OTABLEQ, b43_phy_write(), b43_phy::g, b43_phy_g::ofdmtab_addr, b43_phy_g::ofdmtab_addr_direction, and b43_wldev::phy.
Referenced by b43_wa_art(), and b43_wa_rt().
Variable Documentation
const u16 b43_tab_finefreqa[]
Definition at line 93 of file tables.c.
Referenced by assert_sizes(), and b43_wa_fft().
const u16 b43_tab_finefreqg[]
Definition at line 160 of file tables.c.
Referenced by assert_sizes(), and b43_wa_fft().
const u16 b43_tab_noisea2[]
Initial value:
 {
        0x0001, 0x0001, 0x0001, 0xFFFE,
        0xFFFE, 0x3FFF, 0x1000, 0x0393,
}
Definition at line 227 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nft().
const u16 b43_tab_noisea3[]
Initial value:
 {
        0x5E5E, 0x5E5E, 0x5E5E, 0x3F48,
        0x4C4C, 0x4C4C, 0x4C4C, 0x2D36,
}
Definition at line 232 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nft().
const u16 b43_tab_noiseg1[]
Initial value:
 {
        0x013C, 0x01F5, 0x031A, 0x0631,
        0x0001, 0x0001, 0x0001, 0x0001,
}
Definition at line 237 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nft().
const u16 b43_tab_noiseg2[]
Initial value:
 {
        0x5484, 0x3C40, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
}
Definition at line 242 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nft().
const u16 b43_tab_noisescalea2[]
Initial value:
 {
        0x6767, 0x6767, 0x6767, 0x6767,
        0x6767, 0x6767, 0x6767, 0x6767,
        0x6767, 0x6767, 0x6767, 0x6767,
        0x6767, 0x6700, 0x6767, 0x6767,
        0x6767, 0x6767, 0x6767, 0x6767,
        0x6767, 0x6767, 0x6767, 0x6767,
        0x6767, 0x6767, 0x0067,
}
Definition at line 247 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nst().
const u16 b43_tab_noisescalea3[]
Initial value:
 {
        0x2323, 0x2323, 0x2323, 0x2323,
        0x2323, 0x2323, 0x2323, 0x2323,
        0x2323, 0x2323, 0x2323, 0x2323,
        0x2323, 0x2300, 0x2323, 0x2323,
        0x2323, 0x2323, 0x2323, 0x2323,
        0x2323, 0x2323, 0x2323, 0x2323,
        0x2323, 0x2323, 0x0023,
}
Definition at line 257 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nst().
const u16 b43_tab_noisescaleg1[]
Initial value:
 {
        0x6C77, 0x5162, 0x3B40, 0x3335,
        0x2F2D, 0x2A2A, 0x2527, 0x1F21,
        0x1A1D, 0x1719, 0x1616, 0x1414,
        0x1414, 0x1400, 0x1414, 0x1614,
        0x1716, 0x1A19, 0x1F1D, 0x2521,
        0x2A27, 0x2F2A, 0x332D, 0x3B35,
        0x5140, 0x6C62, 0x0077,
}
Definition at line 267 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nst().
const u16 b43_tab_noisescaleg2[]
Initial value:
 {
        0xD8DD, 0xCBD4, 0xBCC0, 0xB6B7,
        0xB2B0, 0xADAD, 0xA7A9, 0x9FA1,
        0x969B, 0x9195, 0x8F8F, 0x8A8A,
        0x8A8A, 0x8A00, 0x8A8A, 0x8F8A,
        0x918F, 0x9695, 0x9F9B, 0xA7A1,
        0xADA9, 0xB2AD, 0xB6B0, 0xBCB7,
        0xCBC0, 0xD8D4, 0x00DD,
}
Definition at line 277 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nst().
const u16 b43_tab_noisescaleg3[]
Initial value:
 {
        0xA4A4, 0xA4A4, 0xA4A4, 0xA4A4,
        0xA4A4, 0xA4A4, 0xA4A4, 0xA4A4,
        0xA4A4, 0xA4A4, 0xA4A4, 0xA4A4,
        0xA4A4, 0xA400, 0xA4A4, 0xA4A4,
        0xA4A4, 0xA4A4, 0xA4A4, 0xA4A4,
        0xA4A4, 0xA4A4, 0xA4A4, 0xA4A4,
        0xA4A4, 0xA4A4, 0x00A4,
}
Definition at line 287 of file tables.c.
Referenced by assert_sizes(), and b43_wa_nst().
const u32 b43_tab_retard[]
Initial value:
 {
        0xDB93CB87, 0xD666CF64,
        0xD1FDD358, 0xCDA6D826,
        0xCA38DD9F, 0xC729E2B4,
        0xC469E88E, 0xC26AEE2B,
        0xC0DEF46C, 0xC073FA62,
        0xC01D00D5, 0xC0760743,
        0xC1560D1E, 0xC2E51369,
        0xC4ED18FF, 0xC7AC1ED7,
        0xCB2823B2, 0xCEFA28D9,
        0xD2F62D3F, 0xD7BB3197,
        0xDCE53568, 0xE1FE3875,
        0xE7D13B35, 0xED663D35,
        0xF39B3EC4, 0xF98E3FA7,
        0x00004000, 0x06723FA7,
        0x0C653EC4, 0x129A3D35,
        0x182F3B35, 0x1E023875,
        0x231B3568, 0x28453197,
        0x2D0A2D3F, 0x310628D9,
        0x34D823B2, 0x38541ED7,
        0x3B1318FF, 0x3D1B1369,
        0x3EAA0D1E, 0x3F8A0743,
        0x3FE300D5, 0x3F8DFA62,
        0x3F22F46C, 0x3D96EE2B,
        0x3B97E88E, 0x38D7E2B4,
        0x35C8DD9F, 0x325AD826,
        0x2E03D358, 0x299ACF64,
        0x246DCB87,
}
Definition at line 63 of file tables.c.
Referenced by assert_sizes(), and b43_wa_art().
const u32 b43_tab_rotor[]
Initial value:
 {
        0xFEB93FFD, 0xFEC63FFD,
        0xFED23FFD, 0xFEDF3FFD,
        0xFEEC3FFE, 0xFEF83FFE,
        0xFF053FFE, 0xFF113FFE,
        0xFF1E3FFE, 0xFF2A3FFF,
        0xFF373FFF, 0xFF443FFF,
        0xFF503FFF, 0xFF5D3FFF,
        0xFF693FFF, 0xFF763FFF,
        0xFF824000, 0xFF8F4000,
        0xFF9B4000, 0xFFA84000,
        0xFFB54000, 0xFFC14000,
        0xFFCE4000, 0xFFDA4000,
        0xFFE74000, 0xFFF34000,
        0x00004000, 0x000D4000,
        0x00194000, 0x00264000,
        0x00324000, 0x003F4000,
        0x004B4000, 0x00584000,
        0x00654000, 0x00714000,
        0x007E4000, 0x008A3FFF,
        0x00973FFF, 0x00A33FFF,
        0x00B03FFF, 0x00BC3FFF,
        0x00C93FFF, 0x00D63FFF,
        0x00E23FFE, 0x00EF3FFE,
        0x00FB3FFE, 0x01083FFE,
        0x01143FFE, 0x01213FFD,
        0x012E3FFD, 0x013A3FFD,
        0x01473FFD,
}
Definition at line 33 of file tables.c.
Referenced by assert_sizes(), and b43_wa_rt().
const u16 b43_tab_rssiagc1[]
Initial value:
 {
        0xFFF8, 0xFFF8, 0xFFF8, 0xFFF8,
        0xFFF8, 0xFFF9, 0xFFFC, 0xFFFE,
        0xFFF8, 0xFFF8, 0xFFF8, 0xFFF8,
        0xFFF8, 0xFFF8, 0xFFF8, 0xFFF8,
}
Definition at line 331 of file tables.c.
Referenced by assert_sizes(), and b43_phy_rssiagc().
const u16 b43_tab_rssiagc2[]
Initial value:
 {
        0x0820, 0x0820, 0x0920, 0x0C38,
        0x0820, 0x0820, 0x0820, 0x0820,
        0x0820, 0x0820, 0x0920, 0x0A38,
        0x0820, 0x0820, 0x0820, 0x0820,
        0x0820, 0x0820, 0x0920, 0x0A38,
        0x0820, 0x0820, 0x0820, 0x0820,
        0x0820, 0x0820, 0x0920, 0x0A38,
        0x0820, 0x0820, 0x0820, 0x0820,
        0x0820, 0x0820, 0x0920, 0x0A38,
        0x0820, 0x0820, 0x0820, 0x0820,
        0x0820, 0x0820, 0x0920, 0x0A38,
        0x0820, 0x0820, 0x0820, 0x0820,
}
Definition at line 338 of file tables.c.
Referenced by assert_sizes(), and b43_phy_rssiagc().
const u16 b43_tab_sigmasqr1[]
Initial value:
 {
        0x007A, 0x0075, 0x0071, 0x006C,
        0x0067, 0x0063, 0x005E, 0x0059,
        0x0054, 0x0050, 0x004B, 0x0046,
        0x0042, 0x003D, 0x003D, 0x003D,
        0x003D, 0x003D, 0x003D, 0x003D,
        0x003D, 0x003D, 0x003D, 0x003D,
        0x003D, 0x003D, 0x0000, 0x003D,
        0x003D, 0x003D, 0x003D, 0x003D,
        0x003D, 0x003D, 0x003D, 0x003D,
        0x003D, 0x003D, 0x003D, 0x003D,
        0x0042, 0x0046, 0x004B, 0x0050,
        0x0054, 0x0059, 0x005E, 0x0063,
        0x0067, 0x006C, 0x0071, 0x0075,
        0x007A,
}
Definition at line 297 of file tables.c.
Referenced by assert_sizes(), and b43_wa_msst().
const u16 b43_tab_sigmasqr2[]
Initial value:
 {
        0x00DE, 0x00DC, 0x00DA, 0x00D8,
        0x00D6, 0x00D4, 0x00D2, 0x00CF,
        0x00CD, 0x00CA, 0x00C7, 0x00C4,
        0x00C1, 0x00BE, 0x00BE, 0x00BE,
        0x00BE, 0x00BE, 0x00BE, 0x00BE,
        0x00BE, 0x00BE, 0x00BE, 0x00BE,
        0x00BE, 0x00BE, 0x0000, 0x00BE,
        0x00BE, 0x00BE, 0x00BE, 0x00BE,
        0x00BE, 0x00BE, 0x00BE, 0x00BE,
        0x00BE, 0x00BE, 0x00BE, 0x00BE,
        0x00C1, 0x00C4, 0x00C7, 0x00CA,
        0x00CD, 0x00CF, 0x00D2, 0x00D4,
        0x00D6, 0x00D8, 0x00DA, 0x00DC,
        0x00DE,
}
Definition at line 314 of file tables.c.
Referenced by assert_sizes(), and b43_wa_msst().