CompatWireless3.2: drivers/net/wireless/b43/tables_phy_ht.c File Reference
drivers/net/wireless/b43/tables_phy_ht.c File Reference
#include "b43.h"
#include "tables_phy_ht.h"
#include "phy_common.h"
#include "phy_ht.h"
Defines
#define httab_upload(dev, offset, data)
Functions
u32 b43_httab_read (struct b43_wldev *dev, u32 offset)
void b43_httab_read_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, void *_data)
void b43_httab_write (struct b43_wldev *dev, u32 offset, u32 value)
void b43_httab_write_few (struct b43_wldev *dev, u32 offset, size_t num,...)
void b43_httab_write_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, const void *_data)
void b43_phy_ht_tables_init (struct b43_wldev *dev)
Variables
static const u16 b43_httab_0x12 []
static const u16 b43_httab_0x27 []
static const u16 b43_httab_0x26 []
static const u32 b43_httab_0x25 []
static const u32 b43_httab_0x2f []
static const u16 b43_httab_0x1a []
static const u16 b43_httab_0x1b []
static const u16 b43_httab_0x1c []
static const u32 b43_httab_0x1a_0xc0 []
static const u32 b43_httab_0x1a_0x140 []
static const u32 b43_httab_0x1b_0x140 []
static const u32 b43_httab_0x1c_0x140 []
static const u16 b43_httab_0x1a_0x1c0 []
static const u16 b43_httab_0x1b_0x1c0 []
static const u16 b43_httab_0x1c_0x1c0 []
static const u16 b43_httab_0x1a_0x240 []
static const u16 b43_httab_0x1b_0x240 []
static const u16 b43_httab_0x1c_0x240 []
static const u32 b43_httab_0x1f []
static const u32 b43_httab_0x21 []
static const u32 b43_httab_0x23 []
static const u32 b43_httab_0x20 []
static const u32 b43_httab_0x22 []
static const u32 b43_httab_0x24 []
const u32 b43_httab_0x1a_0xc0_late []
Define Documentation
#define httab_upload (dev, offset, data)
Value:
do { \
                b43_httab_write_bulk(dev, offset, ARRAY_SIZE(data), data); \
        } while (0)
Definition at line 804 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
Function Documentation
u32 b43_httab_read (struct b43_wldev * dev, u32 offset)
Definition at line 619 of file tables_phy_ht.c.
References B43_HTTAB_16BIT, B43_HTTAB_32BIT, B43_HTTAB_8BIT, B43_HTTAB_TYPEMASK, B43_PHY_HT_TABLE_ADDR, B43_PHY_HT_TABLE_DATAHI, B43_PHY_HT_TABLE_DATALO, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_ht_channel_setup(), and b43_phy_ht_op_init().
void b43_httab_read_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, void * _data)
Definition at line 650 of file tables_phy_ht.c.
References B43_HTTAB_16BIT, B43_HTTAB_32BIT, B43_HTTAB_8BIT, B43_HTTAB_TYPEMASK, B43_PHY_HT_TABLE_ADDR, B43_PHY_HT_TABLE_DATAHI, B43_PHY_HT_TABLE_DATALO, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
void b43_httab_write (struct b43_wldev * dev, u32 offset, u32 value)
Definition at line 685 of file tables_phy_ht.c.
References B43_HTTAB_16BIT, B43_HTTAB_32BIT, B43_HTTAB_8BIT, B43_HTTAB_TYPEMASK, B43_PHY_HT_TABLE_ADDR, B43_PHY_HT_TABLE_DATAHI, B43_PHY_HT_TABLE_DATALO, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_ht_afe_unk1(), b43_phy_ht_channel_setup(), and b43_phy_ht_op_init().
void b43_httab_write_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, const void * _data)
Definition at line 760 of file tables_phy_ht.c.
References B43_HTTAB_16BIT, B43_HTTAB_32BIT, B43_HTTAB_8BIT, B43_HTTAB_TYPEMASK, B43_PHY_HT_TABLE_ADDR, B43_PHY_HT_TABLE_DATAHI, B43_PHY_HT_TABLE_DATALO, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_ht_op_init().
void b43_httab_write_few (struct b43_wldev * dev, u32 offset, size_t num, ...)
Definition at line 715 of file tables_phy_ht.c.
References B43_HTTAB_16BIT, B43_HTTAB_32BIT, B43_HTTAB_8BIT, B43_HTTAB_TYPEMASK, B43_PHY_HT_TABLE_ADDR, B43_PHY_HT_TABLE_DATAHI, B43_PHY_HT_TABLE_DATALO, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_ht_op_init().
void b43_phy_ht_tables_init (struct b43_wldev * dev)
Definition at line 807 of file tables_phy_ht.c.
References B43_HTTAB16, B43_HTTAB32, b43_httab_0x12, b43_httab_0x1a, b43_httab_0x1a_0x140, b43_httab_0x1a_0x1c0, b43_httab_0x1a_0x240, b43_httab_0x1a_0xc0, b43_httab_0x1a_0xc0_late, b43_httab_0x1b, b43_httab_0x1b_0x140, b43_httab_0x1b_0x1c0, b43_httab_0x1b_0x240, b43_httab_0x1c, b43_httab_0x1c_0x140, b43_httab_0x1c_0x1c0, b43_httab_0x1c_0x240, b43_httab_0x1f, b43_httab_0x20, b43_httab_0x21, b43_httab_0x22, b43_httab_0x23, b43_httab_0x24, b43_httab_0x25, b43_httab_0x26, b43_httab_0x27, b43_httab_0x2f, B43_HTTAB_1A_C0_LATE_SIZE, and httab_upload.
Referenced by b43_phy_ht_op_init().
Variable Documentation
const u16 b43_httab_0x12[] [static]
Initial value:
 {
        0x0000, 0x0008, 0x000a, 0x0010, 0x0012, 0x0019,
        0x001a, 0x001c, 0x0080, 0x0088, 0x008a, 0x0090,
        0x0092, 0x0099, 0x009a, 0x009c, 0x0100, 0x0108,
        0x010a, 0x0110, 0x0112, 0x0119, 0x011a, 0x011c,
        0x0180, 0x0188, 0x018a, 0x0190, 0x0192, 0x0199,
        0x019a, 0x019c, 0x0000, 0x0098, 0x00a0, 0x00a8,
        0x009a, 0x00a2, 0x00aa, 0x0120, 0x0128, 0x0128,
        0x0130, 0x0138, 0x0138, 0x0140, 0x0122, 0x012a,
        0x012a, 0x0132, 0x013a, 0x013a, 0x0142, 0x01a8,
        0x01b0, 0x01b8, 0x01b0, 0x01b8, 0x01c0, 0x01c8,
        0x01c0, 0x01c8, 0x01d0, 0x01d0, 0x01d8, 0x01aa,
        0x01b2, 0x01ba, 0x01b2, 0x01ba, 0x01c2, 0x01ca,
        0x01c2, 0x01ca, 0x01d2, 0x01d2, 0x01da, 0x0001,
        0x0002, 0x0004, 0x0009, 0x000c, 0x0011, 0x0014,
        0x0018, 0x0020, 0x0021, 0x0022, 0x0024, 0x0081,
        0x0082, 0x0084, 0x0089, 0x008c, 0x0091, 0x0094,
        0x0098, 0x00a0, 0x00a1, 0x00a2, 0x00a4, 0x0007,
        0x0007, 0x0007, 0x0007, 0x0007, 0x0007, 0x0007,
        0x0007, 0x0007, 0x0007, 0x0007, 0x0007, 0x0007,
        0x0007, 0x0007, 0x0007, 0x0007, 0x0007, 0x0007,
        0x0007, 0x0007, 0x0007, 0x0007, 0x0007, 0x0007,
        0x0007, 0x0007,
}
Definition at line 30 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x1a[] [static]
Initial value:
 {
        0x0055, 0x0054, 0x0054, 0x0053, 0x0052, 0x0052,
        0x0051, 0x0051, 0x0050, 0x004f, 0x004f, 0x004e,
        0x004e, 0x004d, 0x004c, 0x004c, 0x004b, 0x004a,
        0x0049, 0x0049, 0x0048, 0x0047, 0x0046, 0x0046,
        0x0045, 0x0044, 0x0043, 0x0042, 0x0041, 0x0040,
        0x0040, 0x003f, 0x003e, 0x003d, 0x003c, 0x003a,
        0x0039, 0x0038, 0x0037, 0x0036, 0x0035, 0x0033,
        0x0032, 0x0031, 0x002f, 0x002e, 0x002c, 0x002b,
        0x0029, 0x0027, 0x0025, 0x0023, 0x0021, 0x001f,
        0x001d, 0x001a, 0x0018, 0x0015, 0x0012, 0x000e,
        0x000b, 0x0007, 0x0002, 0x00fd,
}
Definition at line 133 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x1a_0x140[] [static]
Definition at line 210 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x1a_0x1c0[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000,
}
Definition at line 315 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x1a_0x240[] [static]
Initial value:
 {
        0x0036, 0x0036, 0x0036, 0x0036, 0x0036, 0x0036,
        0x0036, 0x0036, 0x0036, 0x0036, 0x0036, 0x0036,
        0x0036, 0x002a, 0x002a, 0x002a, 0x002a, 0x002a,
        0x002a, 0x002a, 0x002a, 0x002a, 0x002a, 0x002a,
        0x001e, 0x001e, 0x001e, 0x001e, 0x001e, 0x001e,
        0x001e, 0x001e, 0x001e, 0x001e, 0x001e, 0x001e,
        0x001e, 0x001e, 0x001e, 0x001e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x01fc, 0x01fc,
        0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc,
        0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6,
}
Definition at line 390 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x1a_0xc0[] [static]
Definition at line 175 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x1a_0xc0_late[]
Definition at line 580 of file tables_phy_ht.c.
Referenced by b43_phy_ht_op_init(), and b43_phy_ht_tables_init().
const u16 b43_httab_0x1b[] [static]
Initial value:
 {
        0x0055, 0x0054, 0x0054, 0x0053, 0x0052, 0x0052,
        0x0051, 0x0051, 0x0050, 0x004f, 0x004f, 0x004e,
        0x004e, 0x004d, 0x004c, 0x004c, 0x004b, 0x004a,
        0x0049, 0x0049, 0x0048, 0x0047, 0x0046, 0x0046,
        0x0045, 0x0044, 0x0043, 0x0042, 0x0041, 0x0040,
        0x0040, 0x003f, 0x003e, 0x003d, 0x003c, 0x003a,
        0x0039, 0x0038, 0x0037, 0x0036, 0x0035, 0x0033,
        0x0032, 0x0031, 0x002f, 0x002e, 0x002c, 0x002b,
        0x0029, 0x0027, 0x0025, 0x0023, 0x0021, 0x001f,
        0x001d, 0x001a, 0x0018, 0x0015, 0x0012, 0x000e,
        0x000b, 0x0007, 0x0002, 0x00fd,
}
Definition at line 147 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x1b_0x140[] [static]
Definition at line 245 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x1b_0x1c0[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000,
}
Definition at line 340 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x1b_0x240[] [static]
Initial value:
 {
        0x0036, 0x0036, 0x0036, 0x0036, 0x0036, 0x0036,
        0x0036, 0x0036, 0x0036, 0x0036, 0x0036, 0x0036,
        0x0036, 0x002a, 0x002a, 0x002a, 0x002a, 0x002a,
        0x002a, 0x002a, 0x002a, 0x002a, 0x002a, 0x002a,
        0x001e, 0x001e, 0x001e, 0x001e, 0x001e, 0x001e,
        0x001e, 0x001e, 0x001e, 0x001e, 0x001e, 0x001e,
        0x001e, 0x001e, 0x001e, 0x001e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x01fc, 0x01fc,
        0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc,
        0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6,
}
Definition at line 415 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x1c[] [static]
Initial value:
 {
        0x0055, 0x0054, 0x0054, 0x0053, 0x0052, 0x0052,
        0x0051, 0x0051, 0x0050, 0x004f, 0x004f, 0x004e,
        0x004e, 0x004d, 0x004c, 0x004c, 0x004b, 0x004a,
        0x0049, 0x0049, 0x0048, 0x0047, 0x0046, 0x0046,
        0x0045, 0x0044, 0x0043, 0x0042, 0x0041, 0x0040,
        0x0040, 0x003f, 0x003e, 0x003d, 0x003c, 0x003a,
        0x0039, 0x0038, 0x0037, 0x0036, 0x0035, 0x0033,
        0x0032, 0x0031, 0x002f, 0x002e, 0x002c, 0x002b,
        0x0029, 0x0027, 0x0025, 0x0023, 0x0021, 0x001f,
        0x001d, 0x001a, 0x0018, 0x0015, 0x0012, 0x000e,
        0x000b, 0x0007, 0x0002, 0x00fd,
}
Definition at line 161 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x1c_0x140[] [static]
Definition at line 280 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x1c_0x1c0[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000,
}
Definition at line 365 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x1c_0x240[] [static]
Initial value:
 {
        0x0036, 0x0036, 0x0036, 0x0036, 0x0036, 0x0036,
        0x0036, 0x0036, 0x0036, 0x0036, 0x0036, 0x0036,
        0x0036, 0x002a, 0x002a, 0x002a, 0x002a, 0x002a,
        0x002a, 0x002a, 0x002a, 0x002a, 0x002a, 0x002a,
        0x001e, 0x001e, 0x001e, 0x001e, 0x001e, 0x001e,
        0x001e, 0x001e, 0x001e, 0x001e, 0x001e, 0x001e,
        0x001e, 0x001e, 0x001e, 0x001e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x000e, 0x000e,
        0x000e, 0x000e, 0x000e, 0x000e, 0x01fc, 0x01fc,
        0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc,
        0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc, 0x01fc,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee, 0x01ee,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6, 0x01d6,
        0x01d6, 0x01d6,
}
Definition at line 440 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x1f[] [static]
Initial value:
 {
        0x00000000, 0x00000000, 0x00016023, 0x00006028,
        0x00034036, 0x0003402e, 0x0007203c, 0x0006e037,
        0x00070030, 0x0009401f, 0x0009a00f, 0x000b600d,
        0x000c8007, 0x000ce007, 0x00101fff, 0x00121ff9,
        0x0012e004, 0x0014dffc, 0x0016dff6, 0x0018dfe9,
        0x001b3fe5, 0x001c5fd0, 0x001ddfc2, 0x001f1fb6,
        0x00207fa4, 0x00219f8f, 0x0022ff7d, 0x00247f6c,
        0x0024df5b, 0x00267f4b, 0x0027df3b, 0x0029bf3b,
        0x002b5f2f, 0x002d3f2e, 0x002f5f2a, 0x002fff15,
        0x00315f0b, 0x0032defa, 0x0033beeb, 0x0034fed9,
        0x00353ec5, 0x00361eb0, 0x00363e9b, 0x0036be87,
        0x0036be70, 0x0038fe67, 0x0044beb2, 0x00513ef3,
        0x00595f11, 0x00669f3d, 0x0078dfdf, 0x00a143aa,
        0x01642fff, 0x0162afff, 0x01620fff, 0x0160cfff,
        0x015f0fff, 0x015dafff, 0x015bcfff, 0x015bcfff,
        0x015b4fff, 0x015acfff, 0x01590fff, 0x0156cfff,
}
Definition at line 465 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x20[] [static]
Initial value:
 {
        0x0b5e002d, 0x0ae2002f, 0x0a3b0032, 0x09a70035,
        0x09220038, 0x08ab003b, 0x081f003f, 0x07a20043,
        0x07340047, 0x06d2004b, 0x067a004f, 0x06170054,
        0x05bf0059, 0x0571005e, 0x051e0064, 0x04d3006a,
        0x04910070, 0x044c0077, 0x040f007e, 0x03d90085,
        0x03a1008d, 0x036f0095, 0x033d009e, 0x030b00a8,
        0x02e000b2, 0x02b900bc, 0x029200c7, 0x026d00d3,
        0x024900e0, 0x022900ed, 0x020a00fb, 0x01ec010a,
        0x01d20119, 0x01b7012a, 0x019e013c, 0x0188014e,
        0x01720162, 0x015d0177, 0x0149018e, 0x013701a5,
        0x012601be, 0x011501d8, 0x010601f4, 0x00f70212,
        0x00e90231, 0x00dc0253, 0x00d00276, 0x00c4029b,
        0x00b902c3, 0x00af02ed, 0x00a50319, 0x009c0348,
        0x0093037a, 0x008b03af, 0x008303e6, 0x007c0422,
        0x00750460, 0x006e04a3, 0x006804e9, 0x00620533,
        0x005d0582, 0x005805d6, 0x0053062e, 0x004e068c,
}
Definition at line 522 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x21[] [static]
Initial value:
 {
        0x00000000, 0x00000000, 0x00016023, 0x00006028,
        0x00034036, 0x0003402e, 0x0007203c, 0x0006e037,
        0x00070030, 0x0009401f, 0x0009a00f, 0x000b600d,
        0x000c8007, 0x000ce007, 0x00101fff, 0x00121ff9,
        0x0012e004, 0x0014dffc, 0x0016dff6, 0x0018dfe9,
        0x001b3fe5, 0x001c5fd0, 0x001ddfc2, 0x001f1fb6,
        0x00207fa4, 0x00219f8f, 0x0022ff7d, 0x00247f6c,
        0x0024df5b, 0x00267f4b, 0x0027df3b, 0x0029bf3b,
        0x002b5f2f, 0x002d3f2e, 0x002f5f2a, 0x002fff15,
        0x00315f0b, 0x0032defa, 0x0033beeb, 0x0034fed9,
        0x00353ec5, 0x00361eb0, 0x00363e9b, 0x0036be87,
        0x0036be70, 0x0038fe67, 0x0044beb2, 0x00513ef3,
        0x00595f11, 0x00669f3d, 0x0078dfdf, 0x00a143aa,
        0x01642fff, 0x0162afff, 0x01620fff, 0x0160cfff,
        0x015f0fff, 0x015dafff, 0x015bcfff, 0x015bcfff,
        0x015b4fff, 0x015acfff, 0x01590fff, 0x0156cfff,
}
Definition at line 484 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x22[] [static]
Initial value:
 {
        0x0b5e002d, 0x0ae2002f, 0x0a3b0032, 0x09a70035,
        0x09220038, 0x08ab003b, 0x081f003f, 0x07a20043,
        0x07340047, 0x06d2004b, 0x067a004f, 0x06170054,
        0x05bf0059, 0x0571005e, 0x051e0064, 0x04d3006a,
        0x04910070, 0x044c0077, 0x040f007e, 0x03d90085,
        0x03a1008d, 0x036f0095, 0x033d009e, 0x030b00a8,
        0x02e000b2, 0x02b900bc, 0x029200c7, 0x026d00d3,
        0x024900e0, 0x022900ed, 0x020a00fb, 0x01ec010a,
        0x01d20119, 0x01b7012a, 0x019e013c, 0x0188014e,
        0x01720162, 0x015d0177, 0x0149018e, 0x013701a5,
        0x012601be, 0x011501d8, 0x010601f4, 0x00f70212,
        0x00e90231, 0x00dc0253, 0x00d00276, 0x00c4029b,
        0x00b902c3, 0x00af02ed, 0x00a50319, 0x009c0348,
        0x0093037a, 0x008b03af, 0x008303e6, 0x007c0422,
        0x00750460, 0x006e04a3, 0x006804e9, 0x00620533,
        0x005d0582, 0x005805d6, 0x0053062e, 0x004e068c,
}
Definition at line 541 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x23[] [static]
Initial value:
 {
        0x00000000, 0x00000000, 0x00016023, 0x00006028,
        0x00034036, 0x0003402e, 0x0007203c, 0x0006e037,
        0x00070030, 0x0009401f, 0x0009a00f, 0x000b600d,
        0x000c8007, 0x000ce007, 0x00101fff, 0x00121ff9,
        0x0012e004, 0x0014dffc, 0x0016dff6, 0x0018dfe9,
        0x001b3fe5, 0x001c5fd0, 0x001ddfc2, 0x001f1fb6,
        0x00207fa4, 0x00219f8f, 0x0022ff7d, 0x00247f6c,
        0x0024df5b, 0x00267f4b, 0x0027df3b, 0x0029bf3b,
        0x002b5f2f, 0x002d3f2e, 0x002f5f2a, 0x002fff15,
        0x00315f0b, 0x0032defa, 0x0033beeb, 0x0034fed9,
        0x00353ec5, 0x00361eb0, 0x00363e9b, 0x0036be87,
        0x0036be70, 0x0038fe67, 0x0044beb2, 0x00513ef3,
        0x00595f11, 0x00669f3d, 0x0078dfdf, 0x00a143aa,
        0x01642fff, 0x0162afff, 0x01620fff, 0x0160cfff,
        0x015f0fff, 0x015dafff, 0x015bcfff, 0x015bcfff,
        0x015b4fff, 0x015acfff, 0x01590fff, 0x0156cfff,
}
Definition at line 503 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x24[] [static]
Initial value:
 {
        0x0b5e002d, 0x0ae2002f, 0x0a3b0032, 0x09a70035,
        0x09220038, 0x08ab003b, 0x081f003f, 0x07a20043,
        0x07340047, 0x06d2004b, 0x067a004f, 0x06170054,
        0x05bf0059, 0x0571005e, 0x051e0064, 0x04d3006a,
        0x04910070, 0x044c0077, 0x040f007e, 0x03d90085,
        0x03a1008d, 0x036f0095, 0x033d009e, 0x030b00a8,
        0x02e000b2, 0x02b900bc, 0x029200c7, 0x026d00d3,
        0x024900e0, 0x022900ed, 0x020a00fb, 0x01ec010a,
        0x01d20119, 0x01b7012a, 0x019e013c, 0x0188014e,
        0x01720162, 0x015d0177, 0x0149018e, 0x013701a5,
        0x012601be, 0x011501d8, 0x010601f4, 0x00f70212,
        0x00e90231, 0x00dc0253, 0x00d00276, 0x00c4029b,
        0x00b902c3, 0x00af02ed, 0x00a50319, 0x009c0348,
        0x0093037a, 0x008b03af, 0x008303e6, 0x007c0422,
        0x00750460, 0x006e04a3, 0x006804e9, 0x00620533,
        0x005d0582, 0x005805d6, 0x0053062e, 0x004e068c,
}
Definition at line 560 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x25[] [static]
Definition at line 89 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x26[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000,
}
Definition at line 64 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u16 b43_httab_0x27[] [static]
Initial value:
 {
        0x0009, 0x000e, 0x0011, 0x0014, 0x0017, 0x001a,
        0x001d, 0x0020, 0x0009, 0x000e, 0x0011, 0x0014,
        0x0017, 0x001a, 0x001d, 0x0020, 0x0009, 0x000e,
        0x0011, 0x0014, 0x0017, 0x001a, 0x001d, 0x0020,
        0x0009, 0x000e, 0x0011, 0x0014, 0x0017, 0x001a,
        0x001d, 0x0020,
}
Definition at line 55 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().
const u32 b43_httab_0x2f[] [static]
Initial value:
 {
        0x00035700, 0x0002cc9a, 0x00026666, 0x0001581f,
        0x0001581f, 0x0001581f, 0x0001581f, 0x0001581f,
        0x0001581f, 0x0001581f, 0x0001581f, 0x00035700,
        0x0002cc9a, 0x00026666, 0x0001581f, 0x0001581f,
        0x0001581f, 0x0001581f, 0x0001581f, 0x0001581f,
        0x0001581f, 0x0001581f,
}
Definition at line 124 of file tables_phy_ht.c.
Referenced by b43_phy_ht_tables_init().