CompatWireless3.2: drivers/net/wireless/b43/tables_phy_lcn.c File Reference
drivers/net/wireless/b43/tables_phy_lcn.c File Reference
#include "b43.h"
#include "tables_phy_lcn.h"
#include "phy_common.h"
#include "phy_lcn.h"
Data Structures
struct b43_lcntab_tx_gain_tbl_entry
Defines
#define lcntab_upload(dev, offset, data)
Functions
u32 b43_lcntab_read (struct b43_wldev *dev, u32 offset)
void b43_lcntab_read_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, void *_data)
void b43_lcntab_write (struct b43_wldev *dev, u32 offset, u32 value)
void b43_lcntab_write_bulk (struct b43_wldev *dev, u32 offset, unsigned int nr_elements, const void *_data)
static void b43_phy_lcn_upload_static_tables (struct b43_wldev *dev)
void b43_phy_lcn_load_tx_gain_tab (struct b43_wldev *dev, const struct b43_lcntab_tx_gain_tbl_entry *gain_table)
static void b43_phy_lcn_load_rfpower (struct b43_wldev *dev)
static void b43_phy_lcn_rewrite_rfpower_table (struct b43_wldev *dev)
static void b43_phy_lcn_clean_papd_comp_table (struct b43_wldev *dev)
void b43_phy_lcn_tables_init (struct b43_wldev *dev)
Variables
static const u16 b43_lcntab_0x02 []
static const u16 b43_lcntab_0x01 []
static const u32 b43_lcntab_0x0b []
static const u32 b43_lcntab_0x0c []
static const u32 b43_lcntab_0x0d []
static const u16 b43_lcntab_0x0e []
static const u16 b43_lcntab_0x0f []
static const u16 b43_lcntab_0x10 []
static const u16 b43_lcntab_0x11 []
static const u32 b43_lcntab_0x12 []
static const u16 b43_lcntab_0x14 []
static const u16 b43_lcntab_0x17 []
static const u16 b43_lcntab_0x00 []
static const u32 b43_lcntab_0x18 []
struct b43_lcntab_tx_gain_tbl_entry b43_lcntab_tx_gain_tbl_2ghz_ext_pa_rev0 [B43_LCNTAB_TX_GAIN_SIZE]
const u16 b43_lcntab_sw_ctl_4313_epa_rev0 []
Define Documentation
#define lcntab_upload (dev, offset, data)
Value:
do { \
                b43_lcntab_write_bulk(dev, offset, ARRAY_SIZE(data), data); \
        } while (0)
Definition at line 613 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
Function Documentation
u32 b43_lcntab_read (struct b43_wldev * dev, u32 offset)
Definition at line 470 of file tables_phy_lcn.c.
References B43_LCNTAB_16BIT, B43_LCNTAB_32BIT, B43_LCNTAB_8BIT, B43_LCNTAB_TYPEMASK, B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_lcn_load_rfpower(), b43_phy_lcn_load_tx_gain_tab(), and b43_phy_lcn_rewrite_rfpower_table().
void b43_lcntab_read_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, void * _data)
Definition at line 500 of file tables_phy_lcn.c.
References B43_LCNTAB_16BIT, B43_LCNTAB_32BIT, B43_LCNTAB_8BIT, B43_LCNTAB_TYPEMASK, B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, b43_phy_read(), b43_phy_write(), and B43_WARN_ON.
void b43_lcntab_write (struct b43_wldev * dev, u32 offset, u32 value)
Definition at line 538 of file tables_phy_lcn.c.
References B43_LCNTAB_16BIT, B43_LCNTAB_32BIT, B43_LCNTAB_8BIT, B43_LCNTAB_TYPEMASK, B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_lcn_clean_papd_comp_table(), b43_phy_lcn_load_tx_gain_tab(), b43_phy_lcn_rewrite_rfpower_table(), b43_phy_lcn_sense_setup(), b43_phy_lcn_set_bbmult(), and b43_radio_2064_init().
void b43_lcntab_write_bulk (struct b43_wldev * dev, u32 offset, unsigned int nr_elements, const void * _data)
Definition at line 568 of file tables_phy_lcn.c.
References B43_LCNTAB_16BIT, B43_LCNTAB_32BIT, B43_LCNTAB_8BIT, B43_LCNTAB_TYPEMASK, B43_PHY_LCN_TABLE_ADDR, B43_PHY_LCN_TABLE_DATAHI, B43_PHY_LCN_TABLE_DATALO, b43_phy_write(), and B43_WARN_ON.
Referenced by b43_phy_lcn_tables_init().
static void b43_phy_lcn_clean_papd_comp_table (struct b43_wldev * dev) [static]
Definition at line 689 of file tables_phy_lcn.c.
References B43_LCNTAB32, and b43_lcntab_write().
Referenced by b43_phy_lcn_tables_init().
static void b43_phy_lcn_load_rfpower (struct b43_wldev * dev) [static]
Definition at line 661 of file tables_phy_lcn.c.
References B43_LCNTAB32, and b43_lcntab_read().
Referenced by b43_phy_lcn_tables_init().
void b43_phy_lcn_load_tx_gain_tab (struct b43_wldev * dev, const struct b43_lcntab_tx_gain_tbl_entry * gain_table)
Definition at line 634 of file tables_phy_lcn.c.
References B43_BFL_FEM, B43_LCNTAB32, b43_lcntab_read(), B43_LCNTAB_TX_GAIN_SIZE, b43_lcntab_write(), b43_lcntab_tx_gain_tbl_entry::bb_mult, b43_bus_dev::bus_sprom, b43_lcntab_tx_gain_tbl_entry::dac, b43_wldev::dev, b43_lcntab_tx_gain_tbl_entry::gm, b43_lcntab_tx_gain_tbl_entry::pad, and b43_lcntab_tx_gain_tbl_entry::pga.
Referenced by b43_phy_lcn_tables_init().
static void b43_phy_lcn_rewrite_rfpower_table (struct b43_wldev * dev) [static]
Definition at line 678 of file tables_phy_lcn.c.
References B43_LCNTAB32, b43_lcntab_read(), and b43_lcntab_write().
Referenced by b43_phy_lcn_tables_init().
void b43_phy_lcn_tables_init (struct b43_wldev * dev)
Definition at line 698 of file tables_phy_lcn.c.
References B43_BFH_FEM_BT, B43_BFL_FEM, b43_current_band(), B43_LCNTAB16, b43_lcntab_sw_ctl_4313_epa_rev0, b43_lcntab_write_bulk(), b43_phy_lcn_clean_papd_comp_table(), b43_phy_lcn_load_rfpower(), b43_phy_lcn_load_tx_gain_tab(), b43_phy_lcn_rewrite_rfpower_table(), b43_phy_lcn_upload_static_tables(), b43err(), b43_bus_dev::bus_sprom, b43_wldev::dev, and b43_wldev::wl.
Referenced by b43_phy_lcn_op_init().
static void b43_phy_lcn_upload_static_tables (struct b43_wldev * dev) [static]
Definition at line 616 of file tables_phy_lcn.c.
References B43_LCNTAB16, B43_LCNTAB32, b43_lcntab_0x00, b43_lcntab_0x01, b43_lcntab_0x02, b43_lcntab_0x0b, b43_lcntab_0x0c, b43_lcntab_0x0d, b43_lcntab_0x0e, b43_lcntab_0x0f, b43_lcntab_0x10, b43_lcntab_0x11, b43_lcntab_0x12, b43_lcntab_0x14, b43_lcntab_0x17, b43_lcntab_0x18, and lcntab_upload.
Referenced by b43_phy_lcn_tables_init().
Variable Documentation
const u16 b43_lcntab_0x00[] [static]
Initial value:
 {
        0x0200, 0x0300, 0x0400, 0x0600, 0x0800, 0x0b00,
        0x1000, 0x1001, 0x1002, 0x1003, 0x1004, 0x1005,
        0x1006, 0x1007, 0x1707, 0x2007, 0x2d07, 0x4007,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0200, 0x0300, 0x0400, 0x0600,
        0x0800, 0x0b00, 0x1000, 0x1001, 0x1002, 0x1003,
        0x1004, 0x1005, 0x1006, 0x1007, 0x1707, 0x2007,
        0x2d07, 0x4007, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x4000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
}
Definition at line 248 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_0x01[] [static]
Initial value:
 {
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
}
Definition at line 56 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_0x02[] [static]
Initial value:
 {
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d, 0x014d, 0x014d,
        0x014d, 0x014d, 0x014d, 0x014d,
}
Definition at line 42 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u32 b43_lcntab_0x0b[] [static]
Initial value:
 {
        0x000141f8, 0x000021f8, 0x000021fb, 0x000041fb,
        0x0001fedb, 0x0000217b, 0x00002133, 0x000040eb,
        0x0001fea3, 0x0000024b,
}
Definition at line 70 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u32 b43_lcntab_0x0c[] [static]
Initial value:
 {
        0x00100001, 0x00200010, 0x00300001, 0x00400010,
        0x00500022, 0x00600122, 0x00700222, 0x00800322,
        0x00900422, 0x00a00522, 0x00b00622, 0x00c00722,
        0x00d00822, 0x00f00922, 0x00100a22, 0x00200b22,
        0x00300c22, 0x00400d22, 0x00500e22, 0x00600f22,
}
Definition at line 76 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u32 b43_lcntab_0x0d[] [static]
Definition at line 84 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_0x0e[] [static]
Initial value:
 {
        0x0401, 0x0402, 0x0403, 0x0404, 0x0405, 0x0406,
        0x0407, 0x0408, 0x0409, 0x040a, 0x058b, 0x058c,
        0x058d, 0x058e, 0x058f, 0x0090, 0x0091, 0x0092,
        0x0193, 0x0194, 0x0195, 0x0196, 0x0197, 0x0198,
        0x0199, 0x019a, 0x019b, 0x019c, 0x019d, 0x019e,
        0x019f, 0x01a0, 0x01a1, 0x01a2, 0x01a3, 0x01a4,
        0x01a5, 0x0000,
}
Definition at line 124 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_0x0f[] [static]
Initial value:
 {
        0x000a, 0x0009, 0x0006, 0x0005, 0x000a, 0x0009,
        0x0006, 0x0005, 0x000a, 0x0009, 0x0006, 0x0005,
        0x000a, 0x0009, 0x0006, 0x0005, 0x000a, 0x0009,
        0x0006, 0x0005, 0x000a, 0x0009, 0x0006, 0x0005,
        0x000a, 0x0009, 0x0006, 0x0005, 0x000a, 0x0009,
        0x0006, 0x0005, 0x000a, 0x0009, 0x0006, 0x0005,
        0x000a, 0x0009, 0x0006, 0x0005, 0x000a, 0x0009,
        0x0006, 0x0005, 0x000a, 0x0009, 0x0006, 0x0005,
        0x000a, 0x0009, 0x0006, 0x0005, 0x000a, 0x0009,
        0x0006, 0x0005, 0x000a, 0x0009, 0x0006, 0x0005,
        0x000a, 0x0009, 0x0006, 0x0005,
}
Definition at line 134 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_0x10[] [static]
Initial value:
 {
        0x005f, 0x0036, 0x0029, 0x001f, 0x005f, 0x0036,
        0x0029, 0x001f, 0x005f, 0x0036, 0x0029, 0x001f,
        0x005f, 0x0036, 0x0029, 0x001f,
}
Definition at line 148 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_0x11[] [static]
Initial value:
 {
        0x0009, 0x000f, 0x0014, 0x0018, 0x00fe, 0x0007,
        0x000b, 0x000f, 0x00fb, 0x00fe, 0x0001, 0x0005,
        0x0008, 0x000b, 0x000e, 0x0011, 0x0014, 0x0017,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0003, 0x0006, 0x0009, 0x000c, 0x000f,
        0x0012, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0003,
        0x0006, 0x0009, 0x000c, 0x000f, 0x0012, 0x0015,
        0x0018, 0x001b, 0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0003, 0x00eb, 0x0000, 0x0000,
}
Definition at line 154 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u32 b43_lcntab_0x12[] [static]
Initial value:
 {
        0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000004, 0x00000000, 0x00000004, 0x00000008,
        0x00000001, 0x00000005, 0x00000009, 0x0000000d,
        0x0000004d, 0x0000008d, 0x0000000d, 0x0000004d,
        0x0000008d, 0x000000cd, 0x0000004f, 0x0000008f,
        0x000000cf, 0x000000d3, 0x00000113, 0x00000513,
        0x00000913, 0x00000953, 0x00000d53, 0x00001153,
        0x00001193, 0x00005193, 0x00009193, 0x0000d193,
        0x00011193, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000004,
        0x00000000, 0x00000004, 0x00000008, 0x00000001,
        0x00000005, 0x00000009, 0x0000000d, 0x0000004d,
        0x0000008d, 0x0000000d, 0x0000004d, 0x0000008d,
        0x000000cd, 0x0000004f, 0x0000008f, 0x000000cf,
        0x000000d3, 0x00000113, 0x00000513, 0x00000913,
        0x00000953, 0x00000d53, 0x00001153, 0x00005153,
        0x00009153, 0x0000d153, 0x00011153, 0x00015153,
        0x00019153, 0x0001d153, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000,
        0x00000000, 0x00000000, 0x00000000, 0x00000000,
}
Definition at line 167 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_0x14[] [static]
Initial value:
 {
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0002, 0x0003, 0x0001, 0x0003, 0x0002, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0002, 0x0003,
        0x0001, 0x0003, 0x0002, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001, 0x0001, 0x0001, 0x0001, 0x0001,
        0x0001, 0x0001,
}
Definition at line 194 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_0x17[] [static]
Initial value:
 {
        0x001a, 0x0034, 0x004e, 0x0068, 0x009c, 0x00d0,
        0x00ea, 0x0104, 0x0034, 0x0068, 0x009c, 0x00d0,
        0x0138, 0x01a0, 0x01d4, 0x0208, 0x004e, 0x009c,
        0x00ea, 0x0138, 0x01d4, 0x0270, 0x02be, 0x030c,
        0x0068, 0x00d0, 0x0138, 0x01a0, 0x0270, 0x0340,
        0x03a8, 0x0410, 0x0018, 0x009c, 0x00d0, 0x0104,
        0x00ea, 0x0138, 0x0186, 0x00d0, 0x0104, 0x0104,
        0x0138, 0x016c, 0x016c, 0x01a0, 0x0138, 0x0186,
        0x0186, 0x01d4, 0x0222, 0x0222, 0x0270, 0x0104,
        0x0138, 0x016c, 0x0138, 0x016c, 0x01a0, 0x01d4,
        0x01a0, 0x01d4, 0x0208, 0x0208, 0x023c, 0x0186,
        0x01d4, 0x0222, 0x01d4, 0x0222, 0x0270, 0x02be,
        0x0270, 0x02be, 0x030c, 0x030c, 0x035a, 0x0036,
        0x006c, 0x00a2, 0x00d8, 0x0144, 0x01b0, 0x01e6,
        0x021c, 0x006c, 0x00d8, 0x0144, 0x01b0, 0x0288,
        0x0360, 0x03cc, 0x0438, 0x00a2, 0x0144, 0x01e6,
        0x0288, 0x03cc, 0x0510, 0x05b2, 0x0654, 0x00d8,
        0x01b0, 0x0288, 0x0360, 0x0510, 0x06c0, 0x0798,
        0x0870, 0x0018, 0x0144, 0x01b0, 0x021c, 0x01e6,
        0x0288, 0x032a, 0x01b0, 0x021c, 0x021c, 0x0288,
        0x02f4, 0x02f4, 0x0360, 0x0288, 0x032a, 0x032a,
        0x03cc, 0x046e, 0x046e, 0x0510, 0x021c, 0x0288,
        0x02f4, 0x0288, 0x02f4, 0x0360, 0x03cc, 0x0360,
        0x03cc, 0x0438, 0x0438, 0x04a4, 0x032a, 0x03cc,
        0x046e, 0x03cc, 0x046e, 0x0510, 0x05b2, 0x0510,
        0x05b2, 0x0654, 0x0654, 0x06f6,
}
Definition at line 219 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u32 b43_lcntab_0x18[] [static]
Definition at line 269 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_upload_static_tables().
const u16 b43_lcntab_sw_ctl_4313_epa_rev0[]
Initial value:
 {
        0x0002, 0x0008, 0x0004, 0x0001, 0x0002, 0x0008,
        0x0004, 0x0001, 0x0002, 0x0008, 0x0004, 0x0001,
        0x0002, 0x0008, 0x0004, 0x0001, 0x0002, 0x0008,
        0x0004, 0x0001, 0x0002, 0x0008, 0x0004, 0x0001,
        0x0002, 0x0008, 0x0004, 0x0001, 0x0002, 0x0008,
        0x0004, 0x0001, 0x0002, 0x0008, 0x0004, 0x0001,
        0x0002, 0x0008, 0x0004, 0x0001, 0x0002, 0x0008,
        0x0004, 0x0001, 0x0002, 0x0008, 0x0004, 0x0001,
        0x0002, 0x0008, 0x0004, 0x0001, 0x0002, 0x0008,
        0x0004, 0x0001, 0x0002, 0x0008, 0x0004, 0x0001,
        0x0002, 0x0008, 0x0004, 0x0001,
}
Definition at line 452 of file tables_phy_lcn.c.
Referenced by b43_phy_lcn_tables_init().
struct b43_lcntab_tx_gain_tbl_entry b43_lcntab_tx_gain_tbl_2ghz_ext_pa_rev0[B43_LCNTAB_TX_GAIN_SIZE]
Definition at line 317 of file tables_phy_lcn.c.