CompatWireless3.2: drivers/net/wireless/b43/wa.h File Reference
drivers/net/wireless/b43/wa.h File Reference
Functions
void b43_wa_initgains (struct b43_wldev *dev)
void b43_wa_all (struct b43_wldev *dev)
Function Documentation
void b43_wa_all (struct b43_wldev * dev)
Definition at line 517 of file wa.c.
References B43_PHYTYPE_A, B43_PHYTYPE_G, b43_wa_2060txlna_gain(), b43_wa_afcdac(), b43_wa_altagc(), b43_wa_analog(), b43_wa_art(), b43_wa_auxclipthr(), b43_wa_boards_a(), b43_wa_boards_g(), b43_wa_cck_shiftbits(), b43_wa_cpll_nonpilot(), b43_wa_crs_blank(), b43_wa_crs_ed(), b43_wa_crs_reset(), b43_wa_crs_thr(), b43_wa_dac(), b43_wa_divider(), b43_wa_fft(), b43_wa_gt(), b43_wa_initgains(), b43_wa_iqadc(), b43_wa_lms(), b43_wa_mixedsignal(), b43_wa_msst(), b43_wa_nft(), b43_wa_nst(), b43_wa_papd(), b43_wa_rssi_adc(), b43_wa_rssi_lt(), b43_wa_rt(), b43_wa_tr_ltov(), b43_wa_txdc_offset(), b43_wa_txlna_gain(), b43_wa_txpuoff_rxpuon(), b43_wa_wrssi_offset(), B43_WARN_ON, b43_wldev::phy, b43_phy::rev, and b43_phy::type.
Referenced by b43_phy_inita().
void b43_wa_initgains (struct b43_wldev * dev)
Definition at line 60 of file wa.c.
References B43_OFDMTAB_LPFGAIN, b43_ofdmtab_write16(), B43_PHY_LNAHPFCTL, B43_PHY_LPFGAINCTL, b43_phy_mask(), b43_phy_maskset(), b43_phy_write(), b43_radio_write16, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_ww(), and b43_wa_all().