CompatWireless3.2: drivers/net/wireless/b43/wa.c File Reference
drivers/net/wireless/b43/wa.c File Reference
#include "b43.h"
#include "main.h"
#include "tables.h"
#include "phy_common.h"
#include "wa.h"
Functions
static void b43_wa_papd (struct b43_wldev *dev)
static void b43_wa_auxclipthr (struct b43_wldev *dev)
static void b43_wa_afcdac (struct b43_wldev *dev)
static void b43_wa_txdc_offset (struct b43_wldev *dev)
void b43_wa_initgains (struct b43_wldev *dev)
static void b43_wa_divider (struct b43_wldev *dev)
static void b43_wa_gt (struct b43_wldev *dev)
static void b43_wa_rssi_lt (struct b43_wldev *dev)
static void b43_wa_analog (struct b43_wldev *dev)
static void b43_wa_dac (struct b43_wldev *dev)
static void b43_wa_fft (struct b43_wldev *dev)
static void b43_wa_nft (struct b43_wldev *dev)
static void b43_wa_rt (struct b43_wldev *dev)
static void b43_write_null_nst (struct b43_wldev *dev)
static void b43_write_nst (struct b43_wldev *dev, const u16 *nst)
static void b43_wa_nst (struct b43_wldev *dev)
static void b43_wa_art (struct b43_wldev *dev)
static void b43_wa_txlna_gain (struct b43_wldev *dev)
static void b43_wa_crs_reset (struct b43_wldev *dev)
static void b43_wa_2060txlna_gain (struct b43_wldev *dev)
static void b43_wa_lms (struct b43_wldev *dev)
static void b43_wa_mixedsignal (struct b43_wldev *dev)
static void b43_wa_msst (struct b43_wldev *dev)
static void b43_wa_iqadc (struct b43_wldev *dev)
static void b43_wa_crs_ed (struct b43_wldev *dev)
static void b43_wa_crs_thr (struct b43_wldev *dev)
static void b43_wa_crs_blank (struct b43_wldev *dev)
static void b43_wa_cck_shiftbits (struct b43_wldev *dev)
static void b43_wa_wrssi_offset (struct b43_wldev *dev)
static void b43_wa_txpuoff_rxpuon (struct b43_wldev *dev)
static void b43_wa_altagc (struct b43_wldev *dev)
static void b43_wa_tr_ltov (struct b43_wldev *dev)
static void b43_wa_cpll_nonpilot (struct b43_wldev *dev)
static void b43_wa_rssi_adc (struct b43_wldev *dev)
static void b43_wa_boards_a (struct b43_wldev *dev)
static void b43_wa_boards_g (struct b43_wldev *dev)
void b43_wa_all (struct b43_wldev *dev)
Function Documentation
static void b43_wa_2060txlna_gain (struct b43_wldev * dev) [static]
Definition at line 264 of file wa.c.
References B43_HF_2060W, b43_hf_read(), and b43_hf_write().
Referenced by b43_wa_all().
static void b43_wa_afcdac (struct b43_wldev * dev) [static]
Definition at line 49 of file wa.c.
References b43_phy_write().
Referenced by b43_wa_all().
void b43_wa_all (struct b43_wldev * dev)
Definition at line 517 of file wa.c.
References B43_PHYTYPE_A, B43_PHYTYPE_G, b43_wa_2060txlna_gain(), b43_wa_afcdac(), b43_wa_altagc(), b43_wa_analog(), b43_wa_art(), b43_wa_auxclipthr(), b43_wa_boards_a(), b43_wa_boards_g(), b43_wa_cck_shiftbits(), b43_wa_cpll_nonpilot(), b43_wa_crs_blank(), b43_wa_crs_ed(), b43_wa_crs_reset(), b43_wa_crs_thr(), b43_wa_dac(), b43_wa_divider(), b43_wa_fft(), b43_wa_gt(), b43_wa_initgains(), b43_wa_iqadc(), b43_wa_lms(), b43_wa_mixedsignal(), b43_wa_msst(), b43_wa_nft(), b43_wa_nst(), b43_wa_papd(), b43_wa_rssi_adc(), b43_wa_rssi_lt(), b43_wa_rt(), b43_wa_tr_ltov(), b43_wa_txdc_offset(), b43_wa_txlna_gain(), b43_wa_txpuoff_rxpuon(), b43_wa_wrssi_offset(), B43_WARN_ON, b43_wldev::phy, b43_phy::rev, and b43_phy::type.
Referenced by b43_phy_inita().
static void b43_wa_altagc (struct b43_wldev * dev) [static]
Definition at line 364 of file wa.c.
References B43_OFDMTAB_AGC1, B43_OFDMTAB_AGC1_R1, B43_OFDMTAB_AGC2, B43_OFDMTAB_AGC3, B43_OFDMTAB_AGC3_R1, b43_ofdmtab_write16(), B43_PHY_ANTWRSETT, B43_PHY_CCKSHIFTBITS_WA, B43_PHY_DIVP1P2GAIN, B43_PHY_DIVSRCHIDX, B43_PHY_LMS, B43_PHY_LPFGAINCTL, b43_phy_mask(), b43_phy_maskset(), B43_PHY_N1N2GAIN, B43_PHY_N1P1GAIN, B43_PHY_OFDM, B43_PHY_P1P2GAIN, B43_PHY_PEAK_COUNT, b43_phy_read(), B43_PHY_VERSION_OFDM, b43_phy_write(), b43_radio_set(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_wa_all().
static void b43_wa_analog (struct b43_wldev * dev) [static]
Definition at line 134 of file wa.c.
References B43_OFDMTAB_DAC, b43_ofdmtab_write16(), B43_PHY_PWRDOWN, b43_phy_read(), B43_PHY_VERSION_OFDM, b43_phy_write(), B43_PHYTYPE_A, B43_PHYVER_VERSION, b43_wldev::phy, and b43_phy::type.
Referenced by b43_wa_all().
static void b43_wa_art (struct b43_wldev * dev) [static]
Definition at line 245 of file wa.c.
References B43_OFDMTAB_ADVRETARD, b43_ofdmtab_write32(), b43_tab_retard, and B43_TAB_RETARD_SIZE.
Referenced by b43_wa_all().
static void b43_wa_auxclipthr (struct b43_wldev * dev) [static]
Definition at line 44 of file wa.c.
References B43_PHY_OFDM, and b43_phy_write().
Referenced by b43_wa_all().
static void b43_wa_boards_a (struct b43_wldev * dev) [static]
Definition at line 459 of file wa.c.
References B43_OFDMTAB_DC, B43_OFDMTAB_UNKNOWN_APHY, b43_ofdmtab_write16(), b43_phy_write(), b43_bus_dev::board_rev, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_wldev::dev, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_wa_all().
static void b43_wa_boards_g (struct b43_wldev * dev) [static]
Definition at line 485 of file wa.c.
References B43_BFL_EXTLNA, B43_BFL_FEM, B43_OFDMTAB_GAINX, B43_OFDMTAB_GAINX_R1, b43_ofdmtab_write16(), B43_PHY_EXTG, B43_PHY_GTABCTL, B43_PHY_GTABDATA, b43_phy_mask(), b43_phy_write(), b43_bus_dev::board_rev, b43_bus_dev::board_type, b43_bus_dev::board_vendor, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_wa_all().
static void b43_wa_cck_shiftbits (struct b43_wldev * dev) [static]
Definition at line 336 of file wa.c.
References B43_PHY_CCKSHIFTBITS, and b43_phy_write().
Referenced by b43_wa_all().
static void b43_wa_cpll_nonpilot (struct b43_wldev * dev) [static]
Definition at line 447 of file wa.c.
References B43_OFDMTAB_UNKNOWN_11, and b43_ofdmtab_write16().
Referenced by b43_wa_all().
static void b43_wa_crs_blank (struct b43_wldev * dev) [static]
Definition at line 331 of file wa.c.
References B43_PHY_OFDM, and b43_phy_write().
Referenced by b43_wa_all().
static void b43_wa_crs_ed (struct b43_wldev * dev) [static]
Definition at line 308 of file wa.c.
References B43_PHY_ANTDWELL, B43_PHY_CRSTHRES1, B43_PHY_CRSTHRES1_R1, B43_PHY_CRSTHRES2, B43_PHY_OFDM, b43_phy_set(), b43_phy_write(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_wa_all().
static void b43_wa_crs_reset (struct b43_wldev * dev) [static]
Definition at line 259 of file wa.c.
References b43_phy_write().
Referenced by b43_wa_all().
static void b43_wa_crs_thr (struct b43_wldev * dev) [static]
Definition at line 326 of file wa.c.
References B43_PHY_CRS0, and b43_phy_maskset().
Referenced by b43_wa_all().
static void b43_wa_dac (struct b43_wldev * dev) [static]
Definition at line 152 of file wa.c.
References b43_phy::analog, B43_OFDMTAB_DAC, b43_ofdmtab_read16(), b43_ofdmtab_write16(), and b43_wldev::phy.
Referenced by b43_wa_all().
static void b43_wa_divider (struct b43_wldev * dev) [static]
Definition at line 84 of file wa.c.
References b43_phy_mask(), and b43_phy_write().
Referenced by b43_wa_all().
static void b43_wa_fft (struct b43_wldev * dev) [static]
Definition at line 162 of file wa.c.
References B43_OFDMTAB_DACRFPABB, b43_ofdmtab_write16(), B43_PHYTYPE_A, b43_tab_finefreqa, B43_TAB_FINEFREQA_SIZE, b43_tab_finefreqg, B43_TAB_FINEFREQG_SIZE, b43_wldev::phy, and b43_phy::type.
Referenced by b43_wa_all().
static void b43_wa_gt (struct b43_wldev * dev) [static]
Definition at line 90 of file wa.c.
References B43_OFDMTAB_GAIN0, B43_OFDMTAB_GAIN1, B43_OFDMTAB_GAIN2, b43_ofdmtab_write16(), b43_wldev::phy, and b43_phy::rev.
Referenced by b43_wa_all().
void b43_wa_initgains (struct b43_wldev * dev)
Definition at line 60 of file wa.c.
References B43_OFDMTAB_LPFGAIN, b43_ofdmtab_write16(), B43_PHY_LNAHPFCTL, B43_PHY_LPFGAINCTL, b43_phy_mask(), b43_phy_maskset(), b43_phy_write(), b43_radio_write16, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_phy_ww(), and b43_wa_all().
static void b43_wa_iqadc (struct b43_wldev * dev) [static]
Definition at line 301 of file wa.c.
References b43_phy::analog, B43_OFDMTAB_DAC, b43_ofdmtab_read16(), b43_ofdmtab_write16(), and b43_wldev::phy.
Referenced by b43_wa_all().
static void b43_wa_lms (struct b43_wldev * dev) [static]
Definition at line 270 of file wa.c.
References b43_phy_maskset().
Referenced by b43_wa_all().
static void b43_wa_mixedsignal (struct b43_wldev * dev) [static]
Definition at line 275 of file wa.c.
References B43_OFDMTAB_DAC, and b43_ofdmtab_write16().
Referenced by b43_wa_all().
static void b43_wa_msst (struct b43_wldev * dev) [static]
Definition at line 280 of file wa.c.
References B43_OFDMTAB_MINSIGSQ, b43_ofdmtab_write16(), B43_PHYTYPE_A, B43_PHYTYPE_G, b43_tab_sigmasqr1, b43_tab_sigmasqr2, B43_TAB_SIGMASQR_SIZE, B43_WARN_ON, b43_wldev::phy, and b43_phy::type.
Referenced by b43_wa_all().
static void b43_wa_nft (struct b43_wldev * dev) [static]
Definition at line 174 of file wa.c.
References B43_OFDMTAB_AGC2, b43_ofdmtab_write16(), B43_PHYTYPE_A, b43_tab_noisea2, B43_TAB_NOISEA2_SIZE, b43_tab_noisea3, B43_TAB_NOISEA3_SIZE, b43_tab_noiseg1, B43_TAB_NOISEG1_SIZE, b43_tab_noiseg2, B43_TAB_NOISEG2_SIZE, b43_wldev::phy, b43_phy::rev, and b43_phy::type.
Referenced by b43_wa_all().
static void b43_wa_nst (struct b43_wldev * dev) [static]
Definition at line 220 of file wa.c.
References B43_PHY_ENCORE, B43_PHY_ENCORE_EN, b43_phy_read(), B43_PHYTYPE_A, b43_tab_noisescalea2, b43_tab_noisescalea3, b43_tab_noisescaleg1, b43_tab_noisescaleg2, b43_tab_noisescaleg3, b43_write_nst(), b43_write_null_nst(), b43_wldev::phy, b43_phy::rev, and b43_phy::type.
Referenced by b43_wa_all().
static void b43_wa_papd (struct b43_wldev * dev) [static]
Definition at line 33 of file wa.c.
References b43_dummy_transmission(), B43_OFDMTAB_PWRDYN2, b43_ofdmtab_read16(), B43_OFDMTAB_UNKNOWN_APHY, and b43_ofdmtab_write16().
Referenced by b43_wa_all().
static void b43_wa_rssi_adc (struct b43_wldev * dev) [static]
Definition at line 453 of file wa.c.
References b43_phy::analog, b43_phy_write(), and b43_wldev::phy.
Referenced by b43_wa_all().
static void b43_wa_rssi_lt (struct b43_wldev * dev) [static]
Definition at line 119 of file wa.c.
References B43_OFDMTAB_RSSI, and b43_ofdmtab_write16().
Referenced by b43_wa_all().
static void b43_wa_rt (struct b43_wldev * dev) [static]
Definition at line 196 of file wa.c.
References B43_OFDMTAB_ROTOR, b43_ofdmtab_write32(), b43_tab_rotor, and B43_TAB_ROTOR_SIZE.
Referenced by b43_wa_all().
static void b43_wa_tr_ltov (struct b43_wldev * dev) [static]
Definition at line 442 of file wa.c.
References B43_GTAB_ORIGTR, and b43_gtab_write().
Referenced by b43_wa_all().
static void b43_wa_txdc_offset (struct b43_wldev * dev) [static]
Definition at line 55 of file wa.c.
References B43_OFDMTAB_DC, and b43_ofdmtab_write16().
Referenced by b43_wa_all().
static void b43_wa_txlna_gain (struct b43_wldev * dev) [static]
Definition at line 254 of file wa.c.
References B43_OFDMTAB_DC, and b43_ofdmtab_write16().
Referenced by b43_wa_all().
static void b43_wa_txpuoff_rxpuon (struct b43_wldev * dev) [static]
Definition at line 358 of file wa.c.
References B43_OFDMTAB_UNKNOWN_0F, and b43_ofdmtab_write16().
Referenced by b43_wa_all().
static void b43_wa_wrssi_offset (struct b43_wldev * dev) [static]
Definition at line 341 of file wa.c.
References b43_ofdmtab_write16(), B43_OFDMTAB_WRSSI, B43_OFDMTAB_WRSSI_R1, b43_wldev::phy, and b43_phy::rev.
Referenced by b43_wa_all().
static void b43_write_nst (struct b43_wldev * dev, const u16 * nst) [static]
Definition at line 212 of file wa.c.
References B43_OFDMTAB_NOISESCALE, b43_ofdmtab_write16(), and B43_TAB_NOISESCALE_SIZE.
Referenced by b43_wa_nst().
static void b43_write_null_nst (struct b43_wldev * dev) [static]
Definition at line 204 of file wa.c.
References B43_OFDMTAB_NOISESCALE, b43_ofdmtab_write16(), and B43_TAB_NOISESCALE_SIZE.
Referenced by b43_wa_nst().