CompatWireless3.2: drivers/net/wireless/b43/xmit.h File Reference
drivers/net/wireless/b43/xmit.h File Reference
#include "main.h"
#include <net/mac80211.h>
Data Structures
struct b43_txhdr
struct b43_tx_legacy_rate_phy_ctl_entry
struct b43_txstatus
struct b43_rxhdr_fw4
struct b43_private_tx_info
Defines
#define _b43_declare_plcp_hdr(size)
#define B43_TXH_MAC_USEFBR 0x10000000
#define B43_TXH_MAC_KEYIDX 0x0FF00000
#define B43_TXH_MAC_KEYIDX_SHIFT 20
#define B43_TXH_MAC_KEYALG 0x00070000
#define B43_TXH_MAC_KEYALG_SHIFT 16
#define B43_TXH_MAC_AMIC 0x00008000
#define B43_TXH_MAC_RIFS 0x00004000
#define B43_TXH_MAC_LIFETIME 0x00002000
#define B43_TXH_MAC_FRAMEBURST 0x00001000
#define B43_TXH_MAC_SENDCTS 0x00000800
#define B43_TXH_MAC_AMPDU 0x00000600
#define B43_TXH_MAC_AMPDU_MPDU 0x00000000
#define B43_TXH_MAC_AMPDU_FIRST 0x00000200
#define B43_TXH_MAC_AMPDU_INTER 0x00000400
#define B43_TXH_MAC_AMPDU_LAST 0x00000600
#define B43_TXH_MAC_40MHZ 0x00000100
#define B43_TXH_MAC_5GHZ 0x00000080
#define B43_TXH_MAC_DFCS 0x00000040
#define B43_TXH_MAC_IGNPMQ 0x00000020
#define B43_TXH_MAC_HWSEQ 0x00000010
#define B43_TXH_MAC_STMSDU 0x00000008
#define B43_TXH_MAC_SENDRTS 0x00000004
#define B43_TXH_MAC_LONGFRAME 0x00000002
#define B43_TXH_MAC_ACK 0x00000001
#define B43_TXH_EFT_FB 0x03
#define B43_TXH_EFT_FB_CCK 0x00
#define B43_TXH_EFT_FB_OFDM 0x01
#define B43_TXH_EFT_FB_EWC 0x02
#define B43_TXH_EFT_FB_N 0x03
#define B43_TXH_EFT_RTS 0x0C
#define B43_TXH_EFT_RTS_CCK 0x00
#define B43_TXH_EFT_RTS_OFDM 0x04
#define B43_TXH_EFT_RTS_EWC 0x08
#define B43_TXH_EFT_RTS_N 0x0C
#define B43_TXH_EFT_RTSFB 0x30
#define B43_TXH_EFT_RTSFB_CCK 0x00
#define B43_TXH_EFT_RTSFB_OFDM 0x10
#define B43_TXH_EFT_RTSFB_EWC 0x20
#define B43_TXH_EFT_RTSFB_N 0x30
#define B43_TXH_PHY_ENC 0x0003
#define B43_TXH_PHY_ENC_CCK 0x0000
#define B43_TXH_PHY_ENC_OFDM 0x0001
#define B43_TXH_PHY_ENC_EWC 0x0002
#define B43_TXH_PHY_ENC_N 0x0003
#define B43_TXH_PHY_SHORTPRMBL 0x0010
#define B43_TXH_PHY_ANT 0x03C0
#define B43_TXH_PHY_ANT0 0x0000
#define B43_TXH_PHY_ANT1 0x0040
#define B43_TXH_PHY_ANT01AUTO 0x00C0
#define B43_TXH_PHY_ANT2 0x0100
#define B43_TXH_PHY_ANT3 0x0200
#define B43_TXH_PHY_TXPWR 0xFC00
#define B43_TXH_PHY_TXPWR_SHIFT 10
#define B43_TXH_PHY1_BW 0x0007
#define B43_TXH_PHY1_BW_10 0x0000
#define B43_TXH_PHY1_BW_10U 0x0001
#define B43_TXH_PHY1_BW_20 0x0002
#define B43_TXH_PHY1_BW_20U 0x0003
#define B43_TXH_PHY1_BW_40 0x0004
#define B43_TXH_PHY1_BW_40DUP 0x0005
#define B43_TXH_PHY1_MODE 0x0038
#define B43_TXH_PHY1_MODE_SISO 0x0000
#define B43_TXH_PHY1_MODE_CDD 0x0008
#define B43_TXH_PHY1_MODE_STBC 0x0010
#define B43_TXH_PHY1_MODE_SDM 0x0018
#define B43_TXH_PHY1_CRATE 0x0700
#define B43_TXH_PHY1_CRATE_1_2 0x0000
#define B43_TXH_PHY1_CRATE_2_3 0x0100
#define B43_TXH_PHY1_CRATE_3_4 0x0200
#define B43_TXH_PHY1_CRATE_4_5 0x0300
#define B43_TXH_PHY1_CRATE_5_6 0x0400
#define B43_TXH_PHY1_CRATE_7_8 0x0600
#define B43_TXH_PHY1_MODUL 0x3800
#define B43_TXH_PHY1_MODUL_BPSK 0x0000
#define B43_TXH_PHY1_MODUL_QPSK 0x0800
#define B43_TXH_PHY1_MODUL_QAM16 0x1000
#define B43_TXH_PHY1_MODUL_QAM64 0x1800
#define B43_TXH_PHY1_MODUL_QAM256 0x2000
#define B43_RX_PHYST0_GAINCTL 0x4000
#define B43_RX_PHYST0_PLCPHCF 0x0200
#define B43_RX_PHYST0_PLCPFV 0x0100
#define B43_RX_PHYST0_SHORTPRMBL 0x0080
#define B43_RX_PHYST0_LCRS 0x0040
#define B43_RX_PHYST0_ANT 0x0020
#define B43_RX_PHYST0_UNSRATE 0x0010
#define B43_RX_PHYST0_CLIP 0x000C
#define B43_RX_PHYST0_CLIP_SHIFT 2
#define B43_RX_PHYST0_FTYPE 0x0003
#define B43_RX_PHYST0_CCK 0x0000
#define B43_RX_PHYST0_OFDM 0x0001
#define B43_RX_PHYST0_PRE_N 0x0002
#define B43_RX_PHYST0_STD_N 0x0003
#define B43_RX_PHYST2_LNAG 0xC000
#define B43_RX_PHYST2_LNAG_SHIFT 14
#define B43_RX_PHYST2_PNAG 0x3C00
#define B43_RX_PHYST2_PNAG_SHIFT 10
#define B43_RX_PHYST2_FOFF 0x03FF
#define B43_RX_PHYST3_DIGG 0x1800
#define B43_RX_PHYST3_DIGG_SHIFT 11
#define B43_RX_PHYST3_TRSTATE 0x0400
#define B43_RX_MAC_RXST_VALID 0x01000000
#define B43_RX_MAC_TKIP_MICERR 0x00100000
#define B43_RX_MAC_TKIP_MICATT 0x00080000
#define B43_RX_MAC_AGGTYPE 0x00060000
#define B43_RX_MAC_AGGTYPE_SHIFT 17
#define B43_RX_MAC_AMSDU 0x00010000
#define B43_RX_MAC_BEACONSENT 0x00008000
#define B43_RX_MAC_KEYIDX 0x000007E0
#define B43_RX_MAC_KEYIDX_SHIFT 5
#define B43_RX_MAC_DECERR 0x00000010
#define B43_RX_MAC_DEC 0x00000008
#define B43_RX_MAC_PADDING 0x00000004
#define B43_RX_MAC_RESP 0x00000002
#define B43_RX_MAC_FCSERR 0x00000001
#define B43_RX_CHAN_40MHZ 0x1000
#define B43_RX_CHAN_5GHZ 0x0800
#define B43_RX_CHAN_ID 0x07F8
#define B43_RX_CHAN_ID_SHIFT 3
#define B43_RX_CHAN_PHYTYPE 0x0007
Enumerations
enum {
B43_TXST_SUPP_NONE, B43_TXST_SUPP_PMQ, B43_TXST_SUPP_FLUSH, B43_TXST_SUPP_PREV,
B43_TXST_SUPP_CHAN, B43_TXST_SUPP_LIFE, B43_TXST_SUPP_UNDER, B43_TXST_SUPP_ABNACK
}
Functions
_b43_declare_plcp_hdr (4)
_b43_declare_plcp_hdr (6)
static size_t b43_txhdr_size (struct b43_wldev *dev)
int b43_generate_txhdr (struct b43_wldev *dev, u8 *txhdr, struct sk_buff *skb_frag, struct ieee80211_tx_info *txctl, u16 cookie)
u8 b43_plcp_get_ratecode_cck (const u8 bitrate)
u8 b43_plcp_get_ratecode_ofdm (const u8 bitrate)
void b43_generate_plcp_hdr (struct b43_plcp_hdr4 *plcp, const u16 octets, const u8 bitrate)
void b43_rx (struct b43_wldev *dev, struct sk_buff *skb, const void *_rxhdr)
void b43_handle_txstatus (struct b43_wldev *dev, const struct b43_txstatus *status)
bool b43_fill_txstatus_report (struct b43_wldev *dev, struct ieee80211_tx_info *report, const struct b43_txstatus *status)
void b43_tx_suspend (struct b43_wldev *dev)
void b43_tx_resume (struct b43_wldev *dev)
static int b43_new_kidx_api (struct b43_wldev *dev)
static u8 b43_kidx_to_fw (struct b43_wldev *dev, u8 raw_kidx)
static u8 b43_kidx_to_raw (struct b43_wldev *dev, u8 firmware_kidx)
static struct b43_private_tx_info * b43_get_priv_tx_info (struct ieee80211_tx_info *info)
Variables
struct b43_txhdr __packed
Define Documentation
#define _b43_declare_plcp_hdr (size)
Value:
struct b43_plcp_hdr##size {             \
                union {                         \
                        __le32 data;            \
                        __u8 raw[size];         \
                } __packed;     \
        } __packed
Definition at line 8 of file xmit.h.
#define B43_RX_CHAN_40MHZ 0x1000
Definition at line 339 of file xmit.h.
#define B43_RX_CHAN_5GHZ 0x0800
Definition at line 340 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_CHAN_ID 0x07F8
Definition at line 341 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_CHAN_ID_SHIFT 3
Definition at line 342 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_CHAN_PHYTYPE 0x0007
Definition at line 343 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_MAC_AGGTYPE 0x00060000
Definition at line 326 of file xmit.h.
#define B43_RX_MAC_AGGTYPE_SHIFT 17
Definition at line 327 of file xmit.h.
#define B43_RX_MAC_AMSDU 0x00010000
Definition at line 328 of file xmit.h.
#define B43_RX_MAC_BEACONSENT 0x00008000
Definition at line 329 of file xmit.h.
#define B43_RX_MAC_DEC 0x00000008
Definition at line 333 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_MAC_DECERR 0x00000010
Definition at line 332 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_MAC_FCSERR 0x00000001
Definition at line 336 of file xmit.h.
Referenced by b43_rx(), and pio_rx_frame().
#define B43_RX_MAC_KEYIDX 0x000007E0
Definition at line 330 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_MAC_KEYIDX_SHIFT 5
Definition at line 331 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_MAC_PADDING 0x00000004
Definition at line 334 of file xmit.h.
Referenced by b43_rx(), and pio_rx_frame().
#define B43_RX_MAC_RESP 0x00000002
Definition at line 335 of file xmit.h.
#define B43_RX_MAC_RXST_VALID 0x01000000
Definition at line 323 of file xmit.h.
#define B43_RX_MAC_TKIP_MICATT 0x00080000
Definition at line 325 of file xmit.h.
#define B43_RX_MAC_TKIP_MICERR 0x00100000
Definition at line 324 of file xmit.h.
#define B43_RX_PHYST0_ANT 0x0020
Definition at line 300 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_PHYST0_CCK 0x0000
Definition at line 305 of file xmit.h.
#define B43_RX_PHYST0_CLIP 0x000C
Definition at line 302 of file xmit.h.
#define B43_RX_PHYST0_CLIP_SHIFT 2
Definition at line 303 of file xmit.h.
#define B43_RX_PHYST0_FTYPE 0x0003
Definition at line 304 of file xmit.h.
#define B43_RX_PHYST0_GAINCTL 0x4000
Definition at line 295 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_PHYST0_LCRS 0x0040
Definition at line 299 of file xmit.h.
#define B43_RX_PHYST0_OFDM 0x0001
Definition at line 306 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_PHYST0_PLCPFV 0x0100
Definition at line 297 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_PHYST0_PLCPHCF 0x0200
Definition at line 296 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_PHYST0_PRE_N 0x0002
Definition at line 307 of file xmit.h.
#define B43_RX_PHYST0_SHORTPRMBL 0x0080
Definition at line 298 of file xmit.h.
Referenced by b43_rx().
#define B43_RX_PHYST0_STD_N 0x0003
Definition at line 308 of file xmit.h.
#define B43_RX_PHYST0_UNSRATE 0x0010
Definition at line 301 of file xmit.h.
#define B43_RX_PHYST2_FOFF 0x03FF
Definition at line 315 of file xmit.h.
#define B43_RX_PHYST2_LNAG 0xC000
Definition at line 311 of file xmit.h.
#define B43_RX_PHYST2_LNAG_SHIFT 14
Definition at line 312 of file xmit.h.
#define B43_RX_PHYST2_PNAG 0x3C00
Definition at line 313 of file xmit.h.
#define B43_RX_PHYST2_PNAG_SHIFT 10
Definition at line 314 of file xmit.h.
#define B43_RX_PHYST3_DIGG 0x1800
Definition at line 318 of file xmit.h.
#define B43_RX_PHYST3_DIGG_SHIFT 11
Definition at line 319 of file xmit.h.
#define B43_RX_PHYST3_TRSTATE 0x0400
Definition at line 320 of file xmit.h.
Referenced by b43_rx().
#define B43_TXH_EFT_FB 0x03
Definition at line 126 of file xmit.h.
#define B43_TXH_EFT_FB_CCK 0x00
Definition at line 127 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_EFT_FB_EWC 0x02
Definition at line 129 of file xmit.h.
#define B43_TXH_EFT_FB_N 0x03
Definition at line 130 of file xmit.h.
#define B43_TXH_EFT_FB_OFDM 0x01
Definition at line 128 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_EFT_RTS 0x0C
Definition at line 131 of file xmit.h.
#define B43_TXH_EFT_RTS_CCK 0x00
Definition at line 132 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_EFT_RTS_EWC 0x08
Definition at line 134 of file xmit.h.
#define B43_TXH_EFT_RTS_N 0x0C
Definition at line 135 of file xmit.h.
#define B43_TXH_EFT_RTS_OFDM 0x04
Definition at line 133 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_EFT_RTSFB 0x30
Definition at line 136 of file xmit.h.
#define B43_TXH_EFT_RTSFB_CCK 0x00
Definition at line 137 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_EFT_RTSFB_EWC 0x20
Definition at line 139 of file xmit.h.
#define B43_TXH_EFT_RTSFB_N 0x30
Definition at line 140 of file xmit.h.
#define B43_TXH_EFT_RTSFB_OFDM 0x10
Definition at line 138 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_40MHZ 0x00000100
Definition at line 115 of file xmit.h.
#define B43_TXH_MAC_5GHZ 0x00000080
Definition at line 116 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_ACK 0x00000001
Definition at line 123 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_AMIC 0x00008000
Definition at line 105 of file xmit.h.
#define B43_TXH_MAC_AMPDU 0x00000600
Definition at line 110 of file xmit.h.
#define B43_TXH_MAC_AMPDU_FIRST 0x00000200
Definition at line 112 of file xmit.h.
#define B43_TXH_MAC_AMPDU_INTER 0x00000400
Definition at line 113 of file xmit.h.
#define B43_TXH_MAC_AMPDU_LAST 0x00000600
Definition at line 114 of file xmit.h.
#define B43_TXH_MAC_AMPDU_MPDU 0x00000000
Definition at line 111 of file xmit.h.
#define B43_TXH_MAC_DFCS 0x00000040
Definition at line 117 of file xmit.h.
#define B43_TXH_MAC_FRAMEBURST 0x00001000
Definition at line 108 of file xmit.h.
#define B43_TXH_MAC_HWSEQ 0x00000010
Definition at line 119 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_IGNPMQ 0x00000020
Definition at line 118 of file xmit.h.
#define B43_TXH_MAC_KEYALG 0x00070000
Definition at line 103 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_KEYALG_SHIFT 16
Definition at line 104 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_KEYIDX 0x0FF00000
Definition at line 101 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_KEYIDX_SHIFT 20
Definition at line 102 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_LIFETIME 0x00002000
Definition at line 107 of file xmit.h.
#define B43_TXH_MAC_LONGFRAME 0x00000002
Definition at line 122 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_RIFS 0x00004000
Definition at line 106 of file xmit.h.
#define B43_TXH_MAC_SENDCTS 0x00000800
Definition at line 109 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_SENDRTS 0x00000004
Definition at line 121 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_STMSDU 0x00000008
Definition at line 120 of file xmit.h.
Referenced by b43_generate_txhdr().
#define B43_TXH_MAC_USEFBR 0x10000000
Definition at line 100 of file xmit.h.
#define B43_TXH_PHY1_BW 0x0007
Definition at line 159 of file xmit.h.
#define B43_TXH_PHY1_BW_10 0x0000
Definition at line 160 of file xmit.h.
#define B43_TXH_PHY1_BW_10U 0x0001
Definition at line 161 of file xmit.h.
#define B43_TXH_PHY1_BW_20 0x0002
Definition at line 162 of file xmit.h.
Referenced by b43_generate_tx_phy_ctl1().
#define B43_TXH_PHY1_BW_20U 0x0003
Definition at line 163 of file xmit.h.
#define B43_TXH_PHY1_BW_40 0x0004
Definition at line 164 of file xmit.h.
#define B43_TXH_PHY1_BW_40DUP 0x0005
Definition at line 165 of file xmit.h.
#define B43_TXH_PHY1_CRATE 0x0700
Definition at line 171 of file xmit.h.
#define B43_TXH_PHY1_CRATE_1_2 0x0000
Definition at line 172 of file xmit.h.
#define B43_TXH_PHY1_CRATE_2_3 0x0100
Definition at line 173 of file xmit.h.
#define B43_TXH_PHY1_CRATE_3_4 0x0200
Definition at line 174 of file xmit.h.
#define B43_TXH_PHY1_CRATE_4_5 0x0300
Definition at line 175 of file xmit.h.
#define B43_TXH_PHY1_CRATE_5_6 0x0400
Definition at line 176 of file xmit.h.
#define B43_TXH_PHY1_CRATE_7_8 0x0600
Definition at line 177 of file xmit.h.
#define B43_TXH_PHY1_MODE 0x0038
Definition at line 166 of file xmit.h.
#define B43_TXH_PHY1_MODE_CDD 0x0008
Definition at line 168 of file xmit.h.
#define B43_TXH_PHY1_MODE_SDM 0x0018
Definition at line 170 of file xmit.h.
#define B43_TXH_PHY1_MODE_SISO 0x0000
Definition at line 167 of file xmit.h.
Referenced by b43_generate_tx_phy_ctl1().
#define B43_TXH_PHY1_MODE_STBC 0x0010
Definition at line 169 of file xmit.h.
#define B43_TXH_PHY1_MODUL 0x3800
Definition at line 178 of file xmit.h.
#define B43_TXH_PHY1_MODUL_BPSK 0x0000
Definition at line 179 of file xmit.h.
#define B43_TXH_PHY1_MODUL_QAM16 0x1000
Definition at line 181 of file xmit.h.
#define B43_TXH_PHY1_MODUL_QAM256 0x2000
Definition at line 183 of file xmit.h.
#define B43_TXH_PHY1_MODUL_QAM64 0x1800
Definition at line 182 of file xmit.h.
#define B43_TXH_PHY1_MODUL_QPSK 0x0800
Definition at line 180 of file xmit.h.
#define B43_TXH_PHY_ANT 0x03C0
Definition at line 149 of file xmit.h.
Referenced by b43_mgmtframe_txantenna(), and b43_write_beacon_template().
#define B43_TXH_PHY_ANT0 0x0000
Definition at line 150 of file xmit.h.
Referenced by b43_antenna_to_phyctl(), and b43_generate_txhdr().
#define B43_TXH_PHY_ANT01AUTO 0x00C0
Definition at line 152 of file xmit.h.
Referenced by b43_antenna_to_phyctl(), b43_generate_txhdr(), and b43_set_phytxctl_defaults().
#define B43_TXH_PHY_ANT1 0x0040
Definition at line 151 of file xmit.h.
Referenced by b43_antenna_to_phyctl(), and b43_generate_txhdr().
#define B43_TXH_PHY_ANT2 0x0100
Definition at line 153 of file xmit.h.
Referenced by b43_antenna_to_phyctl(), and b43_generate_txhdr().
#define B43_TXH_PHY_ANT3 0x0200
Definition at line 154 of file xmit.h.
Referenced by b43_antenna_to_phyctl(), and b43_generate_txhdr().
#define B43_TXH_PHY_ENC 0x0003
Definition at line 143 of file xmit.h.
Referenced by b43_write_beacon_template().
#define B43_TXH_PHY_ENC_CCK 0x0000
Definition at line 144 of file xmit.h.
Referenced by b43_generate_txhdr(), b43_set_phytxctl_defaults(), and b43_write_beacon_template().
#define B43_TXH_PHY_ENC_EWC 0x0002
Definition at line 146 of file xmit.h.
#define B43_TXH_PHY_ENC_N 0x0003
Definition at line 147 of file xmit.h.
#define B43_TXH_PHY_ENC_OFDM 0x0001
Definition at line 145 of file xmit.h.
Referenced by b43_generate_txhdr(), and b43_write_beacon_template().
#define B43_TXH_PHY_SHORTPRMBL 0x0010
Definition at line 148 of file xmit.h.
Referenced by b43_generate_txhdr(), and b43_write_beacon_template().
#define B43_TXH_PHY_TXPWR 0xFC00
Definition at line 155 of file xmit.h.
Referenced by b43_set_phytxctl_defaults().
#define B43_TXH_PHY_TXPWR_SHIFT 10
Definition at line 156 of file xmit.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
B43_TXST_SUPP_NONE
B43_TXST_SUPP_PMQ
B43_TXST_SUPP_FLUSH
B43_TXST_SUPP_PREV
B43_TXST_SUPP_CHAN
B43_TXST_SUPP_LIFE
B43_TXST_SUPP_UNDER
B43_TXST_SUPP_ABNACK
Definition at line 222 of file xmit.h.
Function Documentation
_b43_declare_plcp_hdr (6)
_b43_declare_plcp_hdr (4)
bool b43_fill_txstatus_report (struct b43_wldev * dev, struct ieee80211_tx_info * report, const struct b43_txstatus * status)
Definition at line 873 of file xmit.c.
References b43_txstatus::acked, b43_txstatus::frame_count, b43_wl::hw, b43_txstatus::rts_count, and b43_wldev::wl.
Referenced by b43_dma_handle_txstatus(), and b43_pio_handle_txstatus().
void b43_generate_plcp_hdr (struct b43_plcp_hdr4 * plcp, const u16 octets, const u8 bitrate)
Definition at line 148 of file xmit.c.
References B43_CCK_RATE_11MB, b43_is_ofdm_rate(), b43_plcp_get_ratecode_cck(), b43_plcp_get_ratecode_ofdm(), and B43_WARN_ON.
Referenced by b43_generate_txhdr(), and b43_write_template_common().
int b43_generate_txhdr (struct b43_wldev * dev, u8 * txhdr, struct sk_buff * skb_frag, struct ieee80211_tx_info * txctl, u16 cookie)
Definition at line 240 of file xmit.c.
References b43_key::algorithm, b43_calc_fallback_rate(), B43_CCK_RATE_1MB, B43_FW_HDR_351, B43_FW_HDR_410, B43_FW_HDR_598, b43_generate_plcp_hdr(), b43_generate_tx_phy_ctl1(), b43_ieee80211_antenna_sanitize(), b43_is_ofdm_rate(), b43_kidx_to_fw(), B43_PHYTYPE_A, B43_PHYTYPE_HT, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_plcp_get_ratecode_cck(), b43_plcp_get_ratecode_ofdm(), B43_SEC_ALGO_TKIP, B43_TXH_EFT_FB_CCK, B43_TXH_EFT_FB_OFDM, B43_TXH_EFT_RTS_CCK, B43_TXH_EFT_RTS_OFDM, B43_TXH_EFT_RTSFB_CCK, B43_TXH_EFT_RTSFB_OFDM, B43_TXH_MAC_5GHZ, B43_TXH_MAC_ACK, B43_TXH_MAC_HWSEQ, B43_TXH_MAC_KEYALG, B43_TXH_MAC_KEYALG_SHIFT, B43_TXH_MAC_KEYIDX, B43_TXH_MAC_KEYIDX_SHIFT, B43_TXH_MAC_LONGFRAME, B43_TXH_MAC_SENDCTS, B43_TXH_MAC_SENDRTS, B43_TXH_MAC_STMSDU, B43_TXH_PHY_ANT0, B43_TXH_PHY_ANT01AUTO, B43_TXH_PHY_ANT1, B43_TXH_PHY_ANT2, B43_TXH_PHY_ANT3, B43_TXH_PHY_ENC_CCK, B43_TXH_PHY_ENC_OFDM, B43_TXH_PHY_SHORTPRMBL, B43_WARN_ON, b43_txhdr::chan_radio_code, b43_phy::channel, b43_txhdr::cookie, b43_txhdr::dur_fb, b43_txhdr::extra_ft, b43_wldev::fw, b43_firmware::hdr_format, b43_wl::hw, b43_txhdr::iv, b43_wldev::key, b43_key::keyconf, b43_txhdr::mac_ctl, b43_txhdr::mac_frame_ctl, b43_wldev::phy, b43_txhdr::phy_ctl, b43_txhdr::phy_ctl1, b43_txhdr::phy_ctl1_fb, b43_txhdr::phy_ctl1_rts, b43_txhdr::phy_ctl1_rts_fb, b43_txhdr::phy_rate, b43_txhdr::phy_rate_rts, b43_txhdr::plcp, b43_txhdr::plcp_fb, b43_txhdr::rts_dur_fb, b43_txhdr::rts_frame, b43_txhdr::rts_plcp, b43_txhdr::rts_plcp_fb, b43_txhdr::tx_receiver, b43_phy::type, and b43_wldev::wl.
Referenced by dma_tx_fragment(), and pio_tx_frame().
static struct b43_private_tx_info* b43_get_priv_tx_info (struct ieee80211_tx_info * info) [static, read]
Definition at line 405 of file xmit.h.
Referenced by b43_dma_handle_txstatus(), and dma_tx_fragment().
void b43_handle_txstatus (struct b43_wldev * dev, const struct b43_txstatus * status)
Definition at line 844 of file xmit.c.
References b43_txstatus::acked, b43_debugfs_log_txstat(), b43_dma_handle_txstatus(), b43_phy_txpower_check(), b43_pio_handle_txstatus(), b43_using_pio_transfers(), b43_txstatus::for_ampdu, b43_wl::ieee_stats, b43_txstatus::intermediate, b43_txstatus::rts_count, and b43_wldev::wl.
Referenced by handle_irq_transmit_status().
static u8 b43_kidx_to_fw (struct b43_wldev * dev, u8 raw_kidx) [inline, static]
Definition at line 372 of file xmit.h.
References b43_new_kidx_api().
Referenced by b43_generate_txhdr(), and key_write().
static u8 b43_kidx_to_raw (struct b43_wldev * dev, u8 firmware_kidx) [inline, static]
Definition at line 385 of file xmit.h.
References b43_new_kidx_api().
Referenced by b43_rx().
static int b43_new_kidx_api (struct b43_wldev * dev) [inline, static]
Definition at line 367 of file xmit.h.
References b43_wldev::fw, and b43_firmware::rev.
Referenced by b43_clear_keys(), b43_dump_keymemory(), b43_key_clear(), b43_key_write(), b43_kidx_to_fw(), b43_kidx_to_raw(), do_key_write(), keymac_write(), and rx_tkip_phase1_write().
u8 b43_plcp_get_ratecode_cck (const u8 bitrate)
Definition at line 108 of file xmit.c.
References B43_CCK_RATE_11MB, B43_CCK_RATE_1MB, B43_CCK_RATE_2MB, B43_CCK_RATE_5MB, and B43_WARN_ON.
Referenced by b43_generate_plcp_hdr(), b43_generate_txhdr(), b43_rate_memory_write(), and b43_update_basic_rates().
u8 b43_plcp_get_ratecode_ofdm (const u8 bitrate)
Definition at line 124 of file xmit.c.
References B43_OFDM_RATE_12MB, B43_OFDM_RATE_18MB, B43_OFDM_RATE_24MB, B43_OFDM_RATE_36MB, B43_OFDM_RATE_48MB, B43_OFDM_RATE_54MB, B43_OFDM_RATE_6MB, B43_OFDM_RATE_9MB, and B43_WARN_ON.
Referenced by b43_generate_plcp_hdr(), b43_generate_txhdr(), b43_rate_memory_write(), and b43_update_basic_rates().
void b43_rx (struct b43_wldev * dev, struct sk_buff * skb, const void * _rxhdr)
Definition at line 653 of file xmit.c.
References b43_key::algorithm, b43_channel_to_freq_5ghz(), b43_freq_to_channel_2ghz(), b43_freq_to_channel_5ghz(), B43_FW_HDR_351, B43_FW_HDR_410, B43_FW_HDR_598, b43_kidx_to_raw(), B43_PHYTYPE_A, B43_PHYTYPE_B, B43_PHYTYPE_G, B43_PHYTYPE_HT, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_plcp_get_bitrate_idx_cck(), b43_plcp_get_bitrate_idx_ofdm(), b43_rssi_postprocess(), B43_RX_CHAN_5GHZ, B43_RX_CHAN_ID, B43_RX_CHAN_ID_SHIFT, B43_RX_CHAN_PHYTYPE, B43_RX_MAC_DEC, B43_RX_MAC_DECERR, B43_RX_MAC_FCSERR, B43_RX_MAC_KEYIDX, B43_RX_MAC_KEYIDX_SHIFT, B43_RX_MAC_PADDING, B43_RX_PHYST0_ANT, B43_RX_PHYST0_GAINCTL, B43_RX_PHYST0_OFDM, B43_RX_PHYST0_PLCPFV, B43_RX_PHYST0_PLCPHCF, B43_RX_PHYST0_SHORTPRMBL, B43_RX_PHYST3_TRSTATE, B43_SEC_ALGO_NONE, b43_tsf_read(), B43_WARN_ON, b43dbg(), b43_rxhdr_fw4::channel, b43_wl::filter_flags, b43_wldev::fw, b43_firmware::hdr_format, b43_wl::hw, b43_wl::ieee_stats, b43_rxhdr_fw4::jssi, b43_wldev::key, b43_rxhdr_fw4::mac_status, b43_rxhdr_fw4::mac_time, b43_rxhdr_fw4::phy_ht_power0, b43_rxhdr_fw4::phy_ht_power1, b43_rxhdr_fw4::phy_ht_power2, b43_rxhdr_fw4::phy_status0, b43_rxhdr_fw4::phy_status3, b43_rxhdr_fw4::power0, b43_rxhdr_fw4::power1, b43_rxhdr_fw4::power2, b43_wl::radiotap_enabled, and b43_wldev::wl.
Referenced by dma_rx(), and pio_rx_frame().
void b43_tx_resume (struct b43_wldev * dev)
Definition at line 934 of file xmit.c.
References b43_dma_tx_resume(), b43_pio_tx_resume(), and b43_using_pio_transfers().
void b43_tx_suspend (struct b43_wldev * dev)
Definition at line 925 of file xmit.c.
References b43_dma_tx_suspend(), b43_pio_tx_suspend(), and b43_using_pio_transfers().
static size_t b43_txhdr_size (struct b43_wldev * dev) [inline, static]
Definition at line 187 of file xmit.h.
References B43_FW_HDR_351, B43_FW_HDR_410, B43_FW_HDR_598, b43_wldev::fw, and b43_firmware::hdr_format.
Referenced by b43_dma_handle_txstatus(), b43_pio_handle_txstatus(), b43_pio_tx(), b43_setup_dmaring(), dma_tx_fragment(), and pio_tx_frame().
Variable Documentation
struct b43_rxhdr_fw4 __packed