CompatWireless3.2: drivers/net/wireless/b43/xmit.c File Reference
drivers/net/wireless/b43/xmit.c File Reference
#include "xmit.h"
#include "phy_common.h"
#include "dma.h"
#include "pio.h"
Functions
static struct
b43_tx_legacy_rate_phy_ctl_entry * b43_tx_legacy_rate_phy_ctl_ent (u8 bitrate)
static int b43_plcp_get_bitrate_idx_cck (struct b43_plcp_hdr6 *plcp)
static int b43_plcp_get_bitrate_idx_ofdm (struct b43_plcp_hdr6 *plcp, bool aphy)
u8 b43_plcp_get_ratecode_cck (const u8 bitrate)
u8 b43_plcp_get_ratecode_ofdm (const u8 bitrate)
void b43_generate_plcp_hdr (struct b43_plcp_hdr4 *plcp, const u16 octets, const u8 bitrate)
static u16 b43_generate_tx_phy_ctl1 (struct b43_wldev *dev, u8 bitrate)
static u8 b43_calc_fallback_rate (u8 bitrate)
int b43_generate_txhdr (struct b43_wldev *dev, u8 *_txhdr, struct sk_buff *skb_frag, struct ieee80211_tx_info *info, u16 cookie)
static s8 b43_rssi_postprocess (struct b43_wldev *dev, u8 in_rssi, int ofdm, int adjust_2053, int adjust_2050)
void b43_rx (struct b43_wldev *dev, struct sk_buff *skb, const void *_rxhdr)
void b43_handle_txstatus (struct b43_wldev *dev, const struct b43_txstatus *status)
bool b43_fill_txstatus_report (struct b43_wldev *dev, struct ieee80211_tx_info *report, const struct b43_txstatus *status)
void b43_tx_suspend (struct b43_wldev *dev)
void b43_tx_resume (struct b43_wldev *dev)
Variables
static struct
b43_tx_legacy_rate_phy_ctl_entry b43_tx_legacy_rate_phy_ctl []
Function Documentation
static u8 b43_calc_fallback_rate (u8 bitrate) [static]
Definition at line 207 of file xmit.c.
References B43_CCK_RATE_11MB, B43_CCK_RATE_1MB, B43_CCK_RATE_2MB, B43_CCK_RATE_5MB, B43_OFDM_RATE_12MB, B43_OFDM_RATE_18MB, B43_OFDM_RATE_24MB, B43_OFDM_RATE_36MB, B43_OFDM_RATE_48MB, B43_OFDM_RATE_54MB, B43_OFDM_RATE_6MB, B43_OFDM_RATE_9MB, and B43_WARN_ON.
Referenced by b43_generate_txhdr().
bool b43_fill_txstatus_report (struct b43_wldev * dev, struct ieee80211_tx_info * report, const struct b43_txstatus * status)
Definition at line 873 of file xmit.c.
References b43_txstatus::acked, b43_txstatus::frame_count, b43_wl::hw, b43_txstatus::rts_count, and b43_wldev::wl.
Referenced by b43_dma_handle_txstatus(), and b43_pio_handle_txstatus().
void b43_generate_plcp_hdr (struct b43_plcp_hdr4 * plcp, const u16 octets, const u8 bitrate)
Definition at line 148 of file xmit.c.
References B43_CCK_RATE_11MB, b43_is_ofdm_rate(), b43_plcp_get_ratecode_cck(), b43_plcp_get_ratecode_ofdm(), and B43_WARN_ON.
Referenced by b43_generate_txhdr(), and b43_write_template_common().
static u16 b43_generate_tx_phy_ctl1 (struct b43_wldev * dev, u8 bitrate) [static]
Definition at line 179 of file xmit.c.
References b43_is_cck_rate(), B43_PHYTYPE_LP, b43_tx_legacy_rate_phy_ctl_ent(), B43_TXH_PHY1_BW_20, B43_TXH_PHY1_MODE_SISO, b43_tx_legacy_rate_phy_ctl_entry::coding_rate, b43_tx_legacy_rate_phy_ctl_entry::modulation, b43_wldev::phy, and b43_phy::type.
Referenced by b43_generate_txhdr().
int b43_generate_txhdr (struct b43_wldev * dev, u8 * _txhdr, struct sk_buff * skb_frag, struct ieee80211_tx_info * info, u16 cookie)
Definition at line 240 of file xmit.c.
References b43_key::algorithm, b43_calc_fallback_rate(), B43_CCK_RATE_1MB, B43_FW_HDR_351, B43_FW_HDR_410, B43_FW_HDR_598, b43_generate_plcp_hdr(), b43_generate_tx_phy_ctl1(), b43_ieee80211_antenna_sanitize(), b43_is_ofdm_rate(), b43_kidx_to_fw(), B43_PHYTYPE_A, B43_PHYTYPE_HT, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_plcp_get_ratecode_cck(), b43_plcp_get_ratecode_ofdm(), B43_SEC_ALGO_TKIP, B43_TXH_EFT_FB_CCK, B43_TXH_EFT_FB_OFDM, B43_TXH_EFT_RTS_CCK, B43_TXH_EFT_RTS_OFDM, B43_TXH_EFT_RTSFB_CCK, B43_TXH_EFT_RTSFB_OFDM, B43_TXH_MAC_5GHZ, B43_TXH_MAC_ACK, B43_TXH_MAC_HWSEQ, B43_TXH_MAC_KEYALG, B43_TXH_MAC_KEYALG_SHIFT, B43_TXH_MAC_KEYIDX, B43_TXH_MAC_KEYIDX_SHIFT, B43_TXH_MAC_LONGFRAME, B43_TXH_MAC_SENDCTS, B43_TXH_MAC_SENDRTS, B43_TXH_MAC_STMSDU, B43_TXH_PHY_ANT0, B43_TXH_PHY_ANT01AUTO, B43_TXH_PHY_ANT1, B43_TXH_PHY_ANT2, B43_TXH_PHY_ANT3, B43_TXH_PHY_ENC_CCK, B43_TXH_PHY_ENC_OFDM, B43_TXH_PHY_SHORTPRMBL, B43_WARN_ON, b43_txhdr::chan_radio_code, b43_phy::channel, b43_txhdr::cookie, b43_txhdr::dur_fb, b43_txhdr::extra_ft, b43_wldev::fw, b43_firmware::hdr_format, b43_wl::hw, b43_txhdr::iv, b43_wldev::key, b43_key::keyconf, b43_txhdr::mac_ctl, b43_txhdr::mac_frame_ctl, b43_wldev::phy, b43_txhdr::phy_ctl, b43_txhdr::phy_ctl1, b43_txhdr::phy_ctl1_fb, b43_txhdr::phy_ctl1_rts, b43_txhdr::phy_ctl1_rts_fb, b43_txhdr::phy_rate, b43_txhdr::phy_rate_rts, b43_txhdr::plcp, b43_txhdr::plcp_fb, b43_txhdr::rts_dur_fb, b43_txhdr::rts_frame, b43_txhdr::rts_plcp, b43_txhdr::rts_plcp_fb, b43_txhdr::tx_receiver, b43_phy::type, and b43_wldev::wl.
Referenced by dma_tx_fragment(), and pio_tx_frame().
void b43_handle_txstatus (struct b43_wldev * dev, const struct b43_txstatus * status)
Definition at line 844 of file xmit.c.
References b43_txstatus::acked, b43_debugfs_log_txstat(), b43_dma_handle_txstatus(), b43_phy_txpower_check(), b43_pio_handle_txstatus(), b43_using_pio_transfers(), b43_txstatus::for_ampdu, b43_wl::ieee_stats, b43_txstatus::intermediate, b43_txstatus::rts_count, and b43_wldev::wl.
Referenced by handle_irq_transmit_status().
static int b43_plcp_get_bitrate_idx_cck (struct b43_plcp_hdr6 * plcp) [static]
Definition at line 67 of file xmit.c.
Referenced by b43_rx().
static int b43_plcp_get_bitrate_idx_ofdm (struct b43_plcp_hdr6 * plcp, bool aphy) [static]
Definition at line 83 of file xmit.c.
Referenced by b43_rx().
u8 b43_plcp_get_ratecode_cck (const u8 bitrate)
Definition at line 108 of file xmit.c.
References B43_CCK_RATE_11MB, B43_CCK_RATE_1MB, B43_CCK_RATE_2MB, B43_CCK_RATE_5MB, and B43_WARN_ON.
Referenced by b43_generate_plcp_hdr(), b43_generate_txhdr(), b43_rate_memory_write(), and b43_update_basic_rates().
u8 b43_plcp_get_ratecode_ofdm (const u8 bitrate)
Definition at line 124 of file xmit.c.
References B43_OFDM_RATE_12MB, B43_OFDM_RATE_18MB, B43_OFDM_RATE_24MB, B43_OFDM_RATE_36MB, B43_OFDM_RATE_48MB, B43_OFDM_RATE_54MB, B43_OFDM_RATE_6MB, B43_OFDM_RATE_9MB, and B43_WARN_ON.
Referenced by b43_generate_plcp_hdr(), b43_generate_txhdr(), b43_rate_memory_write(), and b43_update_basic_rates().
static s8 b43_rssi_postprocess (struct b43_wldev * dev, u8 in_rssi, int ofdm, int adjust_2053, int adjust_2050) [static]
Definition at line 574 of file xmit.c.
References B43_BFL_RSSI, B43_PHYTYPE_G, B43_WARN_ON, b43_bus_dev::bus_sprom, b43_wldev::dev, b43_phy::g, b43_phy_g::nrssi_lt, b43_wldev::phy, b43_phy::radio_ver, and b43_phy::type.
Referenced by b43_rx().
void b43_rx (struct b43_wldev * dev, struct sk_buff * skb, const void * _rxhdr)
Definition at line 653 of file xmit.c.
References b43_key::algorithm, b43_channel_to_freq_5ghz(), b43_freq_to_channel_2ghz(), b43_freq_to_channel_5ghz(), B43_FW_HDR_351, B43_FW_HDR_410, B43_FW_HDR_598, b43_kidx_to_raw(), B43_PHYTYPE_A, B43_PHYTYPE_B, B43_PHYTYPE_G, B43_PHYTYPE_HT, B43_PHYTYPE_LP, B43_PHYTYPE_N, b43_plcp_get_bitrate_idx_cck(), b43_plcp_get_bitrate_idx_ofdm(), b43_rssi_postprocess(), B43_RX_CHAN_5GHZ, B43_RX_CHAN_ID, B43_RX_CHAN_ID_SHIFT, B43_RX_CHAN_PHYTYPE, B43_RX_MAC_DEC, B43_RX_MAC_DECERR, B43_RX_MAC_FCSERR, B43_RX_MAC_KEYIDX, B43_RX_MAC_KEYIDX_SHIFT, B43_RX_MAC_PADDING, B43_RX_PHYST0_ANT, B43_RX_PHYST0_GAINCTL, B43_RX_PHYST0_OFDM, B43_RX_PHYST0_PLCPFV, B43_RX_PHYST0_PLCPHCF, B43_RX_PHYST0_SHORTPRMBL, B43_RX_PHYST3_TRSTATE, B43_SEC_ALGO_NONE, b43_tsf_read(), B43_WARN_ON, b43dbg(), b43_rxhdr_fw4::channel, b43_wl::filter_flags, b43_wldev::fw, b43_firmware::hdr_format, b43_wl::hw, b43_wl::ieee_stats, b43_rxhdr_fw4::jssi, b43_wldev::key, b43_rxhdr_fw4::mac_status, b43_rxhdr_fw4::mac_time, b43_rxhdr_fw4::phy_ht_power0, b43_rxhdr_fw4::phy_ht_power1, b43_rxhdr_fw4::phy_ht_power2, b43_rxhdr_fw4::phy_status0, b43_rxhdr_fw4::phy_status3, b43_rxhdr_fw4::power0, b43_rxhdr_fw4::power1, b43_rxhdr_fw4::power2, b43_wl::radiotap_enabled, and b43_wldev::wl.
Referenced by dma_rx(), and pio_rx_frame().
static struct b43_tx_legacy_rate_phy_ctl_entry* b43_tx_legacy_rate_phy_ctl_ent (u8 bitrate) [static, read]
Definition at line 51 of file xmit.c.
References B43_WARN_ON, and b43_tx_legacy_rate_phy_ctl_entry::bitrate.
Referenced by b43_generate_tx_phy_ctl1().
void b43_tx_resume (struct b43_wldev * dev)
Definition at line 934 of file xmit.c.
References b43_dma_tx_resume(), b43_pio_tx_resume(), and b43_using_pio_transfers().
void b43_tx_suspend (struct b43_wldev * dev)
Definition at line 925 of file xmit.c.
References b43_dma_tx_suspend(), b43_pio_tx_suspend(), and b43_using_pio_transfers().
Variable Documentation
struct b43_tx_legacy_rate_phy_ctl_entry b43_tx_legacy_rate_phy_ctl[] [static]
Initial value:
 {
        { B43_CCK_RATE_1MB,     0x0,                    0x0 },
        { B43_CCK_RATE_2MB,     0x0,                    0x1 },
        { B43_CCK_RATE_5MB,     0x0,                    0x2 },
        { B43_CCK_RATE_11MB,    0x0,                    0x3 },
        { B43_OFDM_RATE_6MB,    B43_TXH_PHY1_CRATE_1_2, B43_TXH_PHY1_MODUL_BPSK },
        { B43_OFDM_RATE_9MB,    B43_TXH_PHY1_CRATE_3_4, B43_TXH_PHY1_MODUL_BPSK },
        { B43_OFDM_RATE_12MB,   B43_TXH_PHY1_CRATE_1_2, B43_TXH_PHY1_MODUL_QPSK },
        { B43_OFDM_RATE_18MB,   B43_TXH_PHY1_CRATE_3_4, B43_TXH_PHY1_MODUL_QPSK },
        { B43_OFDM_RATE_24MB,   B43_TXH_PHY1_CRATE_1_2, B43_TXH_PHY1_MODUL_QAM16 },
        { B43_OFDM_RATE_36MB,   B43_TXH_PHY1_CRATE_3_4, B43_TXH_PHY1_MODUL_QAM16 },
        { B43_OFDM_RATE_48MB,   B43_TXH_PHY1_CRATE_2_3, B43_TXH_PHY1_MODUL_QAM64 },
        { B43_OFDM_RATE_54MB,   B43_TXH_PHY1_CRATE_3_4, B43_TXH_PHY1_MODUL_QAM64 },
}
Definition at line 35 of file xmit.c.